### ISSUE TITLE
Implement Reach filtering in VBET

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#1]
BRAT Build has a [command line argument that controls which NHD features to retain](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/brat/sqlbrat/brat_build.py#L247) (ephemeral, intermittent etc). We need the same ability within VBET. The default VBET configuration should include:

* 33400 - Connector
* 46003 - Intermittent
* 46006 - Perenial
* 46007 - Ephemeral
* 55800 - Artificial Path

**Comment by philipbaileynar** [comment]
@KellyMWhitehead I could have sworn this was implemented. Can you confirm?

@joewheaton can you confirm that I've specified the correct reach codes above please?

**Comment by KellyMWhitehead** [comment]
Implemented in fbccb4ea9450abd7f9fd79107b97b5da4d978d0c

VBET now only includes the Fcodes listed above (we can easily add others if needed) and any reach is contained in NHD FlowAreas.

**Comment by MattReimer** [comment]
Verified using Cybercastor
