### ISSUE TITLE
BRAT Vegetation Report Section Data Issues

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#1001]
Reviewing this [latest BRAT project ](https://data.riverscapes.net/p/3a967c39-00c0-4cc9-931d-65d37fdc017c/overview) revealed that the vegetation section doesn't seem to be reporting any values. I suspect that this is a SQL issue. @jtgilbert any recent changes you can think of that might have caused this?

<img width="816" alt="Screenshot 2024-08-23 at 11 45 10 AM" src="https://github.com/user-attachments/assets/4af1c3eb-01b2-48c8-a102-569341ed8128">

**Comment by jtgilbert** [comment]
I'll have a look, there were a lot of changes in consolidating BRAT into one script instead of two, so I'm not surprised report generation was affected.

**Comment by jtgilbert** [comment]
This is happening because an empty view is being returned because the code is trying to join 8 digit to 10 digit watershed ID (HUCs).  I'll test a fix.
