### ISSUE TITLE
RME Report Filter Header

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#1004]
In #965 we filtered which features are included in RME reports.  However, there's no visual indication when reading the report that you are looking at a filtered set of features and not the entire HUC10 (other than the file name).

Please include A section above "Inputs" called "Filters" with some kind of simple, brief, plain English sentence explaining which features are included. Perhaps this also has the SQL WHERE clause underneath for technical clarity.

Hopefully this information can easily be passed into the function that loops over the report types, and therefore this isn't much of a big ask. Reach out if that is not the case.

<img width="816" alt="Screenshot 2024-08-23 at 12 33 29 PM" src="https://github.com/user-attachments/assets/898e5b89-c803-42c5-8df8-9a76de104b5a">

**Comment by r-k-g** [comment]
![image](https://github.com/user-attachments/assets/50ef808c-fafb-41d4-be5b-65efae8f6b5d)
Welcome to feedback on the prose & appearance. 

Currently getting all the information from this dictionary, but it would be trivial to add a second dictionary with the name of the filter and any specific content for each that we want to display.

![image](https://github.com/user-attachments/assets/93193edb-5c30-4622-b937-9a5137aaaf1a)
