### ISSUE TITLE
BRAT.html Box and Whisker Plots appear strange sometimes

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/riverscapes-tools#101]
![image](https://user-images.githubusercontent.com/27084463/97639231-2786af80-1a0c-11eb-9c66-14675c2bf1a9.png)

In many cases, the box and whisker plots look a little strange. This often involves having no 'box', or having most data points appear as points instead of being grouped in the box. This might just be because of how the data is distributed, so maybe it's not really an issue. Screenshot from 17010212.

**Comment by philipbaileynar** [comment]
Super old issue. @r-k-g has reworked these charts significantly.
