### ISSUE TITLE
Incorrect Cybercastor log message in VBET run

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#1013]
Investigating one of the VBET failures I notice the last [CloudWatch log message](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/CybercastorLogs_production/log-events/ecs$252FCybercastorEngine_riverscapesTools_production$252FriverscapesTools$252F82651598f026465fa225c6d9edcc226c) mentions RSContext...

<img width="756" alt="Screenshot 2024-09-11 at 7 44 38 PM" src="https://github.com/user-attachments/assets/972c4e08-2420-417f-a44f-c0200c5b5e91">

**Comment by MattReimer** [comment]
THis is just a string in a shell script inside `riverscapes-tools`

###  See: `scripts/automation/FargateVBET.sh`
