### ISSUE TITLE
Build national NHD HUC10 feature class

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#1026]
I have been struggling to accurately monitor our CONUS run because I am basing completion off of the WBD HUC10s. These differ from the actual data that we are using for Riverscapes Context.

Please write a Python script to download each HUC4 VPU File Geodatabase (using boto) then use OGR2OGR to "append" the HUC10 layer into a new GeoPackage polygon feature class. 

You can use the following boto command to obtain the NHD data from S3: 

```bash
aws s3 cp s3://prd-tnm/StagedProducts/Hydrography/NHDPlusHR/VPU/Current/GDB/NHDPLUS_H_1701_HU4_GDB.zip .
```
or to list them...

```
aws s3 ls s3://prd-tnm/StagedProducts/Hydrography/NHDPlusHR/VPU/Current/GDB/ | grep '.*\.zip' > allzips.txt
```

Then you can adapt the following OGR2OGR command in a single GeoPackage Feature class:

```python
cmd = f'ogr2ogr -f GPKG -makevalid -append  -nln {feature_class} "{output_gpkg_file}" "{input_gpkg_file}" {feature_class}'
subprocess.call([cmd], shell=True, cwd=output_gpkg_dir)
```

# Deliverable

- GeoPackage with a single feature class that is the national HUC10 layer according to NHD. I really only need CONUS. But include Alaska if easy. Definitely ignore Hawaii and any territories.
- I definitely need the following attributes:
    - HUC10
    - name
    - states
    - If possible I need the huc type column for the HUC10s that tells me whether the HUC is "water" or "urban" etc. If this isn't available in the NHD data then I can transpose it from the WBD, being careful about HUC matchups.

**Comment by KellyMWhitehead** [comment]
Huc 10 db was provided to @philipbaileynar 

`huc_conus.py` script saved in rs_context scripts for future use.

**Comment by philipbaileynar** [comment]
Chris Jordan just made us aware of a crosswalk table beteen WBD and NHD.

https://data.usgs.gov/datacatalog/data/USGS:5c86a747e4b09388244b3da1
