### ISSUE TITLE
VBET Contour Research

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#107]
Within VBET, our current post-processing of evidence raster involves a [complicated series of steps](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/vbet/vbet/vbet.py#L270) to vectorize the raster into useful polygons. We do some smoothing, elimination of polygons that don't touch the network, unioning etc. It's extremely slow (48hrs for certain complicated eight digit HUCs) and fiddly, @MattReimer played with the order of these operations until we arrived at something simple.

Please research if contouring the evidence raster might be a better way to vectorize the VBET evidence. This might be a faster, less error prone to produce vectors geometries.

## Questions

1. Contouring produces polylines... not polygons. If contouring does indeed produce better shapes, faster, then how do we convert these to polygons?
1. What contour interval should we use? Perhaps this becomes a VBET input parameter.
1. What post-processing is needed to clean the contours? e.g. removing features that don't touch the network etc.

## Getting Started

Go to the Riverscapes data warehouse (Anabranch program) and download the middle bear VBET. Use the evidence raster in the intermediates as the input to the ESRI [contour](https://desktop.arcgis.com/en/arcmap/10.6/tools/3d-analyst-toolbox/contour.htm) geoprocessing tool. (We will ultimately use the [GDAL contour](https://gdal.org/programs/gdal_contour.html) tool, but they do the same thing).

FYI @joewheaton

**Comment by joewheaton** [comment]
Interesting ideas @philipbaileynar. @shelbysawyer this will be fun to explore. Some initial thoughts

> 1. Contouring produces polylines... not polygons. If contouring does indeed produce better shapes, faster, then how do we convert these to polygons?

I think the shapes could be related to the segmentation.... What we need for the cross members.

> 2. What contour interval should we use? Perhaps this becomes a VBET input parameter.

I would say at 10% liklihood or probability... AFTER we get the transform functions on the 0 to 1 scaled like we want.

> 3. What post-processing is needed to clean the contours? e.g. removing features that don't touch the network etc.

Interseting.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead recently researched both ArcGIS contour and GDAL contour. Both can produce either polyline or polygon results.

The polygons from GDAL contour look useful but still need the same sanitization that we perform on our manual vectorizing of the VBET evidence raster. Therefore contouring does not appear to offer anything new or worth including in VBET.
