### ISSUE TITLE
New HAND Rasters for 1:24,000K

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#111]
Related to #98 

WE now have a running HAND result for some of the huc8s for our VBET investigation

* [16010202 - Middle Bear](https://data.riverscapes.xyz/#/Anabranch/7cf4214e-bb65-4a80-af52-0e9393343088)
* [10190002 - Upper South Platte](https://data.riverscapes.xyz/#/Anabranch/d718ee37-f997-417b-8b3c-4ddc04548007)
* 10190003 - Incomplete
* [10190004 - Clear](https://data.riverscapes.xyz/#/Anabranch/016f7ae4-5492-401d-9085-d1ec5c0d6a78)
* [10190005 - St. Vrain](https://data.riverscapes.xyz/#/Anabranch/24901c83-282f-47f0-b059-bebfb96a1d0c)
* 10190010 - Incomplete

For these projects you will see two HAND rasters:

* **`Height above nearest drainage 1:100K.`**
    * This is the original one and the one you will see in other RSContext projects
    * The filename is `topography/hand.tif`
* **`Height above nearest drainage`**
    * THis is the **new** one at 1:24K
    * The filename is `topography/hand_2.tif`

10190003 and 10190010 failed due to unforseen issues with the TauDEM tool that I haven't taken time to analyze yet. The only error I could get was:

```
/usr/local/runner.sh: line 9:     9 Killed     
```

**Comment by philipbaileynar** [comment]
@joewheaton what's concerning here is that TauDEM dies for some reason on several of the Mile High Flood District DEMs. There is no useful error message. We will dig further but we can't rely on tools that intermittently fail.

For now some of the Mile High RSC and VBET use the new 1:14K derived HAND while some still have the old 1:100K version.

Note that the Milddle Bear is done which should unlock @shelbysawyer .

**Comment by MattReimer** [comment]
#131 Is open for more investigation. I'm calling this closed.
