### ISSUE TITLE
Master List of Reach Attributes - GNAT and River Styler

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#118]
Please provide the master list of stream attributes that pyGNAT needs to calculate. The usual suspects are:

* Sinuosity (valley or reach?)
* Gradient (valley or reach?)
* Stream Order (any particular method?)
* Braidedness?

Obviously it would be nice to have the the master tree of reach types and the criteria for how each attribute applies to each type.... but for now we just need the master list of all attributes that will occur in the reach typing logic.

**Comment by joewheaton** [comment]
Now that you have [TauDEM](https://hydrology.usu.edu/taudem/taudem5/documentation.html) working, we should have @lauren-herbine revisit this. We also need to chat about where some of these things end up (as their own riverscape projects or GNAT) or what...

**Comment by lauren-herbine** [comment]
Ok, so I've amassed a list of attributes discussed over the past couple of months. Some of these I am not sure would actually be getting at the current _form_ of the river, but rather the condition or function (ex: hydropower plants- though they certainly effect streams/rivers, I don't think we would be able to derive any indicator of geomorphic form from their presence/absence or distance from a reach). These are just brainstorming thoughts, so I'd be interested in hearing other's opinions on the utility of these. Perhaps some are redundant? @joewheaton, what were you interested in deriving from TauDEM? 

| Attribute                                             | Form | Function | Other                                                                                                                                                                                       | do we have a tool? |
|-------------------------------------------------------|------|----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|
| confinement                                           | x    |          |                                                                                                                                                                                             | VBET               |
| presence/absence floodplain pockets/floodplain extent | x    |          |                                                                                                                                                                                             |                    |
| grain size                                            | x    |          |                                                                                                                                                                                             | yes?               |
| channel continuity                                    | x    |          |                                                                                                                                                                                             | NHD+?              |
| valley sinuosity                                      | x    |          |                                                                                                                                                                                             | ?                  |
| active channel sinuosity                              | x    |          |                                                                                                                                                                                             | ?                  |
| braiding index                                        | x    | x        |                                                                                                                                                                                             | yes?               |
| active vs. inactive valley bottom                     | x    | x        | would this give us information not derived from other attributes? and be more an indicator of function than form?                                                                           | ?                  |
| valley gradient                                       | x    |          |                                                                                                                                                                                             | yes? VBET?         |
| channel gradient                                      | x    |          |                                                                                                                                                                                             | TauDEM             |
| perrenial stream order                                |      |          | how would this alone affect form? would a small "laterally unconfined, sand bed, braided river" be classified any differently from a large "laterally unconfined, sand bed, braided river"? |                    |
| flow regime                                           | x    |          |                                                                                                                                                                                             | ORNL flow types    |
| EcoRegion                                             | x    |          |                                                                                                                                                                                             |                    |
| geologic formation                                    | x    |          |                                                                                                                                                                                             |                    |
| process based classification                          | x    | x        |                                                                                                                                                                                             |                    |
| bed material                                          | x    |          |                                                                                                                                                                                             | yes?               |
| confluence/diffluence count/channel heads/tributaries |      |          | does this actually quantify/explain the geomorphic form of a river?                                                                                                                         | yes?               |
| anthropogenic margins                                 |      | x        |                                                                                                                                                                                             | VBET?              |
| absolute stream order                                 |      |          | how would this alone affect form? would a small "laterally unconfined, sand bed, braided river" be classified any differently from a large "laterally unconfined, sand bed, braided river"? | yes                |
| stream size                                           |      |          | how would this alone affect form? would a small "laterally unconfined, sand bed, braided river" be classified any differently from a large "laterally unconfined, sand bed, braided river"? | yes                |
| hydropower plants                                     |      | x        |                                                                                                                                                                                             |                    |
| stream temperature                                    |      | x        |                                                                                                                                                                                             |                    |
| stability                                             |      | x        |                                                                                                                                                                                             |                    |
| land use                                              |      | x        |                                                                                                                                                                                             |                    |
| imperviousness of HUC 12                              |      |          |                                                                                                                                                                                             |                    |
| CEM stage                                             |      | x        |                                                                                                                                                                                             |                    |
| status of riparian corridor                           |      | x        |                                                                                                                                                                                             |                    |
| losing vs. gaining reach                              | x    |          |                                                                                                                                                                                             |                    |
| process zone                                          | x    |          |                                                                                                                                                                                             |                    |
| geomorphic units present                              | x    | x        |                                                                                                                                                                                             | GUT                |

**Comment by lauren-herbine** [comment]
more brainstorming- not finished:
| YES (easy to acquire + useful)                               | MAYBE (redundant? data? useful?)  | NO (no data, redundant, indicator of condition) |
| ------------------------------------------------------------ | --------------------------------- | ----------------------------------------------- |
| confinement                                                  | stream order                      | process based classification                    |
| sinuosity (valley, channel, ratio?)                          | active vs. inactive valley bottom | hydropower plants                               |
| gradient (valley, channel, ratio?)                           | geomorphic units present          | stream temp                                     |
| flow regime                                                  | floodplain metrics                | process zone                                    |
| channel connectivity                                         | geologic formation                | land use                                        |
| bed material/grain size                                      | confluence/diffluence count       | CEM stage                                       |
| EcoRegion                                                    | anthropogenic margins             | status of riparian corridor                     |
| [braiding index](file:///C:/Users/leher/Downloads/Definingandmeasuringbraidingintensity.pdf) | channel heads/tribs count         | stability (?)                                   |
|                                                              |                                   | stream size (?)                                 |
|                                                              |                                   | imperviousness of HUC 12                        |

## Confinement

## Sinuosity

- Planform Sinuosity (Channel Segment length/distance of channel segment endpoints). This is easy and only needs the line network as an input.
- Channel Sinuosity (Channel Segment length/ valley bottom Centerline length). We will need vb centerline and a method to spatially join the two (i.e. probably use vb sausages for this).
- Valley Bottom Sinuosity (Valley Bottom Centerline Segment length/distance of Valley Bottom Centerline Segment endpoints)

## Gradient

- dem was sampled directly at the endpoints, no averaging.

## Flow Regime

## Channel connectivity/continuity

## Bed material/grain size

## EcoRegion

## Braiding index/threadedness

* Bar indices
* Channel count index
  * The first is the mean number of links intersected by cross-sections of the river in successive river lengths. River lengths are defined by cross-sections sufficiently far apart that the cross-sections do not cross the same links (or segments) of the network more than once. The number of channels (segments) is then averaged for the river lengths of interest
  * The second index is the total number of links (or segments) in the measured reach
* Channel length index/total sinuosity
  * the total length of channels per unit length of river; now often referred to as ‘total sinuosity’ 
  * a variant of total sinuosity that substitutes the (straight line) reach length with the length of the main channel

**Comment by joewheaton** [comment]
@lauren-herbine the above are all super helpful and I like that you and @philipbaileynar moved these out to individual tasks. 

Another easier set will be to get many of these other LANDFIRE attributes in. Right now we just use BPS and EVT. However,
 there are a ton of other [great products](https://www.landfire.gov/version_comparison.php) (you may want to explore some in[ LFDAT](https://www.landfire.gov/datatool.php) or as [WMS](https://www.landfire.gov/data_access.php)). 

Take a look and think about:
[Disturbance Products](https://www.landfire.gov/disturbance.php)
[Fuels](https://www.landfire.gov/disturbance.php)
[Fire Regime](https://www.landfire.gov/fireregime.php) - includes vegetation departure and succession classes

I suspect many of these are worth putting into a RS Context Project, and some of these we'll want to sample and derive summaries from valley bottom segments, or upstream integrated values (e.g. network attributes tool), vs. buffer sampled values.

**Comment by philipbaileynar** [comment]
Lots of good material here, but old ticket superceded by new RME. Closing for now. Can always use for reference.
