### ISSUE TITLE
Waterbody FCodes

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#119]
Tyler the NHDPlusHR layer for waterbodies has an FCode. Can you please research what these FCodes refer to and provide a list of possible values. Here's a screenshot example from HUC 16030504.

<img width="699" alt="Screen Shot 2020-11-25 at 1 32 30 PM" src="https://user-images.githubusercontent.com/8645379/100283665-c5de3600-2f22-11eb-973c-57990a8f03d6.png">

**Comment by tyler1218hatch** [comment]
From [here.](https://nhd.usgs.gov/userGuide/Robohelpfiles/NHD_User_Guide/Feature_Catalog/Hydrography_Dataset/Complete_FCode_List.htm)

Feature Type | FCode | Description
-- | -- | --
ESTUARY | 49300 | feature type only: no attributes
ICE MASS | 37800 | feature type only: no attributes
LAKE/POND | 39000 | feature type only: no attributes
LAKE/POND | 39001 | Hydrographic Category\|intermittent
LAKE/POND | 39004 | Hydrographic Category\|perennial
LAKE/POND | 39005 | Hydrographic Category\|intermittent; Stage\|high water elevation
LAKE/POND | 39006 | Hydrographic Category\|intermittent; Stage\|date of photography
LAKE/POND | 39009 | Hydrographic Category\|perennial; Stage\|average water elevation
LAKE/POND | 39010 | Hydrographic Category\|perennial; Stage\|normal pool
LAKE/POND | 39011 | Hydrographic Category\|perennial; Stage\|date of photography
LAKE/POND | 39012 | Hydrographic Category\|perennial; Stage\|spillway elevation
PLAYA | 36100 | feature type only: no attributes
RESERVOIR | 43600 | feature type only: no attributes
RESERVOIR | 43601 | Reservoir Type\|aquaculture
RESERVOIR | 43603 | Reservoir Type\|decorative pool
RESERVOIR | 43604 | Reservoir Type\|disposal-tailings pond; Construction Material\|earthen
RESERVOIR | 43605 | Reservoir Type\|disposal-tailings pond
RESERVOIR | 43606 | Reservoir Type\|disposal-unspecified
RESERVOIR | 43607 | Reservoir Type\|evaporator
RESERVOIR | 43608 | Reservoir Type\|swimming pool
RESERVOIR | 43609 | Reservoir Type\|treatment-cooling pond
RESERVOIR | 43610 | Reservoir Type\|treatment-filtration pond
RESERVOIR | 43611 | Reservoir Type\|treatment-settling pond
RESERVOIR | 43612 | Reservoir Type\|treatment-sewage treatment pond
RESERVOIR | 43613 | Reservoir Type\|water storage; Construction Material\|nonearthen
RESERVOIR | 43614 | Reservoir Type\|water storage; Construction Material\|earthen; Hydrographic Category\|intermittent
RESERVOIR | 43615 | Reservoir Type\|water storage; Construction Material\|earthen; Hydrographic Category\|perennial
RESERVOIR | 43617 | Reservoir Type\|water storage
RESERVOIR | 43618 | Reservoir Type\|unspecified; Construction Material\|earthen
RESERVOIR | 43619 | Reservoir Type\|unspecified; Construction Material\|nonearthen
RESERVOIR | 43621 | Reservoir Type\|water storage; Hydrographic category\|perennial
RESERVOIR | 43623 | Reservoir Type\|evaporator; Construction Material\|earthen
RESERVOIR | 43624 | Reservoir Type\|treatment
RESERVOIR | 43625 | Reservoir Type\|disposal
RESERVOIR | 43626 | Reservoir Type\|disposal; Construction Material\|nonearthen
SWAMP/MARSH | 46600 | feature type only: no attributes
SWAMP/MARSH | 46601 | Hydrographic category\|intermittent
SWAMP/MARSH | 46602 | Hydrographic category\|perennial

**Comment by philipbaileynar** [comment]
Perfect. Thanks @tyler1218hatch

**Comment by philipbaileynar** [comment]
I have assigned myself the task of migrating this to a CSV for inclusion in any of our tools. VBET is the obvious candidate, but it might be useful elsewhere.

**Comment by philipbaileynar** [comment]
It's good to have these codes on hand. They might be useful in VBET as we might consider some of these waterbody types valley bottom (e.g. swamp and marsh) but not others (reservoir).

**Comment by philipbaileynar** [comment]
Issue #347 has superseded this issue now. Thanks for the early research.
