### ISSUE TITLE
Produce Example River Style Tree for Initial Set of Styles

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#121]
Please produce a tree for one or more styles. Can be a diagram, document or markdown in vignette.

**Comment by lauren-herbine** [comment]
# Deciding Decisions

*A Research Vignette Gist*

--------

**Author** - [Lauren Herbine](http://etal.joewheaton.org/lauren-herbine.html)

**Date** - 2 November, 2020

**Study Site(s)** - MRB

**Project** - Mississippi River Styles

-------

## Question / Problem

Here I attempt to provide a framework with decision points that will guide the creation of the rstyle tool and database.

-------

## Idea / Hypothesis

Bierley and Fryirs ([2005](file:///C:/Users/leher/Zotero/storage/WR3LLZ3K/Brierlyey_and_Fryirs_2005_book_River_styles_-_ALL.pdf)) laid out an approach to identifying River Styles using three basic measures: river planform, geomorphic units, and bed material texture. They use valley setting (see figure 1) as the entry point to their classification procedure. 

![](https://docs.google.com/drawings/d/e/2PACX-1vRtuOnTHhKsLsOkLzQOAdhIdxA6-KX31BcoU7uQ57sOrj6z6o6viX3ACziaMwCshLGcNQjVgig5OGT9/pub?w=955&h=343)

*Figure 1: A simple tree outlining Bierley and Fryirs's River Style procedure*

Following this convention, I have sketched out an idea including which decisions need to be made, and what type of decisions those will be. 

-------

## Ideas

* **Confinement**
  * Continuous variable (0-1) broken into 3 categories. Depending on which valley setting the reach is in will determine the next set of questions. "Tier 1 Confinement"
* If the reach is **Partly** **Confined**, it will be further broken into **planform confined** or **margin controlled**. The questions asked from there on down will be the same.
* If the reach is **Laterally** **Unconfined**, we are then concerned with how many channels it has- currently that is achieved by a two step process of channel present or channel discontinuous, with the "present" branch then leading to a number of channels decision. This could be shortened a step by using a braiding index. An index of one would mean one channel, an index of zero would mean discontinuous, and anything over one would indicate multi-channel/braiding. From there it would likely be broken into categories.
* **Degree of sinuosity** is a continuous function that would again likely be broken into categories.
* I'm not entirely sure yet how I will measure **lateral stability** (or even if it is something I will want to stick with), but for now I have it as a categorical decision.
* In a **confined** reach, the reach is either entirely constricted (gorge), or is confined with occasional floodplain pockets (canyon). Currently Fryirs and Bierley get at this by a presence/absence of occasional floodplain pockets, but this could also be evaluated by degree of constriction. Categorical idea:
  * greater than 85% confined, 100% constricted = gorge
  * greater than 85% confined, greater than 50% constricted = ?
  * greater than 85% confined, less than 50% constricted = ?
    * basically just trying describe how often floodplain pockets occur
* Once a River Style is chosen via the tree, geomorphic units and structural elements can be predicted. 



## [Tree](https://docs.google.com/drawings/d/e/2PACX-1vQq1VvHnETX0roaXuG5WJBluaVgkXaa29f2fgioSP8pfzQIqYOWgqKeu-9493-P0qyBaAX-4OrxFNUs/pub?w=2238&h=947)


![](https://docs.google.com/drawings/d/e/2PACX-1vQq1VvHnETX0roaXuG5WJBluaVgkXaa29f2fgioSP8pfzQIqYOWgqKeu-9493-P0qyBaAX-4OrxFNUs/pub?w=2238&h=947)



## Quick Example

![](https://docs.google.com/drawings/d/e/2PACX-1vQDJoKM4pzwQODpcBNcXJ0nc5nJQB0LKZtz9d2_TG5Q25VTr6FQni-O7AYvbfa75b98WSRg1xnokShN/pub?w=1692&h=665)

This includes points of the tree I could derive from aerial imagery. There are tools to predict bed material that would allow further splitting of the tree.

## Resources

- Brierley, G., and K. Fryirs. *Geomorphology and River Management: Applications of the River Styles Framework*. Victoria, Australia: Blackwell Publishing, 2005.

**Comment by lauren-herbine** [comment]
Vignette [here](https://gist.github.com/lauren-herbine/779c265aed5e3abc16a5e31780f5fb13)
