### ISSUE TITLE
Likelihood of being a Valley Bottom Raster

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#13]
I would like to emphasize the output of the new VBET that comes out of the box as a **likelihood of being a valley bottom** cell. This value (between 0 & 100%) we will need @wally-mac and crew to develop a reasonable categorical break and symbology for. 

A helpful byproduct would be contours at 10% increments.  

See also Riverscapes/vbet#4

**Comment by wally-mac** [comment]
@tyler1218hatch let's chat about this during our next meeting. 

Thanks

**Comment by philipbaileynar** [comment]
FYI contouring research is complete. Running either ArcGIS or GDAL contour routines produces nothing of additional value over our own vectorization. 

This leaves this task as the effort to produce symbology for the VBET evidence raster. I'm assigning to @wally-mac so he can then assign to one of the USU crew.

**Comment by wally-mac** [comment]
@tyler1218hatch can you please take on this task? Please coordinate with @philipbaileynar.  Thanks!

**Comment by joewheaton** [comment]
@MattReimer, @KellyMWhitehead and @philipbaileynar will be pleased to see this go away.  This is now done and dusted (see #10).
