### ISSUE TITLE
RSContext to use Geopackages

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#135]
This shouldn't be too much trouble but we need to make some decisions about how to package things

### Unanswered Questions:

1. Are we looking to remove shapefiles completely from this project or just where it makes sense?
2. Do all our tools support reading Geopackages as an input? (I think yes but check)
3. How do we want to package things?

### Packaging Suggestion: Group by function

We could just lump everything into a single geopackage but we might want to consider that separating them into themed geopackages by subject or filesize means our tools can download only what they need (can't download 1 layer from a geopacakge)

**As a starting point I'm going to suggest:**

1. Rasters are their own thing. Keep them out of geopackages.
1. 1 GeoPackage for NHD Data
2. 1 GeoPackage for ownership data
3. 1 GeoPackage for network segmentation? (not so sure about this one)

### Things to check

* [ ] Remove dependencies on `rscommons.shapefile` if possible. This should be the last tool to use it so:
* [ ] Remove any `rscommons.shapefile` methods that are no longer in use.

**Comment by joewheaton** [comment]
@MattReimer I came across this unassigned issue while trying to propose and explore a solution to our looming segmentation issues.  I am not sure but it seems like this is decided and could be closed?

> This shouldn't be too much trouble but we need to make some decisions about how to package things
> 

It seems like we might have already made these decisions? Just in case, I'll provide *my* naive answers below. @philipbaileynar can chime in and we can decide and move on.

> ### Unanswered Questions:
> 1. Are we looking to remove shapefiles completely from this project or just where it makes sense?

For Cyber-Castor production grade tools, we are looking to remove shapefiles completely I think. Even in cases where the raw inputs may be shapefiles, I think we are going to the effort of packaging these up in geopackages instead.

> 2. Do all our tools support reading Geopackages as an input? (I think yes but check)

Yes for Cyber-Castor tools.

> 3. How do we want to package things?
> 
> ### Packaging Suggestion: Group by function
> We could just lump everything into a single geopackage but we might want to consider that separating them into themed geopackages by subject or filesize means our tools can download only what they need (can't download 1 layer from a geopacakge)
> 

I think you have landed on geopackages seperated by inputs, intermediates and outputs:
![image](https://user-images.githubusercontent.com/9723905/132142405-dd19bb83-df27-42f6-8785-812ca4bb82de.png)



> **As a starting point I'm going to suggest:**
> 
> 1. Rasters are their own thing. Keep them out of geopackages.
> 2. 1 GeoPackage for NHD Data
> 3. 1 GeoPackage for ownership data
> 4. 1 GeoPackage for network segmentation? (not so sure about this one)
> 

Is this still relevant?

> ### Things to check
> * [ ]  Remove dependencies on `rscommons.shapefile` if possible. This should be the last tool to use it so:
> * [ ]  Remove any `rscommons.shapefile` methods that are no longer in use.

**Comment by MattReimer** [comment]
I think we can accomplish this now but I also see it as a small priority compared to the other issues in the fall release. Let's make sure everything else gets fixed first and we can do this last I'd there's time

**Comment by joewheaton** [comment]
@MattReimer I was asking if there was anything left to do? It seems like this is already done and can be closed. But it sounds like there is some stuff to do? If so, I agree it is a low priority.

**Comment by MattReimer** [comment]
Yes, There are still a whole bunch of shapefiles in RSContext. Mostly NHD products. We do have one geopackage I used to do segmentation but this ticket was more about using geopackages for all the NHD data etc.

**Comment by joewheaton** [comment]
Oh... got it. Seems like a low priority to change up Riverscapes Context. I'd vote to just leave these alone (we convert them to geopackages upon ingestion into our actual tools.

**Comment by MattReimer** [comment]
I don't think there's any remaining work here so I'm closing this issue. Re-open if you disagree.
