### ISSUE TITLE
RCA Research

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#139]
We are on the hook to produce a version of RCAT. We are close, having made progress on several of the inner tools. The last missing piece is [RCA], capturing in this image:

![rca](https://rcat.riverscapes.xyz/assets/images/RCA_workflow.png)

The goal of this ticket is to research the [RCA code](https://github.com/Riverscapes/RCAT/blob/master/RCA.py) and report back on complexity and feasibility of tackling it. The code is long, but I think we have covered much of it in other tools.

## Notes

RCA requires land use intensity. The BRAT data model (see VegetationTypes and LandUses tables below) already has a dataset that converts LandFire EVT to land use intensity. It's captured in a list of [LandUseIDs](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/brat/database/data/LandUses.csv) that I believe are attributes of the LandFire EVT raster.

![brat data model](https://docs.google.com/drawings/d/e/2PACX-1vStWrxD4ZPoZqWN90m3BdNOpaAwT6rVSzUAUWixsePOJGKYWLKEOxgmHGkEhKx0o6ia_wxztdJVdZGi/pub?w=1021&h=807)

My preference here would be to incorporate the land use and/or intensity rasters into the riverscapes context project as a dedicated raster. Advantages: it's a valuable contextual layer that lots of folks could benefit from. Disadvantages: the conversion from land use to intensity is judgemental and we have tried to keep RSC as pure, unbiased data. Perhaps @MattReimer has some thoughts on this.

**Comment by MattReimer** [comment]
We could always fracture land use into its own RS project. Seems a bit weird to do it for one raster but I don't want to have any more than one of these in a riverscapes project and if two people have different ideas of what it should be we're kind of hooped. 

We're going through the same pain for hand rasters (#131) right now, trying to figure out where they fit and how they should be packaged.

There's nothing wrong with having small RSProjects that have one layer in them. 

On the other hand if they really are opinionated about it maybe we just do it in every tool that requires it separately and eat the extra processing.

**Comment by philipbaileynar** [comment]
It just occurred to me that there's one lookup table for the entire nation and one raster (Landfire EVT) this could just be a new raster in the national project... Or a new project with a single national raster in it.

**Comment by philipbaileynar** [comment]
@jtgilbert has developed a new version Riverscapes Compliant version of RCAT
