### ISSUE TITLE
Research pyNHD

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#147]
This python package looks extremely valuable. We need to research it and see if it replaces our ScienceBase retrieval of NHD data.

https://github.com/cheginit/pynhd

See related issues on researching py3DEP (#145) and also including NHD 1:100K in riverscapes context (#146).

And here's the link for the umbrella [Hydrodata](https://hydrodata.readthedocs.io/en/latest/) initiative.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead can you post some follow-up here please?

**Comment by joewheaton** [comment]
@philipbaileynar and @KellyMWhitehead did  you guys ever have a further play with this. I just had a poke around and it does look really useful. @philipbaileynar this seems particularly relevant to conversations you and I had this week about APIs for some of our metric generation.

**Comment by joewheaton** [comment]
Pretty cool cross section functionality too: https://hyriver.readthedocs.io/en/latest/notebooks/cross_section.html 
We could use this to pull some valley bottom cross sections for folks in Riverscapes Studio...

**Comment by philipbaileynar** [comment]
Researched. Interesting. The National Map supersedes this thinking.
