### ISSUE TITLE
Attribute Tables in GPKG need to be written to gpkg_contents

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#149]
All non-spatial tables in gpkg need to be referenced in the gpkg_contents table.  See [Requirement 118](https://www.geopackage.org/spec121/index.html#attributes).

I don't think this affects QGIS, but ESRI doesn't 'see' non-spatial tables unless this is done. 

This is all ready applied to the [schema for RVD ](https://github.com/Riverscapes/riverscapes-tools/blob/d86017907e1b655b9cf9a85c53f16f39e839857b/packages/rvd/database/rvd_schema.sql#L25).

**Comment by MattReimer** [comment]
No action here. Jut a reminder going forward.
