### ISSUE TITLE
Implement new HAND Method in Python

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#151]
***NB: This is a stub issue for now. As we know more about how HAND will be implemented we should fill in the details.***

After myself and @KellyMWhitehead 's investigation we now have a working (albeit somewhat manual) process for calculating hand

We have the idea that HAND might be an inline part of VBET so we'll need a python module that [can run `tauDEM` as a subprocess](https://docs.python.org/3/library/subprocess.html). 

It will be really important to capture errors such as the `killed` error referenced in #131 that resulted from a lack of RAM.

## Update

I've implemented a subprocess call using the pattern I think we want. The one I wrote calls RSCli but it can be patterned and adapted to work with tauDEM

https://github.com/Riverscapes/riverscapes-tools/blob/sanitize_fix/packages/vbet/scripts/subprocess.py#L7-L27

### Related Issues

* #131 
* #111

**Comment by KellyMWhitehead** [comment]
HAND script generated in 1d035e27bdb82fc52e38e6e22d623f6d3ae99b0f and added to VBET in 4b68e6efb3b6fdd4aed9cf383d783dfb6da05d7c
