### ISSUE TITLE
RVD Memory consumption problem

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#155]
Memory consumption in the load_vegetation function seems to scale linearly with the size of the raster input. This is not sustainable since any raster bigger than a threshold will kill the tool

Good example huc is: 10190003

### The problem

The issue is that we're [operating over the whole array](https://github.com/Riverscapes/riverscapes-tools/blob/dev/packages/rvd/rvd/lib/load_vegetation.py#L134) which necessitates [multiple arrays of the same shape as the entire raster](https://github.com/Riverscapes/riverscapes-tools/blob/dev/packages/rvd/rvd/lib/load_vegetation.py#L146-L151). 

The vegetation rasters are much lower resolution than a DEM but still, loading multiple copies into memory eventually causes a crash and means that there will always be an upper limit to the size of raster we can use.

### Proposed Solution

The way to get around this is to use a windowing function when we read the raster and only operate over part of it. 

[We already write intermediate rasters](https://github.com/Riverscapes/riverscapes-tools/blob/dev/packages/rvd/rvd/rvd.py#L237) so we can use more of them to get the array out of memory.

A big caveat here is that, given the way it runs now, we need to do [statistics over the whole array](https://github.com/Riverscapes/riverscapes-tools/blob/dev/packages/rvd/rvd/rvd.py#L451-L452). We need to account for this.

**Comment by MattReimer** [comment]
THis is more of a refactor than I was hoping. Let's punt to Feb release.

**Comment by MattReimer** [comment]
#191 is an upstream effect. Now we have memory profiling though. We can generate a plot and look at how much memory is used and where that process is.

**Comment by philipbaileynar** [comment]
RVD was deprecated and replaced with @jtgilbert new Riverscapes compliance RCAT.
