### ISSUE TITLE
BRAT is not deleting the correct Watershed Parameters

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#157]
When BRAT build finishes building the SQLite database it attempts to save space by [deleting all watersheds except the one pertaining to the run](https://github.com/Riverscapes/riverscapes-tools/blob/32be61538d5782ab7438c5a51659fbe68e3c6ed8/lib/commons/rscommons/database.py#L87) that is being performed.

I am looking at the database for [18010201](https://data.riverscapes.xyz/#/PUBLIC_DATA/a56806c2-7c26-4a28-8e4c-97632382176b) that Kelly ran as part of our BRAT geopackage testing. Sure enough there's only one watershed record present. But the WatershedHydroParams table contains records for other watersheds. It doesn't look like the cascade delete has worked.

here's the [schema](https://tools.riverscapes.xyz/brat/Technical_Reference/database.html) for reference.

**Comment by philipbaileynar** [comment]
Looks like foreign keys are disabled by default (for backwards compatibility). 

https://sqlite.org/foreignkeys.html#fk_enable

and need to be enabled for each connection:

```python
con.execute("PRAGMA foreign_keys = ON")
```

I feel like I knew this, but apparently not...

**Comment by philipbaileynar** [comment]
Apparently I implemented it in some places, but not all...

https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/database.py#L369

**Comment by MattReimer** [comment]
# Before closing test:

- [ ] BRAT Build. TEST: Geopackage watershed hydroparams make sure only params left are for the huc I ran.
- [ ] RVD

**Comment by MattReimer** [comment]
Verified after cybercastor run. This is closed
