### ISSUE TITLE
Missing EVT and BPS Values for BRAT

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#171]
We've updated the National project to the latest landfire values

As a result there are new EVT and BPS values we haven't captured in our [VegetationTypes.csv](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/brat/database/data/VegetationTypes.csv) file

I've added NULL values for everything we don't have. We'll need suitability values though.

Here's a handy google sheet with some information about what's missing.
https://docs.google.com/spreadsheets/d/1w5tCahI5xZc1fguFx6C1oQYUtcr5DSkXRkPJ_DIcyEQ/edit#gid=466376598

### Resources

* [National Landfire](https://www.landfire.gov/version_comparison.php)
* [LF2016_BPS_200_CONUS.zip](https://www.landfire.gov/bulk/downloadfile.php?FNAME=US_200_mosaic-LF2016_BPS_200_CONUS.zip&amp;TYPE=landfire)
* [LF2016_EVT_200_CONUS](https://www.landfire.gov/bulk/downloadfile.php?FNAME=US_200_mosaic-LF2016_EVT_200_CONUS.zip&amp;TYPE=landfire)

**Comment by philipbaileynar** [comment]
@tyler1218hatch I have added some additional LandFire 2.0.0 EVT and BPS codes to the Postgres database. I'm unsure why these were missing but their absence was causing some BRAT runs to fail.

Note that all new vegetation types get a default suitability of zero. Please review and update any that look obviously wrong and should have a higher suitability.

New Existing Vegetation Codes
`SELECT * FROM vegetation_types WHERE created_on >= '2021-01-21' AND epoch_id = 1`

New Historic Vegetation Codes
`SELECT * FROM vegetation_types WHERE created_on >= '2021-01-21' AND epoch_id = 2`

You can close this issue once you've completed your review.

**Comment by tyler1218hatch** [comment]
@philipbaileynar This will probably take a while. Is it alright if I do this over the weekend, or is this urgent?

**Comment by philipbaileynar** [comment]
This is not urgent. BRAT will run with the default values of zero. 

To be honest... We have run a lot of HUCs already that would have choked if these vegetation types occurred. So we can assumed that these missing values are for veg types that are uncommon close to rivers in the Pacific Northwest. 

I would suggest spending less than 30 mins on this. I'm just looking for any that stand out and warrant a value other than zero. 

We can always catch any zeros using the brat report when we review runs.

**Comment by tyler1218hatch** [comment]
@philipbaileynar Okay, this is done. This was mostly coastal/island stuff, so I doubt it will ever come up. This was a pretty quick job, so if we ever do those areas, we should revisit these.

**Comment by philipbaileynar** [comment]
Thanks @tyler1218hatch. The updated values look good. I'm surprised at how many values changed though! Several hundred changes. Not a problem. Just confirming.

**Comment by philipbaileynar** [comment]
@MattReimer I should be clear. These changes are pushed on dev (not master).

**Comment by tyler1218hatch** [comment]
@philipbaileynar Yeah, it was quite a lot that changed. Most of them were vegetation classes we had already identified, but with different regional prefixes. Lots of Suitability values of 1 and 2. Only about 1/3 of the data was actually veg that should be classed as 0.
