### ISSUE TITLE
Change Units on Fair Market Value to more useful

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#177]
Thanks for getting Fair Market Value Raster into Riverscape Context (#113)!

We cannot _easily_ do the symbology until we use the rasters that @tyler1218hatch  created Right now they are in log of $ per hectare. It is only 250 MB for whole country.  I added symbology  I want in https://github.com/Riverscapes/RaveAddIn/pull/109, but first we need to:
- [ ] Substitute Tyler's [Raster with values converted to USD/ha](https://usu.box.com/s/0datkpqdm2c0g111fogc25w848y6iejn) into National Project
- [ ] Re-Run or update all existing Riverscape Context Projects so they have the correct raster (otherwise, my pull request will not work as it for existing one that is log base 10

> [Raster with values converted to USD/ha](https://usu.box.com/s/0datkpqdm2c0g111fogc25w848y6iejn). @philipbaileynar I'll leave it up to you and @joewheaton whether you want the final raster in these units or the log form. These units are more easily understandable, but it may be difficult/impossible to have a logarithmic color ramp with 10.4 layer files. (You could definitely do it with categorical data, so if we want to bin these values instead, that could work too.)

**Comment by philipbaileynar** [comment]
@MattReimer I done gone and messed up by putting the wrong raster on AWS. Sorry. I have now uploaded @tyler1218hatch correct raster onto AWS. It has the word "converted" in the file name.

//nardata/fair_market_value/FairMarketValueConverted.tif.zip

**Comment by philipbaileynar** [comment]
@MattReimer there's a new RAVE release that includes Joe's synmbology and business logic for the correct raster. Please let me know once this change is complete and I will test it out in RAVE.

**Comment by MattReimer** [comment]
National project updated, the EFS is synced. I've kicked off a sample RSContext task we can use to verify

**Comment by MattReimer** [comment]
@philipbaileynar Here it is for verification on the staging server
https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/e8dc9670-3c03-4aac-95df-557b309f35c2
