### ISSUE TITLE
VBET Noise in Urban Areas

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#180]
When the Slope reflects urban areas we end up with a thresholded raster that crashes GDAL polygonize function.

There are two facets to this problem:

1. **Methodology**: Obviously streets are not valley bottoms. We should find a way to filter this out.
2. **Implementation:** Regardless of methodology, when we miss these cases it shouldn't crash the tool. It would be nice to find a solution that allows the tool to run to completion so we can see that there's a problem.

<img width="1118" alt="Screen Shot 2021-01-25 at 3 38 32 PM" src="https://user-images.githubusercontent.com/1063391/105890521-55a46d00-5fc4-11eb-8577-78534d1c173e.png">
<img width="1118" alt="Screen Shot 2021-01-25 at 3 38 59 PM" src="https://user-images.githubusercontent.com/1063391/105890530-589f5d80-5fc4-11eb-85b7-a6c567d9fae4.png">

**Comment by philipbaileynar** [comment]
@joewheaton what is the VBET of and urban area? What is valley bottom downtown San Francisco or Denver? Do we mask these areas out of a national run?

**Comment by KellyMWhitehead** [comment]
Building vbet polygons by reach has improved some of the memory crashes associated with this issue. We can revisit this if geometry quality issues persist.
