### ISSUE TITLE
50% thresholding discards main shape for HUC 10190005

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#182]
Looks like we're getting the wrong shape chosen for the output

After investigation the problem is that our sanitization method is finding the main polygon to be invalid, even after removing small donuts and buffer +/- tricks

Not too hard to see why:

<img width="736" alt="Screen Shot 2021-01-26 at 12 23 46 PM" src="https://user-images.githubusercontent.com/1063391/105901356-17ae4580-5fd2-11eb-9878-fa39bb5ca19b.png">

* puke green is 60% and is working fine
* pink is 50% and after all our sanitization it's still coming back invalid. Not too surprising given the mess around the edges

**Comment by philipbaileynar** [comment]
The new transform curves are introducing lots of noise in these polygons. All those slivers, donuts and island polygons are extra vertices. Not only do they bloat the geometry, but they also increase the risk of the polygon having invalid geometry and crashing VBET.

A really simple fix that would eliminate a LOT of this mess would be to grow ([nibble](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/nibble.htm) in ESRI speak) and then [shrink](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/shrink.htm) the raster by a few pixels. It's an old trick for smoothing the edges of polygons.

**Question: What is the open source raster operation for grow and for shrink?**

**Comment by MattReimer** [comment]
The raster shrink and grow speeds up VBET by a lot and also seems to work in bringing back the 50% thresholding layer
