### ISSUE TITLE
Extensible topographic evidence rasters

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#184]
The VBET workflow includes two general types of evidence that can be broken down further into sub types:

* Channel evidence
    * flow areas
    * flow line network
* Topographic Evidence
    * slope
    * HAND

We want to extend VBET to allow *n* topographic lines of evidence. So essentially we want to be able to provide a list of topographic rasters (always rasters) together with a corresponding transform name that corresponds to a transform curve that exists in the VBET database. Each input rasters gets transformed with it's own transform then combined by the associated weight into the topographic evidence raster.

[VBET workflow diagram](https://docs.google.com/drawings/d/1y_oxpbfGhOBFRdirW1MyyldK_-G0q93kkpH7Vuu0qHs/edit?usp=sharing)

**Comment by joewheaton** [comment]
@MattReimer this is now superseded by #10 and #369. Closing.
