### ISSUE TITLE
Confinement Intermediates

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#188]
1. Confinement needs and intermediates geopackage (like our other tools).
2. Move all "DEBUG" layers to the intermediates geopackage.
3. Drop the prefix "DEBUG" from the buffers intermediate. Call this layer "bankfull channel".

Collaborate with me once this is done so that I can make the corresponding enhancements to RAVE.

**Comment by MattReimer** [comment]
Verified by @KellyMWhitehead for the JAN27 staging run
