### ISSUE TITLE
RVD project layers

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#189]
RVD is producing tons of intermediates that are not referenced in the project. This makes them impossible to include in RAVE.

<img width="226" alt="Screen Shot 2021-01-26 at 8 26 29 PM" src="https://user-images.githubusercontent.com/8645379/105942797-c83d3900-6014-11eb-81f8-5b9d57cf0ae7.png">

All intermediate layers (both vector and raster) must be included in the project file.

Once these are in the project file, do an RVD run, zip it up and get it to me, then help me develop the business logic to make these layers available.

**Comment by joewheaton** [comment]
Can we schedule a time to go through these together? Looks like most of
things are there...

**Comment by philipbaileynar** [comment]
@KellyMWhitehead crushed the RVD layers. We collaborated on the business logic and now this is the new RVD projected tree. We even threw a default view in too. (The red exclamation is a known issue.)

I am talking to USU on Monday to hand off the task of developing the symbology.

<img width="1229" alt="Screen Shot 2021-01-27 at 1 27 02 PM" src="https://user-images.githubusercontent.com/8645379/106056442-83141800-60a3-11eb-810a-d3f54e51679c.png">

**Comment by KellyMWhitehead** [comment]
RVD project updated to include these layers ad05e7372ffdb5b2010d59e49f339ba6db825eb5

Rave business logic updated deedc7bc46641f6d09e84257f8a6c5a4669f0f30

**Comment by joewheaton** [comment]
Nice job gents. One layer I did not see, was the RVDT or riparian vegetation departure type:
![image](https://user-images.githubusercontent.com/9723905/106062557-2d943700-60b4-11eb-8179-25c22e3ed01e.png)

**Comment by joewheaton** [comment]
Here's an [example RCAT (1.0.11) project](https://usu.box.com/s/1ot4804zws6iijjtzo9w4774krkystcs) with layer package with symbology.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead is the departure type stored in an attribute? If so, which attribute please?

**Comment by KellyMWhitehead** [comment]
This is stored the `ConversionType` field.

**Comment by philipbaileynar** [comment]
Thanks @KellyMWhitehead I see the field. 

The good news is that RAVE already has layer files for all the RCA layers. The bad news is that the field names have changed and so you get a classification but no features in the map (see below).

The tough work here is that when you edit the symbology in ArcGIS and point it at the correct field, ArcGIS wipes clean all the symbology and you have to start building each individual symbol class from scratch. I haven't found a workaround to this incredibly frustrating feature of Arc. @tyler1218hatch or @Cashe93 do you have any ideas or how to avoid this setback?

<img width="1423" alt="Screen Shot 2021-01-27 at 4 22 43 PM" src="https://user-images.githubusercontent.com/8645379/106071841-e4e07c00-60bb-11eb-97c0-879bd48c773c.png">

**Comment by philipbaileynar** [comment]
Outstanding tasks are now in RAVE being tracked in the following issue:

https://github.com/Riverscapes/RaveAddIn/issues/114
