### ISSUE TITLE
Confinement Channel Buffer

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#204]
Add percent buffer to confinement channel.

**Comment by philipbaileynar** [comment]
Remind me, this is % of bankfull or % of raster cell size?

**Comment by KellyMWhitehead** [comment]
I'm going to start with % of cell size, but might try % of bankfull as well.

**Comment by KellyMWhitehead** [comment]
updated with d5a593df85a5b5ac86a60414e99e8250bf1c9592

Added 2 knobs to play with:

min_buffer = the minimum buffer value to use if bf is below this value. Ideally this should be something like the raster resolution of the dem (Confinement does not currently use any rasters, but we could go the route of providing a reference raster if that is a better approach).

bankfull_expansion_factor: Similar to how the original confinement was run, a multiplication factor to the bankfull before buffering (1=no change, 1.5 = add 50% bankfull width, 2= twice the bankfull, etc). I propose setting this to 2 for now, but its another knob we can adjust.

The current settings (10m, 2x) do not push the confinement buffers far enough while using vbet 50, but we can work on finding the combination that best represents confinement.

**Comment by KellyMWhitehead** [comment]
merged into dev d5a593df85a5b5ac86a60414e99e8250bf1c9592
