### ISSUE TITLE
VBET and RVD Verification

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#207]
We need to do a quick QA on RVD and the new hand technique. WHen this checks out I'll transfert the RVDs to the production warehouse.

### RVD Klamath (Tagged: FEB8)

- [x] [18010203](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b87fafb9-0d6d-4395-800c-22a16476c072)
- [x] [18010201](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/89f7fde8-14f5-4f6d-b016-48a932fcd9cd)
- [ ] [18010202](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/fe1d524e-abb4-4bdf-8ee1-80dae3fcc286) 

### VBET Hand (Tagged: TEST,FEB8,NEW_HAND)

- [x] [10190010](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/aa053774-1597-4325-bb04-b40501ab0dfc)
- [x] [18010203](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/5c8916f5-de23-472f-a448-aca330d741f3)
- [x] [10190004](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/390baf49-d640-48bc-94d5-087a9f311b8a)
- [x] [17060304](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/ed3f63f1-94c7-4482-8566-74512f728fa8)
- [x] [18010201](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/9559e559-3c91-46c8-9947-057715477162)
- [x] [18010202](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b9519e7e-27ff-4d39-9a3e-594aebfff453)
- [ ] [10190005](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/3288d5e5-ff7a-458b-9c41-5b81ec478b34)

**Comment by KellyMWhitehead** [comment]
RVD seems to be missing "RiparianDeparture" column from outputs. I see it does exist in ReachAttributes table.

Otherwise RVD seems to be correct.

**Comment by KellyMWhitehead** [comment]
Vbet checks out.

Note RAVE has an update that needs to be pulled for the correct HAND business logic.

**Comment by philipbaileynar** [comment]
RAVE 2.0.6 released tonight with @KellyMWhitehead VBET business logic improvements.
