### ISSUE TITLE
Confinement Reach Code filtering

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#212]
Confinement needs the same reach code filtering as our other tools, VBET and BRAT.

Currently confinement is producing results for canals!

Features that have a an FCode that is not in the argument list should be filtered out.

Be sure to assign this issue to @MattReimer after confinement is changed because cyber castor will need to tweak the arguments that it is providing to the tool during automated runs.

**Comment by KellyMWhitehead** [comment]
Fixed in 063d04103c3c2be6b1f74d50746d17c3470f0ce5

@MattReimer Note confinement now uses the same reach codes argument as RVD. Meta argument also added.

**Comment by MattReimer** [comment]
THe arguments have been updated.
