### ISSUE TITLE
VBET Bankfull Buffer Intermediate LAyer

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#213]
VBET needs an intermediate layer that is the flow line network buffered by the bankfull width attribute. This isn't needed by the VBET algorithm or any kind of processing, it's purely for cartographic purposes. (Confinement almost has this layer but it has awkward square ends to the buffers for some processing reason. The VBET version of this layer should use rounded buffer ends.)

VBET has currently has the flow line network buffered by the distance used for analysis (which I think is the maximum of the bankfull attribute or 1 raster cell width). This is correct for analysis and should be kept.

**Comment by KellyMWhitehead** [comment]
Moving this layer to RS Context per https://github.com/Riverscapes/riverscapes-tools/issues/12#issuecomment-696262639
