### ISSUE TITLE
Compression not turned on for Raster layer copy

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#217]
This is a problem with [`rasterio.shutil.copy` in `project.add_project_raster`](https://github.com/Riverscapes/riverscapes-tools/blob/dev/lib/commons/rscommons/classes/rs_project.py#L361). This is the only use of `rasterio.shutil.copy` in the entirety of the code so the scope here is minimal, even if the effect will be large.

It seems that the copy doesn't include compression. We should search for all uses of this code and make sure raster compression is turned on.

### Resources

* Rasterio Docs https://rasterio.readthedocs.io/en/latest/api/rasterio.shutil.html
* Compression types guide https://kokoalberti.com/articles/geotiff-compression-optimization-guide/

**Comment by KellyMWhitehead** [comment]
Note we are limited by what will arcgis will play with: https://desktop.arcgis.com/en/arcmap/10.6/manage-data/raster-and-images/raster-compression.htm

Moving forward with LZW compression and predictor = 2.

**Comment by KellyMWhitehead** [comment]
Fixed: b6076c44719b33e8def821b937b1f10dff59372d

**Comment by MattReimer** [comment]
Hey @KellyMWhitehead , Can you just confirm this is working:
https://data.riverscapes.xyz/#/PUBLIC_DATA/1cd8714a-4352-44d7-b022-2402f7cff8ba
then move this ticke to "Done" in the project

**Comment by KellyMWhitehead** [comment]
All rasters in this project are compressed.
