### ISSUE TITLE
Braiding Index/Threadedness Metric

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#232]
@joewheaton @lauren-herbine Looking for guidance on how we would like this metric generated. 

I will start by looking at what we generated in arcGNAT, but let me know if there is preferred method we want to use.

**Comment by lauren-herbine** [comment]
Still looking into this, but this is what I am deciding between (from [Agozi and Ashmore](https://www.researchgate.net/publication/41733339_Defining_and_Measuring_Braiding_Intensity)):

* Bar indices **(not using)**
* Channel count index
  * mean number of links intersected by cross-sections of the river in successive river lengths. River lengths are defined by cross-sections sufficiently far apart that the cross-sections do not cross the same links (or segments) of the network more than once. The number of channels (segments) is then averaged for the river lengths of interest
  * total number of links (or segments) in the measured reach
* Channel length index/total sinuosity
  * the total length of channels per unit length of river; now often referred to as ‘total sinuosity’ 
  * a variant of total sinuosity that substitutes the (straight line) reach length with the length of the main channel


I'm thinking that a ratio of the length of the main channel to the total length of channels (last bullet point above) would be most appropriate. Anything to do with bars will be stage dependent and I'm assuming very hard to develop a geospatial tool for. For channel count index we would have to make new measurements and calculations, while the channel length index would just be a calculation based on information we already have (from NHD). Thoughts @joewheaton ?

**Comment by KellyMWhitehead** [comment]
Low Priority Metric. 

Reopen if we want to calculate this.
