### ISSUE TITLE
Flow Regime

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#233]
* What flow regime metric do we want for GNAT and Mississippi reach typing?
* What units?
* Input data sources

**Comment by lauren-herbine** [comment]
## Data source:
The [Oak Ridge National Laboratory](https://hydrosource.ornl.gov/node/251) developed the U.S. Stream Classification System (USSCS) to group streams according to five different variables: hydrologic class, stream size class, stream gradient class, stream temperature class, and stream confinement. Their interactive tool classifies (in most cases) down to the HUC 12 level. 

ORNL has [developed hydrologic classes](https://hydrosource.ornl.gov/sites/default/files/2020-10/ORNL_Stream_ClassTool_UserManual2015.pdf) based on landscape, climate, topography, and soil attributes
