### ISSUE TITLE
confinement metric

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#235]
From VBET, using the 80% confidence threshold (@joewheaton would you agree with using the 80 vs. 90%?). 

A continuous metric, units will be % confined. 

When this is used in the decision tree, we will threshold into categories (same/similar to the River Styles we're familiar with: confined, partly (planform and bedrock controlled) confined, laterally unconfined). Might add an anthropogenically confined.

**Comment by joewheaton** [comment]
We need to punt on this decision until @philipbaileynar and @KellyMWhitehead and I tweak the parameters for drainage area and, more importantly, the transform functions. Based on what it is spitting out now, I think for confinement 60% or 70% are likely better choices than 80% or 90%. However, that behavior will be changing shortly.

**Comment by lauren-herbine** [comment]
Ok, great, thanks for the input @joewheaton !

**Comment by philipbaileynar** [comment]
1. Yes, let's wait until we have VBET parameterized to pick which VBET threshold we use. 
2. But what we can do now is get defintions for the levels of confinement that you listed up top...

Please define (in quantitative terms of percent):

* Confined
* Partly confined
* Laterally unconfined.

The definition can change, but please provide an initial set that we can start with.

**Comment by lauren-herbine** [comment]
- Confined: >90% confined
- Partly Confined: Bedrock controlled: 50-89% confined
- Partly Confined: Planform controlled: 10-49% confined
- Laterally unconfined: <10% confined

@philipbaileynar
