### ISSUE TITLE
tribs count

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#239]
How do we want to measure this for GNAT and Mississippi reach typing?
What units?
Input data sources

**Comment by joewheaton** [comment]
See #241 and #249.

**Comment by lauren-herbine** [comment]
moving this to hard no and replacing with Trib Impact (should also give us a count of tribs, so having a pure trib count metric seemed redundant) and Confluence/Diffluence count (#241 measured using #249)
