### ISSUE TITLE
active vs. inactive valley bottom

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#245]
What metric do we want for GNAT and Mississippi reach typing?
What units?
Input data sources

**Comment by joewheaton** [comment]
> What metric do we want for GNAT and Mississippi reach typing?
We want active channel, active floodplain and inactive floodplain.
>What units?
These are fundamentally just proportion of valley bottom area, derived by taking there polygon areas (within the valley bottom sausage segment) and dividing by total valley bottom area. 
Intermediates it is helpful to have these in acres, square kilometers, square miles, square meters. 
>Input data sources
- Ocular estimate of proportions.
- Actual measurement of area from polygon areas (intersected to valley bottom sausage segment).

**Comment by joewheaton** [comment]
@lauren-herbine this issue sort of went dormant, but is essentially now part of VBET. 

@shelbysawyer we are displaying in "Estimated Valley Bottom" Geomorphic Units Active as likelihood 0.99 to 0.8 and inactive 0.8 to 0.68. From what I've seen, this is not a good estimate.  I am speculating that 0.9 will be better as a rough-cut of active vs. inactive. As such I have requested @KellyMWhitehead to change this in #415.

**Comment by joewheaton** [comment]
This is answered.
