### ISSUE TITLE
Zonal Attributes Tool

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#249]
Develop a tool to summarize point, line or polygon attributes by polygon zones, similar to arcgis Tabulate Intersection tool.

GNAT uses include
* tributary Junctions
* Confluence counts
* Diffluences/Bifurcation counts

**Comment by joewheaton** [comment]
This will be used in citizen beaver and jam counts as well. This is a great idea. What we need to keep an eye on is essentially a count of all features and optionally all features of specific attribute type. 

## Tools or Items we count  that will use this:
We will be using this in a ton of different tools:
- BRAT Dam Census
- BRAT Dam Generator
- Citizen Beaver (note counts may represent count groups e.g. a complex with its own count)
- Jam & Dam surveys - fmLTPBR Planning & Monitoring
- LTPBR Structures - fmLTPBR Design & Monitoring
- GUT - GU samples (e.g. count pools or diagonal bars or riffles), and GU census
- Network nodes - anabranch confluence, tributary confluence, anabranch difluence, channel head

## What we're tracking
### What is the primary measurement
For most riverscape tools, we want to know the primary a measurement of :
- How many of these are in this polygon (riverscape) segment or reach - i.e. count of all features
- How many of this type of these are in this polygon (e.g. how many "active" vs. "inactive" beaver dams - i.e. count of features of specific types based on one or two attribute fields.
- How many of these based not just on geometry, but a count attribute. We do a lot of desktop and field data capture events where we get a point location for a collection of features (e.g. a beaver dam complex) where we count the number of dams in it and want that to be what we're summing up).
### Derivative Calculations
Derivative density type summaries that require knowing the area and/or length of the segment (e.g. riverscape valley bottom length, valley bottom area, active area, active floodplain area, active channel main channel length, total channel length (either centerline or thalweg). These collectively then becomes `([#] / [length])` or `([#] / [area])`. Lengths are usually in kilometers or miles but occasionally per 100 m. 

Derivative density summaries include:
- Total Count / Length
- Total Count / Area
- Count by Type / Length
- Count by Type / Area

## Where to start?
It strikes me we should think about the database schema/structure that can accommodate all these and it might be easiest to think about the user interface controls that would be the info query dialog for looking at all these metrics in a specific segment, vs. how each of these could be displayed on a riverscape valley bottom network (segmented) vs. the corresponding drainage network that intersects it.

**Comment by philipbaileynar** [comment]
This ticket predates both RME and QRiS analyses.
