### ISSUE TITLE
Hillshade too dark sometimes

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#252]
I'm not sure why, but occasionally we get hillshades that are way too dark?
![image](https://user-images.githubusercontent.com/9723905/109347321-35203a80-7830-11eb-8f52-fa37f271b724.png)

Any ideas as to why? Is this an easy fix? Notice that the range on the bad one is 221 to 146 whereas the range on the others is 1 to 254.

**Comment by philipbaileynar** [comment]
@MattReimer here's another example. Why might this be happening?

<img width="1638" alt="Screen Shot 2021-03-16 at 10 02 58 AM" src="https://user-images.githubusercontent.com/8645379/111350238-2367d100-863f-11eb-8d6b-db2c09440205.png">

**Comment by MattReimer** [comment]
No idea and kind of impossible to guess before looking at actual pixel values. GDALDem is a pretty black box. Let's find a HUC or two that have this problem and open a bug for myself or @KellyMWhitehead to investigate. 

[GDALDEM](https://gdal.org/programs/gdaldem.html)

Maybe there's a parameter to force the spread. Here are the knobs we get:

```
gdaldem hillshade input_dem output_hillshade
            [-z ZFactor (default=1)] [-s scale* (default=1)]
            [-az Azimuth (default=315)] [-alt Altitude (default=45)]
            [-alg Horn|ZevenbergenThorne] [-combined | -multidirectional | -igor]
            [-compute_edges] [-b Band (default=1)] [-of format] [-co "NAME=VALUE"]* [-q]
```

Offhand I don't see anything that would help. Again though, without investigating pixel values...

**Comment by philipbaileynar** [comment]
@KellyMWhitehead reassigning to you. Can you try running GDALDEM at the command line with a few different parameters to gain some insight please?

**Comment by philipbaileynar** [comment]
@joewheaton we suspect that some DEMs have one or two pixels with rogue values. This is throwing off the raster statistics that are used to determine how to stretch the DEM slope and aspect to hillshade. 

We have looked at the DEMs for one or two affected datasets and we cannot see these rogue pixels either visually or by inspecting the raster histogram. 

This is a really hard problem to solve. It will require a ton of research. We need to balance this with everything else going on right now. We can have VBET and GNAT.... or we can have reliable hillshades.

**Comment by joewheaton** [comment]
Hey @philipbaileynar I hear you. Reading the above made me wonder, perhaps we are not putting a layer file on the hillshades and letting Arc just stretch the greyscale color ramp over actual range of values. Is the difference between some of these that they simply are not being stretched over larger range.

**Comment by joewheaton** [comment]
Hey gents. I figured out this and it is an easy fix. We simply need to make a `hillshade.lyr` and `hillshade.qml` that force the stretching over the full range of 0 to 256. Those where this darkening is happening are simply those that have truncated ranges. I am closing this because it is not a Riverscapes Tool problem. It is a symbology problem:
https://github.com/Riverscapes/RiverscapesXML/issues/243

**Comment by philipbaileynar** [comment]
I was experiencing the same overly dark hillshade raster for a BRAT run in British Columbia. I was playing with some raster processing in QGIS when one of the tools reported a warning that `horizontal and vertical cell sizes are different`. This seemed relevant to hillshade trigonometry and so I reprojected the raster (something we normally try to avoid, but I wanted to resample the raster and force equal cell height and width). Rerunning hillshade  produced a more desireable output!

I could see this problem occurring from NED data where the properties of the original raster tiles are all over the place! 

# Original Hillshade

<img width="968" alt="Screenshot 2022-11-08 at 1 06 42 PM" src="https://user-images.githubusercontent.com/8645379/200675461-006fea8e-2ce3-4402-a19e-21e397502422.png">

# Hillshade after forcing equal cell height and width

<img width="968" alt="Screenshot 2022-11-08 at 1 09 28 PM" src="https://user-images.githubusercontent.com/8645379/200675915-d09daa34-7b7c-4ba6-bf17-ea900c5b9103.png">

FYI @joewheaton @KellyMWhitehead @MattReimer @jtgilbert

**Comment by joewheaton** [comment]
That's interesting... Hmmm.

**Comment by MattReimer** [comment]
This is the tool we use (QGis AND `riverscapes-tools`). 
https://gdal.org/programs/gdaldem.html
