### ISSUE TITLE
VBET re-run job

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#263]
Please re-run VBET for the following HUCs:

* 16050302
* 16040107
* 16040101

Notes:

* Program: Anabranch
* Replace: Yes
* Tags: uses whatever was on these runs last time.
* The goal is to have a copy of VBET for these HUCs that uses the correct HAND raster, not the 1:100K version from Riverscapes context.

**Comment by MattReimer** [comment]
```
SUCCEEDED: (1)
16050302

FAILED: (2)
16040107, 16040101
```

Filed a ticket for the error. Really hoping it's just another memory problem

**Comment by MattReimer** [comment]
Trying a fix to reduce CPU bottlenecking. We'll know in a couple hours

**Comment by MattReimer** [comment]
All done. Should be in the warehouse

**Comment by wally-mac** [comment]
@Cashe93 can you please examine VBET outputs for the 3 LCT focal watersheds (see above)?  Please keep me in the loop on what you find. We'll bring these data into the field with us.

**Comment by MattReimer** [comment]
This is done I think. Closing.
