### ISSUE TITLE
Include Transform Curves in VBET Report 

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#269]
The goal is to include the transform curves used in a particular run into the VBET report.

## Requirements

1. Each transform curve has a
    2. table listing the inflection points
    3. simple MatPlotLib graphic illustrating the curve.
2. Only the transform curves used in the VBET "scenario" are included in the report. (i.e. over time more curves might get added to the VBET database, but only those being actively used in the current run are included in the report.

Keep it simple for this first version. Just dump the table of inflection points and a graphic for each curve. Note that we have existing methods for dumping the table of values, and also the generation of plots (that produce the graphics file in the correct folder).

Here's a mockup of the the report:

# Transform Curves

## Slope Transform Curve

<img width="706" alt="Screen Shot 2021-04-07 at 10 30 44 AM" src="https://user-images.githubusercontent.com/8645379/113909292-61629b80-978c-11eb-84be-5bd381b4faf1.png">

## HAND Transform Curve

<img width="706" alt="Screen Shot 2021-04-07 at 10 30 44 AM" src="https://user-images.githubusercontent.com/8645379/113909292-61629b80-978c-11eb-84be-5bd381b4faf1.png">

## Channel Transform Curve

<img width="706" alt="Screen Shot 2021-04-07 at 10 30 44 AM" src="https://user-images.githubusercontent.com/8645379/113909292-61629b80-978c-11eb-84be-5bd381b4faf1.png">

**Comment by KellyMWhitehead** [comment]
This was completed a while back.

**Comment by joewheaton** [comment]
> This was completed a while back.

This is NOT a helpful closing of an issue. Can you please refer to the issue and/or commit(s) and pull request in which "this was completed"?

**Comment by KellyMWhitehead** [comment]
Transform curves were added to the report in this [commit](https://github.com/Riverscapes/riverscapes-tools/commit/608787cdaf3a6ba2be838effa54cd4f937ab16b6), currently on the 'vbet' branch.
