### ISSUE TITLE
Explore low pass filter for improving VBET vectorization

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#271]
Does it help to run a low pass (3x3, 5x5, or 9x9) averaging filter on the VBET evidence raster just before we vectorize it? Does it make the process faster? How does it affect the vector outputs?

This experiment might involve no code:

1. Run VBET up to the point that it is about to mask and vectorize the output. Use a breakpoint to pause the code.
2. Take the raster that is used to mask and vectorize, and run it through a low pass/smoothing/averaging filter. Overwrite the raster in the VBET project that the code is about to use for vectorization.
3. Continue the code and let it perform the vectorization but using the new smoothed raster.

Experiment with different filter sizes... 3x3, 5x5, 9x9 etc. It doesn't matter if you use the ArcGIS or QGIS smoothing filter.

# Resources

I just found this helpful ESRI post on "boundary smoothing"!!!! Worth reading and seeing if we can replicate these processes in NuMPy.

https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/smoothing-zone-edges-with-boundary-clean-and-majority-filter.htm

FYI @MattReimer for this latter ESRI link.

**Comment by joewheaton** [comment]
@philipbaileynar it seems like this is no longer relevant with how the latest (August) VBET has shaped up? I am closing for now (re-open if you disagree or think we still need this).
