### ISSUE TITLE
Convert StreamsStats Polygons to GeoPackage

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#277]
I have an ESRI file geodatabase containing polygons that determine the extent of different stream stats equations. There are three problems with it in it's current format:

1. It's ESRI File Geodatabase. Ideally this would be a GeoPackage.
2. The geodatabase has something wrong, I think related to coordinate systems. It seems to work better in ArcGIS than QGIS.
3. Each US State is represented as a separate feature class. Ideally these would all be combined into a single feature class with the original feature class as an attribute column so I can relate the features back to the correct layer.

## Deliverable

1. GeoPackage containing all the feature classes merged into a single feature class.
2. Fix the coordinate reference system. I don't mind what the final SRS is, but it needs to work with QGIS.

## Comments

Given ESRI doesn't play nice with GeoPackage, it might be worth doing the preparatory steps in ArcGIS and getting everything into a single ShapeFile. Then Switch to QGIS, load the ShapeFile and export as GeoPackage.

**Comment by KellyMWhitehead** [comment]
SS_regionPolys_20191017_gpkg_v01.zip uploaded to aws. 
Used the following SRS that did not have an ESRI authority id. Worked in QGIS. 

NAD_1983_Contiguous_USA_Albers
WKID: 5070 Authority: EPSG

**Comment by philipbaileynar** [comment]
I am still having a few issues with this dataset:

1. There are quite a few invalid geometries. Self-intersecting polygons I think. Can you try and run the ArcGIS Repair Geometry tool to see if this fixes the problem. This must not delete invalid features, but I'm hoping it can fix them without deleting them.
2. The data are really big! Is there a way you can run some kind of simplify without negatively effecting the overall shapes? My intended use of these data doesn't require crazy accurate polygons...
3. I suspect that the SRS is still giving me some problems. Can you convert to EPSG:4326?

Thanks!

**Comment by KellyMWhitehead** [comment]
* Upon inspection I found many of the polygon edges were raster saw teeth. Used the Generalize tool to simplify the polygons. 
* Ran repair geometry after this to fix invalid features (did not delete any)
* Converted to EPSG 4326
* Loaded to a new gpkg and uploaded to aws as SS_regionPolys_20191017_gpkg_v02.zip. File size now 48mb instead of 900mb.

**Comment by philipbaileynar** [comment]
It's comical how much faster this layer loads after the generalization. Thanks @KellyMWhitehead
