### ISSUE TITLE
BRAT Parametrization Riverscapes Runs 

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#278]
This item is on hold until I figure out the BRAT parameters! Assigning to myself. When I've got that done I will assign to Matt for the actual runs.

----

Please run the following tools:

* 17120007
    * Riverscapes Context (already exists... re-run)
    * VBET (already exists.... re-run)
* 18020001
    * Riverscapes Context
    * BRAT
    * VBET

All projects to go in Anabranch program. No special tag requirements.

Please assign ticket to me when done. I will verify.

**Comment by MattReimer** [comment]
from @philipbaileynar;

> Turns out I need the Riverscapes Context projects first so that I can do the BRAT calibration. @MattReimer can you please run the riverscapes context for 17120007 (replace existing) and 18020001 and then assign back to me when done please.

**Comment by MattReimer** [comment]
Riverscapes Context for HUC 17120007
https://data.riverscapes.xyz/#/Anabranch/4a26ac0e-84c2-4dbb-9035-950d50f392bb

**Comment by MattReimer** [comment]
VBET for HUC 18020001
https://data.riverscapes.xyz/#/Anabranch/8b45b1db-d781-43df-9f5b-0a7899fd9261

BRAT for HUC 18020001
https://data.riverscapes.xyz/#/Anabranch/0a147817-f483-4dea-bc83-1feb600d6664

**Comment by MattReimer** [comment]
VBET for HUC 17120007
https://data.riverscapes.xyz/#/Anabranch/f5650c90-c76e-4c0a-8d6c-3f54a8021ca6

BRAT for HUC 17120007
https://data.riverscapes.xyz/#/Anabranch/2c9ef977-b554-4ad2-8ac5-965f0834fc06

**Comment by philipbaileynar** [comment]
They all seem to check out. Thanks.
