### ISSUE TITLE
Riverscape Context Run for 14060004

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#279]
Please run 14060004 through riverscapes context and place in the Anabranch program. No special tags.

Please assign to me once it's complete.

**Comment by MattReimer** [comment]
Riverscapes Context for HUC 14060004
https://data.riverscapes.xyz/#/Anabranch/590936a4-63ac-4723-86fd-a6b3a7c2f946

**Comment by philipbaileynar** [comment]
Being lazy and reusing ticket... I mean... keeping context. Yes, that's what I mean, keeping context.

Please run VBET for this HUC.

(BRAT will be next, but I'll still parameterizing it)

**Comment by MattReimer** [comment]
VBET for HUC 14060004
https://data.riverscapes.xyz/#/Anabranch/7d66b4d0-aa7b-4e74-879f-9954e08e2395

**Comment by MattReimer** [comment]
BRAT for HUC 14060004
https://data.riverscapes.xyz/#/Anabranch/78e79106-e050-49ac-9478-12133ae55376

**Comment by philipbaileynar** [comment]
This is done. BRAT has some issues ( #291 ), but for now this is done.
