### ISSUE TITLE
Management Values are overwhelmingly "Potential Reservoir or Landuse"

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/riverscapes-tools#28]
In HUC 14050002, almost all of the segments are labeled as "Potential Reservoir or Land Use". This could be related to Riverscapes/sqlBRAT-legacy#60, or it could be a separate issue.  
![image](https://user-images.githubusercontent.com/27084463/86301041-6c1f4d00-bbca-11ea-82a7-bec079f04d5f.png)

**Comment by philipbaileynar** [comment]
THis was a bug that is now fixed.
