### ISSUE TITLE
Create Standalone HAND tool

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#280]
We have HAND inside RSCommons and integrated into VBET but we don't have a version that can be run standalone (yet)

1. [x] Create a new tool that is just running HAND. Inputs are DEM and network shapefile.
2. [x] Create [appropriate shellscript for cybercastor](https://github.com/Riverscapes/riverscapes-tools/tree/master/scripts/automation)
3. [x] We'll need a project type that feeds the input for this.

**Comment by philipbaileynar** [comment]
1. The HAND tool should have an **optional** input polygon layer that is used to mask the LiDAR raster before processing to improve performance.
1. The project that feeds into this process contains two (or maybe three, based on previous bullet) items:
    1. high resolution topo raster
    2. polygon river network - note how this is a polygon not polyline. It is produced by:
        1. user hand-draws polyline reaches and then buffers them.
        2. riverscapes context project:
           1. filtering NHD network by FCode
           2. buffering filtered network by bankfull width
           3. merging with flow areas and waterbodies
    3. polygon valley mask (this is intended to cut down the processing time for very high resolution LiDAR rasters).

The output is a HAND riverscapes project. We probably don't want ALL the inputs in the output project? The input LiDAR rasters could be several Gb.

**Comment by KellyMWhitehead** [comment]
Closing this issue as the stand-alone HAND tool is built and and working.

Please create new tickets for new enhancements or bug fixes related to HAND tool.
