### ISSUE TITLE
VBET Centerlines Cybercastor run Failures

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#287]
17060304 succeeded:
https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/5e70d21b-a712-4ea6-a50a-a596496d7552

FAILED: (4)
10190010, 18010202, 18010201, 18010203

Log files here:
[logs.zip](https://github.com/Riverscapes/riverscapes-tools/files/6437467/logs.zip)

**Comment by KellyMWhitehead** [comment]
Bugs are obsolete due to new centerline method.
