### ISSUE TITLE
iPC_RoadVB values are too high in some watersheds.

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/riverscapes-tools#29]
In the North For John Day watershed, all iPC_RoadVB values are above 179,000 indicating that the closest road to any segment is still 179 km. away, which is not true. I'm not sure exactly what's happening here, or why it only happened in the North Fork John Day.
![image](https://user-images.githubusercontent.com/27084463/86185626-678c6300-bafc-11ea-90f9-e81329aae6fe.png)
![image](https://user-images.githubusercontent.com/27084463/86185640-6d824400-bafc-11ea-8faf-a228616c7be0.png)

**Comment by philipbaileynar** [comment]
Old issue. This is resolved.
