### ISSUE TITLE
BRAT results in large water bodies

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#291]
@wally-mac can you please confirm the desired behaviour in BRAT for large waterbodies. In the screenshot below you will see BRAT is producing capacity results for connectors in large waterbodies (see lake in the west and large waterbody in the east). 

I don't think this is right. What should BRAT do in these large waterbodies:

1. Exclude the reaches for these large waterbodies in the BRAT network used to run the model (i.e. no polyline feature in the output BRAT layer for these reaches).
2. Include the reaches but set the BRAT result to "no dams" capacity.

<img width="540" alt="Screen Shot 2021-05-10 at 2 45 20 PM" src="https://user-images.githubusercontent.com/8645379/117728913-efbca980-b19e-11eb-80b5-ddd87f4e1200.png">

<img width="248" alt="Screen Shot 2021-05-10 at 3 03 41 PM" src="https://user-images.githubusercontent.com/8645379/117730294-fd732e80-b1a0-11eb-9a70-895b1715a777.png">

**Comment by wally-mac** [comment]
Hey @philipbaileynar I agree with you that the way it is currently outputting is not appropriate. I believe the preferred way to show this is with a flow line but with showing no capacity. You could confirm this with Joe but this is how I believe it should be. Thanks for reaching out. I hope things are going well.

**Comment by philipbaileynar** [comment]
Thoughts @joewheaton ?

**Comment by joewheaton** [comment]
This was a good catch @philipbaileynar. Sorry I missed it. See #469 and #470.

**Comment by wally-mac** [comment]
@philipbaileynar I think this issue can be closed.

**Comment by joewheaton** [comment]
> @philipbaileynar I think this issue can be closed.

@wally-mac, @philipbaileynar and @jtgilbert, what issue/commit pull request actually fixed this? It looks like it might have been tied to #469?  I appreciate the desire to clear _old_ stuff off one's list, but can we confirm that this change was rolled forward into all sqlBRAT runs in the warehouse?

I did a spot check for Monatna with [BRAT for HUC 17010202](https://webrave.riverscapes.xyz/#/BLM/08cb629e-734d-437f-bd89-e1a8bedff3ff), but I don't want to assume this was fixed everywhere.

![image](https://user-images.githubusercontent.com/9723905/154131574-bcbfd2b9-58e3-45e0-a27a-03d4b9f4c667.png)

I also did a spot check on Bear River program and found in (BRAT for HUC 16010201)[https://webrave.riverscapes.xyz/#/BEAR/33ebf4eb-bb52-4d78-9974-f821c07713ad], which was run Oct 28th (note that #469 was closed on Oct 29th) and it is still wrong: 
![image](https://user-images.githubusercontent.com/9723905/154132105-e660e8b3-e2f6-491b-9dd0-40c8110bac9a.png)

I am assigning this to @jtgilbert to investigate and request queue up new runs. We may want to wait to run some of those until we're also updating html reports, but we do need a strategy in this inbetween time on what triggers re-runs, and what we live with as old runs. Thanks.

**Comment by philipbaileynar** [comment]
We do not re-run everything when something changes with a model. 

We can review project scope and assess which clients have ongoing funding to support re-runs.

I would prefer @jtgilbert you come through me before triggering re-runs that affect NAR financially (which is to say all CC runs until we have credit card payments hooked up.)
