### ISSUE TITLE
Riverscapes Tools for 10090102

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#293]
Please run the following tools for Lower Tongue, MT (10090102):

- Riverscapes Context
- VBET
- RVD
- Confinement

Notes:

- Program: Network Attributes
- The RSC will be a "replace". (Last run [4 months ago](https://data.riverscapes.xyz/#/net_att/ad6e2405-4fc0-4422-9d42-eb31c66c136f).
- Hold off on BRAT. I don't have it parameterized yet.
- RVD and Confinement are probably not specified for this program yet.

**Comment by MattReimer** [comment]
Riverscapes Context for HUC 10090102
https://data.riverscapes.xyz/#/net_att/ad6e2405-4fc0-4422-9d42-eb31c66c136f

**Comment by MattReimer** [comment]
Just a status update. VBET is running but it's going to take a while. It's been running 24 hours and is only still on the 50% raster

**Comment by MattReimer** [comment]
Just another update: I've kicked this off on the staging server to see if we get better results/performance with Kelly's new improvements to VBET. 

The original job is still running and is currently about 50% of the way through the "80% threshold"

**Comment by MattReimer** [comment]
This completed and then failed because VBET projects weren't added to the net_att program

the run-time was 3 and a half days

```
2021-05-15 18:29:19:: START
2021-05-18 08:00:27:: Complete
```

@philipbaileynar I am restarting this in the BML program this time

**Comment by MattReimer** [comment]
Tracked this one down. looks like it finished VBET finally
https://data.riverscapes.xyz/#/BLM/43889771-81f1-439b-9a72-891b8aa1fae5

Queuing up RVD and confinement now.

**Comment by MattReimer** [comment]
RVD and confinement still running...

**Comment by MattReimer** [comment]
All 4 projects are now in the BLM program
