### ISSUE TITLE
Hand rasterized rivers should include waterbody polygon

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#294]
If the user provides a waterbody polygon to the HAND process it should be merged with the rasterized rivers to produces the raster that is fed into tauDEM. i.e. the "zero elevation" for HAND includes waterbodies.

1. Rasterize river network.
2. Rasterize waterbody polygons (if provided)
3. raster boolen OR operation on the two rasters

<img width="1826" alt="Screen Shot 2021-05-13 at 10 20 21 AM" src="https://user-images.githubusercontent.com/8645379/118162071-309e0380-b3d5-11eb-9053-5a00e9d91658.png">

**Comment by KellyMWhitehead** [comment]
The rasterization step has been pulled from the core HAND process. Generate a binary raster using any combination of flowlines or areas, then provide this as the input for hand. 

- [ ] stand alone HAND tool
- [ ] VBET

**Comment by KellyMWhitehead** [comment]
This issue has been resolved by the following tool enhancements:
1) channel area project incorporates waterbodies into the channel area
2) Rasterization of channel area is done by each tool that has channel area as an input (vbet, taudem, hand).
