### ISSUE TITLE
Run HAND tool for Kern LiDAR Processing

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#299]
From @philipbaileynar 

> could you take a look at the NHD based VBET for this HUC. Does this VBET - perhaps buffered by 100m - contain all the meadows? It would be good to practice using NHD based VBET as the LiDAR mask, given that it's the strategy we intend to use elsewhere.

> If VBET doesn't encompass the meadows then perhaps union the meadows with Nick's channels, buffer by 100m and then use that....

As you can see (our vbet is the hashed green line) we get pretty good agreement with our VBET except for some little channels.

<img width="791" alt="Screenshot 2021-05-14 111958" src="https://user-images.githubusercontent.com/1063391/118313572-c2764100-b4a7-11eb-94b2-dd0a1f8b504b.png">

## Nitty gritty details

* This is HUC 18030002
* [Nick's hand-drawn channel linestring and boundary polygons hand-channels.zip](https://github.com/Riverscapes/riverscapes-tools/files/6480597/hand-channels.zip) in geopackage format.  There's an attribute that gives an estimate of the channel widths, but it's pretty rough.
* [Kern lidar download link](https://waterwayscloud.egnyte.com/fl/t27eM3gJ0m)
* The standalone hand tool is currently sitting on the `handtool` branch (currently stacked on top of the `vbet` branch)
* Use the `[99] Kern LiDAR Processing (Anabranch Solutions LLC) LiDAR Processing` harvest entry for time tracking
* The [latest RSContext we have for 18030002 is here](https://data.riverscapes.xyz/#/Anabranch/9487ad38-0eac-4d78-9bdc-2f0f9f3d007b)
* The [latest VBET we have for 18030002 is here](https://data.riverscapes.xyz/#/Anabranch/e55070ea-d454-4546-974b-b1e894939b96) It's from Jan 29, 2021 6:34 PM so we might want to re-run it with latest improvements

**Comment by philipbaileynar** [comment]
Here's my idea for generating the polygon mask that should be used to SetNULL on the LiDAR image (to speed up processing):

1. Union our NHD VBET with the meadow polygon layer.
2. Dissolve.
3. Buffer by 100m.
4. Optional: smooth/simplify to keep the layer complexity down.

Some thoughts: We could just buffer the meadow polygons and be done. But I like the idea of using the VBET because a) it's how we intend to do things in other places when we don't have custom polygon layers, and b) we end up producing HAND for more places than just the meadows and this might provide the client more context and perhaps let them see the broader picture. They might be too narrowly focused on where they think they want to work. Plus, I fear we will end up being asked to run the tool again if we focus on too narrow an area.

**Comment by KellyMWhitehead** [comment]
@nick4rivers, @joewheaton 
Preview of HAND results for an initial run:

![image](https://user-images.githubusercontent.com/10746997/118727137-291c9700-b7e7-11eb-8dd2-32b5bf334586.png)

I did use the NHD flowlines for the channels since this provided better coverage with when used with the 100m buffered vbet mask, but I can rerun with the channel lines that were provided as well.

**Comment by nick4rivers** [comment]
@KellyMWhitehead - this looks great!! HAND LiDAR - very exciting!!

Thanks for kicking this out. I'd say before you go any further why don't I give these surfaces a look and provide some feedback to everyone on this.  Not sure if NHD will have the accuracy we need here.

**Comment by nick4rivers** [comment]
@KellyMWhitehead and @philipbaileynar. My concern in this case is that NHD will not follow the incised channels we are really interested in? However I have no idea until I look at Kelly's output?

![Screen Shot 2021-05-18 at 3 14 20 PM](https://user-images.githubusercontent.com/34071692/118730088-e1e4d500-b7eb-11eb-8591-92fe616c7fe8.png)

**Comment by philipbaileynar** [comment]
We are queuing up a re-run with your reach lines. We need both runs. This was run an initial run.

**Comment by KellyMWhitehead** [comment]
@nick4rivers 

Here are the results of the two HAND runs:
* [HAND from NHD flowlines](https://data.riverscapes.xyz/#/PUBLIC_DATA/87201c10-bf16-4aad-9257-5c07e086a647)
* [HAND from your channels](https://data.riverscapes.xyz/#/PUBLIC_DATA/d6661c11-6a20-4fc8-a991-c610e0cb2ce8)

**Comment by nick4rivers** [comment]
@KellyMWhitehead - thanks for turning this around. I'll give this some exploration. @joewheaton and @philipbaileynar - let me know if there are bits and pieces you would like evaluated about the application of HAND to the LiDAR data.

**Comment by nick4rivers** [comment]
@joewheaton , @KellyMWhitehead , @philipbaileynar  - little examples showing that relying on NHD as our drainage isn't sufficient when detrending the LiDAR data. The inched channel is basically lost.

![Screen Shot 2021-05-19 at 4 03 58 PM](https://user-images.githubusercontent.com/34071692/118896088-4707fb80-b8bc-11eb-90be-2e2226a87656.png)


![Screen Shot 2021-05-19 at 4 05 00 PM](https://user-images.githubusercontent.com/34071692/118896093-4a02ec00-b8bc-11eb-82c7-e0e7d05c5b86.png)

**Comment by nick4rivers** [comment]
Another example - the cross section from NHD makes no Fing sense.


![Custom](https://user-images.githubusercontent.com/34071692/118896374-f47b0f00-b8bc-11eb-8a00-e3d0d6229f39.png)


![NHD](https://user-images.githubusercontent.com/34071692/118896380-f775ff80-b8bc-11eb-9638-eb8d4807d9e7.png)

**Comment by joewheaton** [comment]
> @KellyMWhitehead - thanks for turning this around. I'll give this some exploration. @joewheaton and @philipbaileynar - let me know if there are bits and pieces you would like evaluated about the application of HAND to the LiDAR data.

@nick4rivers s the first thing you need to do is build business logic to expose everything useful in this project (you need to know how to do this really well) and build the Q and ARC symbology for this. A huge part of what you'll be doing in getting the RIPT to work is building these business logics and sybmology and you need more practice and experience at that.

- [ ] Make yourself a new issue, and list out the component pieces with these tasks `- [ ]` in this repo and get to work at it.

If you have any questions, @shelbysawyer and @lauren-herbine are in the thick of learning the same shit so you can tap them as well as @philipbaileynar and I.

**Comment by joewheaton** [comment]
> @joewheaton , @KellyMWhitehead , @philipbaileynar - little examples showing that relying on NHD as our drainage isn't sufficient when detrending the LiDAR data. The inched channel is basically lost.


This is really interesting @nick4rivers (@nbouwes should see this too). @lauren-herbine and @shelbysawyer will no doubt be interested in this. 

I think that we should be really careful with the conclusion about what input channel evidence to provide to detrending process until we test this in a few more places. It makes sense that the LiDAR is going to be much more sensitive to channel position using HAND (if you want to resolve incised channels). With 10 m DEM the topography generally will not be good enough to even differentiate most channels, much less incised ones. @nick4rivers I think we should have @KellyMWhitehead run this on a polygon input for one of the meadows too to see difference between quick and dirty polyline you drew and a more careful polygon in a smaller area.

**Comment by joewheaton** [comment]
> Another example - the cross section from NHD makes no Fing sense.
> 
> ![Custom](https://user-images.githubusercontent.com/34071692/118896374-f47b0f00-b8bc-11eb-8a00-e3d0d6229f39.png)
> 
> ![NHD](https://user-images.githubusercontent.com/34071692/118896380-f775ff80-b8bc-11eb-9638-eb8d4807d9e7.png)

So we need to [take a closer](https://github.com/Riverscapes/riverscapes-tools/issues/299) look at exactly what HAND algorithm is doing here. As best I can tell, with LiDAR if you give it an input of a channel position up on a higher slope this result actually makes perfect sense. 

1. If you take this cross section, and assume your line is in the channel, it looks like it is about 25 meters away from where the NHD line is. 
2. If you ask the question 25 meters (to the left) of the channel what is the height above the nearest drainage cell (25 meters to the right) the answer is about 4.5 meters (e.g. 1204.5 - 1200).
3. By contrast, if you ask the question at that same point using the NHD input, what is the height above nearest drainage, by definition it is zero. So bottom one checks out.
4. However if you move a few meters to your right, something weird is happening with that wall in the calculation that is 5.5 meters higher as you start moving away down the slope. We need to dig in to this and be able to explain it better.... (@KellyMWhitehead any thoughts?)

**Comment by philipbaileynar** [comment]
Old ticket that predates latest VBET and LiDAR runs. Re-open or create new dedicated ticket if necessary.
