### ISSUE TITLE
VBET for 140600060202

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#300]
We need VBET for this HUC 12 (**TWELVE**).

@MattReimer and @KellyMWhitehead can you coordinate to get this run and into the Anabrach data warehouse program. I don't know:

* If this is the first situation where @KellyMWhitehead should be running our tools and uploading instead of @MattReimer .
* If we run the production VBET or we use @KellyMWhitehead experimental version (which even though the parameters are unproven, they are essentially the same as the production values). It all comes down to whether the experimental version produces a valid riverscapes project. I suspect @MattReimer will have opinions about whether we want outputs in the wild from two very different versions of VBET.

I suggest running it for the HUC8 and then clipping all the layers down to the HUC12.

Please assign to me when it's in the warehouse.

**Comment by MattReimer** [comment]
I don't know why we would run HUC8 and then clip when cybercastor should support HUC12 out of the box just fine.

Just for fun I've kicked it off on the staging server with the latest VBET to see what happens.

**Comment by MattReimer** [comment]
Riverscapes Context for HUC 140600060202
https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/87665ff3-f134-4e22-9020-623ed8ae2b9a

VBET for HUC 140600060202
https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/92d0847c-72eb-4adb-968a-3c8ace851b46

completed successfully and [VBET looks like something](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/92d0847c-72eb-4adb-968a-3c8ace851b46). No idea about the quality though.

**Comment by philipbaileynar** [comment]
This is awesome. Please run in production. Anabranch program. Respond here when done.

**Comment by MattReimer** [comment]
@philipbaileynar sorry this isn't totally clear. You're talking about option 1 right?

**Comment by philipbaileynar** [comment]
Yes. option 1.

**Comment by MattReimer** [comment]
Riverscapes Context for HUC 140600060202
https://data.riverscapes.xyz/#/Anabranch/c68e9360-e678-41a5-8d88-7b55d9750ef3
VBET for HUC 140600060202
https://data.riverscapes.xyz/#/Anabranch/99f49e17-037e-447e-be84-b5b9f8260ab6

**Comment by philipbaileynar** [comment]
Looks great. Impressive.
