### ISSUE TITLE
Hydrologic equations for 10090102?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#305]
@tyler1218hatch do you have the QLow and Q2 hydrologic equations used for 10090102 in Montana BRAT please? Paste them here or put them in Postgres. I don't mind which.

**Comment by tyler1218hatch** [comment]
@philipbaileynar Okay, everything is good to go. All of the necessary data should be in Postgres now!

**Comment by philipbaileynar** [comment]
@tyler1218hatch did you update any default or override veg suitabilities?

**Comment by tyler1218hatch** [comment]
@philipbaileynar Nope. It's usually best for me to do that after a preliminary sqlBRAT run.

**Comment by philipbaileynar** [comment]
Great. Thanks!
