### ISSUE TITLE
oPBRC_UI and oPBRC_CR: Fields should be fixed

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/riverscapes-tools#31]
Documentation [here](http://brat.riverscapes.xyz/BRATData/Outputs/WorkingWithBRATv3XOutputs.html) shows that the field oPBRC_UI should hold data about risk, with the categories (Negligible, Minor, Some, Considerable). And oPBRC_CR should hold data about restoration opportunties (Easiest, Straight Forward, Strategic). However, this attribute table shows that they are switched in sqlBRAT. They need to be switched back.

![image](https://user-images.githubusercontent.com/27084463/86184744-69edbd80-bafa-11ea-9acf-f7398c8b1c2e.png)

Also, the only values for oPBRC_CR (Currently shown as oPBRC_UI) that appeared in the most recent outputs are NA and Easiest - Low-Hanging Fruit. The values "Straight Forward - Quick Return" and "Strategic - Long-Term Investment" don't appear. We need to check if this is actually an error and the conditions need to be updated, or if those watersheds just happened to not have those categories. Attached is an image of the outputs.
![image](https://user-images.githubusercontent.com/27084463/86184181-352d3680-baf9-11ea-87b0-a83429733520.png)
![image](https://user-images.githubusercontent.com/27084463/86184187-38c0bd80-baf9-11ea-9f8a-942cf2d66249.png)

The best place to use as reference is the old [Constraints & Opportunities script.](https://github.com/Riverscapes/pyBRAT/blob/master/Constraints_Opportunities.py)

**Comment by philipbaileynar** [comment]
This issue is fixed.
