### ISSUE TITLE
VBET is buffering artifical connectors

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#312]
The following screenshots were taken from a recent VBET run in 17120006 (Lake Abert) near the California Oregon before for @joewheaton .

* [Riverscapes Context](https://data.riverscapes.xyz/#/Anabranch/1b49939a-d009-474e-ae02-a355f7d5ca8b)
* [VBET](https://data.riverscapes.xyz/#/Anabranch/bfa25724-9f83-40a3-8033-b488357e5748) 

It looks like we are buffering NHD flow lines that represent artifical connectors? I don't think it makes sense to buffer these lines. The waterbodies they represent should be handled in VBET when we pull in the waterbody polygons and flow areas.

<img width="897" alt="Screen Shot 2021-05-25 at 12 10 48 PM" src="https://user-images.githubusercontent.com/8645379/119555507-c9783b80-bd52-11eb-93cc-88707f5c1a2a.png">
<img width="897" alt="Screen Shot 2021-05-25 at 12 12 07 PM" src="https://user-images.githubusercontent.com/8645379/119555515-cbda9580-bd52-11eb-8c8f-a9753d22e125.png">

**Comment by joewheaton** [comment]
This is superseded by current version of VBET
