### ISSUE TITLE
We need to update the names of geopackages and attribute fields to be more consistent with theory

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#316]
This will eventually get assigned to @KellyMWhitehead to implement, but for now @lauren-herbine and I can figure out what is wrong with what currently exists.

As an example, many of the attributes (e.g. constriction proportion) are labeled wrong (i.e. as constriction ratio in this example), and/or in confusingly named parent feature classes (e.g. confinement_ratio is where constriction stuff is).

**Comment by joewheaton** [comment]
- [] Maybe consider renaming the `confinement_ratio' polyline feature class in the `Outputs\confinement.gpkg` to  `Outputs\ChannelNetwork.gpkg` as that is really what this is.

**Comment by lauren-herbine** [comment]
@joewheaton I'm putting what we discussed + further ideas into this [gist](https://gist.github.com/lauren-herbine/a8bd973cf124d3942eeb5c931148d11e) (not currently finished, but it's where I'm housing things as I go).

**Comment by lauren-herbine** [comment]
@joewheaton do you think we can close this issue?
