### ISSUE TITLE
Document VBET Evidence Gathering Methodlogy

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#317]
Please write instructions for USU technicians to use the VBET evidence gathering approach that I shared in a [recent video](https://youtu.be/g_htnyqRGx8).

I don't mind where you publish the page... could be a simple secret GitHub gist for now. The goal is to have instructions that any USU technician can follow to get a QRAVE session set up how I show in the video and start gathering valley bottom evidence. I'm happy if you spend a little time researching and improving on my approach. Default values etc.

Please don't include database connection details in the instructions. Just state that people should contact NAR.

**Comment by KellyMWhitehead** [comment]
@philipbaileynar 

Is there a way to access the user and classification lookup tables?  Those tables did not show up with the database connection.

**Comment by philipbaileynar** [comment]
I think there's a checkbox in the postgres connection in QGIS that turns on showing non spatial tables

**Comment by philipbaileynar** [comment]
see middle of this image

<img width="534" alt="Screen Shot 2021-06-16 at 4 08 40 PM" src="https://user-images.githubusercontent.com/8645379/122306374-2af87980-cebd-11eb-93e1-e9a5690b7689.png">

**Comment by philipbaileynar** [comment]
<img width="534" alt="Screen Shot 2021-06-16 at 4 08 40 PM" src="https://user-images.githubusercontent.com/8645379/122306502-6e52e800-cebd-11eb-9e09-8a69f5bb46ea.png">

**Comment by KellyMWhitehead** [comment]
Method developed, documented, and distributed. There will be opportunity to integrate this workflow with automated tools in the future.

**Comment by joewheaton** [comment]
@KellyMWhitehead please don't just say it is "documented", actually provide link to [your gist or documentation](https://gist.github.com/KellyMWhitehead/eef3fe54aa88ba3e34aa87c055377b99) before closing next time.
