### ISSUE TITLE
VBET Inconsistencies - No views / No DEM?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#319]
Hey @philipbaileynar and @KellyMWhitehead. We have so many different versions of VBET projects floating around, I feel like we need to develop a strategy for purging them, updating and replacing them. This is going to be critical for testing and refinement, which we will ramp up in the next week or so. 

- [ ]  A newer version of VBET project ([v 0.3.3 for 17060304](https://data.riverscapes.xyz/#/PUBLIC_DATA/0dc1c4b1-8f5c-4f43-a584-7bf50668fc60)) has no Project Views, and is missing critical inputs of DEM and 
![image](https://user-images.githubusercontent.com/9723905/123281102-a31afc80-d4c6-11eb-93dd-05eaa5dd05ef.png)

Maybe short of that strategy, can we get some agreement on what HUC8s we will work off of for now for testing and refinement? Maybe:
- Pumpkin Creek
- Klamath (18010202)
- Something in MHFD?

**Comment by MattReimer** [comment]
Good strategies @joewheaton. The view thing could be a bug in QRAVE so I filed an issue there:
https://github.com/Riverscapes/QRAVEPlugin/issues/31

As for the data problems we should probably decide on some conventions. In the past we have tagged things `experimental` when we want them to be reviewed or refined. That still seems like a pretty good stratgey because it means the old copies can be there too and not be replaced until we're happy.

**Comment by philipbaileynar** [comment]
* Pumpkin Creek
* Klamath (18010202)
* MHFD (10190004) see screenshot below. We especially need evidence and focs on the eastern plains

<img width="2045" alt="Screen Shot 2021-06-24 at 8 04 59 AM" src="https://user-images.githubusercontent.com/8645379/123287056-4f5ae400-d4c3-11eb-912f-bd76aa56fd99.png">

<img width="1078" alt="Screen Shot 2020-09-26 at 10 56 07 AM" src="https://user-images.githubusercontent.com/8645379/123287104-584bb580-d4c3-11eb-9a46-946a0d5c4092.png">

**Comment by shelbysawyer** [comment]
@joewheaton Let me know what you're looking for from me here beyond tracking this issue and [Riverscapes/QRAVEPlugin#31](https://github.com/Riverscapes/QRAVEPlugin/issues/31). I always take the projects tagged with `experimental` with a grain of salt, but sometimes I'm not sure if there are other versions out there that I'm pulling from the warehouse unknowingly. 

Are there any related issues/tasks I should split out from here for working with those HUCs (Pumpkin Creek, Klamath (18010202), and MHFD (10190004))?

**Comment by joewheaton** [comment]
That's all @shelbysawyer... Nothing actionable for you on this. @MattReimer has it in [Riverscapes/QRAVEPlugin/issues/31](https://github.com/Riverscapes/QRAVEPlugin/issues/31)
