### ISSUE TITLE
Where is actual channel polygon for VBET?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#320]
@KellyMWhitehead I am trying to figure out what you are actually using for VBET channel polygons. I am pretty confident it is wrong, but I cannot trace it back through the current rats nest of files in VBET projects nor do we (to my knowledge) expose it properly in the business logic nor have any discoverable documentation of what is what (e.g. [this is not yet populated](https://tools.riverscapes.xyz/vbet/)). So help me out please...  [the video below](https://youtu.be/BeFL1wxzt_Y) lays out some issues in some of the projects (should be separated into different tickets) and some specific questions I would like to see discussed and answered here in this issue.
[![https://youtu.be/BeFL1wxzt_Y](https://img.youtube.com/vi/BeFL1wxzt_Y/0.jpg)](https://www.youtube.com/watch?v=BeFL1wxzt_Y)

While @philipbaileynar is losing his remaining hair stressing about getting transform functions right, we can't do the calibration exercise of those transform functions until we have the inputs for each dialed. @shelbysawyer you should watch and read this and add any questions or comments you have.

In a nutshell, I think:
## What I think you're doing
- Calculating flow area (from NHD) raster correctly
- Calculating bankfull width inconsistently (discrepancy between attribute values)
- Calculating the vbet_network_buffered polygon completely wrong (the buffer is 10x the reported bankfull widths... or maybe a cell resolution times it?) 
- Converting this wrong buffer polygon to a raster correctly, but doing this for the flow areas too (why)? It should only be done for flow areas.

## What I want us to be doing
- Be consistent and clear on what bankfull width you are using (make sure if we're deriving and channel_area polygon based on this it is 0.5 x bankfull width buffer.
- Eliminate this buffer-based estimtate in valley bottom segments where NHD_FlowAreas exist
- Combine the flow_Areas and buffer to produce actual input into VBET, which should be an "active channel area" polygon estimate. All the above is just crappy approximation that we use in US for production grade runs based on NHD
- Don't calculate separate evidence rasters for flow_areas and channels. Only do one for "active channel area" polygon.
- Don't calculate Euclidian distance from raster conversion of "active_channel_areas", as this will degrade distance estimate down to resolution of DEM (i.e. 10 m here). Instead, calculate it based on actual polygon (yes I know this will still be a raster @ 10 m resolution), but it will be more accurate. 
- For all (a majority) of riverscapes with active channel widths < 10 m, the converted raster of "active_channel_areas" based on input DEM of NED 10 m will be one pixel wide. Now they are two. 

The above suggestions should help us when we start running VBET over smaller extents but off of better inputs (e.g. LiDAR and actually hand digitized active channel areas). 

- [ ] #330

**Comment by KellyMWhitehead** [comment]
* Bankfull has been updated to only include non-flow area reaches and to use 1/2 the bankfull width generated in RS context. In addition, a minimum buffer parameter has been removed (based on the cell area).
* The bankfull and flow area polygons are now merged to form the channel area polygons.
* @joewheaton when we convert to raster, we have the option of using 1) only cells whose center is within the polygon (default) or 2) all cells that touch the polygon.  This raster is used for generating the euclidian distance from channel, as well as the channel input for hand. Which of these options should we use (in figure below, option1 is dark blue, option 2 is light blue, pink is the channel polygon outlines):
![image](https://user-images.githubusercontent.com/10746997/123975877-8a9d5d00-d972-11eb-83e7-225ee03f7cd1.png)

* @joewheaton Flow area polygons also have islands/donuts. Should we remove 1) no islands, 2) all islands, 3) islands below a threshold area?

**Comment by joewheaton** [comment]
> * Bankfull has been updated to only include non-flow area reaches and to use 1/2 the bankfull width generated in RS context. In addition, a minimum buffer parameter has been removed (based on the cell area).

Nice!

> * The bankfull and flow area polygons are now merged to form the channel area polygons.
> * @joewheaton when we convert to raster, we have the option of using 1) only cells whose center is within the polygon (default) or 2) all cells that touch the polygon.  This raster is used for generating the euclidian distance from channel, as well as the channel input for hand. Which of these options should we use (in figure below, option1 is dark blue, option 2 is light blue, pink is the channel polygon outlines):
Lets use option 2. However, it does make me wonder whether or not when we "vectorize" valley bottoms in areas only two cells wide, if we should revert to original polygons? Anyhow, run with 2) for now.

> * @joewheaton Flow area polygons also have islands/donuts. Should we remove 1) no islands, 2) all islands, 3) islands below a threshold area?

I'm thinking we go with 2 because this is the "channel" polygon.

**Comment by joewheaton** [comment]
So, @KellyMWhitehead can you give us an update on where you did this? I want the new inputs to VBET to be simplified to exactly what we did for business logic for HAND. Namely, there is a "Drainage" or channel input, and a "Topography" input:
![image](https://user-images.githubusercontent.com/9723905/124660289-42df6f80-de63-11eb-88ff-4ca8a6e95d2d.png)

The inputs for either can be a polyline, but by default will be a channel area or drainage (HAND lingo) polygon.  I want a new container for these and I want the algorithm you just developed to be a standalone project type and tool. 
- [ ] Create a new Riverscapes Project type of **Channel Area** to house both this data type and optional tool

**Comment by joewheaton** [comment]
This is all addressed in #347 and new channel area projects.
