### ISSUE TITLE
RS Context Project for VBET Validation Observations

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#324]
@lauren-herbine and I would love to get our hands on at least one additional RS Context project to keep making progress with the VBET validation observations. I've been working in 16010202 (Middle Bear), but another local area that we both know well would be really useful. 

@philipbaileynar Is this an easy to-do?

- [x] RS Context for 16010203 (Little Bear-Logan)

**Comment by MattReimer** [comment]
@KellyMWhitehead when you get a chance: 
project type: RSContext
Program: Anabranch 
tag: cybercastor

**Comment by KellyMWhitehead** [comment]
https://data.riverscapes.xyz/#/Anabranch/f17875c5-455e-4aea-95e7-fc870e9df933

**Comment by KellyMWhitehead** [comment]
@shelbysawyer  please close this request when you have reviewed that the project looks good.

**Comment by shelbysawyer** [comment]
@KellyMWhitehead It looks good. Thank you!
