### ISSUE TITLE
Topographic Wetness Index Research

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#325]
@joewheaton just pointed out that tauDEM includes a tool for calculating Topographic Wetness Index (TWI). It combines slope with a measure of catchment, which intuitively sounds very connected to VBET.

https://hydrology.usu.edu/taudem/taudem5/help53/TopographicWetnessIndex.html

Here is a graphic from a **different** TWI measure from SAGA GIS. I'm including it just as a visual.

![image](https://user-images.githubusercontent.com/8645379/124008579-68670780-d991-11eb-9b28-5faac559ed8a.png)

@KellyMWhitehead can you research the tauDEM TWI tool and research the tools that we would have to run in order to have TWI as an evidence raster to VBET? A bit like HAND, before you can run TWI you have to have to run other tauDEM processes. How onerous or easy is this?

**Comment by KellyMWhitehead** [comment]
Generating this dataset only adds two steps to the HAND process. Here is a [hand project with twi added](https://data.riverscapes.xyz/#/Anabranch/d021df4a-8220-4b97-94fc-6641859ba411).

**Comment by joewheaton** [comment]
Very cool @KellyMWhitehead. I'm having a play... I need to figure out what the hypothetical range of possible values we can produce in this and figure out how we scale this. However, even off a 10 m DEM, we're seeing some really cool patterns that I think are going to be quite helpful as a line of evidence. 

![image](https://user-images.githubusercontent.com/9723905/124039974-37063000-d9c1-11eb-8d75-2f03bec48cc1.png)

@lauren-herbine, @shelbysawyer and @nick4rivers you might all be interested in this too. 

## Some issues it looks like on edges and mainstem
![image](https://user-images.githubusercontent.com/9723905/124040621-797c3c80-d9c2-11eb-83fc-91f940a7b888.png)

## Playing with thresholds
To learn about what this TWI, use HAND as a frame of reference:
![image](https://user-images.githubusercontent.com/9723905/124040762-c4964f80-d9c2-11eb-9341-d1b71f952288.png)

If we use TWI = 10 (more liberal/inclusive)
![image](https://user-images.githubusercontent.com/9723905/124040819-e55ea500-d9c2-11eb-98bf-0b839cd38cec.png)

then if we use TWI = 15 (somewhat restrictive)
![image](https://user-images.githubusercontent.com/9723905/124040722-b0eae900-d9c2-11eb-9827-1286da97a5e8.png)

a TWI = 25:
![image](https://user-images.githubusercontent.com/9723905/124040935-1fc84200-d9c3-11eb-93b3-0b7cbbfad1b5.png)

Anyhow... interesting.

**Comment by lauren-herbine** [comment]
@joewheaton this looks really cool. A couple of quick questions: TWI is an indication of depth to water table- but it is dimensionless, yes? I am not entirely sure I understand what is happening when you set the TWI (to 10, 15, etc.). Are you excluding values greater than the upper bounds that you are setting? 

Potentially the mainstem is showing up as no data as the slope is near zero (ln(a/S))?

**Comment by shelbysawyer** [comment]
To echo @lauren-herbine's comment, I am also confused about how changing thresholds affects the layer behavior.

**Comment by lauren-herbine** [comment]
Shelby and I's question answered in person

**Comment by shelbysawyer** [comment]
Leaving a note here so we remember to return to this:

TWI uses slope in its calculation.. so if we use it as a line of evidence, we'll be weighting slope more heavily. Something to think about.

**Comment by joewheaton** [comment]
> Leaving a note here so we remember to return to this:
> 
> TWI uses slope in its calculation.. so if we use it as a line of evidence, we'll be weighting slope more heavily. Something to think about.

Yes, the two lines of evidence clearly are not independent as TWI is dependent on slope. However, the argument for including both is when either one by itself provides useful insight, but without both we would not be as effectively identifying the valley bottom. So the litmus tests should be:

- How does including this new line of evidence help us discriminate areas that otherwise would be wrongly included?
- How does including this new line of evidence help us include areas that were otherwise wrongly excluded?

Our bigger challenge will be whether or not we can get away without drainage area specific transform functions on this?

We might also consider producing a run with TWI and without slope and see how different they are.

**Comment by joewheaton** [comment]
>TWI is an indication of depth to water table- but it is dimensionless, yes? 

No. It actually has dimensions of length. remember (length^/2/ length)/(length/length). What this length scale physically represents is sort of interesting. Is it a "depth' of water? I don't know. How for example does this quantity compare with HAND (height above nearest drainage)?

> I am not entirely sure I understand what is happening when you set the TWI (to 10, 15, etc.). Are you excluding values greater than the upper bounds that you are setting?
> 

All I am doing is changing the upper bound of the display so that all values over 10 are green, or all values over 15 are green.

> Potentially the mainstem is showing up as no data as the slope is near zero (ln(a/S))?

That's a possibility, but another possibility is the drainage area is not getting correctly passed.

**Comment by shelbysawyer** [comment]
@joewheaton I have a question about TWI related to the updated csv that @KellyMWhitehead provided. I'm noticing a lot of -1 values, which I didn't experience when I queried the layer in Arc / Q. Is the -1 a true TWI output or is there something odd happening somewhere along the way?

**Comment by joewheaton** [comment]
> @joewheaton I have a question about TWI related to the updated csv that @KellyMWhitehead provided. I'm noticing a lot of -1 values, which I didn't experience when I queried the layer in Arc / Q. Is the -1 a true TWI output or is there something odd happening somewhere along the way?

See #355.

**Comment by shelbysawyer** [comment]
@joewheaton For TauDEM and VBET curation purposes.. checking to see if any specific symbology was favored for TWI?

**Comment by joewheaton** [comment]
> @joewheaton For TauDEM and VBET curation purposes.. checking to see if any specific symbology was favored for TWI?

No... I didn't find anything. Probably just blues or greens in VBs and warm colors up the slope?
