### ISSUE TITLE
removing HAND from RSContext?

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#327]
@joewheaton currently we include a HAND raster in RSContext. It is:

* Not made using our flowlines or our rasters
* Difficult to download: it comes from a server in a bathtub or something. Download speeds are pitiful and inflate the runtime of RSContext a lot.
* Error prone: A lot of RSContext failed runs come from problems with downloading this file

We currently have a standalone HAND project **_and_** VBET runs its own HAND. For the life of me I don't see any reason to keep this product in RSContext but I want to check in and make sure nobody is using it. 

So can we remove it for the next version we push out?

**Comment by joewheaton** [comment]
@MattReimer this is a good question and a bigger issue that we should discuss with @philipbaileynar. I like @philipbaileynar litmus test for RS_Context: "these are existing datasets that don't require user judgement or parameterization (like a model would)". I think we underestimate the utility and value of this service. Going and getting a bunch of stuff and clipping or aggregating it to my area of interest (currently any HUC8, 10 or 12), but in principle any area (within reasonable size) is really valuable.  

To me, given above definition, here's how I respond to your individual points:

> Not made using our flowlines or our rasters

This is not relevant here. This is only important to VBET. By defintion, only datasets we include in here are ones that don't require user-judgement or specification. So by this criterion, we can still keep it. We do have two bigger expectation management issues of: 1) taking things away that people come to expect for what they paid (i.e. I used to get HAND as part of what I paid for in RS_Context, now I don't; and 2) differentiating between a free Tarboton produced run and the better value custom HAND runs or VBET-produced HAND runs. 

> Difficult to download: it comes from a server in a bathtub or something. Download speeds are pitiful and inflate the runtime of RSContext a lot.

Well, I hear you on this being tricky. I thought that this was the whole point of having that "National" Riverscapes Project. I have heard you guys talk about how bad the server they host the data on this is? Are you actually making a call to the server every time? If so, why are we not just biting bullet and downloading everything and sucking up in that "National" project? 

> Error prone: A lot of RSContext failed runs come from problems with downloading this file

Good reason, but I need to hear more about this before being swayed by the argument.

>We currently have a standalone HAND project and VBET runs its own HAND. For the life of me I don't see any reason to keep this product in RSContext but I want to check in and make sure nobody is using it.

I use the sloppy HAND runs from Tarbotton all the time. They are one of the most viewed layers out of an RS_Context. Now are they as good as a custom derived HAND. No, not at all. But for some "free" or "cheap" context, it sure is helpful. 


> So can we remove it for the next version we push out?

No... not yet, but happy to discuss further. I think we need a better strategy for RSContext in terms of:

- Differentiating RSContext runs we pull together to support our other models (e.g. BRAT, RCAT, VBET) from those custom runs we produce for a fee (e.g. web store or Anabranch). Those are two really different use cases and end users
- Following through on the curation that @Riverscapes/riverscape-project-curators will be working on to better explain what every layer is in the HTML report and metadata and make the case for the difference between this HAND and a custom HAND.
- Thinking about customization of RSContext web store requests where user can specify 1) custom extents beyond HUC 8, 10 or 12s; 2) which context layers to include of available ones
- Thinking about our process for considering and including "available" layers to "include" in RSContext. Currently, @joewheaton just says I want this. But this is already getting out of hand. Having "custom runs" makes the case for a bigger laundry list of potential candidate layers to include, and it is the user/customer's problem to request from that list.  This could be major bread and butter type stuff at some point. Obviously for supporting RSContext runs, we could get away with leaner runs.

**Comment by MattReimer** [comment]
If it's that critical maybe we could come up with some consensus on running our own HAND for RS_context. It would probably take way less time and really stabilize our processes.

**Comment by lauren-herbine** [comment]
Just putting my two cents in- I do use HAND in the RS context projects a lot. Would love to see them/an updated version of them stay!

**Comment by philipbaileynar** [comment]
My vote is to do a perennial only hand run of our own instead of downloading from that commodore 64.

If we structure it to take a list of list of fcodes, we could expand it down the road to produce multiple hand rasters for different combinations of fcodes.

**Comment by joewheaton** [comment]
> If it's that critical maybe we could come up with some consensus on running our own HAND for RS_context. It would probably take way less time and really stabilize our processes.

I think that running our own HAND or own as part of a TauDEM project could have huge value. However, I don't think it belongs in RS_Context. That breaks Philip's cardinal rule for inclusion there. 

Sorry Pip, having spent a lot more time looking at NHD across the US, I don't think running it for only perrenial is a good idea. We can discuss further. 

Tarboton's HAND is done and has a lot of value as context.

**Comment by MattReimer** [comment]
Due to it being a massive source of failure in RSContext projects and of limited value now that we can do it ourselves in TauDEM we made the choice to remove this in RSContext.

**Comment by philipbaileynar** [comment]
I don't see any commits associated with this issue. @jtgilbert can you confirm that Riverscapes Context is no longer downloading and including the publicly available HAND rasters?

@jtgilbert please re-close this issue if RSC is no longer including HAND.

**Comment by MattReimer** [comment]
Here's the commit. THis is now in the latest release

e0d895bdd5cb7a5a0f8dc40c12d73eab82d931d3
