### ISSUE TITLE
Create a new Riverscapes Project type of Channel Area to house both this data type and optional tool

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#330]
Project Type: Channel Area

All this is a riverscapes project for a polygon that represents a channel area.  Someone could manually digitize and make this (e.g. @nick4rivers in QRiS). Someone could get it from some other source (e.g. a hydraulic model output). It could be for just a riverscape reach or multiple reaches, or could be an entire drainage network.
- [x] Define project type
- [x] Curate Business logic & symbology
- [ ] #412
- [ ] [Add Channel Area as type of Assessment in QRiS](github.com/Riverscapes/QRiS/issues/36)
- [x] #331

**Comment by MattReimer** [comment]
Added the ChannelArea type to the RiverscapesXML repo and added it to the Anabranch program
https://github.com/Riverscapes/RiverscapesXML/pull/150

**Comment by joewheaton** [comment]
There are two sub-tickets still being worked on here, but they are tracked in [QRiS](https://github.com/Riverscapes/riverscapes-tools/issues/github.com/Riverscapes/QRiS/issues/36) and #412. The main tasks here are done.
