### ISSUE TITLE
Add a Network Channel Area Tool

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#331]
## Network Channel Area Tool
This is a specific production grade tool that we will run with
Inputs:
- Flow Network (typically the NHD+HR) with drainage area and precipitation attribute
- Flow Area (typically NHD Flow Areas and/or Water Bodies) 
- Bankfull Width Equation (typically f(precip, drainage area)

Output:
- Channel Area across entire network, where:
  -  in network line areas it uses the bankfull width equation and produces a 1/2 bankfull width buffer to get polygon representation/approximation.
  - in areas with flow area already digitized, it will just use that and erase the polyline derived version (i.e. the polygon input trumps the polyline)
The output should be segmented differentially for the line derived and polygon derived and should have an attribute field with 'method' dentoed (e.g. bankfull_polyline_buffer or pre-existing)

**Comment by philipbaileynar** [comment]
Additional comments:

1. Additional inputs: 
    - Attribute filter field (.e.g. `FCODE`)
    - list of filter attribute values to **retain** (i.e. the list of perennial, intermittent. This also helps avoid buffering canals and pipes etc).
1. An intersect is going to be needed before combining the network polygons and flow area polygons. These polygons are going to overlap where tribs meet large rivers. The flow areas should take precedence. Discard the network area portions (this isn't like VBET where the overlap provides value).


Note how this tool is entirely vector. I was going to suggest that this tool also produce the channel raster, but that would require a decision about cell resolution. Better to leave that for the next tool down the chain that needs the channel area in raster format so it can be combined with some other raster product. Let those other raster products determine the cell resolution elsewhere. Conclusion... keep this tool all vector.

```
my_cool_project
    project.rs.xml
    report.html
    inputs\
        inputs.gpkg
            flow_areas
            network
    intermediates
        intermediates.gpkg
            filtered_network
    outputs
        outputs.gpkg
            channel_areas
```

- Be sure to include the bankfull equation and FCode filter in the project XML and report.
- Note the filtered network layer could be useful for display

Final thoughts... remember that someone might generate this project by manually digitizing the layers. We will automate this from NHD but others will build it by hand. Keep it simple and not onerous to build by hand.

**Comment by MattReimer** [comment]
This is merged. closing

**Comment by joewheaton** [comment]
> Note how this tool is entirely vector. I was going to suggest that this tool also produce the channel raster, but that would require a decision about cell resolution. Better to leave that for the next tool down the chain that needs the channel area in raster format so it can be combined with some other raster product. Let those other raster products determine the cell resolution elsewhere. Conclusion... keep this tool all vector.

Spot on @philipbaileynar! Lets keep it entirely vector.  Operations to go to raster should be in tauDEM (#340) and/or VBET.


> * Be sure to include the bankfull equation and FCode filter in the project XML and report.
> * Note the filtered network layer could be useful for display
> 
Yes, we will want FCode if present for waterbodies, flow areas and drainage networks.

> Final thoughts... remember that someone might generate this project by manually digitizing the layers. We will automate this from NHD but others will build it by hand. Keep it simple and not onerous to build by hand.
Exactly!
