### ISSUE TITLE
Errors in NHD+ HR

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#332]
If we're finding errors in the NHD+ HR (ex: major rivers mapped as both perennial and intermittent), is there someone we should contact at the National Map to log these?

**Comment by philipbaileynar** [comment]
I have had positive results reporting problems to:

Annalisa Stasey
NHD Partner Support
U.S. Geological Survey
National Geospatial Technical Operations Center
1400 Independence Rd
Rolla, MO 65401
(573) 308-3671
astasey@usgs.gov

**Comment by lauren-herbine** [comment]
Great, thanks @philipbaileynar !
Tagging @shelbysawyer and @joewheaton

**Comment by joewheaton** [comment]
Thanks both on this. We got what we needed. @lauren-herbine and/or @shelbysawyer please reach out to Annalisa and share with her some of the issues you are finding (screen shots or a little video will do). Let her know that we're going to be spending a lot of time as a group engaging with 75% of the NHD+ HR network. With our eyes on it, ask if a) they would like us to report certain types of issues, and b) if there is any standard way they would like us to do that reporting?

**Comment by MattReimer** [comment]
Not sure if this is still open. @lauren-herbine could you confirm and close this issue if it's resolved?

**Comment by lauren-herbine** [comment]
Yes, sorry, resolved with Philip's answer
