### ISSUE TITLE
tauDEM riverscapes tool

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#340]
This is a new riverscapes tool that explicitly produces tauDEM datasets needed by our tools. For now we will limit the tool to just the datasets we need immediately. It can easily grow over time. I don't want to expend lots of effort learning complex tauDEM workflows for things that don't immediately plug into our existing tools. 

Immediate tauDEM outputs:

- Inputs
    - DEM
    - Channel Area Vector (see #331)
- Intermediates
    - channel area raster
    - pit fill raster
    - (probably others)
- Outputs
    - HAND
    - TWI
    - Slope

Other Stuff 

- The tool name will be **tauDEM**. 
- Make sure the version of tauDEM or git commit is stored somewhere so we can identify outdated projects when the software changes.
- Make sure that the project XML has
    - verbose acknowledgement of tauDEM tool and developers
    - tauDEM web site URL
    - citation to best paper

**Comment by joewheaton** [comment]
Thank you @KellyMWhitehead for this [first draft project](https://data.riverscapes.xyz/#/Anabranch/448e792e-4873-4467-bdea-dd8ea5c57803)

**Comment by MattReimer** [comment]
I'm calling this done. Let's open enhancement issues and bug issues if we need to change it.

**Comment by joewheaton** [comment]
> I'm calling this done. Let's open enhancement issues and bug issues if we need to change it.

Fair enough. This from @philipbaileynar above was definitely not done. 

> - Make sure that the project XML has
>   - verbose acknowledgement of tauDEM tool and developers
>   - tauDEM web site URL
>   - citation to best paper

The standard thing will be for each projectXML to be associated with the tool documentation and we funnel people off there (see #376). However, to make sure this is done, I'm making a new enhancement issue and assigning it to @philipbaileynar for him to delegate as he sees fix.  See #378
