### ISSUE TITLE
Update ChannelArea tool inputs  to include waterbodies

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#348]
Please include waterbodies as an additional input. They should keep their FCODEs and they should get priority over network lines just like flow area polygons. They will get combined with other flow area and buffered network lines of evidence (minus FCODE filtering in #347) to make a channel area polygon. Please retain their in-built segmentation if possible.

**Comment by KellyMWhitehead** [comment]
Code updated in b01589996a46cf6cf404a79e4d06a0f33a781f42
