### ISSUE TITLE
4. How do we interpret range of values produced in TWI?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#356]
@shelbysawyer, after you're done with transform curves, please investigate this (you will likely need to read TauDEM documentation, do some spreadsheet games and read some papers.

**Comment by shelbysawyer** [comment]
Here is what we're seeing with TWI for points that are not valley bottoms. There is not much difference between small, medium, and large. Ignore the red plot.
![image](https://user-images.githubusercontent.com/73311751/126849271-2f430151-2b07-4c22-a269-adffd3e11e32.png)

**Comment by joewheaton** [comment]
@shelbysawyer new [TWI symbology](https://github.com/Riverscapes/RiverscapesXML/blob/cdee7a89616d738148f331ac188e256427b7ac8d/Symbology/qgis/Shared/twi.qml) makes it a lot easier to interpret TWI:
![image](https://user-images.githubusercontent.com/9723905/129495183-5b30f937-c541-404b-bddd-1692741d3bd6.png)

**Comment by joewheaton** [comment]
This is now sorted out from our #310 and #369 work.
