### ISSUE TITLE
Incorporate most all LANDFIRE into RSContext

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#358]
@Tanmanfalcon, following up on conversation you, @wally-mac, @Cashe93 and I had yesterday, please add to this ticket to answer specifically from [LANDFIRE](https://www.landfire.gov) website which layers to add to RS Context we talked about. Below are some links form an old scoping discussion with @lauren-herbine. When done, please reassign to @philipbaileynar and then he will assign accordingly in NAR to get RSContext updated.

-----------
_Originally posted by @joewheaton in https://github.com/Riverscapes/riverscapes-tools/issues/118#issuecomment-786158515_

> @lauren-herbine the above are all super helpful and I like that you and @philipbaileynar moved these out to individual tasks. 
> 
> Another easier set will be to get many of these other LANDFIRE attributes in. Right now we just use BPS and EVT. However,
>  there are a ton of other [great products](https://www.landfire.gov/version_comparison.php) (you may want to explore some in[ LFDAT](https://www.landfire.gov/datatool.php) or as [WMS](https://www.landfire.gov/data_access.php)). 
> 
> Take a look and think about:
> [Disturbance Products](https://www.landfire.gov/disturbance.php)
> [Fuels](https://www.landfire.gov/disturbance.php)
> [Fire Regime](https://www.landfire.gov/fireregime.php) - includes vegetation departure and succession classes
> 
> I suspect many of these are worth putting into a RS Context Project, and some of these we'll want to sample and derive summaries from valley bottom segments, or upstream integrated values (e.g. network attributes tool), vs. buffer sampled values.
>

**Comment by jtgilbert** [comment]
Added EVH and EVC layers to National Project and RSContext
a0b963850358f5407350590a6887c87d802f8e48

**Comment by joewheaton** [comment]
What about the disturbance (FDist, HDist, NFVTDB), fuel (FCCS, FLM,) and fire regime (FRG, MFRI, PLS, PMS, PRS, SCLass) stuff @jtgilbert? Increasingly we're working at intersection of fire and PBR, so I think [these and maybe other layers](https://www.landfire.gov/comparison_table.php) will be really useful.

**Comment by MattReimer** [comment]
@joewheaton The work for this ticket seems done. Can we close it or is there still something outstanding?

**Comment by joewheaton** [comment]
Waiting on @jtgilbert to confirm @MattReimer. I asked:

> What about the disturbance (FDist, HDist, NFVTDB), fuel (FCCS, FLM,) and fire regime (FRG, MFRI, PLS, PMS, PRS, SCLass) stuff @jtgilbert? Increasingly we're working at intersection of fire and PBR, so I think [these and maybe other layers](https://www.landfire.gov/comparison_table.php) will be really useful.

I never got a response, but I do see a few commits. I don't know if they are like the original (just some arbitrary small subset of LANDFIRE). I asked for a bunch of layers. @jtgilbert?

**Comment by jtgilbert** [comment]
@joewheaton I included a handful more. V 2.2.0 changed a lot of the [layers](https://landfire.gov/comparison_table.php) so if there's others that you think we should have that aren't in that sample project, lmk.
