### ISSUE TITLE
Fix missing carriage returns for `<Warehouse>` versus `<MetaData>` section in top branches of RS Context

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#361]
## The Problem
This is really minor, but it does mean when you open the XML it is less readable. If we are going to have a short period of minor manual editing of `project.rs.xml` to add QA QC tags or do manual curation, I guess it would be nice. I have noticed in just about every `project.rs.xml` the  `<Warehouse>` tag and all the children's content is on one line with the   `<MetaData>` start tag all on one line.
```
<Warehouse><Meta name="id">464661dc-f716-4f18-8913-6c8b714c91d1</Meta><Meta name="user">d6c0ff26-8550-4f80-b9ea-6cc1e70a1c4d</Meta><Meta name="program">PUBLIC_DATA</Meta><Meta name="tags">Mississippi</Meta></Warehouse><MetaData>`
```

The above is from [RS Context for 05010003](https://data.riverscapes.xyz/#/PUBLIC_DATA/91a4b8dc-e62b-4cda-84fd-48fa3277115e) as an example.

Seems like it should be:
```
<Warehouse>
  <Meta name="id">464661dc-f716-4f18-8913-6c8b714c91d1</Meta>
  <Meta name="user">d6c0ff26-8550-4f80-b9ea-6cc1e70a1c4d</Meta>
  <Meta name="program">PUBLIC_DATA</Meta>
  <Meta name="tags">Mississippi</Meta>
</Warehouse>
<MetaData>`
```

## Is this a simple fix?
@MattReimer is this a matter of forcing carriage returns or something? Super low priority.

**Comment by MattReimer** [comment]
This is because the xml library I'm using to do this work doesn't do formatting. 

I get that the xml doesn't read very well but this is going to be some effort to fix and without a good formatter any fix will likely be a bit hack-y

Happy to have the ticket around though as a reminder to check in from time to time.

**Comment by joewheaton** [comment]
No big deal.... just thought I would flag it in case it is easy. Even if it is just a known issue, that's fine too. Thanks.

**Comment by philipbaileynar** [comment]
Note also that we strongly recommend everyone using a powerful text editor such as Visual Studio Code that can easily reformat documents.

The keyboard shortcut in Visual Studio Code is Windows Key (or Mac key) + P and then type "Format Document". It should detect that it's XMLand nicely lay out the document. Once you get in the habit this takes < 1 second after opening a file that's improperly laid out.
