### ISSUE TITLE
tauDEM Project XML Errors

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#367]
The tauDEM project XML uses backslashes instead of forward slashes for folder paths. This is preventing tauDEM projects from working in QRAVE.

```xml
<Outputs>
  <Raster guid="1a6af399-6069-492a-86bd-b11281c24892" id="DINFFLOWDIR_SLP">
	  <Name>TauDEM D-Inf Flow Directions Slope</Name>
	  <Path>outputs\dinfflowdir_slp.tif</Path>
  </Raster>
  <Raster guid="5f776084-03cf-4f88-9820-90cf912fba12" id="HAND_RASTER">
	  <Name>Hand Raster</Name>
	  <Path>outputs\HAND.tif</Path>
  </Raster>
  <Raster guid="d60e19d3-47a4-4a90-b14d-648f52646b2d" id="TWI_RASTER">
	  <Name>TWI Raster</Name>
	  <Path>outputs\twi.tif</Path>
  </Raster>
  <HTMLFile guid="42bf7cb7-3ec5-41fd-afc9-a7602aa13712" id="REPORT">
	  <Name>RSContext Report</Name>
	  <Path>outputs\hand.html</Path>
  </HTMLFile>
```

<img width="412" alt="Screen Shot 2021-08-05 at 9 46 41 AM" src="https://user-images.githubusercontent.com/8645379/128389036-8245b503-7be1-4707-b790-dabb5adbe198.png">

**Comment by philipbaileynar** [comment]
@MattReimer tells me that this is a problem with QRAVE and that the project XML can continue using windows folder paths. QRAVE needs to be able to handle both forward and backslashes.

**Comment by MattReimer** [comment]
Just for completeness here's the issue in QRAVE
https://github.com/Riverscapes/QRAVEPlugin/issues/30

This is not just a problem with QRAVE. It's a problem with all RAVE products. Here's the rules:

1. All tools that read project rs xml files should be able to handle windows paths but...
2. All tools that create project files should, as a best practice, use linux paths by default if they can.

**Comment by philipbaileynar** [comment]
Closing this issue based on Matt's feedback. The solution is to fix RAVE.
