### ISSUE TITLE
Derive and Add Hillshade to TauDEM projects

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#368]
Looking at [TauDEM 17070106](https://data.riverscapes.xyz/#/Anabranch/f713e68d-82d9-4e85-8daa-43ab896e8ad0).  We noticed there is no hillshade in the project. We need to:

- [x] Always derive and store in inputs the hillshade from DEM
- [x] Expose it in Business logic
- [x] Also, make sure the dateCreated field is taken care of (our's still reads as Jul 23 and I know you did this more recently).

**Comment by KellyMWhitehead** [comment]
- Hillshade is now generated with every taudem project and present in the project xml
- Hillshade is now in business logic and loads in qrave and arcrave.
- Time stamp verified in latest version of taudem project file metadata. If it is still not correct, this might be a warehouse issue.

@joewheaton Please check and close if this ticket is complete. Thanks!

**Comment by philipbaileynar** [comment]
I just downloaded a tauDEM project that was just run this week.

The hillshade raster is getting created in the correct location on disk.

`/inputs/dem_hillshade.tif`

And the project XML lists this DEM hillshade correctly in the inputs of the project:


```xml
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/Projects/XSD/V1/TauDEM.xsd">
  <Name>TauDEM project for HUC 1019000205</Name>
  <ProjectType>TauDEM</ProjectType>
  ...
  <Realizations>
    <TauDEM id="TauDEM" dateCreated="2021-09-09T15:21:57.112211" guid="9df1093f-0822-4f62-9903-5ca02b182582" productVersion="1.0.0">
    <Name>TauDEM project for HUC 1019000205</Name>
    <Inputs>
      ...
      <Raster guid="604e90c4-8dab-4933-b722-d844a4ee8863" id="HILLSHADE">
        <Name>DEM Hillshade</Name>
        <Path>inputs/dem_hillshade.tif</Path>
      </Raster>
    </Inputs>
      ...
```

and the latest tauDEM business logic correctly refers to the Hillshade using the correct XPath

```xml
<Node xpathlabel="Name" xpath="Realizations/TauDEM">
  <Children collapsed="false">
    <Node label="Inputs" xpath="Inputs">
    <Children collapsed="true">
      <Node label="Channel Area" xpath="Geopackage/Layers/Vector[@id='CHANNEL_AREA']" type="polygon"  symbology="ChannelArea" id="channel_area" />
      <Node label="Channel Line Input" xpath="Geopackage/Layers/Vector[@id='CHANNEL_LINES']" type="line" symbology="channel_line_network" id="channel_line" />
      <Node label="DEM" xpath="Raster[@id='DEM']" type="raster" symbology="dem" transparency="40" id="dem" />
      <Node label="DEM Hillshade" xpath="Raster[@id='HILLSHADE']" type="raster" symbology="hillshade" id="hillshade" />
```

Finally, I can also confirm that QRAVE correctly loaded the tauDEM project and the hillshade showed up in the map.

Closing this issue because it is complete.
