### ISSUE TITLE
VBET Tweaks and Refinements - 8/5/2021

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#369]
On 8/5/2021, @philipbaileynar, @KellyMWhitehead and @joewheaton dug into the latest VBET iteration on 10190005.  A number of concerns were raised, model behaviors realized and some decisions on changes made. Overall, @KellyMWhitehead is making excellent progress and VBET behavior is making sense. We are also happy with changes @KellyMWhitehead made towards #362.  Once @joewheaton saw the behavior forced by using distance from channel area as a line of evidence, he realized it didn't make sense to use with a transform function (yes... I changed my mind... sorry @KellyMWhitehead).

### To how Channel Area is used
Currently, these intermediates are exposed

![image](https://user-images.githubusercontent.com/9723905/128538607-37bd00e1-66b9-401c-85de-e9bda9b12e87.png)

We propose to:

- [x] A. Remove `Channel Euclidian Distance` and `Normalized Channel Distance` and application of distance from channel transform functions from projects and business logic
- [x] B. Replace `Channel Euclidian Distance` with binary 1 for channel area 0 for outside as `Rasterized Channel Area`
- [x] C.  Change `Normalized Channel Evidence` from something based on Euclidian distance and [transform functions](https://docs.google.com/spreadsheets/d/1rClE5BCK8nBXZBwH7cRRa3MJseE1Vj5xhYutxeHNotE/edit?usp=sharing), to the application of 0.995 to within channel areas 
- [x] D. Get rid of "Combined Evidence" in business logic (redundant with Normalized and "combination" is now in the output) and move and rename `Topographic Evidence` to `Combined Topographic Evidence` in "Normalized Evidence Rasters"

- [x] E. Apply average of three transformed evidences (slope, HAND, TWI) to get new `Combined Topographic Evidence`
- [x] F. Rename final `VBET_Evidence.tif` to `VBET_Likelihood.tif` and make it equal `Combined Topographic Evidence` with `Normalized Channel Evidence` burned in to replace values.

### To how slope is brought in

- [x] #370

@philipbaileynar and @KellyMWhitehead am I forgetting or missing anything? @shelbysawyer and @lauren-herbine this is FYI

**Comment by joewheaton** [comment]
> Changed to `Normalized Channel Raster` in business logic to mirror other normalized raster language (e.g. Normalized Slope Raster). @joewheaton Instead of `Normalized X Raster` should we call it `Normalized X Evidence` instead?

Sounds good @shelbysawyer

**Comment by KellyMWhitehead** [comment]
@joewheaton 

[VBET project](https://data.riverscapes.xyz/#/Anabranch/787ed25d-117d-49a9-a3eb-c14a3a22c564) with the latest changes.

**Comment by joewheaton** [comment]
> @joewheaton
> 
> [VBET project](https://data.riverscapes.xyz/#/Anabranch/787ed25d-117d-49a9-a3eb-c14a3a22c564) with the latest changes.

Thanks @KellyMWhitehead. Can you or @philipbaileynar please clarify if this "latest changes" includes Tasks A, C, E , F and G or only B and D (if it does, please check off tasks accordingly or explain why not and when). 

- [ ] @lauren-herbine, now that you have nice new business logic, please have a look at the Channel Area feeding this project (RiverscapesData/issues/18](https://github.com/Riverscapes/RiverscapesData/issues/18)). 
- [ ] @shelbysawyer please note I've added [TauDEM ](https://github.com/Riverscapes/RiverscapesData/issues/20)& [VBET](https://github.com/Riverscapes/RiverscapesData/issues/19) QA/QC assignments to explore this.
