### ISSUE TITLE
G. Calculate GDAL D8 Slope from DEM as part of TauDEM project and pass as input back to VBET as the Slope input derived from same DEM 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#370]
In current TauDEM we are calculating `Output_D-Infinity_Slope_Grid` as part of [DInfinityFlowDir](https://hydrology.usu.edu/taudem/taudem5/help53/DInfinityFlowDirections.html). We do not **yet** understand exactly what the units and range of this calculation are nor its sensitivity to cell resolution (e.g. 10 m NED vs. 1 m LiDAR). As such, we will continue to include it TauDEM projects, but we will:

- [x] - Move all TauDEM derived grids to a parent folder of `TauDEM Outputs` (including `Output_D-Infinity_Slope_Grid`) in business logic.
- [x] - Add a `GDAL Outputs` to business logic
- [x] - Start calculating a hillshade and put it under `GDAL Outputs` #368
- [x] - Start calculating a D8 Slope (using GDAL) as we know how this works and this is what we will use as input in VBET for #369 and under `GDAL Outputs`
- [x] - Also calculate (for comparison purposes initially) a `Slope Average Down` TauDEM slope raster and put under `TauDEM Outputs`

The reason to separate these outputs under the banner of TauDEM project is because they are both derived from TauDEM input of any DEM, but we want to be clear what is derived using Tarbotton's TauDEM, what is plain old GDAL, but we don't need a whole other project type for the GDAL stuff. 

@philipbaileynar anything I am forgetting? @lauren-herbine and @shelbysawyer FYI... @shelbysawyer, please incorporate above into your https://github.com/Riverscapes/RiverscapesXML/issues/167

**Comment by KellyMWhitehead** [comment]
@joewheaton,

Here is a [new project](https://data.riverscapes.xyz/#/Anabranch/5c9a3651-7d37-4813-a3ab-86a90697bf0c) with the changes, let me know if any other changes or adjustments are needed.

**Comment by joewheaton** [comment]
@shelbysawyer has done a lot of these in her pull request and I think @KellyMWhitehead has addressed all these in what I can tell in my initial [QC review of this project](https://github.com/Riverscapes/RiverscapesData/issues/20).
