### ISSUE TITLE
Where is TauDEM and Channel Area documentation for website?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#376]
Hey @MattReimer. @shelbysawyer and @lauren-herbine are going to start working on documentation for TauDEM and ChannelArea projects. I know for VBET, there is a `VBET/docs` folder in [`packages/`](https://github.com/Riverscapes/riverscapes-tools/tree/master/packages) corresponding to the https://tools.riverscapes.xyz/vbet/ Jekyll pages. However, in the `packages/`](https://github.com/Riverscapes/riverscapes-tools/tree/master/packages) folder there are only the following:
![image](https://user-images.githubusercontent.com/9723905/129099908-778aa3d2-ddec-418a-990a-2635d308d4bd.png)

Can you point us to (or create) where we should start authoring content for:

- [ ] Channel Area tool (e.g. `packages/channelarea/docs`)
- [ ] TauDEM tool (e.g. `packages/taudem/docs`)

**Comment by MattReimer** [comment]
It's all on the `dev` branch @joewheaton. please write any docs there and it will all merge to master with the tools at the same time.

**Comment by joewheaton** [comment]
Okay. Just spelling out as reminder for @joewheaton and @shelbysawyer :
- In general, the changes should be in the branch where that "tool" is getting developed (e.g. for TauDEM in a TauDEM branch)
- In this instance, that tool has been merged into the Development branch, so that's where it is
- It is important that the documentation goes along with the version of the tool
- The *.yml is a little specific to the Riverscapes Tool so we should copy that part from one that works (e.g. VBET)
- @joewheaton will work on a tool site template

**Comment by MattReimer** [comment]
Probably the best thing to do is make a branch called `docs` based on where `dev` is right now and then everyone make your changes there. We can merge it all when I get back in town

**Comment by MattReimer** [comment]
This task is a little ambiguous. I'm closing it for now. Re-open if you think it's not complete

**Comment by joewheaton** [comment]
It was really just a question. And you answered us and gave us direction.
