### ISSUE TITLE
A Hint on Veg layers from RCAT?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#38]
So I was in over in [RCAT seeing how it did in RAVE](https://github.com/Riverscapes/RCAT/issues/24), and discovered that for one of the old ETAL RCAT RS Projects, the existing cover was coming in with symbology preserved through RAVE.  May be worth exploring why @philipbaileynar.

![image](https://user-images.githubusercontent.com/9723905/81106524-061c8f00-8ed3-11ea-807a-d1733bde4aca.png)

Video:
[![](http://img.youtube.com/vi/aPa3qBNZHnY/0.jpg)](http://www.youtube.com/watch?v=aPa3qBNZHnY "")

**Comment by philipbaileynar** [comment]
Four year old ticket! 

I know we still have a few LandFire symbology issues, but closing this in lieu of more up to date information. Re-open if entirely relevant.
