### ISSUE TITLE
Look into some "special" FCodes and how they will affect ChannelArea Projects

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#380]
**Answer these (or similar) questions for the following FCodes:**
Where do these occur? 
How will they affect a ChannelArea Project?
How often do they occur? 
Should we keep them in the filtered lists of FCodes or not?

- [ ] Wash: 48400
- [ ] Submerged Stream: 46100
- [ ] Estuary: 49300
- [ ] Swamp/Marsh: 46600-46602
- [ ] Area of complex channels: 53700

**Comment by joewheaton** [comment]
At first glance, they all sounds like things worth keeping @lauren-herbine
