### ISSUE TITLE
VBET Tweaks and Refinements - 8/16/2021

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#381]
On 8/16/21 @philipbaileynar, @shelbysawyer, @lauren-herbine and @joewheaton discussed latest version of VBET. This feedback was based on progress in https://github.com/Riverscapes/RiverscapesData/issues/19 and from #369. 

- [X] @philipbaileynar please edit this ticket to get the five next steps we talked about queued up and tracked.

My recollection was there were five things you wrote down  (please elaborate as you and @KellyMWhitehead need to):

- [x] 1. Add new cookie cutter feature classes:
    - [x] `active_floodplain` (vbet_80 with channel areas cut out)
    - [x] `inactive_floodplain` (vbet_80 with vbet_68 cut out)
- [x] 2. Remove the current VBET polygon sanitization. The final VBET outputs for 68 and 80 will be pixelated. The only curation will be to:
    - [x] delete polygon features with area less than or equal to 10 pixels (i.e. 100m^2)
    - [x] delete polygon donuts with area less than or equal to 10 pixels
- [x] 3.  Add the input channel area feature class to the VBET output GeoPackage and call `vbet_channel_area`
- [ ] 4. Add centerline code back in to VBET. This is just for review at this stage. It's not an official VBET output for now.
- [x] 5. We live with existing segmentation! 

Once these above tweaks are done, please have @KellyMWhitehead 
- [x] Re-run 10190005 in [this ticket](https://github.com/Riverscapes/RiverscapesData/issues/21)
- [ ] After that, please queue up to [run the 20 Mississippi Testing HUC 8s](https://github.com/Riverscapes/RiverscapesData/issues/24) in RiverscapesData
- [ ] After that, we'll run all of Montana, ND, and SD (RS Context, Channel Area, TauDEM & HAND) in RiverscapesData

**Comment by joewheaton** [comment]
Thanks a ton @philipbaileynar for the clarifications and fixes above. Perfect. 

> Note that if we stick with the pixelated vectors then note that channel area vector will be smooth while 80 and 68 will be jagged. This affects the active floodplain feature class which will have a smooth donut and jagged exterior.

Understood and happy with that.

**Comment by KellyMWhitehead** [comment]
All changes were made except for adding the centerline. The rasterized edges of the new polygons are throwing off the centerline method (the increased number of vertices is adding several hours to the processing time and the jagged edges are producing bad results). Will investigate...

**Comment by philipbaileynar** [comment]
I approve of the decision to put centerlines on hold for now. Kelly, please close this issue and proceed to run the MHFD HUC for review by @joewheaton @lauren-herbine and @shelbysawyer

**Comment by joewheaton** [comment]
Thanks for updates guys. @philipbaileynar lets discuss a strategy for the centerlines. I will start a new ticket to explore this.

**Comment by joewheaton** [comment]
The two outstanding tasks here are already queued up in:
https://github.com/Riverscapes/RiverscapesData/issues/24 

Therefore I am closing this.
