### ISSUE TITLE
NHDPlusFlowlineVAA table not present for huc10, huc12

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#383]
Table is present for huc8 projects but not huc10 or 12. This table is needed for running vbet.

`hydrology/nhd_data.sqlite/NHDPlusFlowlineVAA`

**Comment by MattReimer** [comment]
Note to self: switch from exact huc match to "starts-with" match. That should fix it.

**Comment by MattReimer** [comment]
2769d05 fixes this.
