### ISSUE TITLE
Get riverscapes parameters CLI working for Cashe

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#384]
@MattReimer can you please get @Cashe93  up and running with the "riverscapes parameters CLI" script that I wrote a while back. For background, this is the simple command line interface I wrote for managing the BRAT parameters in postgres.

The script is at `scripts/riverscapes_parameter_cli.py` on the `rs_params_cli` branch that I just rebased onto dev. He will need a .env file with the database credentials. It obviously uses psycopg2 and inquirer.

@Cashe93 ping me when you are up and running and we can discuss how to use this tool to enter [BRAT parameters for Montana and the Dakotas](https://github.com/Riverscapes/RiverscapesData/issues/17).

**Comment by MattReimer** [comment]
We decided to go with QGIS PostGIS table editor instead of the script because then we don't need to install a full python3 environment just to run one script
