### ISSUE TITLE
BRAT slowdown calculating admin agency

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#386]
@MattReimer This [step](https://github.com/Riverscapes/riverscapes-tools/blob/4be68879dffbbced6eee1f775532ab04c30c85ad/packages/brat/sqlbrat/utils/conflict_attributes.py#L165) slows to a crawl, and is taking brat hours to run on some larger hucs.  Any ideas on a good way to speed this up?

**Comment by joewheaton** [comment]
@KellyMWhitehead and @MattReimer and @philipbaileynar, this is something we should chat about before going too far. There are a ton of things BRAT is calculating (admin agency is one of them) under the banner of "Management", very little of which is only of utility for looking at Beaver. Just like we stripped ChannelArea out of VBET, we should look at stripping out some of this Anthropogenic stuff into its own project. That does not mean we will not need to still fix what is causing it to crawl, but isolating it and pulling out of BRAT may have some advantages.

**Comment by philipbaileynar** [comment]
Closing this. We now have an anthro project type and #687 tracks the task to change BRAT to use anthro.
