### ISSUE TITLE
UI Spec on Commercial Grade VBET - V 1.0 (2021)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#389]
- [ ] Wire frames
- [ ] Metric table (dashboard)
- [ ] How will this be delivered

**Comment by joewheaton** [comment]
These are discussed in #8 and #6 for reference.

**Comment by joewheaton** [comment]
Part of the UI Spec for Commercial Grade VBET (which really now means a web-interface feature for VBET inside Riverscapes Studio) includes how people interact with "their" riverscape. This is really about how to take a default (provided segmentation) and potentially tweak the upstream and downstream boundaries of those segments so that the USER gets to define the "segment(s)" they care about.

In #17 we pointed out a variety of ways to get valley bottom segments. :

> A valley bottom segment could be defined as a longitudinal portion (reach or segment) of a riverscape, which spans the entire valley bottom width. They will typically be longer (longitudinally) than it is laterally (cross-valley).
> 
> # Ways to get them
> In a [commercial-grade](riverscapes.xyz/Tools/#tool-grade) or [professional-grade](riverscapes.xyz/Tools/#tool-grade) version of VBET, we might let the user choose which way to get there, or let them choose the valley bottom segmentation method and produce multiple **valley bottom segmentation** realizations. These include (not mutually-exclusive... could be combined or used to further split/segment):
> 
> 1. Load an already segmented network, segments drawn perpendicularity from all reach segment end points into VB intersection.
> 2. Segment based on tributary (of intput VBET network) junctions - _Note: this would be really important that the end  of the tributary includes the fan of that tributary._
> 3. Further segment based on intersection with polygon input (e.g. of land ownership or property boundaries) - pyBRAT has this option
> 4. Further segment based on intersection of polyline input with drainage network (e.g. road crossings) - _Note: it is important not to allow this for polyline intersection of VBET polygon, because many roads run parallel._
> 5. Further segment based on a uniform segmentation length (e.g. RCAT uses 500 m and BRAT uses 300 m by default).
> 6. Further segment based on variable segmentation length defined by continuous network function (this is what Fluvial Corridor Toolbox can do and GNAT implemented as well).
> 
> # Why the above are important
> The valley bottom segment is important as it defines the length-scale over-which potential valley bottom derivatives and metrics can be summarized.
> 
> @philipbaileynar - this is one way we give users ownership of their own VBETs.

To be clear, 1 will always be the default (generally broader length scale) segmentation we start with coming out of VBET. I think it makes sense for this.  For V 1.0 (2021), this IS the **only** option.  2-6 come in V 2.0.

**Comment by joewheaton** [comment]
## 3. How this will be delivered this year (2021)?

@philipbaileynar, we currently have what could be considered an Alpha version of VBET portal at https://maps.riverscapes.xyz/#/VBET (not currently running). What do you think about meeting this year's milestone commitment in one of the following:
1. Commercial Grade 1.0 being provided there in maps.riverscapes for the Montana-Dakotas
2. Commercial Grade 1.0 really just being WebRAVE for now?

I guess I am more interested in what the true version 1.0 of Web Riverscapes Studio looks like. I am worried about what it takes to explore the VBET outputs this year and thinking maybe we only allow viewing one HUC 8 at a time (for now) and then have that simple dashboard display of what you can view based on the _existing_ segment you select that will display some simple metrics.  

Thoughts?

**Comment by philipbaileynar** [comment]
Following on from your suggestion, how about defining the 2021 "Commercial Grade VBET" deliverable as:

1. VBET for all of Montana and the dakotas accessible in WebRAVE (and obviously QRAVE and ArcRAVE)
2. Extending VBET alpha web map with the following features:
   3. Ability to select a HUC2, 4, 6, 8, 10 and report the following metrics:
       1. Total Area
       2. Area active channel
       3. Area active flood plain
       4. Area inactive floodplain
       5. Length of channel broken down by FCode

Out of Scope:

- No centerlines
- No segmentation
- No ability to click on an individual valley bottom polygon

Note that this "regional scale VBET web map" will also be the portal through which VBET in the west is delivered.

**Comment by joewheaton** [comment]
> Following on from your suggestion, how about defining the 2021 "Commercial Grade VBET" deliverable as:
> 
> 1. VBET for all of Montana and the dakotas accessible in WebRAVE (and obviously QRAVE and ArcRAVE)
> 2. Extending VBET alpha web map with the following features:
>    3. Ability to select a HUC2, 4, 6, 8, 10 and report the following metrics:
>    1. Total Area
>    2. Area active channel
>    3. Area active flood plain
>    4. Area inactive floodplain
>    5. Length of channel broken down by FCode
> 
> Out of Scope:
> 
> * No centerlines
> * No segmentation
> * No ability to click on an individual valley bottom polygon
> 
> Note that this "regional scale VBET web map" will also be the portal through which VBET in the west is delivered.

@philipbaileynar sorry I missed this one. As we agreed yesterday we are going to keep our focus on getting VBET dialed and consider commercial grade VBET 1.0 (2021) just:

> Commercial Grade 1.0 really just being all VBET and related projects for Monana-Dakotas viewable in WebRAVE 

I will migrate the good ideas above to a new ticket.
