### ISSUE TITLE
Fall 2021 Tool output  QA

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#399]
@KellyMWhitehead we're going to be collapsing the branches on `riverscapes-tools` soon and we need to know what state this is in.

## Now

1. [x] @KellyMWhitehead Can you please prepare a cybercastor JSON file with the Mississsippi HUCS pointing at the NAR program (feel free to attach it to this ticket so we have it for next time.

Don't kick it off until we merge everything down

```
Tools: RSContext, ChannelArtea, TauDEM
Tags: Fall2021RSTools
Program: AnabranchDEV
Hucs: All the mississippi hucs
GIT_REF: dev
```

------------------------------------------------------------

## After `riverscapes-tools` merge

Once the merge happens the deliveries on this ticket will be

1. [x] @KellyMWhitehead Run this job and report on any cybercastor failures
2. [x] @KellyMWhitehead and @MattReimer file tickets and/or on `riverscapes-tools` 
3. [ ] Someone (TBA) needs to download as many of these projects as possible and check them for any issues in the software (looping back to step 2)

---------------

### Issues raised:

I will keep updating the list

- #410 (This is a data error. we need to solve it but it's not part of this ticket so ignore.
- #411 This is a simple shell scripting problem. very fixable.

**Comment by joewheaton** [comment]
@MattReimer re:

> Someone (TBA) needs to download as many of these projects as possible and check them for any issues in the software (looping back to step 2)

I'm getting this queued up and system in place to do just that (see also #34). My goal is that for every CyberCastor project that gets produced, at least 5-10 minutes of QC is performed and logged.

**Comment by MattReimer** [comment]
@joewheaton that's awesome. This is more of a QA tasks and so we need to move fast and iterate and re-run so we need to be a little careful about sucking up too much time. 

Mississippi QA set has `28 HUCS x 3 Tools x 10 minutes = 14 Hours`. Then if there are fixes we run it all again and that's another 14 hours so.... maybe not.

I think we should make our distinctions between QA and QC here.

* **For QC we want every project checked**.
* For QA we're probably looking for some representative set to give us confidence in our tools.

Happy to discuss though.

**Comment by MattReimer** [comment]
As of yesterday this is done
