### ISSUE TITLE
Get Confinement Working With Latest VBET and Channel Area Outputs

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#408]
Now that VBET is stable it's time to revisit confinement.

- [x] Refactor confinement to take the channel area tool output layer (instead of buffering polylines inside confinement itself)
- [x] Refactor confinement to take VBET68 layer (and works with multiple VBET polygons)
- [x] Confirm or implement the buffering of the channel area layer. This should be 1.5x the raster cell resolution, but given that confinement does not use any rasters, this value should be a command line parameter (i.1. 15m).
- [ ] Run confinement on a single HUC to prove it runs, and provide a quick review before we run it more broadly.

**Comment by lauren-herbine** [comment]
@KellyMWhitehead I am noticing that not all flowlines have confinement calculated for them (specifically mainstem Mississippi). Do you have any ideas as to why this might be happening? I looked at [08010100](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/5aa2a4f8-59c8-4fd2-9f70-92e65cb28732)

See video:
[![Alt-text](https://img.youtube.com/vi/4U4ChRbtwhM/0.jpg)](https://www.youtu.be/watch?v=4U4ChRbtwhM)

**Comment by philipbaileynar** [comment]
Super old issue that refers to Kelly's initial version of a Riverscapes compliant version of confinement. Now we have Jordan's new implement that is a different model. Closing because it refers to a deprecated model.
