### ISSUE TITLE
RS Context: Error Downloading DEM

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#410]
Error downloading file (dem?) from s3 for a handful of huc8's:

[FAILED-11040005.log](https://github.com/Riverscapes/riverscapes-tools/files/7108574/FAILED-11040005.log)
[FAILED-11110103.log](https://github.com/Riverscapes/riverscapes-tools/files/7108583/FAILED-11110103.log)

**Comment by MattReimer** [comment]
The errors here are something like: 

```
2021-09-03 21:02:03:: [error] [RS Context] 404 Client Error: Not Found for url: https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/n38w103/USGS_13_n38w103_20210401.tif
```

Which could mean a typo in the path name on the part of USGS or those records just don't exist. 

Regardless this is a data error and doesn't affect QA for Fall 2021 release #401

**Comment by MattReimer** [comment]
Closing this. Stale issue.
