### ISSUE TITLE
Add metadata to Channel Area Project Inputs and Outputs

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#412]
@philipbaileynar you may want to move this to someone else (or you may say it is done). We need to make sure that:
- NHD Inputs of Flow Areas, flow lines, and water bodies, all clearly trace back to Riverscapes Context and NHD+HR
- Custom inputs have space for custom tags on who provided (e.g. "Manually Digitized Channel Centerline from @nick4rivers")
- Bankfull buffers have adequate information on how and what they were derived from.

Currently the inputs on a standard project look like:
``` XML
<ChannelArea id="ChannelArea" dateCreated="2021-08-19T14:29:35.594617" guid="8cedd2e2-0134-11ec-b3c4-4ccc6a258976" productVersion="0.0.1">
			<Name>Channel Area for HUC 10190005</Name>
			<Inputs>
				<Geopackage guid="ab45a25f-cf07-4d71-b8b9-c714ca9fc771" id="INPUTS">
					<Name>Inputs</Name>
					<Path>inputs\inputs.gpkg</Path>
					<Layers>
						<Vector guid="472cc38c-d783-4f0b-b0e3-f1c8969d70a1" id="FLOWLINES">
							<Name>NHD Flowlines</Name>
							<Path>flowlines</Path>
						</Vector>
						<Vector guid="3e854ec3-66d6-491f-9c63-24bc53a71508" id="FLOWAREAS">
							<Name>NHD Flow Areas</Name>
							<Path>flowareas</Path>
						</Vector>
						<Vector guid="f112faa8-bde8-46fd-8f55-3a9c85e6a7a2" id="WATER_BODIES">
							<Name>NHD Water Body Areas</Name>
							<Path>waterbody</Path>
						</Vector>
					</Layers>
				</Geopackage>
			</Inputs>
```

**Comment by MattReimer** [comment]
Whoever takes this on keep in mind that we have metadata types now. git in touch if you need to know more.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead can you please cut and paste the inputs XML from a channel area project file that was run since the September release and that was run with NHD data. I want to see whether the riverscapes context project metadata are flowing into channel area projects correctly. 

@MattReimer this automated inclusion of upstream metadata should be automatic, correct?

**Comment by MattReimer** [comment]
This is not quite so simple. We're going from a shp file to a geopackage so I'm not sure the augmenter can handle that. 

I don't expect this is going to be a big amount of work

This file is what you need to run (there should be a VSCode launch item for it and if there isn't just copy it from RSContext)
https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/channel/channel/channel_rs.py

The line that should be doing the work is this one I believe
https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/classes/rs_project.py#L546

**Comment by KellyMWhitehead** [comment]
> NHD Inputs of Flow Areas, flow lines, and water bodies, all clearly trace back to Riverscapes Context and NHD+HR

I have checked the xml augmenter for channel is working for NHD/shapefile inputs. Some earlier local runs might have missed this step, but should not be a problem with any cybercastor runs.

> Custom inputs have space for custom tags on who provided (e.g. "Manually Digitized Channel Centerline from @nick4rivers")

This can be done by manually adding tags for now, [example](https://github.com/Riverscapes/RiverscapesData/issues/85)

> Bankfull buffers have adequate information on how and what they were derived from.

The bankfull equation and parameters are recorded in the project metadata in the upcoming release.
