### ISSUE TITLE
Explore RAP API Integration for Riverscapes Studio

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#417]
In #259 I asked the following question of @philipbaileynar and @MattReimer. Can one of you answer over there or here?

> 1. Can you get an API key from Brady and see if we can get back this and suggest how and where we would store it? Would we put it in its own riverscapes project, in a VBET. Would we leave it as its geoJSON or suck it into a Riverscape Context project?

> 3. @philipbaileynar I'm thinking this is a helpful thought exercise for how to connect to some "added value" for my little riverscape. In other words, give me something for the riverscape I care about (< 5 mi) and make my life easier so I don't need to go to that other place to get it. I am not thinking about this as a new "network extent" output in Riverscapes Context or VBET or its own. Is that right?
> 4. @philipbaileynar they do have WMTS for their layers. Should/could we add these as additional "Basemaps" in RAVE?
> 5. @MattReimer, if they have WMTS for their layers, can we use that to display in our web maps (I'm guessing hard no)?

This would be part of Riverscape Studio 2.0 (i.e. 2022) so this is a low priority. But this is part of #390.

**Comment by MattReimer** [comment]
We should be able to add WMTS layers we should be able to integrate that into QRAVE.

**Comment by philipbaileynar** [comment]
I believe ArcGIS can handle WMS and WMTS but not xyz map tiles. Arc Pro can handle map tiles.
