### ISSUE TITLE
Collect Documentation for Riverscapes Context

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#418]
We need to author the Riverscapes Context documentation pages: https://tools.riverscapes.xyz/rscontext/

![image](https://user-images.githubusercontent.com/9723905/132248242-73f40409-146f-4167-8693-f777f71ed142.png)

**Comment by philipbaileynar** [comment]
Note that the latest version of RSC now has metadata for every layer that consists of two things:

1. Brief, plain English summary that draws from this [JSON file](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/rscontext/rscontext/layer_descriptions.json) during the RSC run.
2. a URL that links to a section on [this page](https://tools.riverscapes.xyz/rscontext/data.html). QRAVE (but not yet ArcRAVE) is capable of showing these URLs as a hyperlink that users can click on.

So the task at hand is to author the detailed descriptions of each layer on the [Jekyll markdown page](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/rscontext/docs/data.md) that generates the wiki page represented in the metadata URLs.

**Comment by philipbaileynar** [comment]
This ticket should only be tackled once the latest round of new layers are added to RSC.

Outstanding tasks:

1. Ensure that the JSON file linked above includes all the latest layers.
2. Ensure that the JSON content is getting written to the RSC project.rs.xml correctly.
3. Ensure that the RSC wiki lists all the latest layers.

**Comment by MattReimer** [comment]
@jtgilbert is this done? Do we need to do any work on it for ChannelArea too?

**Comment by jtgilbert** [comment]
Yeah, this was finished with the other RSContext tasks
