### ISSUE TITLE
VBET Area Attributes

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#426]
Please add attribute to fields to the five output VBET feature classes that contains the area of each polygon feature. In all cases, the column name should be called `area_ha` and contain the area in hectares, to 5 decimal places:

- Outputs\vbet.gpkg
    - active_floodplain
    - inactive_floodplain
    - vbet_68
    - vbet_80
    - vbet_channel_area

As discussed, the geometries are in WGS84 so they will need re-projecting for this calculation. I suggest once each feature class is created, looping over each feature, converting the individual geometry to Albers Conic (EPSG: [5070](https://epsg.io/5070)) and grabbing the area.

The other option would be to do a feature class level operation to reproject the entire layer, but this creates clutter that needs cleaning up, and unnecessary IO.

Notes

- double check the EPSG above. I thiiiiiink it's right
- more tickets to come with additional VBET area metrics.

**Comment by KellyMWhitehead** [comment]
Step 1 - add area to features, is complete.
![image](https://user-images.githubusercontent.com/10746997/133528144-7b2ea388-3780-40d8-be4c-decc5b82df4f.png)

**Comment by KellyMWhitehead** [comment]
Added to 0d088e9b558c565085955ff051c1b2570a8ad02e
