### ISSUE TITLE
VBET Output Feature Class Names

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#427]
It's been at least 45 minutes since we renamed VBET feature classes and so it's time to break everything again!

We are about to change the threshold of the active floodplain from 80 to 90 (separate ticket). This won't be the last time we do this (because we love pain) and so let's preemptively rename VBET outputs to omit the threshold value.

|Existing Feature Class Name|Proposed Name|Description|
|---|---|---|
|`vbet_68`|`vbet_full`|continuous valley wide polygons|
|`vbet_80`|`vbet_ia`|continuous polygons the width of the active floodplain|
|`vbet_channel_area`|*no change*| continuous extent of the channel|
|`active_floodplain`|*no change*|`vbet_ia` with `vbet_channel_area` cut out|
|`inactive_floodplain`|*no change*|`vbet_full` with `vbet_ia` cut out|

@joewheaton pleaes approve this change before I assign it to @KellyMWhitehead for action.
@shelbysawyer and @lauren-herbine heads up because this will break business logic.

**Comment by joewheaton** [comment]
I made two minor changes to above table and I approve of these. Thanks!

**Comment by philipbaileynar** [comment]
@joewheaton remind me what "ia" stands for in `vbet_ia` again please?

**Comment by KellyMWhitehead** [comment]
Please review [this project](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/418b1e7b-8897-4773-9f75-b23a9ff9825a) for the threshold and layer name changes. 

Note that the business logic will need to be updated with the new layer names.

**Comment by joewheaton** [comment]
> @joewheaton remind me what "ia" stands for in `vbet_ia` again please?

It is just meant to stand for boundary between **I**nactive and **A**ctive floodplains.

**Comment by philipbaileynar** [comment]
I downloaded the project and review the layers. Nailed it (until next time!)

**Comment by philipbaileynar** [comment]
@joewheaton discovered that @KellyMWhitehead shipped the demo project with custom BL.

**Comment by MattReimer** [comment]
This is all great. Having the hardcoded thresholds in layer and path names was giving me reflux.

**Comment by joewheaton** [comment]
> This is all great. Having the hardcoded thresholds in layer and path names was giving me reflux.

Yes, that was a short-sided on the fly decision originally... my bad. I never liked it.
