### ISSUE TITLE
VBET Threshold Change from 80 to 90

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#428]
Please change the active floodplain threshold from 80 to 90. 

In addition please write both thresholds to the project metadata as below. Note the user of the new [metadata types](https://github.com/Riverscapes/RiverscapesXML/blob/master/Projects/XSD/V1/RiverscapesProject.xsd#L65-L80).

```xml
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/Projects/XSD/V1/VBET.xsd">
    <Name>VBET for HUC 10190004</Name>
    <ProjectType>VBET</ProjectType>
    <MetaData>
        <Meta name="ModelVersion">0.4.0</Meta>
        <Meta name="dateCreated" type="isodate">2021-09-13T22:09:07.238999</Meta>
        <Meta name="HUC8">10190004</Meta>
        <Meta name="HUC">10190004</Meta>
        <Meta name="VBETVersion">0.4.0</Meta>
        <Meta name="VBETTimestamp" type="timestamp">1631570947</Meta>
        <Meta name="Scenario Name">UPDATED_TESTING</Meta>
        <Meta name="FlowlineType">NHD</Meta>
        <Meta name="Runner">Cybercastor</Meta>
        <Meta name="ProcTimeS" type="int">459.33</Meta>
        <Meta name="ProcTimeHuman">7:39 minutes</Meta>

        <Meta type="int" name="VBET_Active_Floodplain_Threshold">90</Meta>
        <Meta type="int" name="VBET_Inactive_Floodplain_Threshold">68</Meta>
    </MetaData>
```

See separate ticket for the renaming of the output features classes #427

**Comment by KellyMWhitehead** [comment]
Please review [this project](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/418b1e7b-8897-4773-9f75-b23a9ff9825a) for the threshold and layer name changes. 

Note that the business logic will need to be updated with the new layer names.

**Comment by philipbaileynar** [comment]
metadata looks good.

<img width="580" alt="Screen Shot 2021-09-16 at 2 48 37 PM" src="https://user-images.githubusercontent.com/8645379/133690411-6872bdf4-dc61-493a-9535-dddb1b6e7255.png">

and I have created this QC issue for @shelbysawyer  to review.

https://github.com/Riverscapes/RiverscapesData/issues/80
