### ISSUE TITLE
VBET Metrics for inactive_floodplain Feature Class

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#431]
These metrics are for the `inactive_floodplain` feature class (in addition to the raw `area_ha` that is already being calculated).

|Attribute Column|Units|Description|
|---|---|---|
|prop_valley_bottom_pc|percent|area of this feature divided by the sum of areas from `vbet_full` that have the same levelPath, multiple by 100|
|prop_inactive_pc|percent|area of this feature divided by the sum of all features in `inactive_floodplain` feature class with the same levelPath, multiplied by 100|

**Comment by joewheaton** [comment]
@philipbaileynar these look good. 

@lauren-herbine and @shelbysawyer FYI... this relates to #395 and #108, and of course #430.

**Comment by KellyMWhitehead** [comment]
Added in 597479469a489092db3016b37514282e963ee714
