### ISSUE TITLE
Stop removing donuts

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#438]
The channel area tool is currently removing interior rings (donuts) from NHD flow areas. This made some sense for small islands, but the way big rivers are digitized means that the spaces between anabranches are also donuts.

In the example below the two anabranches in the first image are actually represented using an exterior and interior ring. The second image shows the channel area tool output with the interior ring removed, causing a filled channel area. Essentially what looks like a lake/waterbody.

# Action

Stop filling donuts (aka dropping interior rings) in the channel area tool. Let HAND, slope and other VBET evidence pull these areas into the valley bottom in VBET. 

<img width="601" alt="Screen Shot 2021-09-20 at 3 05 50 PM" src="https://user-images.githubusercontent.com/8645379/134215161-1f335578-1f57-4200-b2d6-2d3cb854656d.png">

<img width="601" alt="Screen Shot 2021-09-20 at 3 06 10 PM" src="https://user-images.githubusercontent.com/8645379/134215174-84635542-9af9-4b01-a953-bac7255b76b2.png">

**Comment by KellyMWhitehead** [comment]
@philipbaileynar do you happen to have the huc for this? I updated the code, but I can also run a quick test to make sure this particular site is fixed.

**Comment by joewheaton** [comment]
Yes, this is in the Upper Humboldt: https://data.riverscapes.xyz/#/Anabranch/6512c178-985a-4255-bdb8-ede2dbdc742d

**Comment by MattReimer** [comment]
![](https://c.tenor.com/TRjZAIXAxL8AAAAC/donut-simpson.gif)

**Comment by KellyMWhitehead** [comment]
Changed in f3b23cfffe3fdd0d2adb7471541685af15738800
