### ISSUE TITLE
Geopackage Field Alias

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#443]
Research topic of adding Field Aliases to Geopackage layers.

1. Is this a property that can be stored in the geopackage? (tried using optional `gpkg_data_columns`, but didn't seem to have an effect in arc or qgis)
2. layer files? (.lyr or .qml)
3. Other?

If we find a method, then apply to #430

**Comment by philipbaileynar** [comment]
Researched. Wasn't obvious.
