### ISSUE TITLE
Drainage Area raster without values

### ISSUE THREAD

**Issue by sshahverdian** [Riverscapes/riverscapes-tools#446]
When using the Identify tool in ArcGIS to learn a drainage area value, the pixel value comes up 0.000, for all pixels. The symbology appears to know the values of each pixel (it changes along the drainage network) but the identify tool isn't picking it up.
![drainage area - no value](https://user-images.githubusercontent.com/21205131/135509603-62555c30-d0f1-4a79-bfd1-d03a6a5b6423.png)

**Comment by philipbaileynar** [comment]
The best way to get drain areas in riverscapes context is to use the NHD flow lines and use the TotDA_sqkm attribute field. Do not rely on the rasters.

**Comment by sshahverdian** [comment]
Good to know. Thanks.
