### ISSUE TITLE
Research Viability of Riverscapes Context Running to Completion for border-spanning HUCs

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#455]
For a long time, we have struggled with HUCs that span the border with Canada. We have several initiatives that make it a priority to figure out how we can overcome this obstacle:

- @chris3jordan is asking for the CRB
- We have a lot of trans-border HUCs for BLM in Montana and North Dakota for @AldenShallcross 
- VBET in the west project

The starting point is obviously riverscapes context. So the initial questions are:

1. Which riverscapes context layers are breaking for trans-border HUCs?
2. Can we handle these exceptions more gracefully and get RSC to complete for trans-border HUCs?
3. If we are successful, are the mandatory layers for our subsequent tools all present?
    - channel area
    - tauDEM
    - VBET
    - BRAT
    - Confinement

Area of Interest... Chris Jordan is particularly interested in 17020006 Okanogan. Please make this the case study for this task.

<img width="514" alt="Screen Shot 2021-10-18 at 12 12 04 PM" src="https://user-images.githubusercontent.com/8645379/137792513-ee1d1020-902a-478c-bd6e-14d147b86deb.png">

Requst summary: Modify RSC script to successfully produce a project for trans-boundary HUCs that's capable of supporting our downstream tools.

**Comment by KellyMWhitehead** [comment]
Implemented in rscontext version 1.2.2
