### ISSUE TITLE
BRAT: Fix `IsPerennial` to be full list of perennials

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#457]
This is the default:
![image](https://user-images.githubusercontent.com/9723905/137966042-fe769035-8ff9-4ce6-a49a-b7d783bd2360.png)

But, when you apply `"IsPeren"=1` feature filter query, it is too restrictive.

![image](https://user-images.githubusercontent.com/9723905/137969072-58849c8c-8e28-4e32-abf8-f533292f2a88.png)
So if you use `"ReachCode"=46006  or "ReachCode"=55800 or "ReachCode"=33400` you get:
![image](https://user-images.githubusercontent.com/9723905/137969838-251af354-9e02-4f48-96b7-0d3757a7ba3d.png)

We should 
- [ ] Make `IsPeren` based on FCode we use in RS Context
- [ ] Change `ReachCode` to `FlowType`

Related to #456

**Comment by joewheaton** [comment]
@philipbaileynar FYI

**Comment by philipbaileynar** [comment]
Updated summary of tasks:

1. Change `ReachCode` column name on BRAT Attributes table to `FlowType`. 
    - Need to search code for any uses. I think there might be some either in in the conservation model or the report.
1. Change `IsPeren` to use the following definition:

```sql
"ReachCode"=46006 or "ReachCode"=55800 or "ReachCode"=33400
```

@joewheaton you're sure this is the final ruleset for `IsPeren`? This is just using "reach" FCodes and not using waterbody or flow area FCodes. Is that correct?

**Comment by KellyMWhitehead** [comment]
IsPeren added to cff978a4b35a965737a92cc0dd84fbd6f304fce9

FlowType added to be7fd8e5d8341421b78abcc82e797deb6c90b88d
