### ISSUE TITLE
Calculate MODIS LST for hydro region 17

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#46]
The goal of this task is to produce a SQLite database containing land surface temperature (LST) for NHDPlus HR reaches in hydro region 17. For now, this is a one-off request. This process will **not** get integrated into any of our production tools.

LST data are available in a custom (NOAA?) HDF4 format. You can drag these into QGIS and they seem to appear OK!

<img width="531" alt="Screen Shot 2020-07-28 at 3 25 49 PM" src="https://user-images.githubusercontent.com/8645379/92780778-611a3300-f358-11ea-8b6c-cc46ecff762e.png">

The goal is to extract the average value from these rasters for each reach for all MODIS data between 2005 and 2015. We will do this by an area weighted average of the raster cells within the reach catchment polygons (shown in green below):

<img width="920" alt="Screen Shot 2020-09-10 at 9 21 45 AM" src="https://user-images.githubusercontent.com/8645379/92780869-7a22e400-f358-11ea-873b-88927c60b8a8.png">

We want to avoid reprojecting the raster values (because this will resample and alter the raw values). So instead of reprojecting the MODIS rasters we will reproject the catchment polygons to the custom MODIS coordinate reference system. You can see this by right clicking on the MODIS raster in QGIS and viewing the layer properties.

Note that the MODIS rasters contain several bands, each representing a different data product. The product that we want is the `MODIS 8-d daylight pass LST`. This is one of the options when you drag the HDF file into the QGIS map window. It also shows you which band number that represents (note that GDAL bands are 1-based referenced. Not zero based.)

Note that the data source string gives a hint as to how to load one of these HDF files using GDAL driver in Python.

<img width="979" alt="Screen Shot 2020-09-10 at 11 31 34 AM" src="https://user-images.githubusercontent.com/8645379/92781700-37add700-f359-11ea-9058-a6ae6203d9b8.png">

<img width="459" alt="Screen Shot 2020-09-10 at 11 29 54 AM" src="https://user-images.githubusercontent.com/8645379/92781424-f9b0b300-f358-11ea-845e-27a1c2798dc0.png">

## Deliverable

The deliverable should be a simple SQLite database with the following columns:

* NHDPlusID (integer, identifies the reach)
* MODIS_Scene (DATETIME, identifies the MODIS scene for which the LST value applies)
* LST (REAL, mean MODIS 8-d LST value)

Here's some DDL that creates this table in SQLite:

```sql
CREATE TABLE MODIS_LST (
    NHDPlusID   INTEGER  NOT NULL,
    MODIS_Scene DATETIME NOT NULL,
    LST         REAL,
    PRIMARY KEY (
        NHDPlusID,
        MODIS_Scene
    )
)
WITHOUT ROWID;
```

## NHD Data

I see three options for working with the NHD data. My current preference is for #3. Ping me and we can discuss.

1. We run riverscapes context for every 8 digit HUC in hydro region 17. We need to do this anyway for VBET and BRAT. 
1. We take our [code for downloading NHD data](https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/clean_nhd_data.py) and write a new script to just run this method. It will be faster than running riverscapes context for every HUC.
1. We have developed new code for [uploading NHD data to PostGIS](https://github.com/NorthArrowResearch/netatt-monorepo/blob/master/python/netatt/load_nhd.py). This might be the simplest method because then the LST script can simply connect to PostGIS and loop over all the reaches there.

Note that NHD stores the reach identification `NHDPlusID` as a float, but the output SQLite database should store it as an integer. I've found it reliable to simply convert the value in Python.

## MODIS LST Data

We need all MODIS data from 2005 to 2015.

These data are available via an [FTP site](https://e4ftl01.cr.usgs.gov/MOLT/MOD11A2.006/), but I think you need login credentials to download more than a single item. After some poking around I think the best way to obtain the MODIS data is via the desktop software utility called [DAAC2Disk](https://lpdaac.usgs.gov/tools/daac2diskscripts/#products). This seems to handle the login process and then allows you to enter search parameters for filtering to specific datasets.

MODIS raster cell resolution is roughly 900m. Many of the reach catchments will fall inside a single pixel. However, when there are multiple pixels that intersect a MODIS pixel we probably want to do some kind of area weighted average.

## Other useful code.

The following code snippet is the magic source that takes a polygon and loads just the part of a raster that intersects that polygon and loads just those cells into a NumPy array. We use this in BRAT. Note that the Rasterio mask method takes a parameter that determines whether to include all cells that touch the polygon or just those inside the polygon. given the 900m cell resolution you'll have to test this carefully.

https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/raster_buffer_stats.py#L125

Also note that the polygon must be in the same spatial reference as the raster or you get an empty array back. We have lots of examples that [reproject geometries](https://github.com/Riverscapes/riverscapes-tools/blob/c857670b175f0ce3a3dee7f9bf6e53ccf65242b7/packages/brat/sqlbrat/lib/build_network.py#L151-L153). The trick will be loading the bespoke NOAA spatial reference from the MODIS rasters.

Note that raster spatial references and vector spatial references are represented by different object types in Python. Ping me or Matt about this.

## Pseudo Code

```python
create_sqlite_database

open a single MODIS raster and load its projection

create transform from NHD projection to MODIS projection

# There will be > 100,000 reaches. Matt has good code for batching such tasks
for reach in all_reaches:
  load_catchment_polygon
  transform_catchment_polygon to raster SRS
  
  for image in all_images:
    mask = raster_buffer_stats(polygon, image)
    # do some area weighted magic on the mask array here.
    avg_lst = np.average(mask)
		insert_lst_into_sqlite    
      
```

**Comment by philipbaileynar** [comment]
@MattReimer can you respond with where this one-time script should live please? It's not part of an official product, but it will use rs-commons.

**Comment by MattReimer** [comment]
I think `/packages/rscontext/scripts` would be fine for this.

**Comment by philipbaileynar** [comment]
Here is a script that can be adapted to quickly download and unzip NHDPlus HR file geodatabases:

https://github.com/NorthArrowResearch/netatt-monorepo/blob/master/python/netatt/load_nhd.py

**Comment by philipbaileynar** [comment]
I reviewed the initial output of the LST task with and have the following enhancements:

1. Please convert the temperature values to degrees celcius. Note that the MODIS values are special "NASA Kelvin" and that the conversion involves and offset and then a multiplier. The proper conversion is described in the PDF manual on the MODIS site.
1. Please enhance the SQLite database output with a new table that stores the original MODIS cell values. This will bloat the database substantially, but it will enable future users to generate different statistics should they need to (max, min) etc. The new table will have the following columns

* NHDPlusID (int, not null)
* ModisDate (datetime, not null)
* LST (real, MODIS cell value converted to degrees C)
* Area (real, area of MODIS cell overlap with reach catchment polygon. square metres)

Call this table `MODIS_LST_Cells`. Like the main table, this table does not need a ROWID. It also doesn't need a primary key, but the NHDPlusID and ModisDate columns should be indexed.

If the addition of the new table bloats the database to unusable size, or slows the script to be untenable, then we can rethink this strategy.

**Comment by MattReimer** [comment]
The work for this is done and the data are now cranking. I'm going to close this task since the development work is done.
