### ISSUE TITLE
VBET Output bloat due to needless points

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#468]
You can see here that this river segment has a perfectly round end with WAY too many points

From this project: <https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/99e6030d-203c-4fef-8d0d-c98606d1e2bd>

<img width="845" alt="Screen Shot 2021-10-28 at 3 32 52 PM" src="https://user-images.githubusercontent.com/1063391/139463743-663d260d-4ed3-4313-ad5e-b475d3cd5406.png">

<img width="845" alt="Screen Shot 2021-10-28 at 3 29 27 PM" src="https://user-images.githubusercontent.com/1063391/139463731-b6f24066-91b2-4fce-90d3-922b776cfe8e.png">

This is causing out VBET outputs to be gigabytes when they could be 100-200Mb. These points have no real value so we should find a way to simplify

### Considerations

We should do this carefully. 

* This tool can be run at varying scales so we don't just want a blanket simplification that will work on the Mississippi but not a flume.
* We should make sure that whatever strategy we use doesn't add any more time to the process than we need to. VBET is already taking way too long

**Comment by joewheaton** [comment]
@MattReimer I think with all the recent improvements you and @KellyMWhitehead have made to VBET, this is null. Reopen if you disagree.
