### ISSUE TITLE
Research that BRAT waterbody threshold parameter is set correctly?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#470]
sqlBRAT has a [commandline parameter for specifying the max waterbody size](https://github.com/Riverscapes/riverscapes-tools/blob/4d2f3f6af82fa94bdfcc7c9f062550e9ab153fa4/packages/brat/.vscode/launch.json#L53). Artificial paths in waterbodys larger than this value should be filtered out of the BRAT feature class.

This feature originated in pyBRAT. @wally-mac can you remind me what value was used for pyBRAT runs please?

@KellyMWhitehead can you please research that this command line parameter is being interpreted correctly and working as designed. Once @wally-mac tells us the pyBRAT number, please verify that this is what is being used.

If this value is working properly, #469 might be taken care of because artificial paths in large waterbodies will not be present anywhere in the sqlBRAT outputs. I suspect that there is a unit conversion issue that might mean this feature is not working as it should.

**Comment by wally-mac** [comment]
@philipbaileynar in 2014 during the Utah statewide run of BRAT we established a water body threshold size of 500 square meters (a conceivably large beaver pond).

**Comment by KellyMWhitehead** [comment]
The value in cybercastor is set to `--max_waterbody 0.001`

**Comment by philipbaileynar** [comment]
and @KellyMWhitehead are waterbodies with an area larger than this value having their capacity set to 0?

In other words:

1. The property is actually getting used
2. The proprty is being converted to the correct units during comparison with the actual data

**Comment by KellyMWhitehead** [comment]
1) After reviewing the [brat code](https://github.com/Riverscapes/riverscapes-tools/blob/4d2f3f6af82fa94bdfcc7c9f062550e9ab153fa4/packages/brat/sqlbrat/brat_build.py#L173), it appears that max waterbodies is not currently being used.
2) The max waterbodies parameter eventually gets used [here ](https://github.com/Riverscapes/riverscapes-tools/blob/4d2f3f6af82fa94bdfcc7c9f062550e9ab153fa4/lib/commons/rscommons/build_network.py#L90)as an attribute filter.

**Comment by philipbaileynar** [comment]
The usage you refer to in point 2 above is the same behaviour as pyBRAT. 

In preparing the BRAT network, it should only include artifical paths that occur in "small waterbodies", i.e. waterbodies with an area less than the parameter threshold.  This appears to be the logic in the line that you linked to.

So why are artifical paths for big waterbodies being retained? Here's an egregious example for [Lake Abert BRAT run](https://webrave.riverscapes.xyz/#/Anabranch/2f0c0721-617b-4bbe-a477-d1322be9cf20).

<img width="1264" alt="Screen Shot 2021-11-09 at 12 42 21 PM" src="https://user-images.githubusercontent.com/8645379/141001417-e81a0e7e-0862-468c-8eb1-e40b410f75cb.png">

**Comment by KellyMWhitehead** [comment]
Lines 90-97 are not getting run because waterbody_max_size is None here. waterbody_max_size is not getting passed to build_network.

**Comment by philipbaileynar** [comment]
Is the solution as easy as ensuring that the command line argument is sent to the build_network function? Once that is plumbed the lines of code you linked to should be activated and start doing their job?

**Comment by KellyMWhitehead** [comment]
I think its just adding max_waterbodies to line 173 of brat_build. It looks like its plumbed in everywhere else. This really is just an attribute filter for the AreaSqKm field in nhd waterbodies. No geometry calculations involved.

Strange that the vs launch files use a value of `100`, those will need to be changed as well for running locally (but doesn't affect cybercastor).

**Comment by philipbaileynar** [comment]
Yes, this is a problem with default parameters for function arguments; they are easily overlooked.

Please:

1. fix the issue by passing `max_waterbody` parameter into brat_build. 
2. Make sure that both cybercaster your local runs have the correct value for max_waterbody.
3. Do a test run and spot check that waterbodies above that threshold do not have any features in the output BRAT geopackage.
4. Close this issue when this is confirmed.

(It won't result in too many features getting dropped, but it's always nice to discard data rather than accumulate it!)

**Comment by KellyMWhitehead** [comment]
max waterbody param reinstated in a33e6814723a5ef7bf71bcea61ba261f04862592

I had to remove the 58000 fcode filter in the flowlines, since this was including all artificial reaches (overriding the water body max size filter). All artificial reaches included are either 1) inside a flow area polygon or 2) in a water body polygon smaller than the max size. (76727e2405476d9bc9ee845223dba0dcb27cef4d)
