### ISSUE TITLE
Update BRAT pubs/references

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#473]

**Comment by jtgilbert** [comment]
Graham, H. A., Puttock, A., Macfarlane, W. W., Wheaton, J. M., Gilbert, J. T., Campbell-Palmer, R., ... & Brazier, R. E. (2020). Modelling Eurasian beaver foraging habitat and dam suitability, for predicting the location and number of dams throughout catchments in Great Britain. European Journal of Wildlife Research, 66(3), 1-18.

**Comment by joewheaton** [comment]
Always provide DOIs and URLs when you start editing these. See: https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/Common.html#toc-include-citations
