### ISSUE TITLE
Next Steps for VBET: Master Issue

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#476]
I'm using this issue to serve as the master issue for next steps with VBET. I'm really just trying to get some things down on "paper" here, so feel free to edit as you see fit! Based on a recent conversation with @joewheaton, my understanding is that these are my next to-dos:

- [ ] #477

- Currently, the transform curves have been specified, but not calibrated. Calibration will help VBET output a better prediction of valley bottom extent in all settings.

- [x] #478

- Right now, VBET is overpredicting in areas of low slope. One idea to address this issue is to change the weighting of normalized evidence (TWI, HAND, and Slope) for areas under a given slope threshold.

I only need a handful of HUCs across the Montana / Dakotas region to test these tweaks in, but it would be great to have some variety (one with steeper slopes and high elevation meadows / headwaters, one in the low-angle agricultural plains, one with a mix, etc).

**Experimental HUCs:**
[Insert warehouse project link]
[Insert warehouse project link]

[Link](https://github.com/Riverscapes/riverscapes-tools/labels/pkg%3AVBET) to current VBET issues in the `riverscapes-tools` repo

**Comment by lauren-herbine** [comment]
Hey @shelbysawyer it would be awesome if you used the Two Medicine (10030201) watershed as one of your "testing the tweaks in" HUCs. I am using this as a main example watershed, and we already have a lot of our tools run for here (mainly why I chose it).

[RSContext](https://data.riverscapes.xyz/#/BLM/98113441-eae3-4ee4-b6b3-c13445901454)
[VBET](https://data.riverscapes.xyz/#/BLM/871f96ef-ec4f-4eaf-91bb-7f702e0cca36)
[Channel Area](https://data.riverscapes.xyz/#/BLM/4da078f3-78fc-4921-9291-f32b5d17a934)
[TauDEM](https://data.riverscapes.xyz/#/BLM/c95a5971-13aa-4ead-a864-e802d6f1f7d7)

**Comment by joewheaton** [comment]
This is superseded by new work (particularly #652 and #653.).
