### ISSUE TITLE
1. Calibrate VBET transform curves

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#477]
Currently, the transform curves have been specified, but not calibrated. Calibration will help VBET output a better prediction of valley bottom extent in all settings.

We want to partition our specification/calibration points so that we can use the same dataset to both calibrate and validate it. 
- We could break it up-- random sample, 10% from each ecoregion?

@shelbysawyer I am adding here so these become tracked tasks and can be split into issues if needed:
@shelbysawyer please:
- [x] #523
- [x] #524
     - For me this is being clearer about what the NHD and NED data think are likelihoods within a pixel and NOT focusing as much on the boundaries between classes (I think previously we muddled these too things)
       - `Active Channel Area` (where its mapped by NHD, not what it shows on aerial photo)
       - `Active Floodplain` (pick in middle of 10 m pixels that are at least 1 to 2 pixels wide appear low-enough to flood regularly and are supporting riparian vegetation
       - `Inactive Floodplain` (areas in middle of 10 m pixels and meet definition of could plausibly flood, but are distinctive from neighboring hillslopes, terraces.
       - `Terrace` clear examples of terraces that are obviously terraces and clearly from a historic, relic flow-regime (i.e. can't be confused with anthropogenic incision episodes). If not sure, 
       - `Probably not Valley Bottom`
       - `Definitely not Valley Bottom` - way up on a mountain top or hillslope
- [x] Provide new instructions to us (e.g. @lauren-herbine, @jtgilbert, @wally-mac, @sshahverdian, and @nick4rivers - hints in bullets above) to get you another 3000 to 5000 points at new watersheds beyond just the calibration 20 original. Only have us use RS-Context as a line of evidence. Ask for 1-2 hours max of everyone's time.
- [x] @shelbysawyer make a markdown page that can later go on the VBET doc page. Make a video showing exactly what we want them to do.. shoot to map the "center" of each category. Make branch and pull request to docs for this.
   - Maybe direct people on how to handle fans specifically. I'm thinking it is good to have some of `Active Channel Area`, `Active Floodplain` that belong to mainstem only and not tributary adjacent to fans.  I'm thinking it is also good to ask for `Active Channel Area on Fan`, `Active Floodplain on Fan` and `Inactive Floodplain on Fan` specifically on alluvial fans but _only_ on the part of the upper fans that are clearly NOT part of the mainstem trunk valley bottom (avoid shared custody areas at distal edge).
   - Also instruct people to use QRAVE and DEM that adjusts its elevation range to view as line of evidence. Tell them they can optionally look at TauDEM derivative lines of evidence (e.g. slope, topographic index or HAND), but do not use VBET outputs please or combined evidence. Say that toggling basemap imagery is fine, but this is not as important as basing off of what model sees. 
- [ ] Re-run after you have revised and new points the same scripts you ran before based on random 90% sample of data (hold back 10% for validation). We will use these to calibrate the transform curves.  We will weight these validation points differently than we weigh field derived ones.
- [x] #525

**Comment by joewheaton** [comment]
## The old spreadsheet and Slopes first
https://docs.google.com/spreadsheets/d/1rClE5BCK8nBXZBwH7cRRa3MJseE1Vj5xhYutxeHNotE/edit?usp=sharing

We need to play with our slopes that are being too inclusive right now:
![image](https://user-images.githubusercontent.com/9723905/142674001-5e17abc0-4ac8-4b26-8752-7c3e03d20dc5.png)

It seems like what we're using at 0.68 is way too high in each case. It also seems like we have too fat of a tail should fall off quicker.

I have just qualitatively tweaked on a 11-19 tab: 
![image](https://user-images.githubusercontent.com/9723905/142674551-364cba4c-a0d8-4a20-b829-25f4ef43ad40.png)

@shelbysawyer what we need to do is
1. Request a few test runs with above.
2. Interrogate differences.
3. Actually calibrate these curves to nearest degree with our independent data from above. 

And then transferred over to here: https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/vbet/database/data/intersect/intersect/inflections.csv

**Comment by wally-mac** [comment]
@shelbysawyer please let me know how I can help with generation of the calibration points.

**Comment by philipbaileynar** [comment]
| categoryid | displaylabel | count |
| :--- | :--- | :--- |
| 1 | Estimated Active Channel | 791 |
| 2 | Highly Likely Active Floodplain | 442 |
| 3 | Likely Active Floodplain | 228 |
| 4 | Possible Active Floodplain | 137 |
| 5 | Possible Inactive Floodplain | 305 |
| 6 | Plausible Valley Bottom Extent | 310 |
| 8 | Very Unlikely Valley Bottom Extent | 66 |
| 9 | Likely Terrace \(non-valley bottom\) | 18 |
| 10 | Upland \(non-valley bottom\) | 493 |

**Comment by philipbaileynar** [comment]
After updating to new categories:

| categoryid | displaylabel | count |
| :--- | :--- | :--- |
| 11 | Active Channel Area | 791 |
| 12 | Active Floodplain | 807 |
| 13 | Inactive Floodplain | 615 |
| 14 | Terrace | 18 |
| 15 | Probably not Valley Bottom | 66 |
| 16 | Definitely not Valley Bottom | 493 |


```sql
update vbetobservations set categoryid = 11 where categoryid =1;
update vbetobservations set categoryid = 12 where categoryid in (2,3, 4);
update vbetobservations set categoryid = 13 where categoryid in (5,6);
update vbetobservations set categoryid = 14  where categoryid =9;
update vbetobservations set categoryid = 15 where categoryid =8;
update vbetobservations set categoryid = 16 where categoryid =10;
```

**Comment by MattReimer** [comment]
@shelbysawyer where are we with this? I've kind of lost the plot here. Could you either close it or let me know what's still outstanding?

**Comment by shelbysawyer** [comment]
Hi @MattReimer yes-- I'm on the east coast for 2 weeks of field work but will dive into VBET tasks more fully when I'm back in office on Nov 28th.

**Comment by joewheaton** [comment]
@shelbysawyer after you and I discuss #674, lets make a new issue regarding VBET transform curve calibration. This one you can refer back to but has gotten a little too big.
