### ISSUE TITLE
Add metadata tag of cell resolution for every raster from every cyber-castor tool

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#481]
Ideally we would calculate and store in the riverscapes project a metadata tag for cell resolution for every raster in every project. To start, lets at least start doing that for all our cybercastor tools.

**Comment by joewheaton** [comment]
This was prompted by looking at VBET project in WebRAVE and not being able to figure out if it was 10 m or 1 m cell resolution:

[![Video Link https://youtu.be/sdzUiUfI2FU](http://img.youtube.com/vi/sdzUiUfI2FU/0.jpg)](http://www.youtube.com/watch?v=sdzUiUfI2FU "")

**Comment by joewheaton** [comment]
@philipbaileynar and @KellyMWhitehead, is this an easy fix for 0.8.5, or annoying and we kick it out to VBET 1.1?

**Comment by MattReimer** [comment]
It's pretty annoying. Let's Kick it in favour of getting 0.8.5 out the door.

**Comment by philipbaileynar** [comment]
This should be done in a reusable way as a general function in RSCommons. I would like @MattReimer to implement this after the new warehouse is up and running but before we do the big re-run of all HUC8 projects.

**Comment by MattReimer** [comment]
This is a legacy issue that may have fallen through the cracks @jtgilbert can you review and close it if it's no longer relevant.?

**Comment by joewheaton** [comment]
It is even more relevant now. I am simply asking for resolution of input rasters to be layer metadata.

**Comment by jtgilbert** [comment]
Do we want it in layer units or always meters?

**Comment by jtgilbert** [comment]
37c52d321daa2104ae24708388805ff59d104e8b
implemented for RSContext. Downstream projects that consume these rasters will automatically have the metadata. Need to implement for newly created rasters in other projects still.

**Comment by joewheaton** [comment]
I would like it in layer units, but that should be reported in key (i.e type will be a string), and almost always in meters.

**Comment by jtgilbert** [comment]
That's what I mean - our layers are never projected so their units are almost always degrees, but I can roughly convert them to meters for the metadata.

**Comment by jtgilbert** [comment]
This is implemented in RSContext through VBET.
