### ISSUE TITLE
Implement complete and thorough cross project referencing for all inputs/intermedaites from other Cyber Castor tools

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#482]
We are not always doing what we purport to on cross-project referencing (i.e. when an input or intermediate in one model is sourced directly from another project). We have incomplete and partial implementation of this in some of our models. For example, in this TauDEM project below, the Layer information for the DEM helpfully:
![image](https://user-images.githubusercontent.com/9723905/142732635-5ffe56df-d1f3-4e26-8d06-7bb7b71a9c41.png)

We just need 

[![Video Link https://youtu.be/MF5xyvoHIH8](http://img.youtube.com/vi/MF5xyvoHIH8/0.jpg)](http://www.youtube.com/watch?v=MF5xyvoHIH8 "")

## The Ask

- [ ] #483
- [ ] Project Referencing 2 - Feature request - Change the hyperlink from the warehouse link in new tab to a webrave link in new tab (ideally that goes to that project with that specific layer turned on).
- [ ] Project Referencing 3 - Leave the necessary reference breadcrumbs for this to work in all new runs of models (i.e. release new version of each model with metadata being correctly recorded in project.rs.xml)
- [ ] Project Referencing 4 - Fix all existing CyberCastor runs in warehouse to include these correctly (I'd prefer this is not just a re-run brute force  (i.e. 3) but whatever works).
- [ ] Internal Layer Referencing 1 - Every intermediate and output within a project should refer to the input(s) or intermediate(s) within that project that it was derived from.

**Comment by joewheaton** [comment]
@MattReimer and @philipbaileynar I know this some of these may get pushed over to WebRAVE, but this felt more like a project.rs.xml issue at runtime of tools so I put it here.

**Comment by MattReimer** [comment]
This is going to be fixed by Dataset sourcing in the new Warehouse. I'm closing this as it does not directly relate to anything actrionable in the new warehouse.

**Comment by joewheaton** [comment]
@MattReimer okay. I am going to take the five specific asks (those are real features) and assign them to myself to check and see that the Beta or Alpha releases you send me of WebRAVE are dong this. I get you wanting to close things out off your list, but I want to make sure that things I go to the effort of requesting (for good reasons) are tracked somewhere. So I'll make this one my problem for now and trust you've got it. But I will check on it.  Thanks.  

I'm also worried this is in the wrong place. It seems like this issue belongs over in https://github.com/Riverscapes/rs-web-monorepo?
