### ISSUE TITLE
Please update sqlBRAT tool to add metadata tags to inputs to trace for sqlBRAT what project valley bottom, roads and rails came from.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#487]
This is from parent project: https://github.com/Riverscapes/RiverscapesXML/issues/384. 

This is also related to: https://github.com/Riverscapes/riverscapes-tools/issues/482

**Comment by jtgilbert** [comment]
@philipbaileynar I don't think so, the only thing that's really been updated with BRAT is the input paths from the updated upstream projects.
