### ISSUE TITLE
Please update sqlBRAT tool to write the buffer polygons to the intermediates.gpkg

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#488]
This is from parent project: https://github.com/Riverscapes/RiverscapesXML/issues/384. 

This is also related to: https://github.com/Riverscapes/riverscapes-tools/issues/482

**Comment by KellyMWhitehead** [comment]
Added to d509f3bacc4c965fc1de7d2a9c72e3fba353daf7
