### ISSUE TITLE
FIx drainage Area raster without values in RS Context

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#492]
This issue comes from:

### Discussed in https://github.com/Riverscapes/riverscapes-tools/discussions/448

<div type='discussions-op-text'>

<sup>Originally posted by **sshahverdian** September 30, 2021</sup>
When using the Identify tool in ArcGIS to learn a drainage area value, the pixel value comes up 0.000, for all pixels. The symbology appears to know the values of each pixel (it changes along the drainage network) but the identify tool isn't picking it up.
![drainage area - no value](https://user-images.githubusercontent.com/21205131/135509603-62555c30-d0f1-4a79-bfd1-d03a6a5b6423.png)
</div>

**Comment by joewheaton** [comment]
@philipbaileynar we did not adequately answer this issue from @sshahverdian. We need to flag it up as a bug and fix it.

**Comment by joewheaton** [comment]
@jtgilbert notice how we go from a discussion item to an issue. It allows the discussion to remain as that, but creates an actionable issue off of it.

**Comment by jtgilbert** [comment]
removed drainage area from RSContext 
e3a92bbeadbe98d5e91b532d4a2a8137a6102579

**Comment by MattReimer** [comment]
Work is done and verified. Closing
