### ISSUE TITLE
Update MT BRAT Q2 hydrologic equations

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#505]
Issue noticed as part of QC (https://github.com/Riverscapes/RiverscapesData/issues/99)
The equations being used were actually Q50. Please update to Q2:

| Region                             | Q2                                                          |
|------------------------------------|-------------------------------------------------------------|
| West                               | 12.2 * (DRNAREA ** 0.818) * (PRECIP ** 1.42) * (FORESTP1 ** -0.896)     |
| Northwest                          | 223 * (DRNAREA ** 0.732)                                        |
| Northwest Foothills                | 7.6 * (DRNAREA ** 0.469) * (PRECIP ** 1.38)                         |
| Northeast Plains                   | 181 * (DRNAREA ** 0.579) * ((ELEV5K+1) ** -0.28)                    |
| East-Central Plains                | 497 * (DRNAREA ** 0.454) * ((SLP30_30M+1) ** 0.279) * (ET_SPR ** -3.48) |
| Southeast Plains                   | 467 * (DRNAREA ** 0.541) * (FORESTP1 ** -0.067) * (ET_SPR ** -3.99)     |
| Upper Yellowstone-Central Mountain | 131 * (DRNAREA ** 0.708) * ((ELEV6K+1) ** -0.166)                   |
| Southwest                           | 142 * (DRNAREA ** 0.721) * ((ELEV6K+1) ** -0.336)                   |

I'll assign you for now @Cashe93, but pass it along as needed.

**Comment by philipbaileynar** [comment]
Remember @Cashe93 to verify that any watersheds where you are updating equations also have any new parameters required by the equations...

**Comment by jtgilbert** [comment]
@philipbaileynar  good point, but all the params should be there, the equations use the same ones, just have different coefficients and exponents.

**Comment by Cashe93** [comment]
Thanks for compiling these, @jtgilbert. I'll be assigning this to @leallysmith.

**Comment by leallysmith** [comment]
All the Q2 equations have been updated to what you have listed @jtgilbert 

The east central plains region does not have the slop30_30m parameter only the slop50_30m parameter, I will retrieve the slop30_30m values and update here once they're in.

**Comment by philipbaileynar** [comment]
I am showing @jtgilbert how to take ownership of the BRAT parameters postgres database later today. He will be able to export these equations ready for use in sqlBRAT.

**Comment by leallysmith** [comment]
All HUCs in the east central plains region have values for the slop30_30m parameter.
