### ISSUE TITLE
Add Geology to Riverscapes Context Projects

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#506]
### Discussed in https://github.com/Riverscapes/riverscapes-website/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **stephen-bennett** November 30, 2021</sup>
I'd like to request that a geology layer be added to riverscapes projects as it is a fundamental driver of riverscape form and function </div>

**Comment by joewheaton** [comment]
@philipbaileynar after you scope this, we'll decide when and how to prioritize it. No rush.

**Comment by philipbaileynar** [comment]
Completed by @jtgilbert
