### ISSUE TITLE
Confinement ratios off when downloaded

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#507]
Confinement ratio looks good in WebRave (0-1), but when downloaded and looked at in Q, the ratio goes from 1-2. Putting this here to address in future. See video:

https://youtu.be/6ssSMrshGOI

Looking at [10030201](https://data.riverscapes.xyz/#/NRCS_CEAP/c1862e19-cf4c-406f-a292-db1ce6f335ce)

Additionally, not all reaches have confinement calculated for them. I found some headwater reaches along with the mainstem Two Medicine. Need to look into that.

@joewheaton this is what we briefly chatted about

**Comment by philipbaileynar** [comment]
@lauren-herbine note the [FCodes used to run confinement](https://github.com/Riverscapes/riverscapes-tools/blob/cfce0044a829b5b6efd5ddf9ce7f29cb9bb7c604/packages/gnat/.vscode/launch.json#L69). Might answer your question?

**Comment by lauren-herbine** [comment]
Huh, the Two Medicine is listed as a 55800 (artificial path), so the code should cover that...

**Comment by philipbaileynar** [comment]
Two year old issue. Confinement has been completely rewritten since this ticket was created.
