### ISSUE TITLE
Where has VBET been run?

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#514]
Hi @philipbaileynar,

I'm making up a map for my AGU poster to show where VBET has been run and where it will be run in the future. @joewheaton  suggested that I reach out to you to get a table of the HUCs where VBET has been run to do this.

My original thought was to grab the relevant HUC 2 shapefiles for the Mississippi, BLM Montana / Dakotas, and CRB for the "has been run" but I'm not sure exactly which areas are slated to be done next? This is what I'm thinking of, on a basic level:

![map example](https://user-images.githubusercontent.com/73311751/144684569-f89c9bc5-ba9b-4c40-a2b7-f23759d7486b.png)

Thanks!

**Comment by joewheaton** [comment]
@philipbaileynar I was thinking you could just provide from Warehouse database either the list of HUC 8 that have a VBET run or query she can use to select from WBD shapefile. We know where it is planned from HUC 2s.

**Comment by philipbaileynar** [comment]
Here's a CSV of every VBET in the warehouse.

[2021_12_03_vbet_projects.csv](https://github.com/Riverscapes/riverscapes-tools/files/7653042/2021_12_03_vbet_projects.csv)

Future Runs:

- Mississippi two digit HUCs 05, 06, 07, 08, 10, 11
- CEAP will be: 12, 13, 14, 15, 16, 17, 18

My recommendation is to get hold of the national watershed boundary dataset and use attribute queries to make the map. Should be quick and easy.

**Comment by shelbysawyer** [comment]
Great. Thank you!

**Comment by shelbysawyer** [comment]
@Cashe93 Do you know an easy way to do this in ArcMap? I've got a CSV of the HUC8 codes and a HUC8 shapefile for the US. I know how to select by attribute when it's only a few items (picture of how I've always done it), but the CSV has like 500+ HUC codes that I need to select and this method doesn't seem like it will work for this task. I'd have to add the ' symbol to each one. Any suggestions? Is there a much simpler way to go about this? Thanks!

<img width="491" alt="query" src="https://user-images.githubusercontent.com/73311751/144725646-3807f188-dc9d-4084-86bf-79cdc1a8fd7e.PNG">

**Comment by shelbysawyer** [comment]
Commenting with my workflow for reference, even though I'm sure there are much better ways:
1) Formatted column to put each HUC code in single quotes (select column, format cells, custom: `'\#\'`)
2) Used an [online converter](https://convert.town/column-to-comma-separated-list) to convert list into comma separated list
3) Copied this and input it into the ArcMap "select by attribute" query box

**Comment by shelbysawyer** [comment]
One last question for you @philipbaileynar 

For the HUC 2s with area outside the border of the US, will VBET be run only for areas within the border?

**Comment by philipbaileynar** [comment]
I believe it has VBET polygons just in the portion that is inside the US

**Comment by joewheaton** [comment]
@shelbysawyer I know this is closed, but I am dumping the map you made for [your poster](https://eventpilotadmin.com//web/page.php?page=Session&project=AGU21&id=p982905-94120) here for reference:
![image](https://user-images.githubusercontent.com/9723905/146078829-37400490-92d1-4984-b342-5e9682b87d3e.png)
