### ISSUE TITLE
RS Context Downloading multiple DEM's

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#515]
Issue: 
Science base spatial query returns all versions of the dems that intersect the huc polygon. 
See https://github.com/Riverscapes/riverscapes-tools/issues/511

Note this does not impact the data quality or processing, only downloading and storing extra data.

Resolution:
- [ ] Need to select one version of each dem to download from science base (newest?)

**Comment by philipbaileynar** [comment]
Newest makes sense. Can we tell that from S3 or do we need Science Base?

**Comment by KellyMWhitehead** [comment]
In theory we can get it from either, since science base is sending along all urls.

**Comment by philipbaileynar** [comment]
Might be fixed. Do a test run before changing anything.
