### ISSUE TITLE
ArcRAVE VBET Shape Integrity Issue

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#527]
Hi @philipbaileynar and/or @MattReimer,

While exploring a VBET project in ArcRAVE, I noticed issues with a few layers not drawing. Specifically, the Estimated Valley Bottom Geomorphic Units are not drawing properly. 

Here's a video of the issue:
[![Not showing https://youtu.be/IpKcofUv3G8](http://img.youtube.com/vi/IpKcofUv3G8/0.jpg)](http://www.youtube.com/watch?v=IpKcofUv3G8"")

**Comment by MattReimer** [comment]
Oh wow. That's a new one for me. Usually Arc renders anything we throw at it.

 Could be the VBET process is creating impossible shapes?

@shelbysawyer does this probem exist in QRave or WebRAVE?

Can you drop a warehouse or webRAVE link so we can follow up?

**Comment by shelbysawyer** [comment]
[Here](https://data.riverscapes.xyz/#/BLM/871f96ef-ec4f-4eaf-91bb-7f702e0cca36) is the project that I'm seeing the issue in. QRAVE and WebRAVE are working fine, it looks like it's only an issue in ArcRAVE.

**Comment by philipbaileynar** [comment]
Could also be a GeoPackage allows geometries that Esri doesn't allow.

@shelbysawyer can you export the effected layer to ShapeFile from QGIS. Then try loading it in ArcGIS.

**Comment by shelbysawyer** [comment]
@philipbaileynar When I exported the 3 layers from QGIS and added them in ArcGIS, there were no drawing problems.

**Comment by shelbysawyer** [comment]
@philipbaileynar @MattReimer I'm going to keep this open because it's still happening, even though I know it's not a priority right now.

**Comment by shelbysawyer** [comment]
@philipbaileynar I've been exploring the latest VBET runs and noticed that this issue still hasn't gone away in ArcRAVE but is not an issue in QRAVE. For example, here is roughly the same area in a project, opened in both:

ArcRAVE:
<img width="607" alt="arc" src="https://user-images.githubusercontent.com/73311751/189362565-7d2b09ce-1f2f-4f36-beb2-a78ca37026eb.PNG">

QRAVE:
<img width="421" alt="q" src="https://user-images.githubusercontent.com/73311751/189362575-9dd87863-d72a-41a9-a0e1-ed724caba15d.PNG">

**Comment by philipbaileynar** [comment]
@KellyMWhitehead any thoughts? Are we using a spatial view for this layer?

**Comment by joewheaton** [comment]
@shelbysawyer I think this one is obsolete with new version of VBET. Please, in your testing, get VBET, open up in ArcRAVE and make new issue if this one comes up again.
