### ISSUE TITLE
vwReaches layer missing from RVD output gpkg

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#528]
When viewing the contents of the RVD output gpkg in Q, the vwReaches layer is missing:
![2021-12-15_105230](https://user-images.githubusercontent.com/21687931/146240256-93a384b4-c48c-4281-aadb-e0da986bcb00.png)

In Arc, the table exists, but not the layer. It seems to manage to bring in the table and associate it with the reachGeometry layer so that it can still display (there's no way to get it to display in Q):
![2021-12-15_105915](https://user-images.githubusercontent.com/21687931/146240402-0609459e-5556-4e1c-851b-ffc1265fde7b.png)

In WebRave it also shows that the vwReaches is missing and there are no outputs to display as a result:
![2021-11-17_103422](https://user-images.githubusercontent.com/21687931/146240479-1ba0c3e1-dcd2-4046-9d82-c6cc4fd6e883.png)

**Comment by philipbaileynar** [comment]
Geospatial views are a squishy part of the GeoPackage specification. See [requirement 150](https://docs.ogc.org/is/12-128r17/12-128r17.html#_table_definition_3).

@jtgilbert can you check if the view meets the requirement. The first column of the view is a unique integer and that there's also a geometry column?

**Comment by jtgilbert** [comment]
@philipbaileynar When I open it in Arc, the table has both required fields.

**Comment by philipbaileynar** [comment]
RVD is dead. Long live RCAT!
