### ISSUE TITLE
Add Land Use Intensity Raster output to BRAT

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#529]
From: https://github.com/Riverscapes/RiverscapesXML/issues/418 @philipbaileynar  had suggested:

> Land Use Intensity for each vegetation type is stored in the SQLite database. In for users to see this information spatially ssqlBRAT needs to be enhanced to write a new raster that reclassifies the EVT raster with the land use intensities from the database. This is similar to how we produce the veg suitability rasters.

This ticket is to request that enhancement. @philipbaileynar add any notes as needed.

**Comment by philipbaileynar** [comment]
Now part of anthro thanks to @jtgilbert
