### ISSUE TITLE
Where is the code for those cool new BRAT HTML report features?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#544]
In this video, @philipbaileynar shows how he incorporated a bunch of requests from @AldenShallcross on plots he included in the attached EA into the sqlBRAT HTML report. 

[![Video Link](http://img.youtube.com/vi/LV0W8ZBKZiA/0.jpg)](http://www.youtube.com/watch?v=LV0W8ZBKZiA "")

@philipbaileynar can you please point @jtgilbert to what branch you put those changes on?  @Jdgilby you should watch this too.
[LTPBR_EA_11_1_2021.docx](https://github.com/Riverscapes/riverscapes-tools/files/7999367/LTPBR_EA_11_1_2021.docx)

**Comment by philipbaileynar** [comment]
On the [brat_report](https://github.com/Riverscapes/riverscapes-tools/commits/brat_report) branch in this repo.
