### ISSUE TITLE
Start Editing Google Docs for what you want in HTML Reports

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#546]
FYI - @wally-mac, @Riverscapes/riverscape-project-curators, @Jdgilby and @jtgilbert, and @philipbaileynar. See also #545 and #544 

We are finally going to start getting the HTML reports to look like we want for our standard [Production-Grade Network Scale Tools](). This will require @jtgilbert initially getting some training from @philipbaileynar and @MattReimer, but then he can show @Jdgilby and we can start sharing some of this across the @Riverscapes/riverscape-project-curators.

Before we make any changes to code, we need to agree on what we want. Every report will get automatically generated for every one of these projects. So lets make sure it includes (in no particular order):

- Attributes (who's model, who paid for it, who ran it, who curated it)
- All bread crumbs lead to right places (i.e. no good having a reference to something that they can't click on and go there)
- Readable (no variable names) 
- Has enough boiler plate narrative text to explain what is in each section, and refers reader to documentation 
- Has the most typical standard summary information we want for every node in the tree
- Provides summaries that will help you troubleshoot, validate, verify or do QC
- Provides summaries, statistics and graphics that managers or users of model output will want
- Provides links to more generic information on tools, datasets and methods elsewhere
- Is graphically pleasing
- All figures and tables have captions
- Does not need to include maps (although maybe use new geographic information for each project to just have an embedded GoogleMap locator map). 
- Has a useful TOC

This will be iterative. But lets get these cleaned up so they have useful content. Separately, we'll get them looking pretty.

When suggesting graphs, please include an example (can be real or a sketch), explain what it is calculated from.

## Google Docs to Edit and Suggest Features 

- [ ] Make requests and edits for HTML reports in #547
- [ ] Make requests and edits for HTML reports in RSContext [Google Doc](https://docs.google.com/document/d/11xJFKt9xGly8cNvBWU9UFB1VQZFFmdMMEPzia6TkNYE/edit?usp=sharing)
- [ ] Make requests and edits for HTML reports in Channel Area [Google Doc](https://docs.google.com/document/d/11S4H8_B4N_sgjyDUIkft8ZXDcavjlPOctLrGnICzT00/edit?usp=sharing)
- [ ] Make requests and edits for HTML reports in TauDEM [Google Doc](https://docs.google.com/document/d/1v_pL6vgdFBw2li1H--dZRaXD324c16X38JAKpH4L6R8/edit?usp=sharing)
- [ ] #727

**Comment by joewheaton** [comment]
Also, @jtgilbert take a look at https://github.com/Riverscapes/RiverscapesData/issues/163. This is a ridiculously common query we want to be able to run. I have spoken numerous times with @philipbaileynar about getting a PostGIS database going that makes it easy to ask these questions: https://github.com/Riverscapes/RiverscapesData/issues/11.  It does strike me that some of these can at least be answered at HUC 8 scale (not across multiple HUC 8s) as part of our HTML reports. If it warrants a new ticket, make one.

**Comment by wally-mac** [comment]
@jtgilbert, @Jdgilby (is this you Josh?) and @Cashe93 I think it would be useful if we meet and discussed this as a group and then started divvying out tasks.  How about a zoom meeting on this Thursdays 1PM?

**Comment by Cashe93** [comment]
@wally-mac, could we do Wednesday? I will be on the road Thursday and will likely be out of service.

**Comment by wally-mac** [comment]
Yes, how about tomorrow (Wednesday) at 1PM?

**Comment by Cashe93** [comment]
That works for me.

**Comment by Jdgilby** [comment]
@wally-mac It is me. That works for me as well.

**Comment by jtgilbert** [comment]
I'm good with that also.

**Comment by wally-mac** [comment]
Right on, I'll setup a Zoom and send it out.

**Comment by MattReimer** [comment]
I'm punting this forward to the Channel Area milestone. Last activity was 9 months ago. @jtgilbert and @joewheaton what are the actions here? How can we move this forward?

**Comment by joewheaton** [comment]
Let's take a look at BRAT report and see what of these aspirations it achieved and what it fell short on. Then turn to actionable next steps and set priorities.

**Comment by joewheaton** [comment]
@shelbysawyer please start working with @jtgilbert on this and make some new issues. VBET is close enough you can see what is going to be available. So lets get the report dialed to show what we want. I'm happy to brainstorm and meet with you soon on this. See also #661.

**Comment by philipbaileynar** [comment]
Two years since the Google docs were created and not a single contribution.

I'm closing this in favour of smaller, less overwhelming tickets that garner zero input.
