### ISSUE TITLE
Pull Slope, HAND, TWI Values for Updated VBET Observation Points

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#556]
Using [this guide](https://gist.github.com/shelbysawyer/07ffa065aa0c0c772342384fb8869d1a), team members will be collecting additional VBET observation points to create a more robust dataset.

Once additional points are collected, the corresponding slope, HAND, and TWI values will be pulled for each point to inform updates to the VBET transform functions.

**Comment by shelbysawyer** [comment]
@KellyMWhitehead Just putting this on your radar for now. I know the last pull (and creation of the CSV) took a decent amount of time. Do you think the processing time for creating the next CSV will be similar or will an increase in points lengthen that significantly? I believe the last run was with 2,800 points. Ideally this next run will be for 8,000-10,000 points.

**Comment by wally-mac** [comment]
@shelbysawyer thanks for the update. I'm really excited to see how your observations help to inform and calibrate VBET outputs.  Please let me know if my staff and I can be of any assistance. @Cashe93 and @leallysmith this is something that I wanted to make you both aware of.

**Comment by shelbysawyer** [comment]
@wally-mac Just wanted to draw your attention to [this guide](https://gist.github.com/shelbysawyer/07ffa065aa0c0c772342384fb8869d1a) that I made for collecting points. I still need to add in a video that is specific to on-fan observations, but this is otherwise all set.

It looks like everyone has been added as a user except for @leallysmith. @philipbaileynar Can you please add her as a user on the database?

**Comment by wally-mac** [comment]
@shelbysawyer Thanks for sharing the guide. I looked it over and found it very useful. Please let me know where, when and how many observations you would like me and my team to collect.

Thanks

**Comment by shelbysawyer** [comment]
@philipbaileynar To answer the 'where' part of Wally's question above-- if folks don't already have the VBET Validation PostGIS database available to them through QGIS, how do they get it?

**Comment by philipbaileynar** [comment]
@shelbysawyer probably worth scheduling a web meeting where we get all the relevant people connected in one session. Can you organize please?

**Comment by shelbysawyer** [comment]
@philipbaileynar Yes. I'll send out an email now. Thanks Philip.

**Comment by joewheaton** [comment]
@shelbysawyer I updated instructions slightly here: https://gist.github.com/joewheaton/09c851c59cd583414c9be305e57399f0 if you want to review and consider merging back into yours. 

@shelbysawyer I would take whomever can get together as soon as they can get together, but schedule individual meetings if people can't get to it. We want to have everyone's observations by COB on Friday 3/18.  @philipbaileynar just record video of session for adding people to access or find the one you already previously made and @shelbysawyer can add it to her instructions.

**Comment by shelbysawyer** [comment]
Hi @KellyMWhitehead have you had time to get to this?

**Comment by KellyMWhitehead** [comment]
@shelbysawyer Here are the the vbet evidence results:
[vbet_evidence.csv](https://github.com/Riverscapes/riverscapes-tools/files/8422386/vbet_evidence.csv)

Let me know if you have any questions.

**Comment by shelbysawyer** [comment]
Great, thanks @KellyMWhitehead . I'll check this out tomorrow morning!

**Comment by shelbysawyer** [comment]
The results of this pull have been summarized [here](https://gist.github.com/shelbysawyer/ca25780a523b592374c58a0f5758c7e9).
