### ISSUE TITLE
Additional Observations for VBET Validation Database

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#557]
Hi @lauren-herbine, @jtgilbert, @wally-mac, @sshahverdian, and @nick4rivers, @Cashe93, @leallysmith, and @joewheaton, 

I need your help collecting a few more VBET Validation database points. Currently, we have 3,000 points. The goal is to reach around 10,000 points by **COB on Friday, March 18**. If you can spare some time (2 hours max) to grab some points, I'd really appreciate it. I've made a guide below that should answer your questions about how to get started and some tips for decision-making.

Please comment (or leave a video) below if you have any questions along the way, even if it's a video of some points you've collected to get feedback from the team. If you're having trouble with accessing projects in the warehouse, reach out to @jtgilbert. 

### **How your observations will be used:**

These points will be used to inform the specification and calibration of VBET transform functions. These functions dictate how input evidence raster values (`slope`, `Height Above Nearest Drainage` (HAND), `Topographic Wetness Index` (TWI)) are translated to likelihood values, which are then combined to produce the cell values of the `Likelihood of Valley Bottom` raster. 

Each input has its own value (e.g. slope is in degrees from 0 to 90) and the transform function simply coverts this to a likelihood value between 0 and 1 with a simple transform curve. The transform curves are part of every VBET 'Project Report` and based on a calibration exercise last summer were tentatively specified. For example, Slope from [this project](https://webrave.riverscapes.xyz/#/NRCS_CEAP/9e58eb5f-cea6-482c-9a4d-c7107149150d) (in [this report](https://d3k0pn8xvrx1sy.cloudfront.net/NRCS_CEAP/VBET/9e58eb5f-cea6-482c-9a4d-c7107149150d/outputs/vbet.html/index.html#Transforms)) in Transform Zone 1 (i.e. intermediate size streams) has this transform function:
![image](https://user-images.githubusercontent.com/9723905/158417288-669ce65f-5751-463b-9ad6-b094029f7ac9.png)
Specified from this table:

|Slope |	Likelihood Value|
|---|----|
|0.00	| 0.99|
|12.00	| 0.99|
|18.00 |	0.68|
|45.00	| 0.50|
|65.00	| 0.01|
|90.00	| 0.01|

Those likelihoods correspond to how we interpret breaks between active channel, active floodplain, inactive floodplain and areas outside the valley bottom. We will use 90 to 95% of your observations to pool summary statistics and distributions to see what values of slope, height above nearest drainage and topographic wetness index correspond to breaks between these classes and to calibrate the transform functions by input and in total (likelihoods are averaged for total). We will use the remaining 5-10% of your observations as independent validation points.

# Valley Bottom Classification Observation Guide

This guide will walk you through the process of creating valley bottom classification observation points.

### **Observation Categories**

For each valley bottom observation you make, you will be asked to categorize it as one of the following:

`Active Channel Area` (where it's mapped by NHD (`Channel Area Polygons`), not necessarily what it shows on aerial photo)

`Active Floodplain` (middle of 10 m pixels that are at least 1 to 2 pixels wide, appear low-enough to flood regularly, and are supporting riparian vegetation)

`Inactive Floodplain` (middle of 10 m pixels and meet definition of *could plausibly flood*, but are distinctive from neighboring hillslopes, terraces and active floodplains)

`Terrace` (middle of clear examples of terraces that are **obviously** terraces and clearly from a historic, relic flow-regime (i.e. can't be confused with anthropogenic incision episodes)

`Probably not Valley Bottom` (for the indecisive among you)

`Definitely not Valley Bottom` (areas that you are certain are not within the valley bottom - include hillslope points in addition to mountain top points)

`Fan - Active Channel` (on obvious fans: where the channel is mapped by NHD, not necessarily same as what's shown in aerial imagery)

`Fan - Active Floodplain` (on obvious fans: middle of 10 m pixels that appear low enough to flood regularly, or are supporting riparian vegetation)

`Fan - Inactive Floodplain` (on obvious fans: middle of 10 m pixels that could plausibly flood but are distinctive from the active floodplain)

### Step 1: Connect to the Database

This video (< 2 mins) shows you how to set up a connection to the VBET Validation database in QGIS.

[![Not showing https://youtu.be/gIO8uBgthMQ](http://img.youtube.com/vi/gIO8uBgthMQ/0.jpg)](http://www.youtube.com/watch?v=gIO8uBgthMQ"")

### Step 2: Setup

This video (< 2 mins) shows you how to open the VBET Validation database and get set up to efficiently map observations.

[![Not showing https://youtu.be/TYfojyxpvEc](http://img.youtube.com/vi/TYfojyxpvEc/0.jpg)](http://www.youtube.com/watch?v=TYfojyxpvEc"")

### Step 3: Make Observations

This video (5 min) provides a walkthrough of how to edit the database with your observations and some examples of decision-making. 

[![Not showing https://youtu.be/oZiPpZbkoVk](http://img.youtube.com/vi/oZiPpZbkoVk/0.jpg)](http://www.youtube.com/watch?v=oZiPpZbkoVk"")

### Key "Do's and Don'ts":

1. **Do** try to work in watersheds that don't already have observations in them.
2. **Do** put the appropriate layers in place to make observations (NHD or `Channel Area Polygons`, `DEM`, `Hillshade`)
   - If working in a VBET project, **don't** rely on the `Likelihood of Valley Bottom` raster
   - Bring in `HAND` and/or `Slope` to help you understand the landscape better
   - Use aerial imagery for context if you want to, but don't rely on it to make observations.  Remember the aerial imagery is a snapshot of "truth", but not what VBET's truth is. VBET's truth is based on the inputs it has to work with. A later, separate validation exercise will incorporate independent, field based observations of "truth" from a different time slice than that of the input DEM and NHD.
3. **Do** drop points in the middle of your point's classification, not the boundary of that estimated classification
4. **Do** drop points where you're confident and then move on to another area. It's better to have confident observations than to have forced observations for every category in one valley.

### Tips
- If you're worried about getting good distribution (spatial, stream order, terrain setting, etc) of points, you could try starting in the headwaters and move towards the mainstem as you make observations.

**Comment by lauren-herbine** [comment]
Hi @shelbysawyer - I may have missed this somewhere- but what are the Host, Port, and Database entries supposed to be?

Thanks!

**Comment by shelbysawyer** [comment]
> Hi @shelbysawyer - I may have missed this somewhere- but what are the Host, Port, and Database entries supposed to be?
> 
> 
> 
> Thanks!

Hi Lauren! They are in the email I sent. You can access them through the link with the password provided. Let me know if you're still having problems accessing that!

**Comment by shelbysawyer** [comment]
These observations were [pulled](https://github.com/Riverscapes/riverscapes-tools/issues/556) and the results were summarized [here](https://gist.github.com/shelbysawyer/ca25780a523b592374c58a0f5758c7e9).
