### ISSUE TITLE
[Warehouse 3.0] Better Project names 

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#558]
## Problem: 

Currently the automated names we come up for 

- HUC code is in the metadata anyway. People are going to be able to search it so we don't need it in the title
- For RSContext and descendants we should use the common watershed name in the title.

### Relevant discussions

- https://github.com/Riverscapes/rs-web-monorepo/discussions/204

**Comment by joewheaton** [comment]
@MattReimer will we also be able to search by HUC name? The HUC code is great, but the HUC name may be more familiar to some.

**Comment by philipbaileynar** [comment]
It's essential that the HUC name - at the very least - is written to the RSC project metadata and then used in the warehouse search!

**Comment by MattReimer** [comment]
I believe this work is finished. Closing.
