### ISSUE TITLE
[Warehouse 3.0] Updating project references

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#559]
The function of the tool XML augmenter scripts that run after every tool run is going to change

One of the big changes between the old and the new version of the warehouse is that upstream datasets can be referenced. 

Practically this means:
1. The scripts like `vbet_rs.py` no longer need to be responsible for moving metadata in from the old project. That will now happen at the API level and
2. The scripts will need to decorate the project.rs.xml files with relevant `extRef=""` attributes so that the datasets can be shared. 

_Note: This relates to (#558) but that's a separate issue_

## Resources:

- https://github.com/Riverscapes/RiverscapesXML/discussions/449
- Google Doc: [Riverspaces Project XML Improvements](https://docs.google.com/document/d/1EFVe0h9IJMivnw3hTvXV1GG4Wps8RROG5SLpAE3ctr8/edit)
- Documentation on the `extRef=""` xml property: https://github.com/Riverscapes/RiverscapesXML/blob/master/docs/ProjectReferences.md
- Sample Code in NodeJS:
  - [`getRSXPath()`](https://github.com/Riverscapes/rs-web-monorepo/blob/Warehouse3.0/packages/common/src/lib/rsPaths.ts#L164-L187)

**Comment by KellyMWhitehead** [comment]
@MattReimer Is this ticket still valid?

**Comment by MattReimer** [comment]
Yes. Still valid. I saw this happening after @jtgilbert finishes with his V2 XML work on the RSContext milestone

**Comment by MattReimer** [comment]
This is an old one. I think we're done with this. @jtgilbert ?
