### ISSUE TITLE
Active Floodplain not drawing

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#561]
Hey @shelbysawyer any ideas on [this](https://youtu.be/_hIVg4ZlxxQ) (video link)? 

![image](https://user-images.githubusercontent.com/73319684/162828061-8653b6cd-f9fd-43d9-80ad-b1cd2f716fc4.png)

I was using HUC [11020001](https://data.riverscapes.xyz/#/NRCS_CEAP/4811ec77-78e0-4449-a36b-b03428b7be85). In some areas (not all), the active floodplain seems to not draw. Have you seen this before? Is this a known issue?

Thanks!

**Comment by shelbysawyer** [comment]
Hey @lauren-herbine,

Thanks for the video! This is [known issue](https://github.com/Riverscapes/riverscapes-tools/issues/527) that's been documented a few times, but it looks like it hasn't been resolved.

In ArcMap, the error warning pops up like this:
<img width="292" alt="error" src="https://user-images.githubusercontent.com/73311751/162830505-468a634a-deda-4ffe-a01b-f0101142832b.PNG">

When I opened the same project in QGIS, I didn't see any error warnings. When I first documented this issue, I thought QGIS was handling layers fine (no warnings) and a quick zoom looked alright. However, I've just spent some more time in this project and I am seeing what you noticed-- seemingly random areas where the estimated floodplain units are not drawing.

Just going to bring this back to @MattReimer and @philipbaileynar's attention.
