### ISSUE TITLE
Add Political Boundaries to RS Context

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#569]
@philipbaileynar  and @jtgilbert it is becoming increasingly clear for purposes of zonal statistics and HTML reports we need some additional polygon context that are political boundaries (different than administrative or ownership boundaries). These are not currently in RS Context. Please get them into the national project (or find an API that we can access). Much like HUCs and Ownership, we'll need to something clever like include all polygons for the features we intersect and we don't want @KellyMWhitehead to use this for calculating project extents.

We need:
- Country polygon(s) - Typically just US, but could be Mexico and Canada
- State polygon(s) - Typically one state, but some watersheds span multiple
- County polygon(s) - As many as it intersects
- Municipal polygon(s) - City limits that are intersected

We find ourselves needing these for:
- Making maps (an argument can reasonably be made that basemap layers provide these well enough)
- Doing simple locational queries
- Doing simple summary statistics using these boundaries
- Doing contextual comparisons (e.g. this project or watershed is xxx acres in an xx acres state or county)

**Comment by jtgilbert** [comment]
So far, added state and county boundaries
8d0c5d4d176489923286d02449fd680c598b415d

**Comment by joewheaton** [comment]
> So far, added state and county boundaries [8d0c5d4](https://github.com/Riverscapes/riverscapes-tools/commit/8d0c5d4d176489923286d02449fd680c598b415d)

I don't think you realize how helpful this is going to be! These political boundaries really matter and will be  This is really, really useful. Once you have some RS_Context projects with these things I might take a stab at playing with how I would like to see some of the ones that don't come with defined symbology (for geology and LANDFIRE they do obviously), and then we can get these lined out for the @Riverscapes/riverscape-project-curators! 

Thank you!

**Comment by MattReimer** [comment]
This work is done. CLosing
