### ISSUE TITLE
Update Riverscapes Context new layer requests

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#570]
In #118 there is a dumping ground of lots of useful potential inputs to GNAT. Some of these are based on needing NEW layers to be uploaded in National Project and curated through Riverscapes Context. @jtgilbert please go through the list and explode into individual feature requests (enhancements for pkg::RS-Context) for each new data source. Separately, you, @philipbaileynar and I can prioritize which of these to actually do. For now, I just want them put into tighter, actionable tickets (even if we just shelf them for a long time). Please list them here (edit this main thread) with the `- [ ]` syntax and cross them off as you've created them. Each thread should be something like "Add _____ to Riverscapes Context". 

We will need to separately develop a strategy for how to allow at CLI or API call a custom selection of which of these to include in a RS Context run (as if we include everything, the file size could become overwhelming).

**Comment by philipbaileynar** [comment]
The concept of a "national project" has overstayed its welcome! 

@jtgilbert and @MattReimer let's discuss how we might enhance riverscapes context such that there's a core tool that creates the basic RSC project with some essential layers. Then subsequent tools that can retrieve an existing RSC project, add one additional layer, then put the updated RSC project back in the warehouse. This is a more sustainable and scalable solution to the ever growing list of layers that folks are interested in. Each of these layers could go in their own "one layer national project" and then be called in serial fashion to add a single layer to RSC.

**Comment by MattReimer** [comment]
I'm closing this ticket as it is vague and nebulous in scope. Let's open another one if there are defined tasks that need doing.
