### ISSUE TITLE
Attributes and Metrics Desired for GNAT/RS database

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#578]
I am putting this in one new ticket, but can move this/close this if it is not where @philipbaileynar wants it (starting as an issue so we can later break out the metrics into a checklist/build issues off of this, but can move to a discussion if that's more appropriate). I will keep updating it, but just wanted to put it on git early for any feedback/collaboration.

**Links to relevant issues and projects (likely non-exhaustive):**
[Mississippi River Styles project board](https://github.com/Riverscapes/riverscapes-tools/projects/1)
confinement #235 
Grain size #237 
Drainage area #238 
anthropogenic margins #240 (@joewheaton it would be good to revisit [your comment](https://github.com/Riverscapes/riverscapes-tools/issues/240#issuecomment-787487720), specifically the "things we should think about")
confluence/diffluence count #241 
floodplain metrics #243 
stream order #246 
tributary impact #258 
stream size #302 
number (max) of channels #303 
[Attributes and where to get them](https://gist.github.com/lauren-herbine/7ba1a06f6f35ed64904609c2fb9f0f54) gist (not complete, and written when I was more focused on keeping the list lean)
Master list of reach attributes - GNAT and River Styler #118 

<html>
<body>
<!DOCTYPE html><h2 cid="n0" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.75em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.225; cursor: text; border-bottom: 1px solid rgb(238, 238, 238); white-space: pre-wrap; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Attributes and Metrics Desired</span></h2><figure class="md-table-fig" cid="n37" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Attribute/Metric | New Calculation | Pull straight from... | Notes | Window S | Window M | Window L | Machine Code
-- | -- | -- | -- | -- | -- | -- | --
Confinement |   | confinement tool |   | 100 m | 250 m | 1 km |  
Channel Sinuousity | X |   | see relative flow length. do we actually want this? |   |   |   |  
Stream Gradient | X |   |   | 100 m | 250 m | 1 km |  
Valley Gradient | X |   |   | 100 m | 250 m | 1 km |  
Stream Size (bankful) | X |   |   | 100 m | 250 m | 1 km |  
Grainsize |   | grainsize tool | ** |   |   |   |  
Drainage Area |   | RSContext |   |   |   |   |  
Active Floodplain Area |   | VBET |   | 100 m | 250 m | 1 km |  
Active Channel Area |   | VBET |   | 100 m | 250 m | 1 km |  
Stream Type |   | NHD- FCodes |   | 100 m | 250 m | 1 km |  
Headwater |   | GNAT |   | 250 m | 250 m | 250 m |  
Ecoregion III |   | EPA ecoregions | figure out splits | 500 m | 500 m | 500 m |  
Ecoregion IV |   | EPA ecoregions |   | 100 m | 250 m | 1 km |  
Stream Order |   |   |   |   |   |   |  
Anthropogenic Confinement | X | from confinement tool? | will take a while. percentage or presence/absence |   |   |   |  
Relative flow length |   | VBET |   | 100 m | 250 m | 1 km |  
Integrated width of Tier 1 polygons |   | VBET |   | 100 m | 250 m | 1 km |  
count of floodplains RL and RR |   | VBET |   | 100 m | 250 m | 1 km |  
Confluence/Diffluence count |   |   |   | 100 m | 250 m | 1 km |  
Active Channel Area to Valley Bottom Ratio (Channel area to (active + inactive floodplains + channel area)) |   |   |   |   |   |   |  
Active Floodplain Area to Valley Bottom Ratio (Active Floodplain Area to (active + inactive floodplains + channel area)) |   |   |   |   |   |   |  
Baseflow |   | BRAT |   | 100 m | 250 m | 1 K |  
Peak flow |   | BRAT |   | 100 m | 250 m | 1 K |  

</figure><br class="Apple-interchange-newline">
</body>
</html>

@shelbysawyer @MattReimer @KellyMWhitehead tagging for your awareness

**Comment by lauren-herbine** [comment]
### Some gists laying out a little bit of the new direction we're taking:
[Answering Real Questions with Fake Figures](https://gist.github.com/lauren-herbine/6ec0533202de5ce08b155782e8e3ccfc)
[Answering Real Questions with Fake Figures Take II](https://gist.github.com/lauren-herbine/9036fb3d9768d60ee69f83dbe0e94d5b)

**Comment by philipbaileynar** [comment]
old ticket. Superseded by RME. Some material here that can still be referenced as a closed ticket.
