### ISSUE TITLE
VBET Metrics: Master Issue

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#579]
### Background

A new segmentation method has been put forward that will allow us to calculate metrics in moving windows, at scales of 100m for small sections, 250 m for medium sections, and 1 km for large sections. The information stored in these segments will be used in conjunction with other geometries in VBET projects to create a set of metrics for the end-user. The scales and building block combinations for these metrics need to be specified.

The latest and greatest version of VBET should be available soon and I will get to work at exploring exactly how we will break these metrics out into a report. From my perspective, this issue will serve as a jumping-off point for me to organize my questions related to this and also serve as a resource for later documentation.

### Existing Segment Attributes & Description

I see the metrics / attributes as falling into three main categories-- building block metrics, combination metrics, and other.

**Building Block Metrics**: direct measures of geometries

`active_channel_ha`: active channel area

`active_floodplain_ha`: active floodplain area

`inactive_floodplain_ha`: inactive floodplain area

`cnt_active_fp_units`: # active floodplain units

`cnt_inactive_fp_units`: # inactive floodplain units

**Combination Metrics**: combinations of building block metrics

`valley_bottom_ha`: active channel area + active floodplain area + inactive floodplain area

`active_valley_bottom_ha`: active channel area + active floodplain area

`active_valley_bottom_pc`: active channel area + active floodplain / valley_bottom_ha * 100

`active_channel_pc`: active channel area / valley_bottom_ha * 100

`active_floodplain_pc`: active floodplain /  valley_bottom_ha * 100

`inactive_floodplain_pc`: inactive floodplain /  valley_bottom_ha * 100

**Other Attributes**: attributes that are not calculated, but could be useful for metrics ?

`vbet_level_path`: NHD-sourced level path ID

### Additional Attributes Requested

`integrated valley bottom width`
A building block metric.

`acres of inactive floodplain / riverscape mile`
This metric can provide an approximation of valley bottom condition. @joewheaton Do you think this is necessary, or useful? Is there another high-level metric that we could provide instead of this to help approximate condition at the project scale?

### Questions & Queries
Just throwing out some example questions/queries to play the game of making sure we can answer them.

_*How many miles of riverscape are on Public Land in 16010201?*_

_*How many acres of inactive floodplain per mile perennial channel?*_

**Other Questions / Thoughts Moving Forward:**

1. I've noticed that all of the building block metrics are currently in hectares. Should this measure be changed to acres instead, considering VBET target audience? If not changed, could additional columns be added to provide these metrics in acres?
2. At the bottom of reaches, where the window cannot look downstream enough to fulfill the window requirements, how will this be dealt with? It sounds like this has been agreed upon already, but just looking to get specifics here so that I can get it into documentation.

**Comment by MattReimer** [comment]
@shelby could you please review some of the results on 

https://github.com/Riverscapes/riverscapes-tools/discussions/637

and close this if it is complete (or let us know what's outstanding or incorrect)

**Comment by joewheaton** [comment]
@shelbysawyer this is a good reference for you when you write the VBET documentation (#463 and #502). I am closing this as the metrics on IGOs are now slightly different and this is superseded by #661. 

Note that:

> Additional Attributes Requested
> `integrated valley bottom width`  A building block metric.

This is now calculated in IGOs!

> `acres of inactive floodplain / riverscape mile`  This metric can provide an approximation of valley bottom condition. @joewheaton Do you think this is necessary, or useful? Is there another high-level metric that we could provide instead of this to help approximate condition at the project scale?

Note this is requested in #661. 

Also, from your:

> Questions & Queries
> Just throwing out some example questions/queries to play the game of making sure we can answer them.
> 
> How many miles of riverscape are on Public Land in 16010201?

This will be done now using DGOs in GNAT (where we bring back in public stuff) with @lauren-herbine.

> How many acres of inactive floodplain per mile perennial channel?

This is now possible with current IGOs, but requires some unit conversion and the completion by @KellyMWhitehead of #456. He and @philipbaileynar may suggest we move that to a GNAT issue... We'll see. 

> Other Questions / Thoughts Moving Forward:
> 
> I've noticed that all of the building block metrics are currently in hectares. Should this measure be changed to acres instead, considering VBET target audience? If not changed, could additional columns be added to provide these metrics in acres?

Good question. See my A-D requests in #661.

> At the bottom of reaches, where the window cannot look downstream enough to fulfill the window requirements, how will this be dealt with? It sounds like this has been agreed upon already, but just looking to get specifics here so that I can get it into documentation.

I am going to move this over to #661.
