### ISSUE TITLE
Include Mean Annual Precipitation from NHDPlusID

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#58]
The NHDPlusHR dataset includes the mean annual precipitation for each reach. This value is stored in the `NHDPlusIncrPrecipitationMA` table. The values are stored in the `PrecipMA` column. This table also has the NHDPlusID for associating the values back to the reach geometries.

Having the mean annual precipitation for each reach would improve our bankfull width calculations  (#12) that currently use a constant precipitation value for the entire watershed. Watersheds with high relief have spatially variable precipitation as evidenced by the PRISM rasters that we are including in the riverscapes context projects.

The goal of this task is to import the mean annual precipitation value into the riverscapes context projects so these data can be used by our other tools.

I will point out that we keep adding requests for more and more aspects of the NHDPlusHR data! Each request requires us to refactor the code and then re-run every project! Surely (@MattReimer) its about time that we simply convert the NHDPlusHR dataset into a GeoPackage and include the entire thing in the riverscapes context project. It's up front work, but it will avoid future requests like this one. Note I've [prototyped some code](https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/nhd_to_geopackage.py) to do this.

**Comment by philipbaileynar** [comment]
Discussing this with @wally-mac and @tyler1218hatch we realized that the NHD precipitation value is not that useful for the bankfull width calculation because it merely represents the precipitation on the hill slope that drains into each reach. This doesn't capture the upstream catchment that strongly influences reach hydrology.

**Comment by MattReimer** [comment]
This seems resolved-ish. Closing
