### ISSUE TITLE
HUC12 GeoJSON

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#581]
The watershed attribute tool (#570 and #574) will rely on HUC12 polygons, the finest resolution national waterbody dataset that possesses topology. We have some outstanding questions about how to work with the HUC12 layer that has approximately 70,000 polygons for CONUS.

In the following questions, note that we only need the geometries plus the HUC12 identifier attribute. We don't need any other attributes (but maybe include name for easier debugging and maybe future proofing).

1. We will almost certainly be storing this layer as GeoJSON:
    1. What is the file size of saving the entire raw HUC12 layer as a single GeoJSON file (again, no attributes needed)?
    2. How much polygon simplification can be applied while retaining contiguous, mutually exclusive polygons? (i.e. we will be looking up points to see which HUC12 polygon they fall in. We can't have tiny gaps between features.)
    3. What is the file size of the HUC12 layer as a single GeoJSON file after this simplification is applied?
2. What is the largest file size (in kilobytes) of any one HUC12 polygon? (a quick but silly way to do this is to loop over all 70,000 HUC12 polygons and write each GeoJSON polygon to disk; retrieve the file size and then delete the file). We need this information to understand how best to store this information in DynamoDB. We need this answer for both pre and post simplification.

FYI @MattReimer

**Comment by MattReimer** [comment]
hey @jtgilbert I needed this last night so I'll take it on. 

> What is the file size of saving the entire raw HUC12 layer as a single GeoJSON file (again, no attributes needed)?

The total geometry size of huc12 data is about 4Gb

> How much polygon simplification can be applied while retaining contiguous, mutually exclusive polygons? (i.e. we will be looking up points to see which HUC12 polygon they fall in. We can't have tiny gaps between features.)

Simplifying is likely a waste of time if we can use boundingboxes to get us 99% of the way to the answer
