### ISSUE TITLE
Not all flowlines with points

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#586]
There aren't nodes/points on every flowline within this project, and it is especially problematic on the mainstem.
[08040305](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/00580775-c4d2-415b-820d-26754c310e68)

This is an example, but almost every project is like this.

![image](https://user-images.githubusercontent.com/73319684/189725916-d9e31d81-e708-4496-ac6e-cd921980d8bb.png)

**Comment by joewheaton** [comment]
Yes, @KellyMWhitehead this is a recurring problem across every VBET project I have looked at. It seems like for some reason, when you are building or saving to disk the centerline points, you are leaving out or erasing the biggest (earlier level paths). This is clear from the fact that you have centerlines derived (so you're doing those steps correctly), but for some reason it is only later (smaller) level paths that get points.

**Comment by joewheaton** [comment]
@KellyMWhitehead, correct me if I am wrong, but I think this is now fixed with 0.8.x. Re-Open if you disagree.
