### ISSUE TITLE
Significant figures request for GNAT attributes

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#588]
Hi @KellyMWhitehead, I have an attribute table request.

Could you only include a maximum of four significant figures in our attribute tables? For example, change stream_gradient 0.201893447940... to 0.2019.
![image](https://user-images.githubusercontent.com/73319684/189728687-7a462d96-38a2-4e3e-9a1b-d30453702477.png)

Thanks!

**Comment by philipbaileynar** [comment]
We intentionally ignore significant figures when writing data. This provides maximum flexibility to whatever software is  presenting the data. i.e. it could be a report document, pie chart label or in your case another piece of software. 

I recommend exploring ways in QGIS to limit the significant figures.

**Comment by lauren-herbine** [comment]
Thanks @philipbaileynar ! Tagging @joewheaton

**Comment by joewheaton** [comment]
Sorry, I DON'T like this. 

>  We intentionally ignore significant figures when writing data. This provides maximum flexibility to whatever software is presenting the data. i.e. it could be a report document, pie chart label or in your case another piece of software.

This is fair... but

> I recommend exploring ways in QGIS to limit the significant figures.

This is really vague and not clear. What are those "ways"? We need help. Is it a UI setting thing we can control with QRAVE or QRiS? We don't know what those are and it is not good enough to say go figure it out. We don't have to solve this now, but lets not close issues that are NOT actually resolved. Another reasonable thing might be we control it in how we produce reports (something @jtgilbert needs to get @lauren-herbine and @shelbysawyer trained up on how to do).

**Comment by KellyMWhitehead** [comment]
My quick search of displaying fields in Q didn't look promising...

Compromise - apply rounding to attributes in spatial views? Underlying data retains floating point values, and the display layers can be formatted as we like. 

Easy to apply to our existing spatial views, but would require new ones for tables/feature classes we are accessing directly, potentially cluttering up our geopackages.

any thoughts? @philipbaileynar @joewheaton

**Comment by philipbaileynar** [comment]
I'm unsurprised that QGIS doesn't allow for rounding in the attribute viewer. I merely suggested we look and had no knowledge of how to do it or whether it would work. The attribute table viewer is for looking at raw data. It is not a a true "presentation" layer whereby the data should carefully formatted. In terms of QGIS, that would be a map layout!

I don't hate the spatial views rounding, but it is a hack. And it will never be perfect. We will end up with trailing digits like `99.0000000001` etc. 

I think people just need to put up with lots of decimal places in attribute table editor. The place for formatting is in reports, figures, map labels and map legends.

**Comment by joewheaton** [comment]
Okay, thanks @philipbaileynar and @KellyMWhitehead for exploring. I am a little confused, when we write floating point or double precision numbers to an attribute field, can we not control how we write it (i.e. how many significant figures)? It sounds like what you're saying is no, and even if we do exercise this, it will still have trailing digits here and there (I can live with that). 

If we take your suggestion that:

> The place for formatting is in reports, figures, map labels and map legends.

 I can live with that. It means that I will expect more of the following:
- QRiS user interface and reports (i.e. things beyond the attribute table).
- QRAVE and WebRAVE user interface 
- Report formatting in general

Maybe @jtgilbert can weigh in here too. I am fine with the "raw" data being uglier. But lets recognize we have a presentation issue we will need to address.

**Comment by jtgilbert** [comment]
From a Python perspective, it's pretty easy to format numbers to present with appropriate significant digits (e.g. how numbers are now being presented in tables in the updated BRAT report), so it makes sense to me to keep the raw data how it is and tackle formatting at the next level.

**Comment by philipbaileynar** [comment]
There is a probably a better link out there somewhere, but this explains [why you can never accurately store non-integers accurately on a computer](https://www.baeldung.com/cs/floating-point-numbers-inaccuracy). You can round or truncate them for display, but there will always be imprecision when storing them.

We don't control the display in the attribute table form in QGIS. So our only avenues are reports and custom UI.

**Comment by KellyMWhitehead** [comment]
GNAT is now rounding significant digits as originally requested in this ticket.
