### ISSUE TITLE
Branch Cleanup Work

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#597]
Here's what's going to happen, probably today. Please review and back anything up that you want to keep.

## Leave alone

- `dev`
- `docs`
- `master`
- `gh-pages`

### Delete

- `vbet_transform_update`
- `3dep`
- `gnat_tools`
- `vbet_centerlines`
- `vbet_website`
- `brat_report_updates` - @jtgilbert  please investigate and confirm
- `Vegetation_Suitability`
- `brat_summary_stats`
- `brat_reachcode`

### Rebase onto `dev`, test, then merge onto master 

- `watershed_warehouse_scripts`
- `rscontext_hotfix`
- `rs_project_bounds`

@KellyMWhitehead When these get folded in I will ask you to run rscontext on cybercastor to test it.

### Rebase onto master aferward

- `dockerdev`
- `brat_report` - Active branch
- `VBET_GNAT` - Active branch
- `metrics` - Active branch
- `new_project_xml` - Rebase last

**Comment by jtgilbert** [comment]
confirming, `brat_report_updates` can be deleted

**Comment by MattReimer** [comment]
OK, all deletable branches are gone

`dev` now contains: `watershed_warehouse_scripts`, `rscontext_hotfix`, `rs_project_bounds`

@KellyMWhitehead please test rscontext as thoroughly as you need to in order to make sure these fixes don't cause trouble. When you're done I'll merge them into `master` 

The active branches have been merged on top of dev.
