### ISSUE TITLE
How Should I Symbolize VBET Segments?

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#600]
The primary problem I'm facing is that I can't symbolize segments (DGOs) or points by indicator metrics (ex. proportion of inactive floodplain) because the proportions do not add up to 1 and therefore not really tell us much.

For example, in the case of this DGO, here are the proportions that I see:

`active_channel_prop:` 0.997
`active_floodplain_prop:` 0.238
`inactive_floodplain_prop:` 0.765

<img width="1008" alt="metrics_problem" src="https://user-images.githubusercontent.com/73311751/193064834-01abd915-5c26-4dbb-8e25-9e2ec5a1ab51.PNG">

**Comment by joewheaton** [comment]
Great question @shelbysawyer! I am so glad you're thinking and struggling with this one. We are going to need (minimally) to have a way of knowing, how many upstream and downstream DGOs were used (i.e. the window size). Symoblizing, it may not be that easy! But calculating metrics we have to know what we're doing. Lets discuss with @KellyMWhitehead and @philipbaileynar .

**Comment by shelbysawyer** [comment]
Hi @philipbaileynar and @KellyMWhitehead, I know this came up during our Thursday meeting, but I'm not sure we came to a resolution about how to move forward. @wally-mac has a new tech that will take the symbology I come up with for the new layers (points, valley bottom segments, etc) in QRAVE and handle curating those over in ArcRAVE & WebRAVE. Before she can do that, I need to get the symbology right. I'm kind of stalled out on that until I can figure out how to overcome this. 

@KellyMWhitehead When you have time, can you write out how metrics are calculated for nodes that occur in locations that _would_ pull for two different window sizes without your intervention?  I remember you showing us how you got around that, but it would be great to have a written explanation.

@lauren-herbine Tagging you here to go off our conversation on 10/3.

**Comment by KellyMWhitehead** [comment]
Hi @shelbysawyer 

I have made some updates to vbet and attached a project below. This project contains the full temp folder with rasters for each level path. I also added a few specific comments and responses to your google spreadsheet.

* I discovered a bug in one of the transform csv files and fixed it. I think this will fix some of the missing areas on larger streams you have been observing.
* I found a different bug with how the areas and proportions metrics for the dgos. You should now see the proportions for active fp, inactive fp and channel area add up to ~1 (and fp and channel area as well). Remember for the dgo's, these values are for each segment and not the moving window. The moving window metrics only apply to the metrics in the segmentation_points layer.
* The sql used to select the moving window segments for each segmentation point is `LevelPathI = _level_path_ AND seg_distance >= _min_dist_ AND seg_distance <= _max_dist_` where level_path is the level path of the point, min_dist is seg_distance - 0.5 * window_distance and max_dist is seg_distance + 0.5 * window_distance

[VBET 17060304 with temp rasters](s3://nardata/kelly/VBET_17060304_20221004.zip)

Let me know if you have additional questions or concerns.

**Comment by shelbysawyer** [comment]
Awesome @KellyMWhitehead! I don't think this project attached properly. Could you try again please? Thanks!

**Comment by shelbysawyer** [comment]
Dropping a link to this project [here](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b8b1adc6-e498-4e1c-83c1-a12d0e1c8ec4).

**Comment by philipbaileynar** [comment]
@shelbysawyer please close this issue if there are no outstanding actions to be taken.
