### ISSUE TITLE
Update BRAT to reflect new VBET names and structure

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#602]

**Comment by KellyMWhitehead** [comment]
Hi @jtgilbert 

Here is a new vbet project you can use for testing. Please let me know if you have any questions.

[16010202](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b9383c9e-edab-4725-a953-eb9e4cd5ecf1)

**Comment by jtgilbert** [comment]
closing as #604 is the same.
