### ISSUE TITLE
Run VBET for 2 Local Watersheds with "Full" Likelihood Raster 

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#603]
I'm preparing for field work in the Northeast Mississippi River Basin 11/7 - 11/21 with @lauren-herbine and need to run through some of my field methods. 

I will be collecting on-the-ground point observations of valley bottoms. These observations will be collected using the same classification system in the original Postgres database that currently contains ~5,000 desktop-based observations. This is documented in detail [here](https://github.com/Riverscapes/riverscapes-tools/issues/557). 

After field observations have been made, I'll pull the likelihood raster value for each of these points, then create a whisker plot with likelihood on the Y axis. Field observations _in_ the valley bottom (active channel, active floodplain, inactive floodplain) should fall in high likelihood. Field observations _outside of_ the valley bottom (definitely not valley bottom, terrace, etc) should fall in low likelihood. The idea here is to be able to add another layer of validation into VBET results through on-the-ground work and to be able to say something along the lines of "94% of points follow the expected trend".

**Here's the problem:** I can’t validate points that don’t fall in the valley bottom without likelihood rasters that have values in those areas. Right now, those don't exist in VBET projects. @KellyMWhitehead and I chatted briefly about this on 10/12 and it is part of a larger ongoing conversation with @joewheaton and @philipbaileynar.

**The purpose of this issue is** to 1) get two projects in hand that I can test my proposed field methods on and 2) keep the ball rolling on the larger conversation about the status (conclusion?) of the likelihood raster.

@KellyMWhitehead Can you please run VBET for these watersheds?

16010202 (Middle Bear)
16010203 (Little Bear - Logan)

**Comment by KellyMWhitehead** [comment]
@shelbysawyer 

I just so happened to have run [16010202](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b9383c9e-edab-4725-a953-eb9e4cd5ecf1) for jordan yesterday. Feel free to take a look!

**Comment by philipbaileynar** [comment]
@shelbysawyer we do not currently have a full VBET evidence raster. We are actively discussing how to produce one and hope to have this worked out shortly after you are back from the field.

**Comment by MattReimer** [comment]
We now have a VBET evidence raster. 

16010202 is done and 16010203 is on the way. 

@shelbysawyer could you please review and close this issue when you are satisfied?

**Comment by joewheaton** [comment]
These were run and used and superseded many times now. Thanks @MattReimer.
