### ISSUE TITLE
Update sqlBRAT to work with VBET 0.5.2

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#604]
VBET has undergone significant changes; layers have changed names, attributes have come and gone.

This task is to update sqlBRT to work with the latest version of VBET (0.5.2). Essentially this means using the latest correct VBET polygons in the conservation module of VBET to calculate roads, rails and crossings in the valley bottom.

I believe @KellyMWhitehead  has provided @jtgilbert with one or two sample VBET projects to support this work.

**Comment by MattReimer** [comment]
Related to #602 ?

**Comment by philipbaileynar** [comment]
@jtgilbert is this complete? Status please.

**Comment by jtgilbert** [comment]
Current version of sqlBRAT works w/ new VBET structure.
