### ISSUE TITLE
RSContext flow accumulation process

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#605]
I've noticed that the flow accumulation rasters that are produced for RSContext don't continuously produce higher values as they move downstream through the network (there's "reset points" where it drops and then starts increasing again. I've had this issue before with Pygeoprocessing (and other modules) when using the D-infinity algorithm, or when the fill pits algorithm doesn't work well. This raster isn't very useful if not correct, so we should probably look into this along with other improvements to RSContext.

**Comment by philipbaileynar** [comment]
What do folks think of dropping this raster from RSC and instead generating it within our tauDEM projects? I'll hazard a guess that tauDEM is more reliable. There's also an argument that this collects together all our hydro-topographic data into a single project.

FWIW none of our tools using the flow accumulation from RSC. sqlBRAT uses the NHD flow accumulation attributes.

**Comment by jtgilbert** [comment]
@philipbaileynar This makes sense to me. Kind of separates RSContext into primary datasets, where other tools down the line contain derivatives of those datasets.

**Comment by philipbaileynar** [comment]
@MattReimer and @KellyMWhitehead ?

**Comment by philipbaileynar** [comment]
Actions:

1. Remove Flow Accumulation Raster from Riverscapes Context
2. Add Flow Accumulation to tauDEM project
3. Implement new Euclidean distance in BRAT conflict attributes
4. Remove PyGeoprocessing dependency from Riverscapes tools

**Comment by jtgilbert** [comment]
removing flow accumulation and drainage area from RSContext
e3a92bbeadbe98d5e91b532d4a2a8137a6102579

**Comment by joewheaton** [comment]
What we already produce in TauDEM is way better as it uses d-infinity

**Comment by MattReimer** [comment]
This work is done. Closing
