### ISSUE TITLE
Add Ecoregion 4 to rscontext

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#606]
Add ecoregion level 4 shapefiles to rscontext.

**Comment by jtgilbert** [comment]
Added level 4 ecoregion. The shapefile includes level 3 and all lower as well, but field names are a bit different so curation will need to be redone
8d0c5d4d176489923286d02449fd680c598b415d

**Comment by joewheaton** [comment]
Thanks @jtgilbert . Can you work with @wally-mac or @Cashe93 to get the curation going?

**Comment by MattReimer** [comment]
The work "Add Ecoregion 4 to rscontext" is done. @joewheaton can I close this? Is curation a separate task that has work we can track here?

**Comment by joewheaton** [comment]
If Level 4 Ecoregions are there, yes.

**Comment by joewheaton** [comment]
Once I can see the new stuff, I will take a pass through and look at everything. We will want a coordinated effort on queueing up ALL the curation. It is a lot!
