### ISSUE TITLE
Updating `new_project_xml` branch

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#607]
The `new_project_xml` branch was started at a time before a lot of the details of the migration had been set. Since @KellyMWhitehead wrote this we've had some changes:

1. The XSD has been moved to its final place
2. VBET has been almost completely rewritten

The task here is simply the minimum amount of work to get the branch to a good starting place for @jtgilbert to complete the rest of the tickets in this milestone. 

### Tools to Update:

1. RSContext - Most of this should be done and ready. Just a quick check to make sure we're still good
2. ChannelArea - Done I think?
3. Taudem - Probably in good shape?
4. VBET - Will need to be re-done from scratch I'm afraid
5. BRAT - ???

### Things to check:

1. The XSD for all projects is `https://xml.riverscapes.net/Projects/XSD/V2/RiverscapesProject.xsd`. We can now pull this into somewhere more central because they are all the same.
5. The output XML should be valid (notice I didn't say "correct").
6. The output XML _should_ match the migrated XML as closely as possible
7. @KellyMWhitehead will continue to work on `VBET_GNAT` and we will rebase `new_project_xml` on top of that so he can continue to use cybercastor and the warehouse.

### The new truth

A copy of all the `project.rs.xml` files that have been auto migrated is here:

<https://drive.google.com/file/d/1fOwi3Fo2ApbQG2NvEmeDgXsIrNQYgwVp/view?usp=sharing>

These may not match 100% ( especially in the case of VBET) so we probably can just use them as a guideline.

**Comment by KellyMWhitehead** [comment]
Changes made:
* added <Logs> node for log files (all projects)
* rscontext: removed reference for adding hand to project file
* taudem: updated xsd path
* vbet: updated create project, updated xsd path
* BRAT: no changes needed.
* GNAT: updated create project, updated xsd path

all changes pushed to `new_project_xml` branch

**Comment by MattReimer** [comment]
@jtgilbert this should be a better starting point for your work.
