### ISSUE TITLE
PRISM needs to be folded into the National Project

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#609]
or it needs to be included into the national dataset. It's a prerequisite of rs_context now.

Probably we just need to make a project type in the new system

1. Create new project type in the new system
2. Create a project XML 
3. Upload the project to the NEW warehouse
4. update RSContext cybercastor script to download and use the new project

*Transferred from <https://github.com/Riverscapes/rs-web-monorepo/issues/97>*

**Comment by jtgilbert** [comment]
@MattReimer is there a reason this is preferable to adding the datasets to national project?

**Comment by MattReimer** [comment]
Talked about it with @philipbaileynar this morning and we can't remember why we decided this. I think folding them Into the national is entirely appropriate.

**Comment by jtgilbert** [comment]
If that's the case I can easily fold this in to my to do list.

**Comment by MattReimer** [comment]
Yes. Let's do it. We can't consume it from the national project quite yet in the old system but I don't think there's any harm in folding it in for the new Warehouse.

**Comment by jtgilbert** [comment]
shifted prism over to national project 
a0b963850358f5407350590a6887c87d802f8e48

**Comment by MattReimer** [comment]
Nice. Closing this in anticipation of S3 upload (tracked in #619 )
