### ISSUE TITLE
copy_feature_class producing empty feature class

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#610]
https://github.com/Riverscapes/riverscapes-tools/blob/04cc1de48f140794ab367220c86ff11ede390237/lib/commons/rscommons/shapefile.py#L476

Ran into this experimenting with incorporating L4 ecoregions into RSContext. When the features being copied were Albers and the clip_shape was epsg 4326 (WGS 84) the function produced an empty output. When they're both WGS 84 it works.

**Comment by MattReimer** [comment]
Yikes. This function is used nearly 70 times in the code so it's kind of a fundamental thing.

I suggest that whoever fixes this makes a unit test for it:

https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/test/test_vector_ops.py#L39-L57

**Comment by philipbaileynar** [comment]
@jtgilbert do you think this is worth investigating proactively or should we just wait until it occurs and tackle it then?

**Comment by jtgilbert** [comment]
@philipbaileynar I think it's something we should address, but not crucial for the re-run. It seems like this will pop up and become an issue on custom runs with different datasets in different projections. (But so far Clement hasn't run into this either.)

**Comment by philipbaileynar** [comment]
Agreed. Closing issue and removing Rowan. Can reopen should it reoccur.
