### ISSUE TITLE
Add Geology to RS_Context or can Watershed Attribute Tool summarize for WMTS?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#611]
A while back we added Geology as a basemap: https://github.com/Riverscapes/riverscapes-website/discussions/29#discussioncomment-1768391

The new Watershed Attribute Tool is going to be super powerful for producing summaries from upstream.

Moreover, @philipbaileynar added to QRiS a new `Geospatial Metrics Summary` tool that does similar zonal statistics for polygon AOIs or Masks the user defines!

Geology is definitely one of the layers (raster) that a user might want to summarize based on. @jtgilbert I know you are hoovering up some of the requests to get layers into RS_Context.  So some questions:

1.  Is it possible to get the Geology layer into RS_Context? 
2. Do we want it in RS_Context or does it bloat it and should we just make a Geology project? 
3. Can the Watershed Attribute Tool work off of datasets in a WMTS? or do they need to be in a riverscapes project? 
4. Can the `Geospatial Metrics Summary` tool of QRiS summarize for WMTS? I know you said it works on all layers in map @philipbaileynar, but I don't know if we tried this one?

**Comment by jtgilbert** [comment]
@joewheaton I actually started looking into this yesterday. The SGMC geology basemap I brought in is also available on Science Base, so it should be pretty straightforward to bring it in to projects. I think it makes sense to include it into RSContext, as geology is an important part of context, and it makes sense to me to keep "raw" layers in RSContext and have other project types be analyses or derivatives of those datasets.

**Comment by MattReimer** [comment]
Assuming by the 🚀 icons that this work is done. Closing.
