### ISSUE TITLE
Combined Topographic Evidence Raster

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#614]
Please make the latest version of VBET produce a "combined topographic evidence" raster similar to the previous version of VBET (see below).

This should be a simple average of the TRANSFORMED slope and TWI evidence rasters. (The previous version also included HAND, but since HAND is no longer produced for the entire project we need to leave it out for the new version).

This is a single raster for the entire project (typically HUC8).

 
<img width="1292" alt="Screen Shot 2022-10-24 at 3 22 54 PM" src="https://user-images.githubusercontent.com/8645379/197641054-e8e30bf5-6c71-4de6-97a6-2976cbf36816.png">

**Comment by shelbysawyer** [comment]
@KellyMWhitehead I'm just lurking on this issue, but what does 97f7fb787bd02d1950cbe631ec79139f076c575a mean?

**Comment by KellyMWhitehead** [comment]
@shelbysawyer a reference to the git commit with the code changes. I did this out of order (forgot to push first) so the link didn't auto-generate:

https://github.com/Riverscapes/riverscapes-tools/commit/97f7fb787bd02d1950cbe631ec79139f076c575a

**Comment by joewheaton** [comment]
@KellyMWhitehead let us know when you have a project (e.g. those North Eastern Montana runs) to play with. Excited to see this in action.
