### ISSUE TITLE
Riverscapes Context NHD Data Duplication

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#617]
As it is structured right now, RSContext downloads shapefiles of all NHD layers and places them in the project. It then copies the flowlines into a geopackage and subsequently segments the network. It also buffers the HUC8 shapefile to create a processing extent and stores that in the geopackage. The VAA table is itself stored in a separate sqlite db. This results in kind of a messy setup with data stored in 3 places, and with the flowlines in particular being duplicated.

**Comment by jtgilbert** [comment]
The best solution would probably be to copy all layers into the geopackage and then get rid of the original shapefiles and move the VAA table to the geopackage as well - that way all the data exists and is in one place. We'd just have to make sure anything downstream references the gpkg layers and not the shapefiles.

**Comment by MattReimer** [comment]
Agreed. this is all a known issue and we've been waiting to do it because we didn't want to rock the boat.

Well... the boat is rocking so.....

Like you said, it means changing every tool that depends on RSContext (and big changes tot he project.rs.xml and the ensuing businesslogic too)

I vote for doing this work but @philipbaileynar and @joewheaton back me up?

**Comment by KellyMWhitehead** [comment]
This is a good time to do this. A few tools use the vaa table and it would be nice if they were in the same gpkg with the flowlines.

**Comment by joewheaton** [comment]
Fully on board... Time to run the rapid. Nice scouting...

**Comment by philipbaileynar** [comment]
Please proceed and clean up hydrology data in RSC as part of this phase of work:

1. All hydrology will be in a single GeoPackage:
    - Flow lines
    - Flow areas
    - HUC boundaries (2-12)
    - stream catchments
    - VAA
2. Legacy hydrology ShapeFiles will be removed.
3. Business Logic will be updated to remove references to legacy ShapeFiles.
4. Symbology checked to ensure compatible with new GeoPackage.

Other Notes:

- Make sure to use the "copy feature class" function is RSCommons (don't need to write anything custom).
- Think about projection. (We don't re-project rasters, but we can re-project vectors...)
- Try to keep layer and attribute names unchanged from original.

**Comment by MattReimer** [comment]
Work is done. Closing.
