### ISSUE TITLE
RSC Catchment Wings Feature Class

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#620]
NHD data are downloaded from Science Base at the scale of a Vector Processing Unit (VPU) which is a HUC4. We when select the appropriate flow lines and catchment wings for inclusion in our HUC8 projects.

The selection of stream catchment wings is currently performed using a spatial selection using the HUC8 boundary. This selects polygons in neighbouring HUC8s because the catchment wings are raster derived and their saw-tooth outlines straddle the smoother HUC8 polygon. This results in most RSC projects including additional stream catchment wings from neighbouring HUCS (see below).

The task is to improve the selection of stream catchment wings for inclusion in RSC projects by joining the stream catchment feature class to the flow lines feature class using the common `NHDPlusID` attribute and then selecting on the features that have a ReachCode that starts with the eight digits of the relevant HUC being processed.

<img width="1640" alt="Screen Shot 2022-10-28 at 10 34 54 AM" src="https://user-images.githubusercontent.com/8645379/198719194-06792553-e50c-4827-a14f-cf18f9e7c42b.png">

**Comment by jtgilbert** [comment]
The selection uses the OGR SetSpatialFilter method, which automatically uses "intersects" as the spatial relationship; there isn't a way to change it to "contains" or anything else.

**Comment by philipbaileynar** [comment]
I know. That's why I suggested the table join approach and leveraging the `ReachCode` filter using HUC code match.

**Comment by jtgilbert** [comment]
Sounds good, I'll look into it, but that probably won't be done by this afternoon, rebuilding the project xml after fixing nhd has given me some headaches

**Comment by philipbaileynar** [comment]
Presumably the `SetSpatialFilter` approach to selecting polygons was also affected by the multi-part features? In other words, this is just a messy data issue that has always existed.

Its hard to tell if this issue is a one off, or affects lots of HUCs. If it's the latter then we could insert call `MultiPartToSinglePart` before we select features...

My vote is proceed with the table join selection using `ReachCode` and ignore the multi issue unless you think that this might be pervasive.

**Comment by jtgilbert** [comment]
@philipbaileynar using that approach results in some missing catchment wings where there is no network segment. Thoughts?

![catchment_wing_join](https://user-images.githubusercontent.com/21687931/199560017-2f8d70c0-0953-4d14-84c7-6cb387cffdef.png)

**Comment by MattReimer** [comment]
* Buffer the HUC8 outward 10m and intersect to get rid of weird outliers?
* buffer the HUC8 inward 10m and intersect to get everything else?

**Comment by jtgilbert** [comment]
I think a Multipart to Singlepart and then intersect with inward buffer will probably give best results.

**Comment by philipbaileynar** [comment]
I do not like the buffer approach because it is scale dependent. Weird shapes will cause unforeseen problems. Should the buffer be 1, 5, 10m? Depends on the geometries.

How about:

1. Use the `SetSpatialFilter` that we were using before. It's fast and this will get all the catchment polygons that we want. It will include the unassigned polygons identified above, plus those annoying catchments that touch the polygon along the exterior.
2. Collapse the HUC boundary to a polyline and do a second `SetSpatialFilter`. This will provide a list of catchment polygons that touch the polyline. Loop over this list and look up the flowline feature using the `NHDPlusID`. Check the `ReachCode` of the flowline feature. Discard if it doesn't start with the HUC code.

The lookup I propose in step 2, could be performed in memory but would require some lists with a couple of thousands items to be kept in memory. Alternatively, this is substantially easier if the data are already in a GeoPackage (because you can use SQL). So this might be a case where we first store all the polygons. Then go back and delete the records that we don't want. If we do end up deleting records, remember to do a [vacuum](https://www.sqlite.org/lang_vacuum.html).

**Comment by philipbaileynar** [comment]
After further reflection I don't think the polyline thing is needed.

1. Use `SetSpatialFilter` using the HUC polygon to copy all catchments, including the ones from adjacent HUCs that touch the HUC boundary.
2. Run the following SQL to delete the catchments that are associated with adjacent HUCs:

```sql
DELETE FROM catchments c INNER JOIN flowlines f ON c.NHDPlusID = f.NHDPlusID
WHERE f.ReachCode NOT LIKE '17010506%';
```

This assumes that the catchment polygons are in a feature class (table) called `catchments` and the flowlines are already copied into the same GeoPackage in a table called `flowlines`.

Here's some sample Python code:

```python

import sqlite3

conn = sqlite3.connect(geopackage_path)
curs = conn.cursor()

# These database indexes will make eveything go faster!
curs.execute('CREATE INDEX ux_catchments_nhdplusid ON catchments(nhdplusid)')
curs.execute('CREATE INDEX ux_flowlines_nhdplusid ON flowlines(nhdplusid)')
curs.execute('CREATE INDEX ux_flowlines_reachcode ON flowlines(reachcode)')

# Note the percent sign at the end is a wildcard to capture all reach codes starting with the target HUC code
curs.execute(f'DELETE FROM catchments c INNER JOIN flowlines f ON c.NHDPlusID = f.NHDPlusID WHERE f.ReachCode NOT LIKE '{huc_code}%')

# defragment geopackage SQLite database to get rid of gaps on disk
curs.execute('VACUUM')
```

**Comment by jtgilbert** [comment]
thanks, @philipbaileynar I was actually just thinking this

**Comment by MattReimer** [comment]
THis work is completed by @jtgilbert. Closing
