### ISSUE TITLE
ModuleNotFoundError: No module named 'minifier'

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#622]
We have an issue with a small but crucial pip install that is currently out of date:

The [HTML5print](https://pypi.org/project/html5print/) module (last released in 2016) requires the [slimit](https://pypi.org/project/slimit/) module (last released in 2013) and this `slimit` module is broken

- `html5print` has an open issue for this [here](https://github.com/berniey/html5print/issues/13)
- `slimit` has a number of fixes that make it work with Python3 but the developer is [unresponsive](https://github.com/rspivak/slimit/issues/107)

A temporary fix to unblock developers:

```bash
./venv/bin/pip3 uninstall slimit
./venv/bin/pip3 install pip install git+https://github.com/rspivak/slimit.git@3533eba9ad5b39f3a015ae6269670022ab310847
```

### A better fix

Neither `html5print` nor `slimit` are being used and we only use these modules to beautify our html output. I think we could get around this issue completely by finding a better, more up-to-date module to do this work.

**Comment by philipbaileynar** [comment]
If we skip beautifying our HTML, can we just use Visual Studio Code "Format Document" within the team when we need to make sense of the HTML?

I vote to remove these libraries immediately and take our time finding a replacement.

**Comment by MattReimer** [comment]
Agreed. I originally thought this was used for XML prettifying (which we actually need) but it's not. @jtgilbert , this is only used in the rs_report and that's your next stop right? Can you pull it out please?

**Comment by jtgilbert** [comment]
@MattReimer is this only in the commons setup, or is there other places it might also be?
