### ISSUE TITLE
Selective Retention of VBET Intermediates

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#624]
@KellyMWhitehead what would it take to add a new command line argument to VBET that is a comma separated list of level path identifiers. The max number of level paths would be capped at 10. VBET would retain the intermediates (HAND, transformed HAND etc) for just the specified level paths (and delete intermediates as usual for all other level paths).

Rationale: @joewheaton and @shelbysawyer want to investigate the tributary fans issue. I had hoped that the synthesized VBET evidence raster (#613) would satisfy this need, but looking at this raster myself I can see that it's hard to see the boundaries between level paths, particularly at tributaries. 

If we are able to implement this feature request it would provide researchers all the intermediates for one or two confluences to thoroughly understand VBET inner workings.

To be clear... The code should strictly enforce the 10 level path limit and abort if more are provided. We can't keep too many intermediate datasets.

**Comment by KellyMWhitehead** [comment]
This capability is already set up. We can filter vbet to run on specified level paths, and set the debug flag to True to retain temporary files (rasters).

**Comment by joewheaton** [comment]
Cool @KellyMWhitehead. Can you just give me the first 4 levelpaths on a project?

**Comment by MattReimer** [comment]
We've got something way more advanced now. The `--debug` flag will dump a zip file with every intermediate raster we created. 

Also the `--debug` flag enables detailed timers that report on the order, time taken of level paths and dumps both a CSV to the root of the project AND a table in the geopackage that you can marry to a shapefile layer in QGIS. 

I'm closing this.
