### ISSUE TITLE
Channel Area Improvements

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#625]
Quick checklist of things to check on this tool.

### Channel Area

- [x] Riverscapes XML `project.rs.xml` file validates against <https://xml.riverscapes.net/Projects/XSD/V2/RiverscapesProject.xsd>
- [x] All layers are correctly represented in the `project.rs.xml` file
- [x] Every layer in the XML represents a real dataset on disk.
- [x] Project and layer Metadata review 
- [x] Project loads correctly in Rave
- [ ] Report review

### Taudem

- [x] Riverscapes XML `project.rs.xml` file validates against <https://xml.riverscapes.net/Projects/XSD/V2/RiverscapesProject.xsd>
- [x] All layers are correctly represented in the `project.rs.xml` file
- [x] All rasters have compression turned on
- [x] Every layer in the XML represents a real dataset on disk.
- [x] Project and layer Metadata review 
- [x] Project loads correctly in Rave
- [ ] Report review

@jtgilbert feel free to add/remove items. We can copy this ticket forward to the next tool as well.

**Comment by jtgilbert** [comment]
Everything is done but report updates. I'm closing this, report updates will be ongoing in the future.
