### ISSUE TITLE
d-inf area raster values are nodata in most channel locations

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#627]
Additionally, the values seem mostly wonky and incorrect.

I have yet to have a d-inf workflow produce a drainage area raster that makes sense. I propose that we stick with the d-8 algorithms to produce a drainage area raster.

**Comment by jtgilbert** [comment]
from taudocs:

`D-Infinity Contributing Area: Calculates a grid of specific catchment area which is the contributing area per unit contour length using the multiple flow direction D-infinity approach.`

Not sure if this is useful for anything? Seems like a raster of simple contributing area would be more useful...

**Comment by jtgilbert** [comment]
I think we should pare back TauDEM to producing VBET inputs, and the basic grid analyses that people use most (D8 flow-dir, flow_acc, and da). That'll lean up the projects a bit too.

**Comment by jtgilbert** [comment]
Looks like that layer is actually an input for TWI, shoud be in intermediates if exposed at all.

**Comment by jtgilbert** [comment]
closing as this is mostly just changes to business logic that I'll make with updates.

**Comment by joewheaton** [comment]
@jtgilbert we should still keep this as an intermediate in TauDEM, but maybe we don't use their label of Drainage Area. This quantity is the D-infinity version of what is needed in the classic Montgomery & Dietrich c. 88 "Where do Channels Begin". There might actually be another variable, which is what you are thinking, that is actually drainage area. From TauDEM, many of the variable names are a little unintuitive or misleading. I agree, we should also have the D8 drainage area because it is what we're used to.

**Comment by jtgilbert** [comment]
@joewheaton after poking around I actually think I'm getting good results from the d-inf algorithms too. There's a flag you have to turn on and now there's no longer nodata values along the channels. Since the D-inf stuff is used to generate hand and TWI (and now seems to be producing good catchment area results) do you think we just keep that, or should we add any D-8. Not adding keeps project size down, but I'm good with either choice.

**Comment by joewheaton** [comment]
Oh, that is huge that you figured out that flag. I think it must control the inevitable divide by zero problem. We notice that a lot when the entire drainage area is not contained by the DEM. I think there is also a perimeter handoff on drainage area.

Anyhow, D infinity is a far better algorithm for flow accumulation and slope, so let's use it. Having D8 also is fine to keep for comparison.

**Comment by joewheaton** [comment]
We may choose to not produce D8 for custom high resolution and LiDaR runs. Please try running one (e.g Asotin) to see how it works.
