### ISSUE TITLE
Possible Bug in RSCommons rs_project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#629]
I spotted this potential bug while using this method in QRiS:

https://github.com/Riverscapes/riverscapes-tools/blob/dcae1ab0b5356da398dff4d8909c1dfbb703e647/lib/commons/rscommons/classes/rs_project.py#L339

**Comment by MattReimer** [comment]
Good catch!

**Comment by MattReimer** [comment]
THis is merged now. Should appear next time we rebase on top of `dev` branch
