### ISSUE TITLE
Index Riverscapes Context Hydrology GeoPackages

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#631]
The following indexes will speed up any queries that use the following columns in WHERE clauses! The indexes will take up some space on disk, slightly bloating the database files. But I think it is worth the performance boost when running queries.

The two commented out lines below are the only two existing indexes that I could find. So maybe find the place in the code where these existing indexes are being created and add the others to the same place.

# Hydrology.gpkg

```python
import sqlite3

conn = sqlite3.connect(db_path)

conn.execute('CREATE INDEX ix_nhdarea_fcode on NHDArea(FCode));
conn.execute('CREATE INDEX ix_nhdarea_nhdplusid on NHDArea(NHDPlusID));

conn.execute('CREATE INDEX ix_nhdflowline_reachcode on NHDFlowline(ReachCode));
conn.execute('CREATE INDEX ix_nhdflowline_fcode on NHDFlowline(FCode));
#conn.execute('CREATE INDEX ix_nhdflowline_nhdplusid on NHDFlowline(NHDPlusID));

#conn.execute('CREATE INDEX ix_nhdpluscatchment_nhdplusid on NHDPlusCatchment(NHDPlusID));

conn.execute('CREATE INDEX ix_nhdplusflowlinevaa_nhdplusid on NHDPlusFlowlineVAA(NHDPlusID));
conn.execute('CREATE INDEX ix_nhdplusflowlinevaa_levelpathl on NHDPlusFlowlineVAA(LevelPathl));
conn.execute('CREATE INDEX ix_nhdplusflowlinevaa_ReachCode on NHDPlusFlowlineVAA(ReachCode));

conn.execute('CREATE INDEX ix_nhdwaterbody_fcode on NHDWaterbody(FCode));
conn.execute('CREATE INDEX ix_nhdwaterbody_reachcode on NHDWaterbody(ReachCode));
```

# Hydro_derivates.gpkg

Using the pattern shown above I would recommend indexing the following columns on both tables `network_intersected` and `network_intersected_300m`:

- ReachCode
- NHDPlusID
- FCode

FYI @MattReimer @KellyMWhitehead

**Comment by jtgilbert** [comment]
Re: the lines commented out, that is strange, I can only find one spot creating indexes right now and that's on the VAA when its exported from the gdb to the gpkg....

**Comment by jtgilbert** [comment]
@philipbaileynar I can't find anywhere in the code that is creating those two existing indexes. Even the copying of the NHDPlusID from the VAA table to the flowlines (the two affected layers there) happens before the layers are copied into the gpkg...

**Comment by philipbaileynar** [comment]
@jtgilbert this is the statement. It looks to be part of the `export_table` routine. Perhaps you can simply add the columns above as arguments to this method?

https://github.com/Riverscapes/riverscapes-tools/blob/dcae1ab0b5356da398dff4d8909c1dfbb703e647/lib/commons/rscommons/filegdb.py#L155

**Comment by jtgilbert** [comment]
@philipbaileynar I thought that's what it was too, but the only place that function is used it doesn't specify the optional fields that have it index columns...

**Comment by philipbaileynar** [comment]
Ok but can you leverage this existing code for the current request? Are you using the export_table routine?

**Comment by jtgilbert** [comment]
Only to retrieve the VAA from the NHD gdb. I could add the code here straight to rscontext.py or add it into the export feature class function that copies the actual nhd layers from the gdb to the gpkg.
