### ISSUE TITLE
HUC8 10050015 Failure (on the canadian border)

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#639]
Hey Kelly,

Can you look into this failure please? Re: https://github.com/Riverscapes/riverscapes-tools/discussions/637

https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/2bd97f8b-b480-4b44-b93d-9179d66166f9

**Comment by joewheaton** [comment]
@KellyMWhitehead and @philipbaileynar this is a very high priority please. We really need those HUCs.

**Comment by joewheaton** [comment]
See #652 where the HUC10 in hist HUC8 worked.

**Comment by joewheaton** [comment]
Clarification @MattReimer. Did you attempt to run the HUC 8 and it failed (HUC 10 looks like it worked that doesn't straddle border)?

**Comment by MattReimer** [comment]
This failed again last night. I am less and less convinced this has anything to do with the canadian border

I've kicked it off again in case it has something to do with the --debug flag but I don't think we should sit around waiting to find out.

```
2022-12-09 06:31:19,946 DEBUG    [raster_update  ] Timer: 0.1753990600045654
2022-12-09 06:31:20,243 DEBUG    [raster_update  ] Timer: 0.29747750000387896
2022-12-09 06:31:20,491 DEBUG    [raster_update  ] Timer: 0.24729560199921252
2022-12-09 06:31:20,562 ERROR    [Debug          ] Error executing code: Read or write failed. /usr/local/data/output/intermediates/hand_composite.tif, band 1: IReadBlock failed at X offset 0, Y offset 2609: TIFFReadEncodedStrip() failed.
```

The error seems to happen about 15 hours into the process. after about 1922 `raster_update` operations. unfortunately it never got to the `temp` zip step s there's no to start in the middle of this process and just see what happens

**Comment by philipbaileynar** [comment]
Could we process a trans border HUC10 to see if that succeeds? i.e. separate the issues of trans border versus big HUC.

**Comment by MattReimer** [comment]
YEah. I'll kick one off now. 

Also I've confirmed this is not a border problem:

<img width="687" alt="Screenshot 2022-12-09 at 8 40 23 AM" src="https://user-images.githubusercontent.com/1063391/206749953-fda01bad-24ac-4b5e-845a-7e48792738fe.png">

I can repro the problem in qgis. Something is corrupting the raster along the way.

**Comment by MattReimer** [comment]
The corrupted TIF problem was hiding another real issue. The HUC 10s that cross the canadian border are failing because they are missing a layer from RSContext:

```
No layer named "network/processing_extent" found
```

- [VBET for HUC 1005001503](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/f4ee54a3-5e1e-46dd-a326-2b45177a5fa2)
- [VBET for HUC 1005001506](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/d87e8a38-ba40-4c65-94b0-2177f4b4f15d)
- [VBET for HUC 1005001501](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/25b978cd-0e89-4bbb-9c5e-069ce352e3ab)

**Comment by MattReimer** [comment]
There were bugs hiding bugs hiding bugs on this one. 

https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/848851ed-342c-4e84-9442-75c3957e796c

I'm closing this ticket because this HUC10 is on the Canadian border AND there is clearly a VBET shape. Any other problems will be tracked through more specific issues

- #681 is the big one here.
