### ISSUE TITLE
composite_hand raster not compressed (even though it is)

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#643]
`hand_composite` is uncompressed and 315Mb even though the DEFLATE tag seems to be set correctly and the DEM is only 16Mb.

https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b7c607c7-5916-465b-b36f-e162bd936c21

**Comment by MattReimer** [comment]
When using rasterio's 'r+' file mode and our windowed windowing method (yes that's real) we sacrifice compression for a huge speed increase in writing a lot of tiny raster windows. 

What we need to do is recompress the raster in-place outside the for loop when we're done with the file and this should compress the file properly.

**Comment by philipbaileynar** [comment]
Respect @MattReimer ! Impressive find and fix!

**Comment by MattReimer** [comment]
Just for future reference. this is all implemented using a `raster_recompress` function (in the VBET package only. It should probably move to commons at some point).

Here's the code:

https://github.com/Riverscapes/riverscapes-tools/commit/dd6b3f7639604383240a5c78d44f69a507feae0e#diff-14dd79f1fb6ff81f3ddd2d6e3a90a1cf0fd3cee7c6a2399e29f4e82c4a4543b7R715-R717

**Comment by MattReimer** [comment]
Just a quick followup:

* The process added about a minute to a HUC10. Not aggregious. The should scale more or less linearly for raster size. 
* I verified that the rasters are the same after the operation and they are compressed up to 90%
