### ISSUE TITLE
VBET Evidence Raster Offset

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#644]
The creation of VBET evidence rasters is producing some kind of raster offset that produces "ghosting" of features. The image below is a single VBET evidence raster for a single LevelPath. Notice how the lake is "ghosted" twice in the raster!

- HUC: [16010202](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/d8485cc8-db2c-4b59-b410-a92f26a375dc)
- Level Path: 70000400011364

<img width="1064" alt="Screenshot 2022-11-29 at 4 32 09 AM" src="https://user-images.githubusercontent.com/8645379/204530125-cfe70d03-099a-4d50-b0d1-2ab812aa688f.png">

My understanding is that this raster is produced by multiplying the global topographic evidence raster with the "normalized hand for the level path". Both these two rasters appear to be correctly referenced. The two screenshots below are of precisely the same spatial extent as above. I have turned on the flow lines for reference and symbolized them by Level Path. The magenta line is 70000400011364, the level path being processed.

# Topographic Evidence
<img width="1064" alt="Screenshot 2022-11-29 at 4 35 03 AM" src="https://user-images.githubusercontent.com/8645379/204530593-eeae9717-ef38-403a-a787-0031599c13be.png">

# Normalized HAND

<img width="1064" alt="Screenshot 2022-11-29 at 4 35 24 AM" src="https://user-images.githubusercontent.com/8645379/204530667-fc63d52e-0cc3-4328-839c-ad51fea78a87.png">

# Hypothesis

I think that this problem is a raster extent offset problem. The global topographic evidence raster extends to the entire HUC while the local HAND rasters only extend to the level path buffer. The level path shown is the longest, mainstem level path and so they "almost" line up and errors are hard to see.

I discovered this error while researching why mainstem VBET polygons are so noisy (what we refer to as "swiss cheese"). Our discussions in Lyon focused on stream the incorrect application of size transform zones. This might still be a problem, but we can't be sure until this offset problem is resolved.

@joewheaton @MattReimer

**Comment by philipbaileynar** [comment]
I have tried to find out how this affects other reaches, ones that are smaller than the mainstem and that do not span most of the HUC extent.

In the top image above the offset seems to be east/west so I picked a smaller east/west level path at random (70000600008087). I don't see ghosting, but that might be because the level path analysis extent is clipped so tightly to the flow line. However, there is certainly some weird masking going on near the western end of this level path that might be due to an offset.

This is the VBET evidence raster for 70000600008087:

<img width="782" alt="Screenshot 2022-11-29 at 5 19 14 AM" src="https://user-images.githubusercontent.com/8645379/204539448-d6d8f8fe-e103-4f43-a90d-ed68aece2150.png">

**Comment by joewheaton** [comment]
Interesting... I have not noticed this, but it could be obscured by some other things. I still think what we discovered last week is the fundamental problem we see most frequently but this is important too.

**Comment by philipbaileynar** [comment]
@joewheaton it is the other way round. This offset problem is obscuring other things. This is the main, fundamental problem for partially incomplete mainstem valley bottoms. In my research today I am far less confident that the transform zone issue will solve the mainstem VB protruding up into tribs than I am that the issue described here will make our mainstem VB more coherent.

@joewheaton last week we identified two problems and possible fixes:

Problem|Possible Fix
---|---
Messy holes in the VB polygons in larger mainstems.|I believe that the problem identified by this ticket is the major cause of this mess! The offset is retarding the evidence (see images below)
Mainstem VB protruding up tributaries|I actually couldn't find definitive cause of this! But I still think that this needs investigation (as separate ticket).

See these two images below. 

# Mainstem VB

This is another section of the same mainstem of 16020101. There's nothing on the Google imagery to suggest that this mainstem VB should have the three narrow sections! The landscape looks homogeneous. I would expect this to be a wide mainstem VB with near constant width. What's causing the constrictions?

<img width="1350" alt="Screenshot 2022-11-29 at 6 19 25 AM" src="https://user-images.githubusercontent.com/8645379/204553953-1d2813c5-18c6-4d81-b147-a4ad7544fd47.png">

# Offset Evidence

Here's the VBET evidence for the same section. Look at the three swaths of extremely low VB probability!!!!!! These are artifacts of a completely different part of the landscape.

<img width="1350" alt="Screenshot 2022-11-29 at 6 22 03 AM" src="https://user-images.githubusercontent.com/8645379/204554620-fd056b2c-16fe-4493-a32e-ed208cb0dc46.png">

**Comment by philipbaileynar** [comment]
et Voila!

Purple is original VB before the fix. Orange is after @KellyMWhitehead fixed a windowing problem in the combination of evidence.

<img width="1087" alt="Screenshot 2022-11-30 at 2 31 59 PM" src="https://user-images.githubusercontent.com/8645379/204922579-94125922-761a-4c4c-9be2-b205917af106.png">

<img width="1087" alt="Screenshot 2022-11-30 at 2 33 15 PM" src="https://user-images.githubusercontent.com/8645379/204922612-ccd52044-0f8f-4424-b73c-17268ec6018c.png">

**Comment by philipbaileynar** [comment]
Here's another area that was previously producing a noisy, swiss cheese VB and now looks much more coherent!
<img width="625" alt="Screenshot 2022-11-30 at 2 34 35 PM" src="https://user-images.githubusercontent.com/8645379/204922786-9a10411e-6a52-4406-b493-bc61bbd9a185.png">

<img width="625" alt="Screenshot 2022-11-30 at 2 34 44 PM" src="https://user-images.githubusercontent.com/8645379/204922818-c3786308-7580-47c1-bb56-61daed40cf8c.png">

**Comment by joewheaton** [comment]
This is a big find and fix. Question @philipbaileynar, are we still "cleaning up" the thresholded polygons for each levelpath by removing doughnut holes smaller than some area threshold? My eye was drawn to some of the ones above that are real and fine, and others that may be too small?

**Comment by philipbaileynar** [comment]
Yes.  @KellyMWhitehead what is the current threshold please?

I agree @joewheaton that it looks like we could increase this threshold. What distance across a donut do you is reasonable to drop?

**Comment by KellyMWhitehead** [comment]
We currently have two processes related to clean up of the thresholded rasters:

1) [SieveFilter](https://gdal.org/api/gdal_alg.html#_CPPv415GDALSieveFilter15GDALRasterBandH15GDALRasterBandH15GDALRasterBandHiiPPc16GDALProgressFuncPv) for cleaning up small pixels outside of the main polygon. I don't recall if this takes care of donuts or just the cells with values. Current parameters are set to `threshold=10, connectedness=8`

2) [Binary Closing](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.binary_closing.html) in particular for cleaning up raster edges, but I believe this also cleans up donuts as well. Currently set to 2 iterations.

We can either play around with these values, or (rather than destabilizing the current vbet universe) just add one last filter step at the end to clean up any remaining donuts of a particular size.

**Comment by joewheaton** [comment]
Thank you @KellyMWhitehead for the clarification. @shelbysawyer and I should just be aware of what it is we are doing and what these thresholds are currently at. Lets not change anything. To me this is calibration only to be played with after we validate independently and decide if we do not like it.

**Comment by joewheaton** [comment]
@shelbysawyer see @KellyMWhitehead comment above for when you are writing documentation. 

@philipbaileynar and @KellyMWhitehead, I think (from my review) you have fixed this issue in 0.8.1. If you are not satisficed or disagree. Re-Open.
