### ISSUE TITLE
New Anthropogenic Project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#645]
We need to break anthropogenic data and calculations out of sqlBRAT and into a dedicated projected where they can be used by both sqlBRAT and RCAT. The new project has two goals:

- Collect together data layers relevant to anthropogenic calculations
- Perform the land use intensity calculation used by both sqlBRAT and RCAT

# Project Definition

- Full name: Anthropogenic Context
- Abbreviated name: Anthro
- Type: Hybrid Network Model - channel & riverscape networks

# Layers

- Inputs
    - Integrated geographic object (IGOs, points from VBET)
    - valley bottom polygons
    - Digital geographic object (DGOs, polygons with IGOs at their centre)
    - Canals
    - Roads
    - Rail
    - Land Use Intesity Raster (Land Use Intensity attribute from LandFire Existing Veg Type WRAT)
    - Levees (@joewheaton mentioned something about a national Levee dataset)
    - hill shade (display only)
- Outputs
    - IGO points with attributes:
        - level path
        - measure (distance down level path)
        - Land Use Intensity (0-1) calculated as attribute.
        - length road per unit area
        - length rail per unit area
        - length canal per unit area
        - length levee per unit area
        - BRAT also has several land use intensity bins that need review (very low, low, medium, high, very high)

# Folder Structure

```
inputs\
    anthro_inputs.gpkg
    land_use_intensity.tiff
outputs\
    anthro_outputs.gpkg
report\
    report.html
    images\
        *.png
project.rs.xml
```

# Calculations

- See the [sqlBRAT land use intesity calculations](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/brat/sqlbrat/utils/land_use.py)

Note that sqlBRAT performed the land use intensity on channel network polylines. This new anthro project will calculate the value based on a moving window for each of the IGO points. @kelly can provide the moving window algorithm that we are using elsewhere.

# Questions

- All roads or filtered by type?
- Technically this project does not need flow lines, merely canals. Include flow lines anyway?
- Include hillshade?
- The moving window land use calculation probably requires the DGO polygons as an input, not just the IGOs.
- What other metrics are needed for each IGO?
    - length roads?
    - length canal
    - length railroad

**Comment by philipbaileynar** [comment]
Just attaching this here until we document it for real...

- Digital Geographic Objects (DGOs) are polygons
- Integrated Geographic Objects (IGOs) are points at the center of the DGOs.
- The level paths are the Unified Geographic Objects (UGOs) red and yellow
- Any collection of DGOs that share common attributes are Aggregated Geographic Objects (AGO) (not shown)

Adapted from Alber & Piegay (2011).

<img width="753" alt="Screenshot 2022-11-29 at 1 21 39 PM" src="https://user-images.githubusercontent.com/8645379/204654398-07b091e1-0a3c-4db1-b819-7c2e3ccb93ab.png">

**Comment by joewheaton** [comment]
@jtgilbert any questions?

**Comment by jtgilbert** [comment]
@joewheaton should I bet setting up the output IGOs so that they contain (and calculate) all of the attributes BRAT uses (ie the iPC attributes)?

**Comment by joewheaton** [comment]
> @joewheaton should I bet setting up the output IGOs so that they contain (and calculate) all of the attributes BRAT uses (ie the iPC attributes)?

Good question @jtgilbert. I can't say without looking more carefully at it. Why don't you make a table and go through each iPC attribute and we can see if and how it makes sense as a riverscape metric. Some will, some might not. Most will have some sort of crosswalk that makes sesne, but some will have cross walks that might make sense, but just are not that useful.

**Comment by jtgilbert** [comment]
@joewheaton in that same vein, including flowlines for the purpose of channel network outputs implies that this project should contain outputs to make available for both channel (flowlines) and riverscape (igos) tools, right? Eventually network-based BRAT will ingest a network from this project with iPC attributes already calculated?

**Comment by joewheaton** [comment]
> @joewheaton in that same vein, including flowlines for the purpose of channel network outputs implies that this project should contain outputs to make available for both channel (flowlines) and riverscape (igos) tools, right? Eventually network-based BRAT will ingest a network from this project with iPC attributes already calculated?

That's right. I think the pre processing of channel network is over in RS Context now.

**Comment by philipbaileynar** [comment]
Anthro is now done. Closing. Create new issues with any lingering tasks.
