### ISSUE TITLE
IGOs Retained Outside UGO

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#647]
The centroids of segmentation polygons (IGOs) are being retained outside of the level path valley bottom (UGO).

Notice how the purple IGO dots extend outside the yellow tributary valley bottom.

I suspect what's going on is that the blue dots are being calculated correctly for the entire length of the tributary, right down to the junction with the mainstem. However, we want to discard those points that are not in the final tributary valley bottom after it is clipped by the mainstem valley bottom.

<img width="1211" alt="Screenshot 2022-12-01 at 12 52 52 PM" src="https://user-images.githubusercontent.com/8645379/205157610-a86b2559-9c0c-4bfe-b19e-2eed2435d2da.png">

**Comment by jtgilbert** [comment]
And here it looks like the trib causes the distance numbering to reset
![Screenshot 2022-12-01 162656](https://user-images.githubusercontent.com/21687931/205180609-3c502154-9795-4df9-81d2-6906a31dce27.png)

**Comment by philipbaileynar** [comment]
@KellyMWhitehead any thoughts? Comments?

**Comment by KellyMWhitehead** [comment]
The extra IGO's were due to removing centerline clipping when we moved to the raster-based vbet method. I am adding centerline clipping back to the process.  

I am not sure what is causing the unusual distance measuring, but perhaps cleaning up the IGO's outside of their correct vbet polygons will fix this issue too. Stay tuned...

**Comment by KellyMWhitehead** [comment]
This is fixed in version 0.8.1, all igo's should be in their correct vbet polygon.

This in turn should fix the incorrect distancing at tributary junctions, but reopen if anyone sees this issue cropping up again.
