### ISSUE TITLE
TABLE: VBET `0.8.5` Runs on HUC 10s

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#651]
Related to #638, @MattReimer and I discussed and @philipbaileynar asked me to specify some HUC 10s within some of the priority HUC 8s we are testing on. The purpose is to speed up the dev cycles. 

Original Sheet:

https://docs.google.com/spreadsheets/d/1ZtuVuxLqjAxFU-MrxOX6ZjL8jtduqcyNwyuZvaPRaPI/edit#gid=1279742273

_**UPDATED:: DEC14**: `0.8.5` is coming in slowly so I thought I'd update even while there are some HUC8s still cranking._

HUC | HUC8 Name | Version | Duration | notes |   |  
-- | -- | -- | -- | -- | -- | --
05010003 | Lower Ohio-Little Pigeon | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/18c59055-5fc3-4507-b1ab-f7accfcf4586) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/18c59055-5fc3-4507-b1ab-f7accfcf4586)
0501000301 | Upper Little Tennessee | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/4f030430-fb54-4dce-9dab-3786a17c1cb3) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/4f030430-fb54-4dce-9dab-3786a17c1cb3)
05020004 | Upper Little Tennessee | 0.8.5 |   | Test some reservoirs in Smoky Mountains | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/95f77210-0dba-4a57-98be-c50979cec445) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/95f77210-0dba-4a57-98be-c50979cec445)
0502000405 | Lower Clinch | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b07a5372-1f95-45fd-825e-b26ef9854563) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/b07a5372-1f95-45fd-825e-b26ef9854563)
05040003 | Lower Clinch | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/2013d0ef-0e91-4c29-870a-cf3874a19c6c) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/2013d0ef-0e91-4c29-870a-cf3874a19c6c)
0504000306 | Chippewa | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/5a3f5110-eb8d-437c-9628-cd2288e98343) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/5a3f5110-eb8d-437c-9628-cd2288e98343)
05140201 | Chippewa | 0.8.5 |   | Lots of pothole lakes and low relief as well as agriculture. |   |  
0514020112 | Flambeau | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/55e8086b-aee3-4112-adab-0847e65741b0) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/55e8086b-aee3-4112-adab-0847e65741b0)
06010202 | Flambeau | 0.8.5 |   | Glaciated lakes and low relief | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/308b93c3-6e9c-409b-bd1e-ab331f9a28a5) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/308b93c3-6e9c-409b-bd1e-ab331f9a28a5)
0601020203 | Two Medicine | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/7bfca046-e483-4613-8de0-604393b591ea) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/7bfca046-e483-4613-8de0-604393b591ea)
06010207 | Two Medicine | 0.8.5 |   | High alpine extending out of Rockies onto plains | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/3e521fac-8994-4a2d-b119-9f31c69f6108) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/3e521fac-8994-4a2d-b119-9f31c69f6108)
0601020704 | Rock | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/f7835230-54c6-4c19-90e2-1e07a448d6c8) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/f7835230-54c6-4c19-90e2-1e07a448d6c8)
07020005 | Rock | 0.8.5 |   | This Willow Creek HUC10 tributary is focus of study with Alden, BLM and NWF.. Not quite on the CDN border. |   |  
0702000504 | Rock | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/184c6bba-0eb4-496b-b45b-4c14eebf9ca8) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/184c6bba-0eb4-496b-b45b-4c14eebf9ca8)
07050002 | Upper South Platte | 0.8.5 |   | Mainstem South Platte upstream of Denver with lots of urbanization. |   |  
0705000202 | Upper South Platte | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/3ad36178-7465-4c93-9c00-05b24f37f66a) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/3ad36178-7465-4c93-9c00-05b24f37f66a)
10030201 | Middle South Platte-Cherry Creek | 0.8.5 |   | Tributary originating on plains with mainly intermittent and crop circles and mainstem that goes perennial then goes dry | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/06b6dd14-92ad-41a3-9337-5a55f0343e84) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/06b6dd14-92ad-41a3-9337-5a55f0343e84)
1003020102 | Middle South Platte-Cherry Creek | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/9d570e58-bb47-442a-845a-f298378abf02) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/9d570e58-bb47-442a-845a-f298378abf02)
10050015 | Clear | 0.8.5 |   | Easy mid-watershed high Rockies (FAILED TO UPLOAD. Nothing to do with VBET) |   |  
1005001505 | Clear | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b99745cc-c723-4110-9347-7801883eb62c) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/b99745cc-c723-4110-9347-7801883eb62c)
10190002 | St. Vrain | 0.8.5 |   | Lower South Platte gravel mining pit on mainstem mess |   |  
1019000209 | St. Vrain | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/560bacfe-9b6d-473a-a541-62fb5e034413) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/560bacfe-9b6d-473a-a541-62fb5e034413)
10190003 | Kiowa | 0.8.5 |   | Arid and low relief | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/9e9e99aa-bbc5-456e-8e6c-22a03a9161e2) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/9e9e99aa-bbc5-456e-8e6c-22a03a9161e2)
1019000309 | Bear Lake | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/1bd88089-7b4c-4bfb-a5b0-d97553d6c886) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/1bd88089-7b4c-4bfb-a5b0-d97553d6c886)
10190004 | Bear Lake | 0.8.5 |   | See how it handles Bear Lake itself. related to #659 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/12aae315-9b05-419d-8502-016a9803abfc) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/12aae315-9b05-419d-8502-016a9803abfc)
1019000402 | Middle Bear (HUC10) | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/cf40d9b0-7750-4527-a3cc-7c44c4a44c07) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/cf40d9b0-7750-4527-a3cc-7c44c4a44c07)
10190005 | Middle Bear (HUC10) | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/93e94e78-3af7-42ea-88ab-8b3b275e2649) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/93e94e78-3af7-42ea-88ab-8b3b275e2649)
1019000507 | Middle Bear (HUC10) | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/711d8511-aa6b-4620-9630-265c6badd6b5) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/711d8511-aa6b-4620-9630-265c6badd6b5)
10190010 | Logan River from HUC8: Little Bear-Logan Logan River | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/2ba1ae9d-8981-4709-adc1-7f78945ed28f) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/2ba1ae9d-8981-4709-adc1-7f78945ed28f)
1019001003 | Logan River from HUC8: Little Bear-Logan Logan River | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/3122aedd-c0a0-4f3b-b905-c04fa353f3d9) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/3122aedd-c0a0-4f3b-b905-c04fa353f3d9)
16010201 | Middle Fork Clearwater | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/8731134f-0336-408c-94ba-02c445897b49) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/8731134f-0336-408c-94ba-02c445897b49)
1601020101 | Middle Fork Clearwater | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/709046ce-b72d-4f83-aad2-63fc80a0edd6) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/709046ce-b72d-4f83-aad2-63fc80a0edd6)
16010202 |   | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/158a9fb9-3e5f-42a8-8b60-946dd5a0038a) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/158a9fb9-3e5f-42a8-8b60-946dd5a0038a)
1601020201 |   | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/298c99fb-53ff-474a-87ce-2a2b5c5edc52) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/298c99fb-53ff-474a-87ce-2a2b5c5edc52)
1601020204 |   | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/28f64242-c494-4ebc-9503-d9228c925ddb) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/28f64242-c494-4ebc-9503-d9228c925ddb)
16010203 |   | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/d7de0f02-912c-4c58-a7ab-6129b5614ff2) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/d7de0f02-912c-4c58-a7ab-6129b5614ff2)
1601020303 |   | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/76f9f5f3-ad66-4099-a7ba-9bce642bc32a) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/76f9f5f3-ad66-4099-a7ba-9bce642bc32a)
17060304 |   | 0.8.5 |   | Kelly's favorite | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/c77129e9-605e-4c66-952b-f3046dd7c845) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/c77129e9-605e-4c66-952b-f3046dd7c845)
1706030402 |   | 0.8.5 |   |   | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/1e8e010f-773c-4fbe-ad30-5b60f140924f) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/1e8e010f-773c-4fbe-ad30-5b60f140924f)

**Comment by joewheaton** [comment]
@MattReimer, @philipbaileynar and @KellyMWhitehead lets use these 23 HUC 10s in table above and list below for testing:

`0501000301, 0502000405, 0504000306, 0501000301, 0502000405, 0504000306, 0514020112, 0601020203, 0601020704, 
0702000504, 0705000202, 1003020102, 1005001505, 1019000209, 1019000309, 1019000402, 1019000507, 1019001003, 1601020101, 1601020303, 1706030402, 1601020201,1601020204`


FYI @shelbysawyer

**Comment by KellyMWhitehead** [comment]
Queued up and running the upstream projects, and will kick off vbet once these are ready.

**Comment by KellyMWhitehead** [comment]
These are now up and running on VBET (and starting to finish).

I will update the table with project links, but for now you can look for a warehouse tag of "DEC02"

**Comment by MattReimer** [comment]
I took the liberty of updating above with `0.8.2`

**Comment by joewheaton** [comment]
@MattReimer and @KellyMWhitehead are you wanting me to look at this? Is 0.8.3 already run reflecting re-architecture. It I'm downloading now to see if I can tell.

**Comment by MattReimer** [comment]
`0.8.3` is done. By all means take a look.

**Comment by MattReimer** [comment]
`0.8.4` is in there. HUC8s are failing which is a known issue #681

**Comment by philipbaileynar** [comment]
Closing this issue now that we are at 0.8.6.
