### ISSUE TITLE
Bug VBET 0.8.1 - Fix Levelpath vased VBET processing to not use transform functions from drainage wings

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#655]
In Lyon, @MattReimer, @philipbaileynar and @joewheaton had a breakthrough discovery for why the tributary fans were incorrectly getting included in the mainstem's valley bottom. The culprit was the assignment, by drainage wing of which transform function to use. The individual lines of evidence, all looked good.  However, it is probably driven by the slope transform function and when we incorrectly use on the tributary fan the transform functions from the tributary! We should be using the transform functions of the mainstem, which would generally have a lower slope threshold and then exclude the fans from play (or so @joewheaton hypothesizes). 

Even in the [video](https://youtu.be/-mkad06CWg0) from #652 on WebRV, it is very apparent in most of the HUC10s. 

## Suggested Culprits
It can get really confusing to assign blame because we now have such a complicated order of operations. We now have two lines of evidence that are calculated globally (slope and TWI) and one that is calculated by level path. This obscures the fact that ALL evidence is transformed to a 0-1 index.  
### Culprit 1 - Transform Zones coming from Drainage Wings 
The geometry of the transform zones from tributary drainage wings is extending across the Fans (where they exist) the evidence for the smaller (upstream tributary) transform zones of slope, which are increasing the slope threshold and erroneously including fans and extending upstream into the tributary the "mainstem valley bottom" boundary. 

### Culprit 2 - Transform Zones Applied Uniformly for Slope & TWI (as opposed to independently by levelpath)
The real crux of the problem is _when_ we apply the transform curves. To fix this, we unfortunately have a situation where we the idea of "transform zones" globally disappears and needs to be relegated back to the level path (see solution). The problem is once you recognize culprit 1, we have no mechanism for fixing it with a global transform zone.  

# Suggested Solution
Below I offer a suggestion, that is based very much on current work flows, but moving a few key pieces around.

- [ ] A. Figure out a new method for **flagging the transform zones at each calculated levelpath** (NOT all)
Perhaps this is something like:
1. Identify current levelpath of focus. 
2. Run through calculating HAND first (like you already do).
3. Decide if your levelpath crosses a "size" transform boundary (i.e. moving upstream from a big to medium or medium to small).
4. If it does not, identify the "size" for transform curve (`0,1` or `2`) and apply globally using your levelpath's `envelope_polygon`.  EXIT. Otherwise,
5. If it does, flag upstream cells (maybe using distance upstream raster) and create at level path level the equivalent of a `transform_zone.tif` raster. You only need one for all evidence (you are currently allowing us to do this separately for all three evidence. We never have and never will use this. Although nice, it bloats size unnecessarily if we are doing this at level path and is one more layer of complication. 

- [ ] **Apply and keep the "transformed" HAND, Slope and TWI evidence independently at each levelpath**. _NOTE: there will be `local_HAND_levelpath.tif`, but no `local_SLOPE_levelpath.tif` and no `local_TWI_levelpath.tif`. However, there will be three tranformed rasters:_
1. `normalized_hand_levepath.tif` - already produced
2. `normalized_slope_levepath.tif` - new
3. `normalized_TWI_levepath.tif` - new

- [ ] Use same method for creating "composite" HAND and "composite Transformed HAND, to create **"composite" Transformed TWI" and "Transformed Slope"** (NOTE it is unnecessary to do a "composite" TWI or Slope as these remain global evidence. In principle, you can create the `composite_transform_zones.tif` (we only need one), because you actually are keeping track of which levelpath (and therefore its transform zone) wins for each cell on the reassembly. 
- [ ] Please can we output a simplified **summary of levelpath stats** (maybe to go in report) of the super helpful `level_path_debug.csv` file that reports about levelpaths order and those used? For example, from the 1003020102 VBET, I can see:
- Summary Count of all LevelPaths: 454 (but log says 461)
- Summary Count of channel segment inputs: 1183
- Summary Count of LevelPaths excluded from VBET: 1 (RED FLAG for me... why are ALL these being calculated. I thought we skipped ones that were included)
- Total Time calculating levelpaths: 5685.4 sec (1.6 hours)
- Average Time per levelpath: 12.3 sec
- Max Time & Levelpath: 1216.5 sec (20.2 minutes) for 23001300004948
- [x] As @MattReimer offered in Lyon, please move the rasters in `temp.zip/rasters/` to their individual levelpaths to make troubleshooting easier.  _Lower Priority_

The above is NOT easy, but it is fundamental. I predict this will give us better outputs that are easier to troubleshoot and cleaner for downstream steps of centerlines, DGOs, everything. Happy to chat through. I suggest we try it on one HUC10 and see how it goes.

**Comment by MattReimer** [comment]
> As @MattReimer offered in Lyon, please move the rasters in temp.zip/rasters/ to their individual levelpaths to make troubleshooting easier. Lower Priority

We're not going to do this for now because it's too disruptive. Those rasters are being kept in their own folder for a good reason.

**Comment by philipbaileynar** [comment]
Lots of good requests and suggestions here. Unfortunately we have to deporioritize them below the essential fixes for 0.8.5

**Comment by philipbaileynar** [comment]
I have moved the request for a level path summary to #689. The other requests are outdated based on the status of 0.8.6.
