### ISSUE TITLE
VBET Business Logic for Troubleshooting

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#657]
In this period of rapid development and bug testing, it is crazy we DO NOT have a business logic that reveals all the new layers. I am assuming (I will confirm) that we are putting everything in the `project.rs.xml`?  I will have a look and see if I can get a temporary one going to help with troubleshooting!

**Comment by joewheaton** [comment]
> @joewheaton The VBET_ALL.xml that I authored should only be missing a couple (of the very newest) layers-- updating that will be easier than starting fresh.

Shoot... sorry I missed this. I had my head down and just threw one together here. Let me know if you have in yours anything I am missing.

**Comment by MattReimer** [comment]
closing this as https://github.com/Riverscapes/RiverscapesXML/pull/499
is merged

**Comment by joewheaton** [comment]
Funny, I was just looking at a WebRAVE project, and all of the sudden the new business logic appeared. The new layers are not curated yet, so for the most part not showing up, but still cool.
