### ISSUE TITLE
VBET 0.8.1 - Problem in VBET of large valley bottoms where TWI is culprit

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#659]
I mentioned a problem in the larger valley bottoms in #652:
> 5. There are some noticeable warts on bigger valley bottoms... 
We see this in many of the HUC 10s, but in this ticket I will focus on using the [Badger Creek HUC10 1003020102](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/2fa6227b-f7d3-4cde-b3b1-484f0ad736d9) of the Two Medicine HUC8 10030201. 

There may be many causes for these "warts", but lets define them as:
- Unexplained islands of low-likelihood VBET thresholded out of valley bottom.
- Areas that when excluded are leading to poor discretization geometry of DGOs with Thiessen polygons. 

In [this video https://youtu.be/GIjDhGXE8Sg](https://youtu.be/GIjDhGXE8Sg) I pan around and turn on and off different examples from the composite layers, the global layers and the individual mainstem level path layers. Below are a few pics.

Some examples:
![image](https://user-images.githubusercontent.com/9723905/205601106-458b232e-2ad4-4e3d-bc38-ce20850ee4a1.png)
The same place looking at the composite likelihood raster:
![image](https://user-images.githubusercontent.com/9723905/205602099-083f671b-5c68-4f9c-9405-ee723fe36797.png)
And now why I think TWI may be a partial culprit:
![image](https://user-images.githubusercontent.com/9723905/205602976-7eb44a1a-65be-4305-a679-826f3e776423.png)

## Related questions

1. Does TWI help our VBET performance at all? _@joewheaton reasoned this might be helpful for headwater meadows and fans. The evidence is coherent and seems like it would, but maybe it is causing us problems?_
2. When TWI is NoData, are we correctly proceeding with the calculation based on the other lines of evidence (slope and HAND)? 
3. If we are correctly proceeding, is there something about the average of just slope and HAND evidence that is skewing these values so low? I can't see it in individual evidence as slope and HAND evidence is high in both these areas.
4. Is it worth a troubleshooting step of doing a complete run of one HUC 10 without using TWI as a line of evidence? Would that tell us anything? 
5. Is TWI the true culprit, or are there other problems in assembly of the different evidence first?

**Comment by joewheaton** [comment]
It is possible that the suggestion in #655 will help (in part) with this. It doesn't change the significance of questions 2 and 3. Maybe hold off on 1, 4?

**Comment by joewheaton** [comment]
Here's another one from [1601020204](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/9cc4a320-eb3e-4ab7-b5d9-2d1039815cca):
![image](https://user-images.githubusercontent.com/9723905/205660746-55b6606b-ea48-4768-b7b1-3ee1d0c0a3fe.png)

**Comment by philipbaileynar** [comment]
Fix for this is in the works... But I sense this is going to be huge.

Here's TWI for the bottom of Bear Lake. Yellow is NoData!!!!! And look at the second image how that manifests in VBET. Almost a perfect 1:1 relationship between mainstem valley bottom omissions and NoData TWI.


<img width="1331" alt="Screenshot 2022-12-06 at 2 00 34 PM" src="https://user-images.githubusercontent.com/8645379/206032503-e8d4590b-fff4-427e-9a48-e2da3515a37d.png">

<img width="1331" alt="Screenshot 2022-12-06 at 2 01 53 PM" src="https://user-images.githubusercontent.com/8645379/206032759-363be02a-cb9d-4c49-9f0c-3b531d623526.png">

**Comment by KellyMWhitehead** [comment]
This is the big change for vbet version 0.8.2

**Comment by joewheaton** [comment]
This is having dramatic results! Everything I've looked at looks way better with this fix. Nice work guys!

**Comment by MattReimer** [comment]
fixed as of 0.8.3
