### ISSUE TITLE
VBET 0.8.1 - Metrics Questions & Requests

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#661]
The IGO (integrated geographic object) centerline points are where the magic sauce of our moving window metrics for VBET are now calculated. These are stored in the `output/vbet.gpkg/segmentation_points`. I have some questions and requests. @shelbysawyer will take the answers here and 
- [ ] Curate views for remaining metrics.
- [ ] Author metric documentation on VBET website once we have answers. 

@philipbaileynar we can work through this together with @KellyMWhitehead. This is a lower priority than the "Blockers" obviously, but needs doing before we hit run on everything.  

The table looks like this for now:
![image](https://user-images.githubusercontent.com/9723905/205637221-7c5691cb-e9b1-4f68-a3ed-58d0e7130c7b.png)

# My questions

- [x] 1. Why is `LevelPathl` a floating point and not an integer?
- [x] 2. Is `seg_distance` the distance downstream or upstream from source or sink along a level path? Values repeat, so I presume it resets for each levelpath? What can/should we use it for?
- [x] 3. What are the units of every metric? Where is this documented? Where or how to do you suggest it be exposed to user?
- [x] 4. Are all the `_area` suffix metrics in units of hectares or square meters? 
- [x] 5. What exactly is `window_area`? _Is it the valley bottom area within the moving window?
- [x] 5. For all the `_area_prop` metrics, the numerator is clear, but is the denominator `window_area`? It appears to be, but want confirmation.
- [x] 6. Please confirm that `integrated_width` is in meters and is just `window_area` divided by `centerline_length`.
- [ ] 7. I do not understand the values stored in the `_cl_len` suffix metrics for `active_floodplain`, `inactive floodplain` ,`active_channel`, and `floodplain`. I didn't know you were deriving centerlines for `active_floodplain`  `inactive floodplain`, and `floodplain`. HOW are you doing this? Where are intermediates? What are the units? They do not make any sense! For example in a reach that was 98.8 m long, the `active_channel_area_cl_len` wsa 1.98 (units?)! I would expect most of these to be relatively meaningless.
- [ ] 8. Can `active_channel_area_cl_len` just be the sum of the length of all the NHD channels in that moving window? That would be useful!

## Shelby Question
Carry over from #579 
- [ ] 9. > At the bottom of reaches, where the window cannot look downstream enough to fulfill the window requirements, how will this be dealt with? It sounds like this has been agreed upon already, but just looking to get specifics here so that I can get it into documentation.

# My Requests

I really want to produce a few metrics that are not here. If I know answers to above, I can calculate them with symbology value expressions (i.e. QML) so don't necessarily need new attributes. However, I will list them here in case you (@philipbaileynar or @KellyMWhitehead ) think they might be worth exposing as new metrics in the table. 
- [x] A. `VB_Acerage_per_mile` - the amount of valley bottom (i.e. `window_area` converted to acres and divided by `centerline_length` converted to miles). This absolute currency is extremely important. 
- [x] B. `VB_Hectares_per_km` - the amount of valley bottom (i.e. `window_area` converted to hectares and divided by `centerline_length` converted to kilometers). 
- [x] C. `Active_Prop_Acerage_per_mile` - the amount of active floodplain and active channel  (i.e. `active_floodplain_area` plus `active_channel_area` converted to acres and divided by `centerline_length` converted to miles). This is used to express current conditions.
- [x] - D. `Inactive_Prop_Acerage_per_mile` - the amount of inactive floodplain and active channel  (i.e. `inactive_floodplain_area` plus converted to acres and divided by `centerline_length` converted to miles). This is also used to express current conditions.
- [x] E.. optionally we can metric equivalents of C & D
- [x] F. I would like integrated width calculations for the floodplain, channel, active floodplain, and inactive floodplain as well please. These are just the the area of each divided by `centerline_length`. This recasts things in a currency directly comparable to the valley bottom width (`integrated_width`).
- [ ] G. Where is the transfer of the NHD FCode metric so we can assign each DGO a perennial, intermittent or ephemeral status. I have requested this before and suggested previously (#456) it could be based solely on the FCODE attribute of the intersecting flowline of the levelpath that the DGO was derived from. 
- [ ] H. Can `active_channel_area_cl_lp_len` representing only the length of the levelpath those DGOs were calculated from be calculated? This would be equal to `active_channel_area_cl_len` in single thread reaches, but in multi-thread reaches this would give us a very useful measure.
- [ ] I .Lets calculate a `Relative_Flow_Length` like @kbartelt  does in RIM, that is `active_channel_area_cl_len` divided by `centerline_length`. 
- [ ] J. Lets calculate a main channel sinuosity `cl_lp_Sinuosity` as  `active_channel_area_cl_lp_len` divided by `centerline_length`. Note this is different from planform sinuosity, which requires a straight line distance. We'll leave that to GNAT.

None of these are departures from things I have asked for since the beginning. They are just refinements.  They also represent some of the ways we will report summary and zonal statistics across the entire run or much bigger runs.

**Comment by joewheaton** [comment]
> 2. Is `seg_distance` the distance downstream or upstream from source or sink along a level path? Values repeat, so I presume it resets for each levelpath? What can/should we use it for?

Yes, it resets for each level path and is distance from bottom of levelpath. It is literally the cummlative segmentation distance at each centerline IGO point from the mouth of that levelpath (within current HUC). This is really useful if a user wants to select by levelpath and then do a long profile plot. 

![image](https://user-images.githubusercontent.com/9723905/205647663-5a2a753c-c5f3-48aa-9674-7e24d2842a6a.png)

**Comment by philipbaileynar** [comment]
Here's a skeleton [documentation page](https://tools.riverscapes.net/vbet/vbet_metrics.html) to start gathering this information.

Here's the [markdown](https://github.com/Riverscapes/riverscapes-tools/blob/docs/packages/vbet/docs/vbet_metrics.md). @KellyMWhitehead please add definitions to satisfy Joe's inquiries.

**Comment by KellyMWhitehead** [comment]
Metrics A-F to be included in 0.8.6.

G-J need a little more tlc to get working.

**Comment by philipbaileynar** [comment]
- A-F are in 0.8.6 as Kelly stated.
- G is tracked in #456 
- H-L are best tackled in GNAT and are now tracked in #690
