### ISSUE TITLE
TEST HUC8 vs HUC10: VBET for Middle Bear 16010202

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#663]
> Did you make a ticket for that somewhere @MattReimer? That is interesting.

> No, I confess I did not. All that kind of got sidetracked last week. Feel free to create one if you'd like. I'm not sure of the best wording. It's just a quick (ish) someone (shelby?) could do to see if we have any big problems. Maybe it's nothing but we won't know until we look.

_Originally posted by @MattReimer in https://github.com/Riverscapes/riverscapes-tools/issues/660#issuecomment-1337635995_
      
Okay, I am going to assign this first to @KellyMWhitehead to run the following (please check off when done and provide webRV links as a reply:

_(https://docs.google.com/spreadsheets/d/1ZtuVuxLqjAxFU-MrxOX6ZjL8jtduqcyNwyuZvaPRaPI/edit#gid=125951305)_

HUC10 | HUC8 Name | Version | Duration |   |   | notes
-- | -- | -- | -- | -- | -- | --
16010202 | Middle Bear (HUC8) | 0.8.3 | 12:26:42 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/7e5bd0ee-f887-4c88-b4d6-4351bd684756) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/7e5bd0ee-f887-4c88-b4d6-4351bd684756) |  
1601020201 | Middle Bear (HUC10) | 0.8.3 | 0:38:14 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/e74fc3a3-9714-46eb-b9e5-5d6ca53203ad) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/e74fc3a3-9714-46eb-b9e5-5d6ca53203ad) |  
1601020202 | Middle Bear (HUC10) | 0.8.3 | 1:37:58 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/fe786ad9-8944-407b-b11e-8a4833a47efc) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/fe786ad9-8944-407b-b11e-8a4833a47efc) |  
1601020203 | Middle Bear (HUC10) | 0.8.3 | 2:38:21 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/c3b3ba9c-bcb9-44bd-8877-e88e706cce8a) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/c3b3ba9c-bcb9-44bd-8877-e88e706cce8a) |  
1601020204 | Middle Bear (HUC10) | 0.8.3 | 2:19:30 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/a52492f9-1580-47d8-bead-629aedf8168e) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/a52492f9-1580-47d8-bead-629aedf8168e) |  
1601020205 | Middle Bear (HUC10) | 0.8.3 | 2:41:04 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/70c420a3-69a0-41cd-9fbf-56370b8ab4e4) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/70c420a3-69a0-41cd-9fbf-56370b8ab4e4) |  
1601020206 | Middle Bear (HUC10) | 0.8.3 | 2:32:45 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/7a75a8f7-4964-4bcc-bef4-b514d54225f8) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/7a75a8f7-4964-4bcc-bef4-b514d54225f8) |  
1601020207 | Middle Bear (HUC10) | 0.8.3 | 1:12:57 | [WH](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/c73c23eb-46a0-43dd-b455-6c81c9c2416e) | [RV](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/c73c23eb-46a0-43dd-b455-6c81c9c2416e) |  

Then assign this ticket to @shelbysawyer and she will compare the HUC10 an HUC8 runs to find out if they are essentially the same or are their differences. 
- [ ] Compare HUC8 VBET with the HUC10 VBETs that make up same extent 

_**Note:** "Correctness" is not the concern in this ticket. All we care about is: Are they the same?_

**Comment by joewheaton** [comment]
FYI @MattReimer. Note, we might want to hold off on this until later in the week to see if we make some progress on some of the other bugs first.

**Comment by philipbaileynar** [comment]
Hold off on this for now. At least until the TWI fix (#659) is complete. Maybe until transform zones is fixed.

**Comment by MattReimer** [comment]
All done @shelbysawyer assigning to you. 🤞

**Comment by joewheaton** [comment]
@shelbysawyer do you understand this task? Essentially see if they are producing the same outputs?

**Comment by shelbysawyer** [comment]
@joewheaton I believe so. I'll be looking at the HUC 10 projects side by side with the "parent" HUC 8 project to make sure that they look the same, right? In terms of outputs, I'll focus on the likelihood raster, VB extent vector layer, and segmented VBs?
