### ISSUE TITLE
Duplicate distances on some level paths

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#665]
Some of the DGOs along the same level path end up attributed with the same distance (distance 0 is somewhere in the middle and then increases in both upstream and downstream direction.
![Screenshot 2022-12-05 104240](https://user-images.githubusercontent.com/21687931/205714367-3f6e1f51-4ff6-4241-a3eb-31c86b78199f.png)

**Comment by KellyMWhitehead** [comment]
This is caused by multiple centerline segments/features getting generated when the level path flowlines do not dissolve properly into one long feature. Most likely ogr precision issue.

I will tackle this soon...

**Comment by KellyMWhitehead** [comment]
I have reviewed several hucs, issue seems to be resolved.
