### ISSUE TITLE
VBET Centerlines not generated when Flowline endpoints off cost raster

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#667]
Known issue - VBET skips generating a centerline for a level path when the flowline endpoints do not fall on the cost path raster. This is usually by a very small distance.

Proposed solution:
1) check if endpoint falls on raster
2) if not, move specified distance (e.g. pixel size, 1m) up the line and generate new point, test again.
3) limit number of iterations by some % of line distance, log issue if still unable to generate centerline.

**Comment by joewheaton** [comment]
@KellyMWhitehead this is interesting. Do you think that is what I was seeing on https://github.com/Riverscapes/riverscapes-tools/issues/654#issuecomment-1337697906 ?

**Comment by philipbaileynar** [comment]
> @KellyMWhitehead this is interesting. Do you think that is what I was seeing on [#654 (comment)](https://github.com/Riverscapes/riverscapes-tools/issues/654#issuecomment-1337697906) ?

#654 was definitely caused by the `IsEmpty` channel area geometry problem. But there have been several recent HUCs where the mainstem failed to build a centerline (and IGOs) because the downstream end of the centerline polyline was slightly off the rater.

**Comment by KellyMWhitehead** [comment]
Fix is ready for version 0.8.2

**Comment by KellyMWhitehead** [comment]
Verified issue has been resolved for 1601020201
