### ISSUE TITLE
Discontinuous Valley Bottoms (Ribbons)

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#671]
Example... In the screenshot below the blue valley bottom was calculated first. Then the organge valley bot
tom was calculated and presumably it covered much of the same blue mainstem. But when the orange valley bottom was incorporated into the overall valley bottom raster it only retains the orange where the raster is currently NoData. The blue is retained correctly, but there are places where the orange extends beyond the blue. This leaves isolated, discontinuous sections of valley bottom associated with the organge level path.

<img width="1748" alt="Screenshot 2022-12-08 at 10 33 29 AM" src="https://user-images.githubusercontent.com/8645379/206562844-ab6b033a-526d-44f8-9683-d438b7678008.png">

This can produce stranger results. @joewheaton noted where this clipping causes discontinuity in the centerline and IGOs too:

<img width="1181" alt="Screenshot 2022-12-08 at 11 09 46 AM" src="https://user-images.githubusercontent.com/8645379/206562984-3b2b86a3-3823-42a1-aa5e-cab3f0b20b21.png">

# Solution

It would be ideal if we can solve this ribbon issue in raster space! Perhaps just keep largest raster "region" for each level path? Sounds risky.

If we have to go to vector space then we could use a spatial attribute filter to select all valley bottom polygons associated with a level path that touch the flow line or the valley centerline. Delete the others.

**Comment by KellyMWhitehead** [comment]
Figured out a method to clean this up in raster space.
Ready for v0.8.4

**Comment by MattReimer** [comment]
This is good enough for now. Ribboning is way reduced

**Comment by philipbaileynar** [comment]
Ribboning is virtually gone is the 0.8.4 HUC that I reviewed. There are still a couple of places where it still appears, but in my opinion this is solved.
