### ISSUE TITLE
Eliminate / Reduce TWI NoData in large valley bottoms - Zero Slope?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#672]
In #659 we overcame problems where TWI is NoData by omitting it from the math to combine VBET evidence.

It's worth researching why TWI NoData is prolific in flat areas as shown [here](https://github.com/Riverscapes/riverscapes-tools/issues/659#issuecomment-1340067569).

In #627 @jtgilbert made improvements in tauDEM tools by playing with DInf flow direction in combination with tauDEMs command line parameters.

# Zero Slope is the Culprit?

But @jtgilbert suggests that the problem with TWI might be zero slope values in the denominator of the TWI formula.

Can we try reclassifying zero slope as 0.000001 or something similar and seeing if that resolves the TWI NoData issue?

Note that this change is for the tauDEM project where we run TWI.... not VBET where we use the raster!

**Comment by KellyMWhitehead** [comment]
@philipbaileynar 
Do we want this reclass for the output slope raster, or just as an temporary raster used when generating twi?

**Comment by philipbaileynar** [comment]
Probably temporary. Good question

**Comment by KellyMWhitehead** [comment]
Having a better luck using the -nc flag with `areadinf` (highlighted areas indicate no-data):

twi with -nc for `areadinf`
![Image](https://user-images.githubusercontent.com/10746997/206819231-86104055-8548-474f-a345-0115855c0af8.png)

twi without -nc for `areadinf`
![Image](https://user-images.githubusercontent.com/10746997/206819283-43237cc7-f767-45df-8593-7d8b3af760c0.png)

**Comment by philipbaileynar** [comment]
Significantly better but not perfect. 

Are you pairing this with the non-zero slope fix?

**Comment by jtgilbert** [comment]
Yeah, the -nc flag just helps with the channels themselves and the ridge areas where they originate, not so much the big nodata patches in lowlands. Paired with non-zero it just take care of most of it....

**Comment by KellyMWhitehead** [comment]
fixed in taudem 1.2.1

- D-Infinity slope now uses -nc flag
- D-Infinity slope raster zero values reclassed to non-zero value (0.0001) when generating TWI (see dinf_flowdir_slp_reclass.tif)
