### ISSUE TITLE
TABLE: VBET 0.8.4 - Verify  HUC 10 Initial Screening of Results using WebRV

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#677]
@joewheaton will begin reviewing 0.8.4 now that #673 appears partially inaccurate. 

Specifically, verify the following [changes](https://github.com/Riverscapes/riverscapes-tools/blob/VBET_GNAT/packages/vbet/changelog.md) were for 0.8.4:
> - change input parameter to use processing_extent layer instead of huc8 to match actual watershed boundary 
> -  implement raster cleaning to remove "vbet ribbons" (related to #671)

These were from 0.8.3 and seem to have all worked, but keep an eye out:

> Changed
> - single transform per level path (based on max stream order) (related to #666)
> - segmentation_points renamed to vbet_igos 
> - output fields store level path id as string instead of float 
> Fixed
> - collect linestring uses shapely instead of ogr to improve merging of level path reaches when generating centerline
> 

I will wait for @MattReimer to add tab to https://docs.google.com/spreadsheets/d/1ZtuVuxLqjAxFU-MrxOX6ZjL8jtduqcyNwyuZvaPRaPI/edit#gid=1279742273 to generate table:

**Comment by joewheaton** [comment]
## Some Spotchecks of Ribbons

### Working
This is in  for 1003020102 [0.8.4](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/de53bcad-b34e-4a3a-934a-af28ca33cd10) vs. [0.8.3](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/50b098aa-c85c-4340-a207-e8eb79c8cff4)
Before:
![image](https://user-images.githubusercontent.com/9723905/207091399-c95d08d2-7dab-42a9-9d38-ded9553469f4.png)
After:
![image](https://user-images.githubusercontent.com/9723905/207092023-938fb53e-5bb4-4eae-82d5-78a4c91374bb.png)

Before:
![image](https://user-images.githubusercontent.com/9723905/207092697-3f169d6e-c20a-4350-9cd4-82c012174d97.png)

After:
![image](https://user-images.githubusercontent.com/9723905/207093065-cd87e51d-1522-4bab-9a7c-72446fc78228.png)

**Comment by MattReimer** [comment]
#671  greatly improved this. I'm closing this.

**Comment by joewheaton** [comment]
This is for me to review. I'm not done yet...
