### ISSUE TITLE
Two hydro 17 BRAT runs

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#68]
@tyler1218hatch these are the two BRAT runs that you requested so that you can get insight into the hydrology and vegetation. 

* [17090005](https://data.riverscapes.xyz/#/BRAT_CRB/2480f686-8a99-4d12-9701-af6680dfbbdc)
* [17110019](https://data.riverscapes.xyz/#/BRAT_CRB/a43161df-7afb-4615-b693-af32f5c20121)

I would really like to discuss your findings when you dig into these runs. Part of my motivation is to understand what information you are using to review the quality of the run and make sure that a) you know how to quickly get at the information that you need, b) add any additional queries/reports to help speed up your review.

**Comment by tyler1218hatch** [comment]
@philipbaileynar The main thing I do to validate (besides just looking at the suitability rasters) is to take a look at the veg classes that are strongly impacting calculations. Here's how that goes.

Take (or create) the 100m buffer for the river network
Clip the EVT and BPS rasters by that buffer
Sort the clipped rasters' attribute table by total count
Check the suitability values for the common veg classes (more than 1%ish representation)
I then compare those suitability values to values from nearby BRAT runs or old BRAT runs, as well as just checking to make sure the values are logical.

As far as ways you can help, I'm not sure. How hard would it be to produce a report breakdown of the 30 most common veg classes within the 100m buffer?

**Comment by tyler1218hatch** [comment]
@philipbaileynar Missed a step: First I have to join together each veg raster with its corresponding suitability raster, so i can see which veg classes correspond to which suitabilities. It would be nice if there was a raster that had those values already together.

**Comment by philipbaileynar** [comment]
Let's go through this tomorrow. There are definitely some easy victories with the report. 

For example the query for the 30 most common veg classes is dead simple. 

Talk to you at 12:30 central Wednesday.

**Comment by philipbaileynar** [comment]
Here are two queries that report the most frequent vegetation types in the 100m. The first is for historic veg and the latter is existing veg:

```sql
SELECT * FROM vwReachVegetationTypes WHERE (EpochID = 2) AND (Buffer = 100) ORDER BY TotalArea DESC LIMIT 30;
SELECT * FROM vwReachVegetationTypes WHERE (EpochID = 1) AND (Buffer = 100) ORDER BY TotalArea DESC LIMIT 30;
```

It would take just a couple of minutes to include these queries as tables in the BRAT report.

**Comment by philipbaileynar** [comment]
@tyler1218hatch I have re-run these two BRAT projects again, this time with the area weighted average suitability and also the breakdown of each suitability level.

They are up in the warehouse. Don't use the links above. Go to the warehouse and search for the two HUC codes.

Let me know if there are other report items that would make your review process more efficient.

**Comment by tyler1218hatch** [comment]
Closing this because I think we got everything we needed!
