### ISSUE TITLE
Task: RE-Run Taudem for VBET HUCs

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#680]
THis is so that we incorporate our d-inf changes into `0.8.5`

**Comment by KellyMWhitehead** [comment]
Successfully run for 39 huc8/10's:

17060304, 1601020201, 0514020112, 1003020102, 16010203, 07050002, 05010003, 1601020204, 1019001003, 10190005, 10190004, 1005001505, 05020004, 10050015, 0504000306, 1706030402, 0601020704, 06010202, 0501000301, 05040003, 10030201, 16010201, 10190010, 1019000507, 0702000504, 1601020303, 06010207, 1019000402, 16010202, 1601020101, 05140201, 10190003, 1019000309, 1019000209, 0705000202, 07020005, 0502000405, 10190002, 0601020203

Tags: Cybercastor,TWI_Fix

**Comment by joewheaton** [comment]
@shelbysawyer and @lauren-herbine this fix has really dramatically improved the coherence of TWI as a line of evidence.  It was partly the flag that @jtgilbert found, but more so getting rid of the zero slope values to avoid the divide by zero problem (i.e. changing slope of 0 to 0.0000000000001) so the mat gets an answer. 
![image](https://user-images.githubusercontent.com/9723905/207918958-a080b0b5-497a-42f7-b2bc-49d663caefba.png)

**Comment by lauren-herbine** [comment]
Looks great!
