### ISSUE TITLE
Corrupted TIF files when running HUC8 scale VBET

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#681]
Originally we thought this was related to #639 but that may have been an issue masking this one. 

It seems like this is an issue that only happens on or after about 16 hours of processing so it's going to be hard to pin down. 

GOing to have to get creative here I think.

**Comment by MattReimer** [comment]
Seems like this issue is solved using our new VRT assembly method but I want to wait until some really big HUC8s come through the pipe until I close it,

**Comment by philipbaileynar** [comment]
Looks solved in 0.8.6
