### ISSUE TITLE
VBET Donut Threshold

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#683]
@KellyMWhitehead can you explore  a raster based donut threshold please.

Perhaps start with everything small than 20 pixels, 400sqm?

In this HUC [1003020102](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/9d570e58-bb47-442a-845a-f298378abf02) example zeveral small (25m across) donuts caused significant valley centreline sinuosity.

<img width="930" alt="Screenshot 2022-12-14 at 12 35 17 PM" src="https://user-images.githubusercontent.com/8645379/207708346-daf0a7b4-46d9-4418-b79f-8bcbfceab3de.png">

**Comment by KellyMWhitehead** [comment]
donut filtering now set for 20-pixel sized areas

**Comment by joewheaton** [comment]
Thanks. Is this a parameter exposed in run configuration or something hardcoded? Might be something we need to adjust for custom runs and different resolutions.

**Comment by KellyMWhitehead** [comment]
Currently hardcoded, but easy enough to change to a parameter.

**Comment by philipbaileynar** [comment]
Working! Probably can tolerate a bigger threshold, but I'll leave that to the calibration crew and a new ticket.

<img width="929" alt="Screenshot 2022-12-19 at 12 18 13 PM" src="https://user-images.githubusercontent.com/8645379/208513542-7fab7431-7e77-4bc4-a238-12bfa4d91a06.png">
