### ISSUE TITLE
Anabranch Project Runs

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#694]
- Environment: Production
- Program: Anabranch
- HUCs: 17060107, 10050015, 17060103, 16010202
- tags: None needed
- Tools:
    - RSC
    - Channel Area
    - tauDEM
    - VBET
    - BRAT
    - GNAT

[spreadsheet](https://docs.google.com/spreadsheets/d/141mB1ZVud5dE_u4F33avvxieOcrk-h4V3vR_ug-sPlg/edit?usp=sharing)

**Comment by KellyMWhitehead** [comment]
All runs complete and spreadsheet updated as of 1/6/23.
