### ISSUE TITLE
VBET: Incorrect Integrated VB Width Values

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#697]
[Project link](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/3f1022bc-f892-4ed7-9ab7-05b313b2a76d), v. 0.8.6

I created a graphic to show some issues that @lauren-herbine and I have run into while exploring the most recent VBET runs:

![13](https://user-images.githubusercontent.com/73311751/216692756-1a8b76ee-e7df-4430-8e4e-ca0739546112.png)

**Problem A** has already been documented in a few places, such as #696. Could the shared levelpath observation in the graphic have anything to do with this?

**Problem B** refers to an issue with the way the integrated VB width metric is being calculated. Many IGOs have correct width values-- I manually validated in QGIS. However, others do not.. and from my perspective on this, it's difficult to understand why. For example, in the graphic above, the bend that is showing wildly large integrated VB widths (yellow IGOs, <10 km) looks pretty good. The VB extent and centerline have geometries that look like VBET is performing well. Also, note that it also occurs again on another bend in Dry Fork. If odd geometry isn't driving this problem, what is?

**Comment by joewheaton** [comment]
@shelbysawyer thanks for this. My impression is that this is now fixed. Re-open or make a specific more actionable new ticket if I am mistaken.
