### ISSUE TITLE
Need VBET v.0.8.6 run for 05140201

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#699]
I'm moving into the calibration process for VBET and need to be able to compare field observations to the latest VBET runs. We have all necessary HUCs apart from one, Lower Ohio - Little Pigeon (05140201). Can you please run VBET for this watershed?

**Comment by KellyMWhitehead** [comment]
I have kicked off this visit.

**Comment by KellyMWhitehead** [comment]
Still running...

I might need to chop this into huc10s and rerun.
