### ISSUE TITLE
Why are the % thresholds an intermediate?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#7]
Why are the thresholds an intermediate? They also show up in the outputs? Seems odd.

![image](https://user-images.githubusercontent.com/9723905/81013004-b4fb9500-8e17-11ea-91be-460be51b4207.png)

I see where you hard-code these in https://github.com/Riverscapes/sqlBRAT/blob/master/vbet.py#L48, but I don't see that there is any difference between the intermediate and output? Why include them in both? It makes sense to expose the hard-code as a user-input (fine if command line or config file for now). Especially in light of Riverscapes/vbet#6.

**Comment by MattReimer** [comment]
This should be addressed now. The shapes in the intermediate package are raw and unsmoothed. The evidence raster is now separate layers as per a previous issue.
