### ISSUE TITLE
VBET 0.8.6  Problem C. - Missing Data in reassembly of VBET evidence raster... still.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#702]

**Comment by joewheaton** [comment]
@jtgilbert I have a sneaking suspicion this is still present because we don't initialize the composite raster with a raster the full data extent of the watershed with values of 0 or 0.001. I think that might be cartographically helpful so we don't end up with parts of the watershed with no values. IF they are left out, they should just be zero. Thoughts?

**Comment by shelbysawyer** [comment]
Just making a note that this is still happening in our newest runs--

![error](https://user-images.githubusercontent.com/73311751/236986758-a44538fb-9266-4bfb-b1ea-ce75efeab239.JPG)
