### ISSUE TITLE
Anhtro 0.0.1 - Please add missing `<ProjectBounds>` to code to write to `project.rs.xml`

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#703]
Thanks @jtgilbert for sharing your Anthro project. Your Project File is missing the `<ProjectBounds>` required by the warehouse in the `project.rs.xml` file between `<MetaData>` and `<Realizations>`.  Please ask @MattReimer or @KellyMWhitehead how they do this or see how it is done in other tools.

Should look something like:
 ``` xml
</MetaData>
	<ProjectBounds>
		<Centroid>
			<Lat>40.05781393379423</Lat>
			<Lng>-106.07380409560582</Lng>
		</Centroid>
		<BoundingBox>
			<MinLat>39.92577642633667</MinLat>
			<MinLng>-106.20239261060925</MinLng>
			<MaxLat>40.177535795647096</MaxLat>
			<MaxLng>-105.97185534061569</MaxLng>
		</BoundingBox>
		<Path>project_bounds.geojson</Path>
	</ProjectBounds>
	<Realizations>

```

**Comment by jtgilbert** [comment]
There's a secondary script that adds that, but I can't run it because the VBET I'm using as an input has XML v1 and it needs to be xml V2.

**Comment by philipbaileynar** [comment]
Asked and answered.
