### ISSUE TITLE
Normalized Slope & TWI Rasters Not Working

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#709]
This is a follow-up from a recent conversation with @KellyMWhitehead 

The normalized evidence rasters that live in VBET's Intermediates (HAND, TWI, slope) are able to be added to projects, but the normalized slope and TWI rasters don't actually seem to contain any information. This seems to be more than a simple display or symbology issue.

In order to move forward with VBET calibration work, I need to be able to experiment with weighting individual normalized lines of evidence to manually recreate VBET's likelihood raster.

<img width="257" alt="twislope" src="https://user-images.githubusercontent.com/73311751/219445462-cefeea55-325c-4f18-83eb-8c3fc77d74d2.PNG">

**Comment by jtgilbert** [comment]
Fixed: e27ca7005e3a9122c8148c816428150646a5f40e
