### ISSUE TITLE
New VBET evidence raster

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#711]
FYI @joewheaton. Putting this here to document it. I've discussed these changes with @philipbaileynar @KellyMWhitehead @shelbysawyer and @lauren-herbine . 

I'm suggesting some changes here that will be fairly easy to implement, that don't require any changes to the structure or order of operations of Kelly's code. 
1. Get rid of TWI as an evidence raster. Two reasons: the high values on any flat surface make separating active vs. inactive VB from evidence raster values almost meaningless, and TWI is largely a function of slope, and is therefore somewhat redundant as an evidence layer. (I do think we should hang onto it as a layer because it has potential down the road for IDing fans.)
2. I've come up with a distance adjustment for the slope evidence, so that a value of, for example 1 degree that occurs in the channel is not weighted the same as a cell that is 1 degree a mile away from the channel. In other words, for a given slope value, it's weight decreases with distance from the level path.
3. Weighting: I think HAND should be weighted higher than the slope evidence. This is key for meaningfully separating active v inactive floodplain. 

The picture below is an example of implementing these changes on the main Bear level path in the HUC10 containing Oneida Narrows. The takeaways are that this method creates "likelihood" values of 0 once you are clearly up out of the VB, and that the values of "likelihood" within the VB are broader, potentially making it easier to identify good thresholds to use to split active and inactive. I've tested in different size level paths, but still need to test in an area with a super wide VB.

![new_evidence](https://user-images.githubusercontent.com/21687931/219461069-d4f45163-2a72-43b7-b8d9-a1f67ed8c9c9.png)

**Comment by philipbaileynar** [comment]
I really like all of these suggestions. Random additional thoughts:

- TWI is noisy! Eliminating it will increase valley bottom coherence.
- Including TWI kinda double weights slope, which has the adverse effect of discounting HAND. This is bad!
- Distance weighting slope is logical. Need to watch out for scaling affects.
- Increasing HAND weight is no brainer.

**Comment by joewheaton** [comment]
I am happy with all these suggestions too. If they work, that's fine. 

I don't know if we need to keep TWI at all if we leave it in TauDEM. Let's decide after we see a few examples.

Thank you all for your efforts.

**Comment by jtgilbert** [comment]
Middle Bear test run:
https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/3ee25add-f67a-43ef-8711-8183d92f719a

**Comment by lauren-herbine** [comment]
Hi @jtgilbert , here are a couple of things I noticed from a quick pan around- are these to be expected?
https://vimeo.com/801791867/6c9e9afb21

**Comment by jtgilbert** [comment]
Hey @lauren-herbine thanks for putting eyes on it. You're exactly right it looks like it's an order of operations thing, the VB for Cub is extending up tribs, and the 0.995 channel cells outside that are where the trib channel was burned in so you get that valley inside valley effect. I think the road thing is the way that the terrain associated with the level path gets clipped, so it creates some kind of weird HAND rasters that become evident when it's reassembled into the final evidence. That is probably worth looking into. I'm running a test now to see if I can get the VBs to intrude less into their tributaries too, which should clean up some of the weirdness around Worm Creek.

**Comment by lauren-herbine** [comment]
Ok, sounds good! I'm curious to see how the HAND raster clipping issue goes- let me know if I can help with any of that.
