### ISSUE TITLE
Remove VB polygons that do not have a levelapth and also do not contain water bodies

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#713]
Valley bottoms are generated for levelpaths, by length in descending order, and then valley bottoms are generated for channel areas without levelpaths (ex. waterbodies). The riverscape VBs (ones with levelpaths) take precedence over no levelpath VBs, and the result is that some of the no levelpath VBs get leftover even though they don't contain a water body (because the water body in question exists completely inside a larger valley bottom), like this case:

<img width="484" alt="vb" src="https://user-images.githubusercontent.com/73311751/220478849-2503be42-7c6b-41b5-a208-6b52a446154a.PNG">

These are noisy and should be removed.

**Comment by jtgilbert** [comment]
https://github.com/Riverscapes/riverscapes-tools/commit/b47a4a280bf4fd3d812a55fd2f62605e958c8027
