### ISSUE TITLE
VB/Inactive thresholding not working on some level paths

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#714]
For some level paths (in most but not all cases it's where there's some sort of discontinuity in the level path) there's an active vb raster, but not an inactive raster. These end up not having a valley bottom polygon in the output.

![discontinuous_levelpaths](https://user-images.githubusercontent.com/21687931/221637390-671b2d0a-456a-46f4-a17c-473f0a48ad8d.png)

**Comment by jtgilbert** [comment]
@KellyMWhitehead I'll assign you on some of these VBET issues in case you can quickly think of right where to go for the fix since you're most familiar with the code. If you don't know off hand where the problem is feel free to reassign to me to dig in.

**Comment by jtgilbert** [comment]
Actually looks like this is caused by the zone raster not encompassing a whole level path at its creation.

![missingzone](https://user-images.githubusercontent.com/21687931/222463908-a90a4beb-740f-44a3-a000-c8a359283a6d.png)

**Comment by KellyMWhitehead** [comment]
A thought just occurred to me - maybe check the fcodes along the nhd line. We do a filter and that might be causing some sections to be excluded...

**Comment by jtgilbert** [comment]
@KellyMWhitehead ah yeah makes sense, I'll look at it.

**Comment by jtgilbert** [comment]
It looks like what's happening is where there is a gap in the channel area (in this case caused by a water body),

![chan_area_gap](https://user-images.githubusercontent.com/21687931/222469533-4bc9af14-d4f4-4aa3-a4f8-11dbabd09d01.png)

the resulting valley bottom raster has two pieces, with a separation between them.

![vbet_raster_gap](https://user-images.githubusercontent.com/21687931/222469727-c0f931f1-1e22-44e4-85cb-ca8748cbdf7a.png)

When that raster is used to generate the zones, only one of the pieces ends up retained.

![missed_from_zone](https://user-images.githubusercontent.com/21687931/222469816-215d210b-80db-4ecd-a1be-65052fba4c03.png)
