### ISSUE TITLE
Test likelihood functions for evidence raster transformations

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#715]
Use calibration data converted to binary valley/not valley to parameterize log-likelihood functions to use for transformations.

**Comment by jtgilbert** [comment]
continuous log-likelihood transform functions are implemented and working - will want to further calibrate with @shelbysawyer calibration data classed as binary (valley bottom, not valley bottom).

**Comment by joewheaton** [comment]
> Related to this, I want to revisit DA thresholds for different stream sizes.

I think you said you are using 25 and 250 square kilometers as breaks?
