### ISSUE TITLE
Update terminology in VBET layers

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#716]
To avoid problems with peer review and be more transparent, some terminology being used should be changed:
"normalized" should be changed to "transformed"
"likelihood" needs to specified as "relative likelihood"
"active" and "inactive" vb... more transparency on what this means/what drives it...

**Comment by shelbysawyer** [comment]
@jtgilbert Please let me know if there's anything I can help with.

**Comment by jtgilbert** [comment]
@shelbysawyer @lauren-herbine I've chatted briefly with @joewheaton and @MattReimer about this, and Scott as well. FYI, anything that was called 'normalized' is now 'transformed' to avoid the impression of it being a linear 0-1 transformation. When we display evidence I think we should specify 'RELATIVE likelihood' rather than 'likelihood' since it's not actually a probability. 

The ones I'm still not quite sure what to call are 'active' and 'inactive' layers. Those are loaded terms since they involve some kind of temporal aspect, and include hydrology which VBET does not include. Essentially we're trying to separate the topographically lowest points in the VB from the rest in order to provide a first order approximation that can be used for recovery potential, correct?

**Comment by shelbysawyer** [comment]
- Agree that "transformed" makes more sense than "normalized" for evidence rasters
- Agree that "relative likelihood" is fine and helps convey to users that it's not a probability
- In November, @joewheaton and I discussed changing what is currently "Estimated Active Channel, Estimated Active Floodplain, Estimated Inactive Floodplain" to "Estimated Active Valley Bottom, Estimated Inactive Valley Bottom". Personally, I think these layers names work well. Yes, they are rough estimations drawn from which areas have the highest likelihood values based on VBET's lines of evidence. I think having "estimated" in the layer title conveys this and calibration for specifying where the line is drawn between estimated active/inactive should be relatively easy. I think these layers convey useful information to users.

**Comment by joewheaton** [comment]
@jtgilbert I think you have done most of these changes in renaming filenames? Maybe work with @shelbysawyer and make a new ticket for anything outstanding, as well as the associated updates to business logic and reports. Then close this issue.
