### ISSUE TITLE
Getting Thiessen Polygons Working

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#72]
@MattReimer I have stubbed out the new version of the Riparian Vegetation Departure (RVD). It's on a branch called `rvd`. This involved moving more generic code from sqlBRAT and moving up into RSCommons. e.g. database.py, report.py. I was careful and ran all our existing tools on a single HUC as a regression test.

RVD uses Thiessen polygons. I have copied over the Thiessen code from the old [rivertools](https://github.com/RBTDevelopmentGroup/rivertools) repo and put it in RSCommons. But I can't get it to work. Something to do with `scipy.spatial`. Intellisense seems know about this module, but perhaps it needs separate installation?

Anyway, can you please enhance RVD so that it produces a ShapeFile of Thiessen polygons around the segmented reach polylines. The goal is a ShapeFile of one polygon per segmented reach polyline. The reach polylines are stored in the `segmented.shp` intermediate ShapeFile and uniquely identified by `ReachID`. 

I'm confident that if we can explode the reach lines to vertex points and then produce a Thiessen polygon for each point. The question then becomes how do we union together the polygons for all points with the same `ReachID`? See the bottom figure [here](http://rcat.riverscapes.xyz/Documentation/Version_1.0/RVD) for a cartoon of what this should look like (after the subsequent step of clipping the Thiessen polygons with the valley bottom).

**Comment by MattReimer** [comment]
I'm going to close this off. Thiessen polygon library has been merged but nothing in the context of RVD has been done. We can tackle that as a separate issue or part of RVD
