### ISSUE TITLE
VBET 0.8.9 mainstems are still "absorbing" whole tributaries into their valley bottoms

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#720]
**Project:** [0502000405](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/e1a9073f-afda-495d-9dae-47fb00535e5b)
**Problem:** Mainstem valley bottoms are absorbing the valley bottoms of whole tributaries. This not only means that the valley bottom extent and ownership are incorrect, but also means that the tributary (in this case, Horseshoe Run) does not get a centerline and therefore no metrics can be calculated for it.

This problem is a recurring and has been documented many times (ex. #696). @jtgilbert you [said previously](https://github.com/Riverscapes/riverscapes-tools/issues/696#issuecomment-1434906392) that this issue has been solved in XML V2. I don't know the difference between V1 and V2-- is this problem occurring in 0.8.9 runs to be expected or not?

**Comment by shelbysawyer** [comment]
<img width="466" alt="issue720" src="https://user-images.githubusercontent.com/73311751/225204850-1661e1b9-06ac-4798-901c-0b3426552559.PNG">

**Comment by jtgilbert** [comment]
@shelbysawyer sorry should have explained this to you guys. This is solved it just won't be implemented until the runs are done in the new warehouse using V2 xml. FYI @lauren-herbine

**Comment by joewheaton** [comment]
Thanks for pointing to this one @shelbysawyer! Got it.
