### ISSUE TITLE
Migrate Automation scripts for new Warehouse

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#722]
On the `new_project_xml` branch we need new Automation shell scripts.

Some changes:

- Tags now only needs the output, not the input.
- Add new checks for environment variables that you add

Here are the ones that are already done. You can use them as a pattern:

```
FargateRSContext.sh
FargateVBET.sh
```

and here are the files that need changing:

```
FargateAllTools.sh
FargateBRAT.sh
FargateChannel.sh
FargateConfinement.sh
FargateGNAT.sh
FargateRSContextChannelAreaTauDEM.sh
FargateRVD.sh
FargateTauDEM.sh
```

**Comment by KellyMWhitehead** [comment]
- [ ] FargateAllTools.sh
- [ ] FargateBRAT.sh
- [ ] FargateChannel.sh
- [ ] FargateConfinement.sh
- [ ] FargateGNAT.sh
- [ ] FargateRSContextChannelAreaTauDEM.sh
- [ ] FargateRVD.sh
- [ ] FargateTauDEM.sh

**Comment by KellyMWhitehead** [comment]
Scripts have been migrated, need to be tested.

**Comment by MattReimer** [comment]
good enough. Thanks for doing that.
