### ISSUE TITLE
Test HUC 10 vs HUC 8 VBET for documentation

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#725]
I'm queuing this task up for myself to do once we have the [0.9.0](https://github.com/Riverscapes/riverscapes-tools/issues/724) runs.

@jtgilbert Would you be able to run the projects needed for my to test this on 3 HUC8s? Maybe 0502004 (Cheat), 16010202 (Middle Bear), and one other one that we've had issues with? If that sounds doable, I can make a list of the necessary HUC8 and HUC10 codes.

**Comment by joewheaton** [comment]
@shelbysawyer I like using the Middle Bear, and the Cheat. Maybe also choose one from the mainstem Ohio. I am pretty sure the answer will be no, they are slightly different on the shared levelpaths. And, we can live with that. But we will need to document it and understand it.

**Comment by jtgilbert** [comment]
@shelbysawyer for now, there's a 0.9.0 run for Middle Bear and Cheat that can be compared with the couple of HUC10s also run within each of those.

**Comment by philipbaileynar** [comment]
Looks like @jtgilbert solved this back in March 2023. Closing.
