### ISSUE TITLE
Cybercastor `rstools_add_job.py` rework

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#726]
## Background:

Cybercastor has a very simple GraphQL API separate from everything else:

https://github.com/NorthArrowResearch/cybercastor/blob/master/packages/common/src/schema.graphql.ts

In the past we have used a script in the `python` folder of the `northarrowresearch/cybercastor` repo to generate the inputs needed toi call `addJob`

This script took an input that had to be created from scratch that looked something like this:

```json
{
  "name": "Running 0.8.5",
  "description": "TEST",
  "taskScriptId": "vbet",
  "meta": {},
  "env": {
    "PROGRAM": "AnabranchDEV",
    "CHANNEL_TAGS": "Cybercastor,TWI_Fix",
    "TAUDEM_TAGS": "Cybercastor,TWI_Fix",
    "RSCONTEXT_TAGS": "Cybercastor,TWI_Fix",
    "VBET_TAGS": "DEC14",
    "GIT_REF": "VBET_GNAT"
  },
  "resources": {
    "cpu": 4096,
    "memory": 30720,
    "disk": 80
  },
  "hucs": [
    "05010003",
    "0501000301",
    "05020004",
    "0502000405",
    "05040003",
  ]
}
```

This JSON structure is more-or-less arbitrary and has nothing really to do with Cybercastor itself.

The add [`rstools_add_job.py`](https://github.com/NorthArrowResearch/cybercastor/blob/master/python/scripts/rstools_add_job.py) has other capabilities too like:

1. Download logs from any running, completed or failed jobs.
2. Stop tasks that are currently running
3. Restart failed tasks
4. etc.

## The problem

In the new system a simple huc isn't enough to use per task. 

## What we need. 

1. We need a second QueryMonster. Currently we're only interacting with the Cybercastor API but the new script is going to need to make Riverscapes API calls as well to fetch project ids.
2. The script needs to send correct environment variables to start the task [for each script that we have](https://github.com/Riverscapes/riverscapes-tools/tree/new_project_xml/scripts/automation)

So in the case of RSContext the [environment variables we need to send in are here](https://github.com/Riverscapes/riverscapes-tools/blob/new_project_xml/scripts/automation/FargateRSContext.sh#L10-L16):

```bash
(: "${HUC?}")
(: "${TAGS?}")
(: "${VISIBILITY?}")
(: "${APIURL?}")
# These are machine credentials for the API which will allow the CLI to delegate uploading to either a specific user or an org
(: "${MACHINE_CLIENT?}")
(: "${MACHINE_SECRET?}")
```

The only one that is specific to the task is the HUC. The rest can be environment variables on the job object that all tasks can share. 

## Other notes

* DO NOT WORK in the cybercastor repo. All of this python has been moved into [`riverscapes-tools` on the `new_project_xml` branch under the folder `lib/cybercastor`](https://github.com/Riverscapes/riverscapes-tools/tree/new_project_xml/lib/cybercastor). Also there is a new workspace called `CYBERCASTOR.code-workspace`.
* I haven't swapped the Auth over to Auth0 yet on cybercastor so that means using your old Cognito username and password in your `.env` file. We'll be using Cognito to log into Cybercastor but we'll need to log into Auth0 to get at RiverscapesAPI. It's unfortunate but it's what it is.
* I have a sketch working for the new QueryMonster 
* You'll need to pip install `boto3` and `inquirer` if you haven't already.

Update: 

Forgot to mention the list of curently available engines and task definitions is always here

https://cybercastor.northarrowresearch.com/engines/manifest.json

* `rstools` is the old warehouse engine
* `riverscapesTools` is the new warehouse engine

**Comment by philipbaileynar** [comment]
My understanding:

1. Take a list of HUC codes (HUC10, but could be other scales too) and tool types
2. Figure out what upstream models are needed to support the requested runs
3. Search the warehouse API for the presence of the required upstream runs
4. If there are multiples of any particular model, prompt the user to choose which one to use
5. If there are no models for a particular then warn the user
6. collate all the information together and send it to the cybercastor API

Questions

1. Can/should. I use `inquirer` for this? Is a UI worth it?
2. What is the typical HUC list size? 1, 10, 50, 100? (this informs how I handle errors. Don't to get 75 prompts into a process only for it to fail)
3. When one or problems occur (i.e. one HUC is missing one upstream project) should the whole thing abort? Or still proceed with the partial run?
4. If multiple upstream projects exist, what's the logical order to present to the user model version/date run or the reverse of that?

**Comment by MattReimer** [comment]
> My understanding:

100% correct

> Questions
> 1. Can/should. I use `inquirer` for this? Is a UI worth it?

I leave that up to you. the current `rstools_add_job.py` uses inquirer to pretty great effect and it's a lot cheaper to develop than a UI. I don't want to limit your choices at all though so if you think a UI would work then go for it.

> 2. What is the typical HUC list size? 1, 10, 50, 100? (this informs how I handle errors. Don't to get 75 prompts into a process only for it to fail)

It varies. We've run jobs with as many as 400 tasks before. That may not be possible going forward. It really depends on how big a batch you want. Less jobs per batch = more work for the tech running it. There really aren't limits here in terms of size. 

> 3. When one or problems occur (i.e. one HUC is missing one upstream project) should the whole thing abort? Or still proceed with the partial run?

I think we should make it so that you must have the prerequisites for every task in a job, otherwise we get into partial jobs or splitting jobs with the same name into multiples with different tasks in them and that's hard to manage and understand. 

We make the rules here though so none of this is a hard rule. We're aiming to make things easier for kelly, jordan, ourselves and anyone else who might need to use it.

> 4. If multiple upstream projects exist, what's the logical order to present to the user model version/date run or the reverse of that?

we could sort by model version first and then by date run. I think in most existing cases there's rarely a choice of more than 3 items so it's not going to be a huge list.

**Comment by MattReimer** [comment]
This work is complete. Thanks @philipbaileynar for the great API lookup library.

**Comment by joewheaton** [comment]
This is powerful. Do we have a ticket somewhere extracting all this awesome cybercastor tidbits to documentation (I know a low priority, but I don't want to lose things like this)?

**Comment by MattReimer** [comment]
> This is powerful. Do we have a ticket somewhere extracting all this awesome cybercastor tidbits to documentation (I know a low priority, but I don't want to lose things like this)?

No. This is all just wrapped up in how the API works. The API iteself will need some beefy documentation with python examples. Important, true but still lower priority than almost everything else I'm working on right now. 

I filed a ticket to track that.
https://github.com/Riverscapes/rs-web-monorepo/issues/332
