### ISSUE TITLE
Incorrect Proportion of Active Floodplain values

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#728]
- Bug found while working in [this](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/ab986f2e-b508-4452-8e6a-e53f7457f339) VBET 0.9.0 project
- [Here](https://youtu.be/vXDS7fMPDm0) is the video link explaining the problem

**Comment by jtgilbert** [comment]
@shelbysawyer have you looked at some other projects to see if this pops up regularly. With this specific project there's a chance I hadn't aligned IGO spacing and window sizes yet, which could have caused some problems. But it's also very possible it's a systematic problem.

**Comment by shelbysawyer** [comment]
I haven't-- in fact, it wasn't even doing this consistently across the watershed. But I think it's worth looking into. I can spend some time trying to identify if this is or isn't happening in the newest projects. This project was run 3/20.

**Comment by shelbysawyer** [comment]
@jtgilbert I looked through some of the new projects with the VbetCalibration tag and I'm not seeing this. Will reopen if I notice it again.
