### ISSUE TITLE
Extract evidence raster values for observation points from the newest VBET runs into csv

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#733]
We originally specified the VBET transform functions based on summary statistics of the 5,000 observations in the vbetobservations database. We are now moving into the calibration/validation and verification phase for production grade VBET 3.0 and need to pull VBET evidence raster values again for this purpose. The csv we need will be similar to the csv that Kelly provided last year for transform function specification: [vbet_evidence.csv](https://github.com/Riverscapes/riverscapes-tools/files/11159736/vbet_evidence.csv). @KellyMWhitehead, do you still have the script from the last time you pulled these values for a csv?

Observations will be divided into a random 90/10 split. 90% will be used to train the transform functions based on the pulled evidence values (HAND and slope) and drainage size (small, medium, large). HUC 10 VBET projects where the other 10% of points exist will then be run with the updated transform functions. We will iterate on the transform functions as needed to validate.

Feel free to check out the fields in the csv that @KellyMWhitehead provided for the last round, but here are the basics that we need:
- FID
- Observation ID
- HUC 10
- Updated date
- Valley Bottom Classification (either ID **with** lookup table **or** the name)
- Drainage Area
- HAND
- Slope

If possible, it would be helpful to also know if the point falls in VB with perennial, intermittent, or ephemeral flow.

**Notes for this pull of values:**
- HAND is now being calculated by levelpath and exists as a composite raster, so we expect the values to be different
- Slope values should be the same
- TWI is no longer a line of evidence
- Instead of stream order, drainage area thresholds (25 and 250) are now driving the split between small, medium, and large catchments
- Instead of using the original observation categories (ex. "estimated inactive floodplain"), we are now using a simple "in or out of VB" logic. I can add this field to the CSV (ex. 0 for in, 1 for out) once the values are pulled, following this scheme:

**In**
Active Channel Area
Fan - Active Channel
Active Floodplain
Fan - Active Floodplain
Inactive Floodplain
Fan - Inactive Floodplain

**Out**
Probably Not Valley Bottom
Definitely Not Valley Bottom
Terrace

**Comment by KellyMWhitehead** [comment]
@jtgilbert 

Here is the [script](https://github.com/Riverscapes/riverscapes-tools/blob/6e50c0f0d343fc7f541c25f5f78f65f53af28274/packages/vbet/scripts/vbet_evidence.py) I use to pull the observation evidence.

I think the first step was to copy the postgres feature class to a local geopackage. Other than that its pretty basic (feel free to modify or update as needed).
