### ISSUE TITLE
Remove legacy riverscapes developers

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#74]
@joewheaton can we purge legacy developers from the riverscapes GitHub organization?

I described to you recently that the industry standard practice for collaboration within GitHub is to keep the developer teams small. External contributors can fork any riverscapes repo, make changes to their own forked copy and contribute their changes back to the official riverscapes repos using pull requests. Contributors do **not** need to be members of the riverscapes development team to do this. Any GitHub user can do this.

Please approve the cleanup of the riverscapes organization GitHub teams and removal of anyone who is a member of Anabranch, USU ET AL or NAR. People like Matt Nahorniak and Pete McHugh. 

GitHub has lots of resources (documentation and videos) outlining the workflow that I describe above. We can link to these materials from "how-to" pages on the main [riverscapes.xyz](http://riverscapes.xyz) web site and also the [riverscapes GitHub organization page](https://github.com/Riverscapes).

Why do to this effort?

1. It's the industry best practice.
1. The effort to maintain permissions grows exponentially as we continually add repos.
1. We now have several repos serving public facing services. We are trying to keep the master branches locked down to only the build master (@MattReimer) as a way of reducing the risk of breaking production systems. But this is fiddly and complicated when there are dozens of members of the organization.
1. Day-to-day activities like assigning issues will be faster when the dropdown lists don't also contain my Mum's second cousin twice removed!!!!!!

**Comment by MattReimer** [comment]
We shouldn't be adding individual users to repos at all. That's what Teams are for

https://github.com/orgs/Riverscapes/teams

People should be added to teams and then teams should be given access to repos.

**Comment by joewheaton** [comment]
Yes please go do it! If any of them want back in, we can always add them later.

**Comment by philipbaileynar** [comment]
Done!
