### ISSUE TITLE
Cleaning National Ownership Layer

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#741]
@Jdgilby can you please help us with a data processing task.

The national ownership layer that we incorporate into Riverscapes Context projects has two problems:

- Several hundred of the geometries are invalid (self intersecting polygons etc)
- Many of the polygons are vast! (one monster feature covers most of the Eastern US).

Can you please download this layer from the [national project in the new warehouse](https://warehouse.riverscapes.net/p/ca03b7b0-7c70-43f2-bf22-85732653704a/overview) and clean it for us please? Two explicit tasks:

1. Fix any invalid geometries (I'm pretty sure that in the past I tried running ArcGIS `RepairGeometry` geoprocessing tool on this layer and that did NOT fix the self intersecting geometries.)
2. Intersect the repaired ownership layer with the national counties layer (also in the national project). This will ensure that no polygon is larger than a US county. This should speed up any tools that use the layer. It will introduce a few redundant feature boundaries, but that's a minor detail we can live with.

I don't mind how you tackle this request. I hope that you can use some kind of automated geometry repair features and that you don't have to go feature-by-feature!

Notes:

- I ran this request by @joewheaton and he was supportive of you helping us with this task.
- Please reach out to @jtgilbert if you need help getting the layers etc. Jordan worked with these data recently.
- I am available if you have any questions or need help with the new warehouse.

**Comment by joewheaton** [comment]
@Jdgilby you can bill this to So. Oregon Resilience Bond.

**Comment by Jdgilby** [comment]
Hey @philipbaileynar I think this was a simple fix. Maybe Qs geometry repair is better, but I checked the datasets geometry and found 3000+ self-ring intersections. Ran it through fix geometry and checked again and it says they're all gone. 

How do you want me to package up the new shapefile/get it back into the national dataset project on the warehouse?

**Comment by Jdgilby** [comment]
And as for the intersect goes, do you need county attributes appended to ownership or does the call for ownership data just pull an intersect from the HUC8 boundary to decide which polygons are pulled in?

**Comment by philipbaileynar** [comment]
Thanks for the fast response @Jdgilby 

We do NOT need the county attributes on the ownership. The only reason to perform the intersection was to subdivide the very big ownership polygons into smaller, more performant features. Counties just happened to be a convenient size.

Please give the finished feature class to @jtgilbert. I believe he knows how to upload it? Shout Jordan if that's not the case and @MattReimer can step in and help.

**Comment by Jdgilby** [comment]
Sounds good, I'll get it moving along.
