### ISSUE TITLE
RSC Including Too Many Watershed Boundaries

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#742]
The following code in RSC tries to only include the watershed boundaries for larger scales in which the target project exists.

https://github.com/Riverscapes/riverscapes-tools/blob/84d2e2f250e8549368973595b28ddca8260a9308/lib/commons/rscommons/clean_nhd_data.py#L29-L36

It does this by using an SQL wildcard (percent sign). This isn't working and it is including too many polygons.

In the screenshot below you can see that the target project is HUC 0504000307. This should only bring in 8 digit watershed boundaries that match `05040003%` but it is matching 05040002, 05040001, 05040006 etc.

Perhaps the code has an "off by one" error and is accidentally stripping the HUC code by two many characters. So when it's trying to match 8 digit HUCs it's actually using a 7 digit search pattern?

<img width="1474" alt="Screenshot 2023-04-12 at 11 26 18 AM" src="https://user-images.githubusercontent.com/8645379/231550787-658c83f9-4307-4d06-b97e-7b55fb0e2b7c.png">

**Comment by jtgilbert** [comment]
5816be78dc7254c2427fa57fe9cad95194a70c3a
