### ISSUE TITLE
RS Context Review - JW

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#743]
Assigned Hucs

- [x] REVIEW: [501000301](https://warehouse.riverscapes.net/p/fc212b46-4ab1-401d-a6f7-71681883a956/)

Review Tasks
- [x] Visit the project on the new Data Exchange
    - [x] Check each tab of the project view in the Data Exchange
    - [x] Inspect project metadata for irregularities
    - [x] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [x] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [x] Map extents are a known issue. Please ignore.
    - [x] Check for missing layers
    - [x] Check for symbology issues
    - [x] Check for layer naming problems
    - [x] Check for tiling irregularities 
    - [x] Miscellaneous errors
- [x] Download the Project into QRave
    - [x] Check for missing layers
    - [x] Check for symbology issues
    - [x] Check for layer naming problems

- [x]  REVIEW: [701010102](https://warehouse.riverscapes.net/p/50bc33c0-671a-4f93-b9d9-a6dc8211a610/)
- [x] REVIEW: [1005000403](https://warehouse.riverscapes.net/p/5e9b00c9-ea35-49e6-9c93-1e0179ea023f/)
- [x] REVIEW: [1601020203](https://warehouse.riverscapes.net/p/3a8993d5-c129-488a-8236-200400effbd8/)
- [x] REVIEW: [1706010302](https://warehouse.riverscapes.net/p/04f07fb9-c4dd-4ec5-8984-9958672c38fc/)

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.

**Comment by joewheaton** [comment]
Review of RS Context [501000301](https://warehouse.riverscapes.net/p/fc212b46-4ab1-401d-a6f7-71681883a956/):
https://youtu.be/Ze60sYAgu9s

[![Video Link](http://img.youtube.com/vi/Ze60sYAgu9s/0.jpg)](http://www.youtube.com/watch?v=Ze60sYAgu9s "")

Overall, okay, this is working overall, which should be celebrated. However, in the weeds, I found a lot of problems. There are issues with the Warehouse UI and WebRV UI that we should work through separately, but you'll hear my frustration in there with them and suggestions. Many of those frustrations have been voiced previously and, in fairness, are features we have not yet gotten to. So lets just focus on the stuff specific to RS_Context.  

First off, I cover a bunch of  Curation things others will see already in https://github.com/Riverscapes/RiverscapesXML/issues/545.  So if you find these things, don't waste your time:
![image](https://user-images.githubusercontent.com/9723905/231716887-d9fe309b-abc4-4f54-a3b3-0cc340496068.png)

If you want to raise a more specific point for a layer mentioned, do so, but do so by creating an issue out of the task in that list.

**Comment by joewheaton** [comment]
Here are the problems I cover in video:

- https://github.com/Riverscapes/rs-web-monorepo/issues/336
- https://github.com/Riverscapes/rs-web-monorepo/issues/346
- https://github.com/Riverscapes/rs-web-monorepo/issues/349
- https://github.com/Riverscapes/rs-web-monorepo/issues/350
- https://github.com/Riverscapes/rs-web-monorepo/issues/351
- https://github.com/Riverscapes/rs-web-monorepo/issues/352


RS_Context Specific and not already covered for curation:
-  https://github.com/Riverscapes/rs-web-monorepo/issues/353
- https://github.com/Riverscapes/riverscapes-tools/issues/752 
-

**Comment by MattReimer** [comment]
This is fantastic @joewheaton. Easy to follow and fantastic to get light on this stuff.
