### ISSUE TITLE
RS Context Review - JG

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#744]
Assigned Hucs

[401020110](https://warehouse.riverscapes.net/p/c21c394e-1c1a-477f-860c-c7f455bd28dd/)
[902010101](https://warehouse.riverscapes.net/p/2fe37bab-fd6e-443c-a7d1-3fd2e174b670/)
[1003020102](https://warehouse.riverscapes.net/p/90182879-4966-4277-a649-fc8bac54f12f/)
[1604010102](https://warehouse.riverscapes.net/p/0ebd1d15-c1c9-4e37-921b-0d5a7e1c7de0/)
[1803000202](https://warehouse.riverscapes.net/p/fed6aca4-b003-4291-8fec-a3414cbee986/)

Review Tasks
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [ ] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.

**Comment by joewheaton** [comment]
@jtgilbert, please note:

> I cover a bunch of  Curation things others will see already in https://github.com/Riverscapes/RiverscapesXML/issues/545.  So if you find these things, don't waste your time:
> ![image](https://user-images.githubusercontent.com/9723905/231716887-d9fe309b-abc4-4f54-a3b3-0cc340496068.png)
> 
> If you want to raise a more specific point for a layer mentioned, do so, but do so by creating an issue out of the task in that list.
From #743
