### ISSUE TITLE
RS Context Review - KW

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#745]
Assigned Hucs

[504000303](https://warehouse.riverscapes.net/p/3657e68d-f86e-467c-ad0f-0535e634f20d/)
[806020103](https://warehouse.riverscapes.net/p/51cd36df-d699-4104-8a77-c46a863a9609/)
[1011020505](https://warehouse.riverscapes.net/p/1b42e6d4-c035-45bf-8633-1e005c31e0a8/)
[1406000403](https://warehouse.riverscapes.net/p/dba102af-3df4-4fc2-9d19-44ff42c25b8c/)
[1701020504](https://warehouse.riverscapes.net/p/8de38f82-123f-43f6-a3b5-0578b32cd4e9/)

Review Tasks
- [x] Visit the project on the new Data Exchange
    - [x] Check each tab of the project view in the Data Exchange
    - [x] Inspect project metadata for irregularities
    - [x] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [x] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.

**Comment by joewheaton** [comment]
@KellyMWhitehead , please note:

> I cover a bunch of  Curation things others will see already in https://github.com/Riverscapes/RiverscapesXML/issues/545.  So if you find these things, don't waste your time:
> ![image](https://user-images.githubusercontent.com/9723905/231716887-d9fe309b-abc4-4f54-a3b3-0cc340496068.png)
> 
> If you want to raise a more specific point for a layer mentioned, do so, but do so by creating an issue out of the task in that list.
From #743
