### ISSUE TITLE
RS Context Review - LH

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#746]
Assigned Hucs

[514020102](https://warehouse.riverscapes.net/p/be9dfa93-b2ac-40a4-9787-c6c8c250c7c6/)
[808010206](https://warehouse.riverscapes.net/p/c579ff2c-88de-4ca0-8f61-ba4d09460159/)
[1019001004](https://warehouse.riverscapes.net/p/488cf281-d96c-4d81-acb9-0fef5edfd1c6/)
[1104000503](https://warehouse.riverscapes.net/p/efa7f8d2-66f2-419c-bf68-3a757a05d7e7/)
[1701010302](https://warehouse.riverscapes.net/p/8a7b03e5-7896-45fb-928f-1402f05fc557/)

Review Tasks
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [ ] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.

**Comment by joewheaton** [comment]
@lauren-herbine  before you get too far please note:

> I cover a bunch of  Curation things others will see already in https://github.com/Riverscapes/RiverscapesXML/issues/545.  So if you find these things, don't waste your time:
> ![image](https://user-images.githubusercontent.com/9723905/231716887-d9fe309b-abc4-4f54-a3b3-0cc340496068.png)
> 
> If you want to raise a more specific point for a layer mentioned, do so, but do so by creating an issue out of the task in that list.
From #743 
See also issues that are being logged by others
