### ISSUE TITLE
RS Context Review - MR

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#747]
Assigned Hucs

[502000403](https://warehouse.riverscapes.net/p/0962270c-60f3-4128-a1f5-42dd0a0f4f05/)
[708010504](https://warehouse.riverscapes.net/p/18eec6b6-9bc8-4bcd-a310-f112c5844abb/)
[1009010210](https://warehouse.riverscapes.net/p/17b2bc7c-3e79-4b7c-a2f4-4e51777ef56c/)
[1605030202](https://warehouse.riverscapes.net/p/7b874f23-3b7b-4b20-9810-1287aa6ed4e0/)
[1704020205](https://warehouse.riverscapes.net/p/51ca1fd3-4158-4944-ac4f-9d8e5dee2746/)

Review Tasks
- [x] Visit the project on the new Data Exchange
    - [x] Check each tab of the project view in the Data Exchange
    - [x] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [x] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [x] Map extents are a known issue. Please ignore.
    - [x] Check for missing layers
    - [x] Check for symbology issues
    - [x] Check for layer naming problems
    - [x] Check for tiling irregularities 
    - [x] Miscellaneous errors
- [x] Download the Project into QRave
    - [x] Check for missing layers
    - [x] Check for symbology issues
    - [x] Check for layer naming problems

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.

**Comment by MattReimer** [comment]
Filed an issue:
https://github.com/Riverscapes/rs-web-monorepo/issues/342

### Misc Problems

- Road layer says its tiled but is missing in Web (present on QRave)
- Too many huc8s showing for a huc10 project
- Huc6 and huc4 are the same layer

#### Raster Layers that need symbology:

- Succession classes
- Vegetation Departure
- Vegetation Condition
- FCCS
- New landfire layers

#### Vector layers that need Symbolofgy:

- State Boundaries
- County BOundaries
- Geology
- Ecoregions
