### ISSUE TITLE
RS Context Review - PB

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#748]
Assigned Hucs

[601020201](https://warehouse.riverscapes.net/p/000f62f2-b6ea-4631-91b4-e005c9ce03df/)
[705000203](https://warehouse.riverscapes.net/p/1977629d-231f-4a9f-9c5f-bcd8829b179a/)
[1002000805](https://warehouse.riverscapes.net/p/88b51f0a-1578-4c23-8478-aed098419a0a/)
[1604010302](https://warehouse.riverscapes.net/p/bb1faa12-ac30-4720-be9a-ac4b6ab2c624/)
[1709000606](https://warehouse.riverscapes.net/p/3be88eb7-ce2e-4be3-a27b-82da5a394860/)

Review Tasks
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [ ] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.

**Comment by philipbaileynar** [comment]
- Canals has metadata for transportation layer #754
 - Roads appear in QRAVE but not in WebRave
 - Too many HUC8 polygons #753 
 - Pipes and Ditches missing cartography
 - Zoom to extent of layers doesn't work
 - Level 1 Ecoregions don't appear in WebRAVE (but do in QRAVE)
 -

**Comment by joewheaton** [comment]
@philipbaileynar I also noticed the following
> * Roads appear in QRAVE but not in WebRave
> * Too many HUC8 polygons [Too many HUC8s showing on a HUC10 project #753](https://github.com/Riverscapes/riverscapes-tools/issues/753)
> * Pipes and Ditches missing cartography
> * Zoom to extent of layers doesn't work
> * Level 1 Ecoregions don't appear in WebRAVE (but do in QRAVE)

@philipbaileynar before you get too far (or we waste others time and loose credibility logging same issues), please note:

> I cover a bunch of  Curation things others will see already in https://github.com/Riverscapes/RiverscapesXML/issues/545.  So if you find these things, don't waste your time:
> ![image](https://user-images.githubusercontent.com/9723905/231716887-d9fe309b-abc4-4f54-a3b3-0cc340496068.png)
> 
> If you want to raise a more specific point for a layer mentioned, do so, but do so by creating an issue out of the task in that list.
From #743

**Comment by MattReimer** [comment]
this is stale. Closing,
