### ISSUE TITLE
RS Context Review - SS

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#749]
Assigned Hucs

[501000306](https://warehouse.riverscapes.net/p/782b2327-73a7-4f9b-823e-17e00938b8bd/)
[801010002](https://warehouse.riverscapes.net/p/c0464c94-313e-4686-8bb0-021eefee6512/)
[1006000606](https://warehouse.riverscapes.net/p/960942d9-e3df-4df3-b72e-65915511b293/)
[1111010308](https://warehouse.riverscapes.net/p/b8472b67-9936-4fd8-9dc2-2069654ba5b7/)
[1707030107](https://warehouse.riverscapes.net/p/bce75f8d-d49b-40a6-be7c-506505e7f26e/)

Review Tasks
- [x] Visit the project on the new Data Exchange
    - [x] Check each tab of the project view in the Data Exchange
    - [x] #758
    - [x] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [x] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [x] Map extents are a known issue. Please ignore.
    - [x] Check for missing layers
    - [x] Check for symbology issues
    - [x] Check for layer naming problems
    - [x] Check for tiling irregularities 
    - [x] Miscellaneous errors
- [x] Download the Project into QRave
    - [x] Check for missing layers
    - [x] Check for symbology issues
    - [x] Check for layer naming problems

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.

**Comment by shelbysawyer** [comment]
@KellyMWhitehead @philipbaileynar I'm having issues getting to the projects-- I keep getting stuck in this weird sign in loop where it prompts me to sign in to see the projects, but then doesn't show me a sign in window. [I made a quick (1 minute) video](https://youtu.be/E6bTSONSLU8) to show what I see on my end. I tried to view the projects in a different browser and it was still doing that.

**Comment by philipbaileynar** [comment]
This is a cookie problem. Which browser are you using?

Make sure that you disable third party cookies for this site (warehouse.rivrerscapes.net) and then try again. Please report back.

I have logged the issue on the [warehouse repo](https://github.com/Riverscapes/rs-web-monorepo/issues/344).

**Comment by shelbysawyer** [comment]
I'm using Chrome, but it also happened using Microsoft Edge.

I just went and double-checked-- all third party cookies are blocked in Chrome already.

**Comment by philipbaileynar** [comment]
I'm sorry... tired... please enable third party cookies just for this site.

**Comment by shelbysawyer** [comment]
Et voila! Success. Thanks!

**Comment by joewheaton** [comment]
@shelbysawyer before you get too far, please note:

> I cover a bunch of  Curation things others will see already in https://github.com/Riverscapes/RiverscapesXML/issues/545.  So if you find these things, don't waste your time:
> ![image](https://user-images.githubusercontent.com/9723905/231716887-d9fe309b-abc4-4f54-a3b3-0cc340496068.png)
> 
> If you want to raise a more specific point for a layer mentioned, do so, but do so by creating an issue out of the task in that list.
From #743

**Comment by shelbysawyer** [comment]
-- in progress --

- #758
- [River polygons distorted at project-level zoom in WebRV #564](https://github.com/Riverscapes/RiverscapesXML/issues/564)
-  [Only parts of 2-, 4-, and 6-Digit HUC display in WebRV #565](https://github.com/Riverscapes/RiverscapesXML/issues/565)
- [Unnecessary Legend Items in Region - 2-Digit HUC legend in WebRV #566](https://github.com/Riverscapes/RiverscapesXML/issues/566)
