### ISSUE TITLE
Clipping Ownership and Geology to HUC boundary in RSC

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#751]
Once the revised ownership layer is in the national project  (per #741) can you please implement clipping it to the HUC boundary within RSC. 

I believe that the same block of code is used to import several different vector feature classes. I suspect that it uses a `SpatialAttributeFilter` to select all features in the source layer that "touch" the target HUC polygon. I think that you can leave this `SpatialAttributeFilter` in place and simply add a new `clip_to_extent` boolean parameter to this function. When true this will perform the additional step of clipping the selected feature to the HUC boundary. When false, the entire feature will get copied to the output, unclipped (same behaviour as before). We will use this unclipped approach for counties and states.

Please implement clipping on the geology layer as well.

Perhaps review all uses of this "copy vector layer" function to see if there are other uses that we have overlooked.

**Comment by jtgilbert** [comment]
I was just looking through this and noticed that the code that deals with ecoregions has it's own function, but is essentially exactly the same as copy vector layer so I'll get rid of that redundancy as well.

**Comment by philipbaileynar** [comment]
I don't know what the code does with attributes, but the ecoregion attributes are important to subsequent tools.

**Comment by jtgilbert** [comment]
Another Q. Right now we arbitrarily buffer the HUC by 10 km, which is probably overkill for HUC10s. Should we reduce to 1km..?

**Comment by philipbaileynar** [comment]
I like 1km for HUC10s. Yes please.

FWIW I believe that the 10km buffer had something to do with BRAT's "distance from anthropogenic" analysis. Maybe...

**Comment by jtgilbert** [comment]
3265100ffc23e6068f7238ce7b82a90722d631c0

**Comment by philipbaileynar** [comment]
Wow that was surprisingly quick. Did it go well? Does it speed up processing ownership in RSC? Does that county polygon intersection seem to be doing the job?

**Comment by jtgilbert** [comment]
Yes to all!

**Comment by joewheaton** [comment]
Are you guys going to re-run the RS_Contexts that we're supposed to be reviewing, or is there one that has been queued up with this new fixes. Exciting...
