### ISSUE TITLE
Too many HUC8s showing on a HUC10 project

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#753]
<img width="689" alt="Screenshot 2023-04-12 at 3 36 03 PM" src="https://user-images.githubusercontent.com/1063391/231601185-dc45e363-1f67-4289-a55c-75f5b5a89705.png">

We seem to be overselecting huc8s for a huc10 project.  The other layers seem to be fine.

**Comment by jtgilbert** [comment]
already solved here https://github.com/Riverscapes/riverscapes-tools/issues/742

**Comment by joewheaton** [comment]
Sadly, this fix is not reflect in #743 Review RS_Context HUCs.

**Comment by jtgilbert** [comment]
@joewheaton fyi I closed all of the things I fixed after people's reviews. I ran tests to make sure the fixes worked but we haven't rerun the HUCs so that's why they're not showing up on the projects in the warehouse yet.
