### ISSUE TITLE
Canals layer getting transportation metadata

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#754]
Witnessed in several RSC projects. Here's [an example.](https://warehouse.riverscapes.net/rv/3be88eb7-ce2e-4be3-a27b-82da5a394860).

We get canals from NHD right? Not Transportation?

Here's the XML:

```xml
<Vector id="Canals">
    <Name>Canals</Name>
    <Path>transportation/canals.shp</Path>
    <MetaData>
        <Meta name="Description">The USGS Transportation downloadable data from The National Map (TNM) is based on TIGER/Line data provided through U.S. Census Bureau and supplemented with HERE road data to create tile cache base maps. Some of the TIGER/Line data includes limited corrections done by USGS. Transportation data consists of roads, railroads, trails, airports, and other features associated with the transport of people or commerce. The data is downloaded from science base by state then clipped to the project extent.</Meta>
        <Meta name="SourceUrl" type="url">https://data.usgs.gov/datacatalog/data/USGS:ad3d631d-f51f-4b6a-91a3-e617d6a58b4e</Meta>
        <Meta name="DataProductVersion">2020</Meta>
        <Meta name="DocsUrl" type="url">https://tools.riverscapes.net/data/html#Canals</Meta>
        <Meta name="North Carolina" type="url">https://prd-tnm.s3.amazonaws.com/StagedProducts/Tran/Shape/TRAN_North_Carolina_State_Shape.zip</Meta>
    </MetaData>
</Vector>
```

<img width="809" alt="Screenshot 2023-04-12 at 9 01 55 PM" src="https://user-images.githubusercontent.com/8645379/231649209-cde964a9-0058-4ebb-a991-662fc5e2036e.png">

**Comment by philipbaileynar** [comment]
Any thoughts on this @jtgilbert ?

**Comment by jtgilbert** [comment]
This is because it is downloaded with the transportation datasets and at the step they get downloaded I had it automatically attribute all of those datasets with the same metadata...

**Comment by philipbaileynar** [comment]
So all of our riverscapes models use canals from transportation data? Do they make any attempt to merge with NHD data with the canals and pipes FCODEs?

**Comment by jtgilbert** [comment]
Doesn't look like it, there's no attributes in the canal dataset, but it is identical to the what's coded as canals in NHD so they're probably just stealing it and for who knows what reason not keeping the attributes.
