### ISSUE TITLE
Level 1 Ecoregion not including polygon in actual HUC!

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#756]
See  https://youtu.be/Ze60sYAgu9s?t=2133 from https://github.com/Riverscapes/riverscapes-tools/issues/743

**Comment by philipbaileynar** [comment]
I suspect that this might be related to the 10km buffer we were applying to the HUC boundary and then including all features that touch that buffer. (Same process was being used for ownership.)

@jtgilbert do you agree? Please confirm that you just changed this buffer to 1km? Also, did you decide to intersect ecoregions or continue to include if touches?

**Comment by joewheaton** [comment]
@jtgilbert and @philipbaileynar can we chat about clipping buffer before we go too far. I am excited we can now clip, but I want to think about the ways in which a cartographically minded user will use these contextual layers to make a map that extends beyond the watershed boundaries. I don't like these buffers based on watershed boundaries. We are already serving the user who will use these as model input.

I think I would prefer a rectangular buffer with some pad TBD such that I get enough ownership, geology, ecoregion context etc, to at least cover a Vicinity Map if not also some location maps.

I would value @CHafen input on this as well.

**Comment by jtgilbert** [comment]
Ecoregions aren't being buffered right now, it's just grabbing whatever touches. I suspect this may be an issue of symbology rather than data because the shapefile for all 4 levels is the same, just symbolized different.

**Comment by philipbaileynar** [comment]
I don't like the buffer either. But let me just explain where it came from...

I incorporated a buffer for some layers when I was developing sqlBRAT and the conservation module measures distance to human infrastructure. There are often features (roads, rail) just downstream, outside the mouth of watersheds. Clipping the contextual layers to just the watershed boundary skews the BRAT distance analysis for reaches lower down in the watershed. It's less of a problem in the headwaters where there are fewer roads etc on hilltops.

I think that we should eliminate buffers altogether, especially if they are for maps in reports/publications. The rectangular buffers are never going to have the right aspect ratio or extent. Watershed orientation (east-west, north-south) varies wildly and affects how much buffer is needed.

Let's focus on making the data suitable for analysis and exploration INSIDE watersheds. After all if you want context, just go download the surrounding HUC 10s.... We are running the whole country! Let's not store four times the area of United States.

Conclusion. Clip to the watershed. Users can download adjacent HUCs for bespoke maps.

**Comment by jtgilbert** [comment]
@joewheaton proposed this morning, for selecting and clipping vector layers, to use a buffered bounding box of the HUC8 so that the layers encompass enough area beyond the HUC10 to be useful for contextual maps. 

What do you think of @philipbaileynar 's alternative suggestion here? There's clearly discussion about how much "context" we want to include for a given HUC10 vs needing to download additional projects for that context...

**Comment by philipbaileynar** [comment]
This only affects vector data so I'm fine accommodating Joe's suggestion (we discussed it in person too). 

Just as long as we clip rasters to the HUC boundary, I'm less concerned with how we slice and dice vectors.

**Comment by jtgilbert** [comment]
37c52d321daa2104ae24708388805ff59d104e8b
Here's how it looks, if you like it @joewheaton we can close this.

![Screenshot 2023-04-17 185047](https://user-images.githubusercontent.com/21687931/232641102-8146b828-f26f-4f7f-a771-dc8eaf8e0688.png)

**Comment by joewheaton** [comment]
Nice

**Comment by jtgilbert** [comment]
Closing for now, can reopen if there's still an issue with ecoregion polygons or if we want to revisit how these are clipped.
