### ISSUE TITLE
Repeated elements in RSContext metadata

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#758]
Apologies if this issue would be better logged in another repo--

The HUC and Processing time are listed twice in the metadata (HUC as both HUC and Hydrologic Unit Code, processing time as both ProcTimeS and Processing Time). Could we hide the 'HUC' and 'ProcTimeS' rows from users?
![meta](https://user-images.githubusercontent.com/73311751/231861017-e24d0ef9-7b85-48d1-a58a-6eab6cd4e5db.JPG)

**Comment by joewheaton** [comment]
@shelbysawyer good observation. Notice that all the repeated elements have a different font. These are "non visible" Metadata that the user interface has not yet been updated to reflect. @MattReimer this is a known issue. Do you want to close it in favor of another ticket you already have.

**Comment by MattReimer** [comment]
Yeah. This is actually covered by several different issues:

On the XML side we implemented a new attribute and updated `riverscapes-tools` to use it properly:

- https://github.com/Riverscapes/RiverscapesXML/issues/541
- https://github.com/Riverscapes/rs-web-monorepo/issues/333
- #732 - Updating the metadata to the new system

And the on the front end / visual side we plan to hide metadata that is marked as such:

- https://github.com/Riverscapes/rs-web-monorepo/issues/330
