### ISSUE TITLE
RS Context Review 2 - PB

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#759]
- [ ] [601020201](https://warehouse.riverscapes.net/p/03be576d-fd39-4455-b776-2da5ebda342d/)
- [ ] [705000203](https://warehouse.riverscapes.net/p/fffc2def-7a3d-4f2c-8fb7-91dd60016602/)
- [ ] [1002000805](https://warehouse.riverscapes.net/p/0275d24b-021f-44c2-a545-f1fbd4422b69/)
- [ ] [1604010302](https://warehouse.riverscapes.net/p/69070118-990b-4f9e-92bc-e17baff51f31/)
- [ ] [1709000606](https://warehouse.riverscapes.net/p/a85af7ab-f6ed-415e-98a3-e49fe7b656f5/)

**Comment by MattReimer** [comment]
This is long overdue. I'm closing it.
