### ISSUE TITLE
RS Context Review 2 - JW

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#760]
- [x] [501000301](https://warehouse.riverscapes.net/p/ad534e5a-159c-474a-89b8-955906af85eb/)
- [x] [701010102](https://warehouse.riverscapes.net/p/4f905707-fe5a-4ea0-8061-523a8f1d3608/)
- [x] [1005000403](https://warehouse.riverscapes.net/p/25e5c66c-04de-444e-9cce-05fdc418928a/)
- [x] [1601020203](https://warehouse.riverscapes.net/p/2d132e17-1379-4da8-bf5b-006bafe22446/)
- [x] [1706010302](https://warehouse.riverscapes.net/p/882f3d51-ccd3-4c3e-b9ad-836ab61d6ece/)

**Comment by joewheaton** [comment]
No new issues found. Some of the old issues posted have been resolved... some remain. Looking as expected.
