### ISSUE TITLE
RS Context Review 2 - LH

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#763]
- [ ] 0[514020102](https://warehouse.riverscapes.net/p/b226262b-f4eb-41e1-a215-14882a3191c6/)
- [x] Visit the project on the new Data Exchange
    - [x] Check each tab of the project view in the Data Exchange
    - [x] Inspect project metadata for irregularities
    - [x] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [x] Map extents are a known issue. Please ignore.
    - [x] Check for missing layers
    - [x] Check for symbology issues
    *good except known symbology (LANDFIRE, political boundaries, etc.) issues*
    - [x] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [x] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
- [ ] 0[808010206](https://warehouse.riverscapes.net/p/fec1e746-66a2-4730-8812-1792bd0399a3/)
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [x] Map extents are a known issue. Please ignore.
    - [x] Check for missing layers
    - [x] Check for symbology issues
       *good except known LANDFIRE symbology issues*
    - [x] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
- [ ] [1019001004](https://warehouse.riverscapes.net/p/2a65025e-240d-43db-9f30-1c1e3803cc98/)
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [ ] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
       *good except known LANDFIRE symbology issues*
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
- [ ] [1104000503](https://warehouse.riverscapes.net/p/f6c8680b-20b3-45a5-b3e4-03eb6f3f6e48/)
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [ ] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
       *good except known LANDFIRE symbology issues*
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
- [ ] [1701010302](https://warehouse.riverscapes.net/p/b10cb98c-50a5-442c-8ddc-0e3e9a048cfe/)
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [ ] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
        *good except known LANDFIRE symbology issues*
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems

**Comment by lauren-herbine** [comment]
For my reference:
Review Tasks
- [ ] Visit the project on the new Data Exchange
    - [ ] Check each tab of the project view in the Data Exchange
    - [ ] Inspect project metadata for irregularities
    - [ ] Check that project is findable on the Data Exchange map and in the Data Exchange search
- [ ] Visit the project on WebRV by clicking the map button on the project page in the new Data Exchange
    - [ ] Map extents are a known issue. Please ignore.
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems
    - [ ] Check for tiling irregularities 
    - [ ] Miscellaneous errors
- [ ] Download the Project into QRave
    - [ ] Check for missing layers
    - [ ] Check for symbology issues
    - [ ] Check for layer naming problems

Please report any new bugs or issues as either: Data/RS Context Tool issue or Warehouse/Viewer/Symbology issue.
