### ISSUE TITLE
Channel Area and TauDEM Review - LH

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#769]
Channel Area

- [ ] [514020102](https://warehouse.riverscapes.net/p/82fe6d23-268b-4967-acf0-51009b7b267a/)
- [ ] [808010206](https://warehouse.riverscapes.net/p/897ea035-ad35-4be4-8e1f-4e29d0a480f0/)
- [ ] [1019001004](https://warehouse.riverscapes.net/p/d8c1761e-db91-44b2-b388-dbc529291bd2/)
- [ ] [1104000503](https://warehouse.riverscapes.net/p/4e112413-b099-4e68-a98e-fb05c2b2abf1/)
- [ ] [1701010302](https://warehouse.riverscapes.net/p/7f33f393-40cc-42e6-a2b8-b1e8120bc30a/)

TauDEM

- [ ] [514020102](https://warehouse.riverscapes.net/p/8364af88-5847-432d-be50-25702db1163e/)
- [ ] [808010206](https://warehouse.riverscapes.net/p/1b65e665-2ca4-4713-aa7b-261acad75040/)
- [ ] [1019001004](https://warehouse.riverscapes.net/p/81f26378-9350-4b9f-9cb4-fa1503fb7209/)
- [ ] [1104000503](https://warehouse.riverscapes.net/p/415426c2-cfdb-4220-ba98-da3320b44dc9/)
- [ ] [1701010302](https://warehouse.riverscapes.net/p/95ae8cdc-4023-44a2-ae87-8f1abefc31bf/)

**Comment by MattReimer** [comment]
This is stale. Closing
