### ISSUE TITLE
Channel Area and TauDEM Review - PB

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#770]
Channel Area

- [ ] [601020201](https://warehouse.riverscapes.net/p/0313b9bb-d8cf-4af7-9550-3112f683b8a8/)
- [ ] [705000203](https://warehouse.riverscapes.net/p/d1947f40-817c-42f6-915a-428885dda763/)
- [ ] [1002000805](https://warehouse.riverscapes.net/p/e232c2f4-3b58-4ac8-a802-2519c59f7382/)
- [ ] [1604010302](https://warehouse.riverscapes.net/p/6c845be6-3438-4396-bee7-95383ad70f1b/)
- [ ] [1709000606](https://warehouse.riverscapes.net/p/07d94852-9199-4ca9-907b-6466e47b1af7/)

TauDEM

- [ ] [601020201](https://warehouse.riverscapes.net/p/eae5a08e-31e5-4736-b245-68fcf750a12b/)
- [ ] [705000203](https://warehouse.riverscapes.net/p/9e074b46-523e-4424-8a38-560df82708b0/)
- [ ] [1002000805](https://warehouse.riverscapes.net/p/ea5d9cf9-125c-421e-a2ab-04baf74ff929/)
- [ ] [1604010302](https://warehouse.riverscapes.net/p/0f846b04-208a-42f3-96f6-364baa527a69/)
- [ ] [1709000606](https://warehouse.riverscapes.net/p/d8b3a57f-3634-4254-8725-814c9c97fc93/)

**Comment by MattReimer** [comment]
Very stale. Closing
