### ISSUE TITLE
Potential Bug in How Hectares VB / Km is being calculated

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#772]
I've been working through [updating the symbology](https://github.com/Riverscapes/RiverscapesXML/issues/577) for many layers in VBET, and noticed this. FYI @joewheaton. First, look at the Hectares of VB per Kilometer layer:

![hec_vb_per_km](https://user-images.githubusercontent.com/73311751/232636618-565a8182-1e38-426a-8c22-0be03ae2ddbd.JPG)

Then, look at the Hectares of Estimated Low-Lying Valley Bottom per Kilometer layer:

![lowlying_hec_per_km](https://user-images.githubusercontent.com/73311751/232636623-745fbeaa-4ab0-46b4-bc64-0c260ed0908e.JPG)

Based off the symbology, it's reading as if there more hectares of low-lying valley bottom per kilometer than there are of total hectares of valley bottom per kilometer. For example, I see an area that looks like 2 hectares of VB / km, but then has ~15 low-lying hectares of VB / km. What's causing this?

**Comment by jtgilbert** [comment]
This is strange, I downloaded this project and only have a handful of cases where low-lying > total, and it's basically just cases where they're essentially the same, and the inactive area is 0. I'm not seeing any that are drastically different like these pictures of the symbology suggest...

**Comment by shelbysawyer** [comment]
Strange! Do you mind if I keep this open until I poke around in a few other projects?

**Comment by jtgilbert** [comment]
Yeah, keep it open, I do want to look into how exactly these are calculated since total != low_lying + elevated all the time.

**Comment by shelbysawyer** [comment]
I made a [short video](https://youtu.be/-SiFdyidT3w) (<1 min) of what I'm experiencing with this problem.

**Comment by jtgilbert** [comment]
Nice, thanks. Looks like it acres/mi are adding up correctly but not ha/km. Must be a conversion calculation issue or something, I'll look into it today.

**Comment by jtgilbert** [comment]
fixed in my test run.
