### ISSUE TITLE
Taudem 	1.2.2 issues

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#774]
This is originall from: https://github.com/Riverscapes/riverscapes-tools/issues/768

See Video: https://youtu.be/cMDtzcRvXaY

## Tau DEM

- [x] Around 21:30 in [1005000403](https://warehouse.riverscapes.net/p/57011dd4-6713-40ec-b110-864f91064361/) I notice that HAND is not being calculated for the entire watershed. There are noDAta zones. Why? I haven't seen this before from TauDEM (it happens in VBET of course).  Actually, I think by 27:00 that this makes sense (@jtgilbert to confirm). Because TauDEM is d-inf flow direction based, it can't calculate it for cells outside the drainage. Thus, it highlights parts that the USGS HUC boundaries are incorrect.
- [ ] Around 23:00 in [1005000403](https://warehouse.riverscapes.net/p/57011dd4-6713-40ec-b110-864f91064361/) I notice that Channel Extent Raster has a weird data extent. It should have no-data for everything outside the analysis area (i.e. HUC 10) and false for everything inside.
- [ ] Around 23:45 in [1005000403](https://warehouse.riverscapes.net/p/57011dd4-6713-40ec-b110-864f91064361/) I notice that Flow Direction is NOT showing up in WebRV, but it exists and is fine in downloaded project and displays properly in QRV.

**Comment by philipbaileynar** [comment]
Regarding your first point about NULL in HAND, yes we have seen this in LIDAR runs when areas flow outwards to the periphery of the HUC and not towards a central drainage point.
