### ISSUE TITLE
Mainstem as Artificial Path

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#777]
This could just be stemming from the NHD, in which case I am assuming there is nothing we can do about it, but just wanted to log it in case it's something else-

In 17060304 in RME, the Middle Fork of the Clearwater is listed as an artificial path which is very off-base. It is the mainstem:
![image](https://user-images.githubusercontent.com/73319684/233487157-f8ed7861-4368-4896-895d-b5c9d3a2d1e0.png)
(ignore my half-done symbology)

Will update if I find it elsewhere, but this isn't something I think I've seen before.

**Comment by KellyMWhitehead** [comment]
This means the flowline is inside a flow area polygon. This isn't obvious where the channel and flow area are narrow and have a similar shape, but makes more sense in large reservoirs or lakes, where nhd is trying to make connections across large areas.

**Comment by lauren-herbine** [comment]
Ah, thank you @KellyMWhitehead . Closing.
