### ISSUE TITLE
DGOs not being generated

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#780]
@joewheaton noticed that in [this](https://warehouse.riverscapes.net/rv/b12d3279-1b95-4268-9a40-5db52a5b4488) VBET project, a couple of the level paths did not end up with DGOs. Log suggests it's due to invalid geometries causing the process to skip.

**Comment by joewheaton** [comment]
Here's another one: https://warehouse.riverscapes.net/rv/2f4c49c1-c367-4d86-b87f-0a98f61c2c88

![image](https://user-images.githubusercontent.com/9723905/234100429-4a621867-192e-4bce-957a-ccd3c58a49ca.png)

**Comment by jtgilbert** [comment]
this one's actually a little different @joewheaton b/c the other one did generate IGOs, just not DGOs. I think it may be related though.

**Comment by jtgilbert** [comment]
I think this one is actually a cross-border issue (channel area crosses but DEM doesn't so it leaves out that level path).
