### ISSUE TITLE
VBET HAND Raster (composite) has extremely incorrect values

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#782]
This problem (incorrect HAND values) has been documented before and is a known issue, but I can't find the issue where it was already discussed--

In the process of trying to collect a new round of observation points to specify the updated transform curves, I'm realizing just how off HAND is. For example, a cell directly adjacent to a channel, which according to the DEM is actually lower in elevation, is being calculated as 27 m above the channel in the HAND raster. **Please watch [this <3 minute video](https://youtu.be/-1_kwGExeew) where I show this problem**. It's not an isolated issue.

We can get around this for now by constantly toggling between the DEM and HAND when grabbing observation points to make sure HAND isn't _horribly_ wrong and would result in pulling a wild value for the transform curves, but this problem doesn't just affect transform curve generation. There will be areas that _should_ be mapped as valley bottom that won't be due to HAND having an incorrect value. 

If we're going to follow through with running VBET where the other 10% of points lie, the valley bottoms that we'll be validating those observations against will also be affected by the HAND raster being wrong. 

**Should figuring out this problem take priority over trying to grab points for transform curves?** @joewheaton @jtgilbert Thoughts?

**Comment by lauren-herbine** [comment]
Wow, this seems like it could be a major roadblock- if HAND isn't performing the way we're expecting it to perform, won't this have major ramifications for where VBET maps valley bottom? Especially now that slope is so lightly weighted?

**Comment by jtgilbert** [comment]
Oh shit I should have mentioned the composite HAND is a terrible reference because  it's put back together AFTER generating the VB polygon, so values outside of the valley bottom are not reliable. I've been using the HAND in TauDEM and just choosing places where it's not in question which stream segment/basin the points belong to so it doesn't matter that it's not the levelpath specific HAND. Hope that makes sense.

**Comment by shelbysawyer** [comment]
Ahhh-- I didn't realize I should be looking at the TauDEM HAND raster. That makes sense-- and why the HAND cells outside the valley bottoms of channels are so wild. Closing this issue for now, but I'm wondering if we should only expose the HAND composite _interior_ raster to avoid users getting confused about this too?
