### ISSUE TITLE
If level path flowline has a gap, valley bottom output is incomplete

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#784]
The clean_raster_regions function keeps only the largest vbet zone, so if a level path is discontinuous, the valley associated with the smaller segments gets removed. This isn't super common, but causes problems where it pops up.

**Comment by joewheaton** [comment]
@jtgilbert, please:
- [ ]  work with @shelbysawyer to show her how to fix the Channel Area input network line where this is a problem. For example in [this project]() from a 3.0.7 run:

Please also:
- [ ] Work with @MattReimer to figure out the QC reporting steps in Channel Area, re-uploading, triggering re-runs and replacements when this is found (as well as reporting of fix in VBET metadata.

**Comment by joewheaton** [comment]
This is still showing up here in [Burnt Creek](https://warehouse.riverscapes.net/rv/e1526904-1fd6-4f21-bc27-2225187839ec) for 3.0.7:
![image](https://github.com/Riverscapes/riverscapes-tools/assets/9723905/4e13fbf8-bbba-48c9-bdcb-9fbd2fcef1fb)

@shelbysawyer please attempt to manually fix the Channel Area inputs for that project associated with this. Then work with @KellyMWhitehead to requeue the Channel Area → TauDEM → VBET re-runs on same versions as current. 

![image](https://github.com/Riverscapes/riverscapes-tools/assets/9723905/0c05bb61-6aa3-4214-a981-16ea964e36ec)
