### ISSUE TITLE
Migrate Unrunnables to new Warehouse

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#786]
In order to retire the old Warehouse we need to move everything we can't re-run with cybercastor into the new warehouse. Fortunately we had Tyler Kuntz write a migration script that does the XML migration work for us.

### Preparation

1. Get a copy of the sqliteDB dump of the old warehouse (ask matt. no need to do this yourself)
2. Curate the list and decide if there's anything we don't want to run:

```sql
SELECT *
FROM projects
WHERE LOWER(tags) NOT LIKE '%cybercastor%' and LOWER(meta) NOT LIKE '%cybercastor%'
```

If it's helpful I've already made a view we can look at:
    - https://docs.google.com/spreadsheets/d/17jU6egeQkrxyZ3rUvNdluZQxmtS80ieQBDA-VhxlS-4/edit#gid=115626673 

3. Run the migration script to generate new XML files
    - It's been a while since this script was run. The script SHOULD find any XML validation errors so if there are any we'll need to make tweaks and re-run. Luckily it's fast. 

5. You'll need to install the latest version of the CLI (2.0.23) at time of writing:

(You'll need NodeJS 16 installed)

```
npm install -g @riverscapes/cli
```

I think we can lump these into 2 categories

1. Anabranch
2. CHaMP/AsotinIMW

###  Anabranch

There are only 34 projects here and they're all kind of custom so automation is less likely to be effective. 

1. Download the project from the old warehouse
2. plug in the new XML file
3. Use `rscli` to upload it to the new warehouse into the `Anabranch` organization.
4. Note the new GUID in the spreadsheet (there's a "New Guid" column) so we can build some redirects later

```bash
rscli upload /path/to/project --org <org_id> --visibility PRIVATE --tags NEWTAGS
```

### CHaMP

This one is going to need some thought. One potential idea is:

1. Mirror the two programs to a new bucket
2. create a folder structure locally with the appropriate XML files
3. AWS s3 sync the local folders into the bucket
5. Create a temporary to use an s3 command to simulate project upload to the new warehouse. This way we can avoid all the transfer time of bringing it all down locally.

Notes:

1. CHaMP projects do not have project bounds. We might need to punt on this. We can migrate them now and then add bounds later.
2. PUBLIC_DATA program looks like we can ignore all of it. There may be exceptions so please confirm

3. There are a bunch of projects that don't have `cybercastor` in the tags but DO have cybercastor in the metadata

```sql
SELECT *
FROM projects
WHERE (LOWER(tags) LIKE '%cybercastor%' and LOWER(meta) NOT LIKE '%cybercastor%') OR
(LOWER(tags) not LIKE '%cybercastor%' and LOWER(meta)  LIKE '%cybercastor%')
```
What should we do with these?

4. Should these unrunnables be PRIVATE?
6. Do we want to keep the same tags as the old warehouse or invent new ones?
7. The new hidden/locked metadata rules are not applied. Can we ignore these?

-------------------------

#### Resources 

- Orgs in the new warehouse:
    - Asotin IMW - https://warehouse.riverscapes.net/o/40250a14-556f-467e-8acc-e2594f028af7
    - CHaMP - https://warehouse.riverscapes.net/o/c7d8c487-c377-42b0-a5b6-4c16db18fb41
    - Anabranch - https://warehouse.riverscapes.net/o/d4c09f98-13de-492a-8f55-31f6477a1083

**Comment by joewheaton** [comment]
Excited to see this happening @MattReimer. Please do not forget these extremely important programs with "unrunnables":
- [ ] BRAT CRB
- [ ] BLM Montana Dakotas (just pyBRAT stuff)
- [ ] Bear River Resilience Bond ??? 
- [ ] Asotin IMW
- [ ] Bonneville Environmental Foundation
- [ ] Upper Klamath - USFWS
- [ ] Greater Yellowstone Ecosystem Coordinating Committee
- [ ] Idaho Department of Fish and Game
- [ ] John Day Watershed Council
- [ ] Powder Basin Watershed Council
- [ ] TNC Calfironia
- [ ] SGI Mesic Workshops - SGI
- [ ] US Forest Service PIBO

![image](https://github.com/Riverscapes/riverscapes-tools/assets/9723905/e53d36c2-9c24-4184-936e-44152430409c)

Everything above is tied to contracted deliverables, that link to old warehouse URLs. As such I expect:
- [ ] All old warehouse project URLs to redirect to new Warehouse URL
- [ ] Make the owner of Asotin IMW - Anabranch Solutions. Make NOAA owner of BRAT CRB. All of the rest of these the owner can be ETAL.
- [ ] Everything that was found in a "Program" in old warehouse should be in a new Collection in the new Warehouse. This includes both "unrunables" and any "rerunables" (e.g. cybercator replacement runs of VBET and BRAT in BRAT CRB.

Maybe you already had planned to do all the above, but I want to be explicit in what I was assuming and expecting and @philipbaileynar and I had discussed at multiple points over the past year.

**Comment by MattReimer** [comment]
@joewheaton that's fine. We've already started moving things with a slightly different structure (i.e. we have organizations for every program) but we can use the API to transfer ownerships and create the collections structure you suggested here. 

@KellyMWhitehead let's talk.

**Comment by MattReimer** [comment]
This is complete. Anything we missed counts as a bug.
