### ISSUE TITLE
Waterbody split by catchments

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#794]
The new RSContext creates a copy of NHDArea that is split by the catchments and attributed with their attributes. This process was not applied to the NHDWaterbody layer, so downstream Channel Area and VBET projects that have level paths with waterbodies end up with missing levelpaths (and DGOs) in the VBET outputs. 

For now we can work a manual fix to Channel Area projects and then re run VBET.

For next version of RSContext we should repeat what we did for NHDArea with NHDWaterbodies.

**Comment by philipbaileynar** [comment]
@jtgilbert can you review. Action or close please.

**Comment by jtgilbert** [comment]
Yep, this is related to the issue I noticed last week, so this will be top priority for finishing RSContext udates.

**Comment by philipbaileynar** [comment]
Jordan's code is now merged onto dev.
