### ISSUE TITLE
What user experience does VBET require?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#8]
As we contemplate a "commercial grade" VBET we find ourselves at a familiar  decision; which technology should we use to build the end user VBET product? I have [summarized these before during BRAT development](https://docs.google.com/document/d/1_hqjF_Y2du4SBXfwFqnBsMAHV8y1M9hDTuadzzWezpo/edit?usp=sharing).

Another way of asking this question is: In which environment will users interact with VBET, add datasets, parameterize runs, hand edit and refine outputs, segment, calculate attributes etc. The options and some comments:

* ArcGIS
  * Delivers the best user interface (e.g. GCD), but
  * The VBET code dependencies will never install on Windows by all but the most technically sophisticated of operators.
  * It will not only take a massive budget to write VBET algorithms in .Net but doing so would require VBET algorithms to be finalized (as was the case with GCD). This is not the case with VBET (as evidenced by all the issues in this repo).
* QGIS
  * Possible, but a) realistically no one uses it, and b) previous plugin experiences suggest that deployment is a problem.
* Command line
* Web (browser, PWA etc)
  * Very expensive UI for workflow that is still in flux.

I want to come back to an idea that I floated for BRAT but that we rejected. Now that we have production grade data warehouses, I think it should be reconsidered.

We build the VBET user interface as an ArcGIS .net AddIn. Users can add datasets to VBET projects just like they do in GCD. But when they trigger calculations the datasets are uploaded to a data warehouse where the processing occurs. The outputs are downloaded, together with GUIDs for any of the inputs that were uploaded to make the run happen. Whenever the user attempts another calculation that uses the same inputs, the UI is clever enough to realize which inputs have already been uploaded and not re-upload them again.

This is obviously complex and requires a lot of non-VBET specific infrastructure to be in place before it will work. But it's a method that we can reuse with lots of our tools. It allows us to build rich user interfaces in .net as well as easily switch to QGIS, ArcPro etc.

**Comment by MattReimer** [comment]
I'm moving this to discussions since that's what this is.
