### ISSUE TITLE
Anthro "'NoneType' object has no attribute 'intersection'" error

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#800]
Log attached.

[FAILED-0701020505.log](https://github.com/Riverscapes/riverscapes-tools/files/12005016/FAILED-0701020505.log)

**Comment by philipbaileynar** [comment]
@KellyMWhitehead how many of the outstanding failures (as of 11 Jul 2023) does this affect?

![image](https://github.com/Riverscapes/riverscapes-tools/assets/8645379/828fd4ce-c1bc-441c-9744-8021b330fe35)
