### ISSUE TITLE
RME Feedback

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#832]
This feedback originated from a review of a sample RME project for 1601020204 provided by @jtgilbert on 24th Oct 2023.

# metrics table 

- `name` field should be required and have a unique index
-  `machine_code` field should be required and have a unique index.
- Is it OK that there are metrics with NULL `field_name`?

# metric_values table

- The two foreign keys both require cascade delete (add `ON DELETE CASCADE` to the constraint definition).
- `metric_value` is of type `REAL` which is fine unless we plan on storing categorical metrics (such as owneership agency "BLM").
- Provide a name for the primary key on (dgo_id, metric_id) and call it `pk_metric_values`
- Remove the index `ix_metric_values`. It's on the field 1`dgo_id` which is already covered by the aforementioned primary key.
- Add a new index called `fx_metric_values_metric_id` on `metric_id`. (I can explain how these last three recommendations interact).

# points

- Is this a good table/feature class name? Would `igos` be better?
- Why are some columns mixed case and some lower?
- LevelPathI`, `FCode` and `seg_distance` should all be required (`NOT NULL`).
- Why do all our tools have that capital I at the end? Do we need it?
- It's unlikely that someone will query `seg_distance` without also including `LevelPathI`. Why not use a single compound index on (`LevelPathI`, `seg_distance`). It will take up the same amount of space as the two separate indices but will have better performance when querying either just level path or both fields.
- I thought we weren't storing IGO metrics? And only using DGO metrics?

# vbet_segments

- Are these DGOs? Better table name?
- Most of the field and indexing comments for the `points` table also apply here.

# measurements

- If measurements have identical data design as metrics (i.e. a lookup table with name and machine code and then a separate values table), why not combine them in the metrics table and just have a `metric_type` field to distinguish them?
- If keeping separate, then all the comments on the `metrics` table also apply here.

# measurement_values

- All comments to both the measurements and metric_values table apply here

# igo_metric_values

- What's the difference between the `metric_values` table and the `igo_metric_values` table?
- All comments to the metric_values table apply here.

# dgo_metrics_pivot

- Naming? What is this a pivot of? `metrics`? More consistent naming needed. 

# Pivot tables

- The pivot tables should be views not tables?????????

# gpkg_contents

- Reuse the spatial bounds from the real feature classes for the spatial views. Try this syntax:

```sql
INSERT INTO gpkg_contents (table_name, data_type, identifier, min_x, min_y, max_x_ max_y, srs_id)
SELECT 'my_view_name', 'features', 'my_view_name', min_x, min_y, max_y, max_y, srs_id FROM gpkg_contents WHERE table_name = vbet_segments
```

**Comment by jtgilbert** [comment]
In the interest of getting runs into the exchange for @lauren-herbine and @shelbysawyer I've fixed most of this, while putting off for future versions and more discussion changes related to simplifying the database (merging measurements and metrics into one table).

**Comment by philipbaileynar** [comment]
can you confirm that you have switched the pivots from tables (duplicated data) to views please?

**Comment by jtgilbert** [comment]
@philipbaileynar oh yeah, still need to do that. I'll add that to the test I'm doing now then confirm before merging PR.

**Comment by jtgilbert** [comment]
@philipbaileynar That turns out to be more complicated than I anticipated because I'm updating the tables after creating them (which you can't do with views) to insert the text metrics after the number metrics.

**Comment by philipbaileynar** [comment]
Let's meet Tuesday to discuss. 

I do NOT want to proceed until we nail this database design.

**Comment by lauren-herbine** [comment]
What time are you all meeting today?

**Comment by shelbysawyer** [comment]
I'd also hop on the call if you think it's relevant. Did all IGO metrics end up getting slashed?

**Comment by jtgilbert** [comment]
@lauren-herbine @shelbysawyer It's calculating all the metrics fine, we're just trying to figure out how to have the cleanest sql database in the output without redundancies.
