### ISSUE TITLE
Ownership Layer Updates

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#838]
We need the ownership layer updated with the following requirements:
- download a new dataset that includes Alaska
- fix null geometries
- simplify (providing it doesn't mess the geometries)
- reproject to 4326

https://catalog.data.gov/dataset/blm-natl-sma-surface-management-agency-area-polygons-national-geospatial-data-asset-ngda

Please send this new version to me and I will get it included in the national project.

This is a fairly urgent need so we can start running RSC for the BLM priority watersheds in Alaska.

**Comment by philipbaileynar** [comment]
We have decided to abort incorporating Alaska into the existing National Project and instead we will build a new dedicated "national" project for Alaska #846 

So this task might be as simple as getting the latest ownership layer uploaded into the Data Exchange.

**Comment by Jdgilby** [comment]
https://drive.google.com/file/d/1yYpbZm9t0XyfPlpKOumJbyn3JXw1WTze/view?usp=sharing
https://drive.google.com/file/d/1yVYco37geXWpo2gBuNqaOAt2x5xgFYRF/view?usp=sharing
Alaska and Lower 48 as seperate .zip files.

**Comment by philipbaileynar** [comment]
Thanks Josh!

**Comment by philipbaileynar** [comment]
Closing. New ownership layer is live and been tested for Upper Bear within the new Development "mini" national project.
