### ISSUE TITLE
National Project Extent Review

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#839]
Please review all layers in the national project that are used by our model waterfall and confirm that they include Alaska.

- [ ] #838
- [ ] Vegetation
- [ ] ?????

FYI @Jdgilby @jtgilbert @joewheaton

**Comment by KellyMWhitehead** [comment]
Datasets that need Alaska added:
- Ecoregions Level 3
- Ecoregions Level 4
- Geology
- Landfire Rasters
- Prism Rasters

**Comment by philipbaileynar** [comment]
Do any of these not extend to Alaska?

**Comment by KellyMWhitehead** [comment]
Only the political boundaries (us states/counties) extend into Alaska. The national project layers above do not.

**Comment by philipbaileynar** [comment]
I meant... which of the original sources are unavailable in Alaska? i.e. does the official Landfire data extend to Alaska? (I know our current national project does not)

**Comment by KellyMWhitehead** [comment]
Sorry, misunderstood. Here is what I found:

- Ecoregions Level 3
  - https://gaftp.epa.gov/EPADataCommons/ORD/Ecoregions/ak/ak_eco_l3.htm
- Ecoregions Level 4
  - Not available
- Geology
  - Separate layer from CONUS: https://www.sciencebase.gov/catalog/item/5771b88fe4b07657d1a6c752
- Landfire Rasters
  - AK is available for version 220: https://landfire.gov/version_download.php
- Prism Rasters
  - https://prism.oregonstate.edu/projects/public/alaska/grids/
- Market Value
  - CONUS only

**Comment by philipbaileynar** [comment]
@joewheaton @jtgilbert What do you want to do about Ecoregions? We have started to bake ecoregions IV into our models assuming the most granular version can always be summarized at coarser levels. Should we switch to ecoregions III because it is available for the entire US?

**Comment by jtgilbert** [comment]
So far we haven't actually used ecoregions for anything right? They'll soon be used for querying with them included in the RME outputs. Level 3 seems like an acceptable level of detail for these types of queries, and if it makes it consistent across US where we can include Alaska, I think it makes sense to stick with L3 (also less symbology issues). 
I also think that we should drop that market value raster.... takes up space, not used, probably outdated at this point....

**Comment by philipbaileynar** [comment]
Separate issues for each dataset that requires work:

- [ ] #841

**Comment by philipbaileynar** [comment]
Research complete. Closing this issue. I will create a new issue dedicated to creating a new "national" project for Alaska.
