### ISSUE TITLE
Update Ecoregions to National Project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#841]
The goal of this ticket is to update the ecoregions datasets in the national project. The goal

- [ ] One **Level 3** feature class that includes both CONUS and Alaska
    - [ ] Make sure any invalid geometries are removed.
    - [ ] EPSG:4326
    - [ ] National Project business logic correctly refers to this dataset
    - [ ] Symbology
- [ ] One **level 4** feature class that includes just CONUS
    - [ ] Make sure any invalid geometries are removed.
    - [ ] EPSG:4326
    - [ ] National Project business logic correctly refers to this dataset
    - [ ] Symbology

At the risk of being blunt... this task is only complete once the layers refered to above are uploaded and working correctly in the map viewer via the Riverscapes Data Exchange.

FYI @joewheaton @jtgilbert @KellyMWhitehead

**Comment by philipbaileynar** [comment]
@Jdgilby this task is still needed.

The only change is that this task will not include downloading and integrating the data for Alaska. The existing CONUS national datasets need tidying as specified above, but they will not include Alaska.

**Comment by philipbaileynar** [comment]
@jtgilbert and @Jdgilby been a while. I'm completely unsure where this got to!

**Comment by jtgilbert** [comment]
Closing for now. This hasn't caused any issues, is in the correct projection and recently had updated symbology done.
