### ISSUE TITLE
Stream Type

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#849]
nhd_dgo_streamtype not working in [0.6.0](https://data.riverscapes.net/p/63baffc0-a3ee-4ffe-bd61-bcb6214c84e3/)

@jtgilbert nhd_dgo_streamtype is labeling everything as 46003 and is not breaking things out by FCode

**Comment by jtgilbert** [comment]
good catch @lauren-herbine thanks
