### ISSUE TITLE
Fix 'Roads in Valley Bottom' in Anthro

### ISSUE THREAD

**Issue by dominique-shore** [Riverscapes/riverscapes-tools#851]
The anthro/intermediates/railroads within the valley bottom layer is not being created in Anthro. 

When added to QRAVE and WebRAVE, nothing appears and the attribute table is empty in QRAVE. 

Symbology problem reported in issue https://github.com/Riverscapes/RiverscapesXML/issues/665

**Comment by jtgilbert** [comment]
@dominique-shore In the projects you've found where this is an issue, will you check the version number. All of the Anthro projects I happen to have downloaded locally are 0.2.0 and don't seem to have this issue. I suspect it might be 0.1.0 versions...

**Comment by jtgilbert** [comment]
Actually I just downloaded one that @joewheaton mentioned had issues ([Echo Creek](https://data.riverscapes.net/p/b3ebdfe2-0874-43c1-823b-cb4af155690f/)) and the roads clipped to valley bottoms are there...

**Comment by dominique-shore** [comment]
@jtgilbert I am downloading the Anthro 0.1.0 version. That is the only version available for me. I just downloaded it and had the same problem where I can see the input roads file, but not the roads in the valley bottom. Perhaps it's been fixed for 0.2.0, but that's not publicly available, I'm guessing? 
 
![Screenshot 2023-11-15 163656](https://github.com/Riverscapes/riverscapes-tools/assets/106760640/1f4e74b6-5af4-4fb6-a33e-c7f2772fdba1)

![Screenshot 2023-11-15 164126](https://github.com/Riverscapes/riverscapes-tools/assets/106760640/a488deb3-f601-4002-b50b-b7be7f3f6534)

![Screenshot 2023-11-15 164113](https://github.com/Riverscapes/riverscapes-tools/assets/106760640/dc4fbd54-a9c5-4d2c-b2c1-b8e39d9097bf)

**Comment by dominique-shore** [comment]
I see now the road_valleybottom layer does exist in the .gpkg, it's just not appearing when I add it using QRAVE. It seems similar to the issue I'm seeing with the vwIgos layer in RCAT https://github.com/Riverscapes/RiverscapesXML/issues/650

**Comment by jtgilbert** [comment]
Ah yeah that makes sense. I'm going to assume its a symbology issue and close this for now.
