### ISSUE TITLE
Migrate the tools site to Gatsby

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#861]
@philipbaileynar, with three of the six primary pages being moved (see https://github.com/Riverscapes/developer-website/issues/1),  it seems a high priority to:
- [ ] Migrate Tools Site: https://tools.riverscapes.net (3 pages)
 
Also a high (but slightly lower priority) are the specific tools pages:
- [ ] https://tools.riverscapes.net/rscontext/ (3 pages)
- [ ] https://tools.riverscapes.net/channel/ (3 pages)
- [ ] https://tools.riverscapes.net/taudem/ (3 pages)
- [ ] https://tools.riverscapes.net/vbet/ (5 pages)
- [ ] https://tools.riverscapes.net/brat/ (25 pages)
- [ ] https://tools.riverscapes.net/anthro/ (2 pages) 

FYI @jtgilbert , @shelbysawyer and @dominique-shore

**Comment by philipbaileynar** [comment]
All migrated. More content needed.
