### ISSUE TITLE
Broken (and incorrect) link on data.riverscapes.net

### ISSUE THREAD

**Issue by dominique-shore** [Riverscapes/riverscapes-tools#865]
At the top of the Info tab for every project in data.riverscapes.net, there is a link to the free RAVE plugins

![image](https://github.com/Riverscapes/riverscapes-tools/assets/106760640/4401f00b-abaa-43e6-88ea-6335df542820)

This link goes to rave.riverscapes.net, which is not live so it goes to the GitHub 404 page.

Also - we do not have a RAVE plug-in for ArcGIS, we have one for ArcMap (older version).

(I did make an issue (https://github.com/Riverscapes/rs-web-monorepo/issues/457) in the RiverscapesData repo, but closed it because I think this a better place for this issue. Apologies for the confusion)

**Comment by philipbaileynar** [comment]
Actually the Web Mono Repo is the correct place.

closing this one in favour of:

https://github.com/Riverscapes/rs-web-monorepo/issues/457
