### ISSUE TITLE
RCAT Version 3.0.1 not displaying in WebRAVE

### ISSUE THREAD

**Issue by dominique-shore** [Riverscapes/riverscapes-tools#866]
As far as I can tell, no RCAT Model Version 3.0.1 will appear in WebRave. I've tried zooming and adding different layers to no avail. I have not had the same problem with version 3.0.4 or 3.1.1. 

As this is an old model run, and not appearing in WebRAVE, perhaps we should not make them publicly viewable? I doubt most users will easily see they can open a newer model version.

**Comment by jtgilbert** [comment]
closing b/c there are currently no v 3.0.1 in the exchange.
