### ISSUE TITLE
networked_intersected missing lots of segments from NHDFlowline

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#878]
Looking through channel and rs_context outputs, the 'network_intersected' feature class that we're using for downstream tools is actually  missing lots of important segments (e.g., standard perennial flowline reaches). 
fyi @philipbaileynar @KellyMWhitehead

**Comment by jtgilbert** [comment]
![Screenshot 2024-01-29 101349](https://github.com/Riverscapes/riverscapes-tools/assets/21687931/723f6552-fc2d-4341-b087-0a8914a64d18)

Red is NHDFlowline and Blue is network_intersected (HUC 1601010102)

**Comment by KellyMWhitehead** [comment]
This is now fixed. Somewhere along the line the geometry wasn't getting copied over during the segmentation process for features that didn't need to be split.
