### ISSUE TITLE
Missing Python Packages

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#904]
I went to run the merge project script in the Cybercastor workspace using CodeSpaces and the following Python packages were missing:

- `semantic_version`
- `rsxml`

I can pip install them as needed, but would be nice to have them included in the box.

**Comment by MattReimer** [comment]
I'm closing this. It has been fixed on the dev branch. 

'Semantic_version' should not be used in favour of 'semver' (for consistency with our other tools)
