### ISSUE TITLE
RME Issues

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#919]
@jtgilbert this is the shopping list of RME fixes that need fixing before Tuesday's Montana workshop:

Data

- RME is missing BRAT metrics
- RME is missing riverscape length metric

Business Logic

- Still some nagging issues that DGOs don't show up. (They were present for Color Country but missing for Upper Bear.) 

Symbology

- Can we switch to non-rule based symbology? Use `to_real()` instead.

**Comment by jtgilbert** [comment]
fyi @philipbaileynar idk if it necessarily matters, but adding BRAT into RME adds a bunch of geoprocessing (because BRAT metrics are not yet stored on DGOs), so it slows it down a lot.

**Comment by philipbaileynar** [comment]
Is your point that RME will be slow to run, or that this extra work will delay the release of the next version?

**Comment by jtgilbert** [comment]
No, works done, it's just way slower now.
