### ISSUE TITLE
Update National LandFire Rasters

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#93]
Thanks to @tyler1218hatch we now have national LandFire 2.0.0 rasters! This is a hug step forward! Hopefully we don't have to revisit this topic again for a very long time.

@MattReimer can you please incorporate these rasters into the national project and ensure that they are wired up for the next batch of tool runs.

I have put them on s3 in nardata/temp please delete them from this location when you are done.

The rasters might require some cleaning:

- -9999 should be reclassified as NoData.
- LZW compression doesn't feel quite right. I think we use no-deflate on integer rasters right?

Please also pay specifical attention to the XML lookup files that Tyler prodived with the raster. Maybe we can use these directly in place of the ones we generated?

**Comment by joewheaton** [comment]
Exciting... nice work @tyler1218hatch. What year(s) are the EVTs from?

**Comment by joewheaton** [comment]
Just a thought... and I have not looked into the tags you are using in that national datasets riverscape project (can't remember what you call that), but if we don't already, these should have tags for:
- Publication Date
- Acquisition Date (of imagery)
- Source Organization
- URL
- Citation

**Comment by MattReimer** [comment]
```
gdal_translate \
  -ot UInt16 \
  -co COMPRESS=DEFLATE \
  "/Volumes/Extreme SSD/newlandfire/input.tif" \
  "/Volumes/Extreme SSD/newlandfire/output.tif"
```

Uint16 and the DEFLATE option give us a little savings on space.

**Comment by tyler1218hatch** [comment]
@joewheaton The EVT and BPS are both from LANDFIRE 2.0.0, which I believe is 2016.

**Comment by MattReimer** [comment]
Updated in the nationalproject.

**Comment by philipbaileynar** [comment]
I just ran 020600030501 through RSC and VBET. It's in Maryland in the east. I can report that both the historic and vegetation rasters worked!

Thanks @tyler1218hatch and @MattReimer
