### ISSUE TITLE
Confinement extents

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#943]
In my confinement updates I got rid of rs_context as an input b/c all of the necessary inputs were in VBET, but that made it so that when running the confinement_rs script it doesn't grab the project extents from rs_contexts project xml.

fyi @KellyMWhitehead

**Comment by KellyMWhitehead** [comment]
I went ahead and added rs context back to the cybercastor shell. I will run it and report back here.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead status please? Close if completed and tested.
