### ISSUE TITLE
BRAT Report Style Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#948]
As a general rule try and implement these fixes at the lowest level possible. In other words, try and use CSS improvements rather than styling individual HTML tags.

1. Better semantic heading fonts. H1 shoulder be bigger than H2. H2 should be bigger than h3 etc.

2. Remove the incremental indendation of sections.

<img width="397" alt="Screenshot 2024-05-09 at 12 18 13 PM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/d1f222d9-4bc5-477f-92f5-062ef588c221">

3. Reduce the border around the info boxes to 1px? and drop cell spacing to zero.
 
<img width="414" alt="Screenshot 2024-05-09 at 12 18 56 PM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/5b5c719a-5108-4f56-9845-26578d6753b0">

4. Data tables should match info box styling. Set outer border to 1pm. Remove the cell spacing.

5.  Implement "Total" row for all data tables where relevent.

6. Is there are "one fix all" to avoid pie chart label overlaps?

7. Are 3D pie charts being used? If so, turn off and make 2D.

<img width="823" alt="Screenshot 2024-05-09 at 12 19 44 PM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/a993ca8e-ce0e-48d2-a616-38134fcb8d9a">

8. What are the redundant horizontal rules HR at the end of the capacity section?

<img width="441" alt="Screenshot 2024-05-09 at 12 22 22 PM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/1f451617-60b0-4a9c-a2e6-ead16de662d0">

9. Risk table first column should left aligned.

10. Risk table has "None" when it should be zero.

11. Stream discharge plot series should be "riverscapes blue" not burnt orange.

**Comment by philipbaileynar** [comment]
Another request.

Please change the report background to white. Currently it's a subtle cream colour. This doesn't work with the PNG graphics that have a white background and the alternating table rows that also use pure white.

<img width="471" alt="Screenshot 2024-05-09 at 4 23 45 PM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/780ec0bd-1fa0-467d-8dd3-fc179a67b92e">

**Comment by r-k-g** [comment]
[report.zip](https://github.com/Riverscapes/riverscapes-tools/files/15297756/report.zip)
New report style example

**Comment by philipbaileynar** [comment]
# Feedback

1. Slight gap in cell border? Is this still some cell spacing or padding?
<img width="471" alt="Screenshot 2024-05-13 at 11 03 32 AM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/e9bd61af-b510-48d8-af20-51c82b223239">

2. Don't add categories to pie charts that have a value of zero.
3. In the Hydrology section the "Drainage area threshold" is right aligned but the other items are left aligned. (I think this is some automated behaviour because it is integer and not string or float)
4. Weird rounding going on. I'm fine if 99.9% rounds to 100%. but the bar in the chart doesn't appear to be at 100%
<img width="1102" alt="Screenshot 2024-05-13 at 11 10 06 AM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/481a3345-8308-4b33-a3c1-f094fdab5db6">

5. Missing class. This might require a left join instead of an inner join.
<img width="386" alt="Screenshot 2024-05-13 at 11 11 54 AM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/536f5986-8f59-42cc-98cb-d74b45522fef">

6. Silly request. Can you remove the colons on the project metadata table after the labels?
<img width="386" alt="Screenshot 2024-05-13 at 11 13 11 AM" src="https://github.com/Riverscapes/riverscapes-tools/assets/8645379/923373b2-83a0-4c81-b70a-da09635a1e64">

**Comment by philipbaileynar** [comment]
Can you use a regex on metadata (or look at the metadata type) and add a hyperlink to URLs?

**Comment by r-k-g** [comment]
[report.zip](https://github.com/Riverscapes/riverscapes-tools/files/15300286/report.zip)
Updated report example
