### ISSUE TITLE
tauDEM Report Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#953]
... make sure work on this report uses all the recent improvements to the BRAT report (#948 )...

1. Any URLs in the dataset tables should be hyperlinked to their source.
2. The "project path" is included in the dataset table and then repeated under the table as well. Remove the one under the table.
3. The file size for rasters should be added **inside** the info box.
4. The file size for vector layers is not possible (because a single *.gpkg GeoPackage can store multiple layers. Remove this information for vectors.)
5. The "Original URLs" for rasters appears to be a list of URLs. Can we detect that it's a list (`isinstance(xxxx, list)`) and then convert to individual URLs?

@jtgilbert anything else you can think of for the tauDEM report? Any parameters or configuration for this model that we could include?

**Comment by r-k-g** [comment]
[taudemreport.zip](https://github.com/Riverscapes/riverscapes-tools/files/15314725/taudemreport.zip)
Example report
