### ISSUE TITLE
Channel Area Report Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#954]
1. make sure all the changes for BRAT and tauDEM reports are applied to the Channel Area report. In particular:
    2. Remove redundant horizontal lines.
    3. Clean up the data source tables with the same changes suggested for both BRAT and tauDEM.
4. Under Outputs, replace the opening sentence "The Channel Area Tool..." with the paragraph from [this page](https://tools.riverscapes.net/channelarea/). Also replace the "here" link with this URL.
5. Change the Data Source Breakdown table to show both hectares and acres and in the units. (I suspect. that the current table is in m^2).
6. Below the "Data Source Breakdown" add more "breakdowns". Hopefully this can be done with a generic block of code that can just be called multiple times based on a different attribute table field.
    1. FCode breakdown. Summarize the areas (in the same way as the data source breakdown table) by the FCode column (FCode categorizes waterbodies into different types: streams, pipes, canals etc)
    2. Ownership.
    3. Ecoregion_iii
    4. Ecoregion_iv
    5. stream order
7. Also add feature count to the breakdown tables.

**Comment by r-k-g** [comment]
[channelareareport.zip](https://github.com/Riverscapes/riverscapes-tools/files/15314721/channelareareport.zip)
Example report
