### ISSUE TITLE
RCAT some intermediates rasters not in project xml

### ISSUE THREAD

**Issue by r-k-g** [Riverscapes/riverscapes-tools#962]
Some of the files that appear in the "intermediates" folder for a [downloaded RCAT project ](https://data.riverscapes.net/p/ef65232a-d114-4370-8b8c-98c01adb9ccd/) do not appear in the project.rs.xml and correspondingly are not in the html report.

 - intermediates/canal.tif
 - intermediates/channel.tif
 - intermediates/d8_slp.tif
 - intermediates/rail.tif
 - intermediates/road.tif
 - intermediates/valley.tif

Shown highlighted in file explorer: 
![image](https://github.com/Riverscapes/riverscapes-tools/assets/80495206/36bf47a7-03dd-40c3-b94f-19aa861e27db)

Should these be in the project.rs.xml and report?

**Comment by jtgilbert** [comment]
Don't think I want to expose these.
