### ISSUE TITLE
RSContext project name should match downstream project names (use name not HUC #)

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#963]

**Comment by philipbaileynar** [comment]
[Agreed upon at North Van Retreat](https://docs.google.com/document/d/1iJptNYK88mj_ZoqodXuVcajuy5Fg0wIfMw1pp7cxnoE/edit?usp=sharing)

# HUC model runs:

`<project_type> For <HUC Name>`

# Merged model projects

`Merged <project_type> for “area name”`

# Synthesis Projects

`“Area name” Synthesis`
