### ISSUE TITLE
What filters for tools listing?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#972]
We are about to embark on developing a new home page for [tools.riverscapes.net](https://tools.riverscapes.net). This will fulfill our vision of a FILTERABLE list of tool cards per our discussions with the information architect...

# Questions

1. What filters do we want above the list of cards. I strongly recommend not more than 4 filters. Here is the [wire frame of the existing design](https://drive.google.com/file/d/1QNszocWjfbtLdDOJwwg7QDrWQo7FM3xo/view?usp=drive_link) that we will follow if there are no other concerns.
2. What type of filter controls:
    - Multi-select checkboxes to the left (as shown in mock-up)
    - Multi-select dropdowns as horizontal ribbon across the top.
    - Single select dropdowns as horizontal ribbon across the top.

@joewheaton ????

**Comment by joewheaton** [comment]
Well, based on [ this](https://developer.riverscapes.net- /MIGRATED/Tools/), I would include 
- Resolution 
- Extent 
- Interface
- Status

**Comment by philipbaileynar** [comment]
Thanks @joewheaton 

Comments:

1. We intend to make the default view "cards" rather than a table. Cards behave better on different screen sizes (i.e. they are more responsive). Tables should be reserved for "data". Not saying we can't get there, but the default should be cards (much like a lot of HiveBrite views).
1. We will skip the icons. They are hard to read and don't add much (per several readers I have spoken to). Each card can have a title graphic and we can bake things like the ESRI and Q logos into those. I came up with the "gas tank" graphic idea and don't think it works. Too small for the detail required.

# Question

1. Can the two uses you list above be accomplished by simply an initial filter on "compliance status"?

**Comment by philipbaileynar** [comment]
Thanks @joewheaton
