### ISSUE TITLE
New LandFire Version into Riverscapes Context

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#977]
- [ ] @MattReimer and @jtgilbert get new LandFire rasters into National Project.
- [ ] @jtgilbert to integrate new LandFire into RSC project.
- [ ] @jtgilbert to update BL and symbology for this project.

**Comment by jtgilbert** [comment]
#976

**Comment by philipbaileynar** [comment]
Closing duplicate.
