### ISSUE TITLE
Research running HAND

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#98]
The HAND rasters that we download and use in riverscapes are created from the NHDPlus 1:100,000 data. Our riverscapes data uses NHD 1:24,000 data.

Therefore there are lots of places where we have reaches but the network on which HAND was calculated does not contain a reach. In these places the HAND values are higher than expected because the raster contains the height down to the nearest 1:100K reach. This is particularly relevant in VBET we threshold HAND to only retain pixels with low values.

Please research the HAND source code and report back the complexity and effort required for use to produce our own HAND rasters.

Note that HAND is one type of output from the the D-Infinity Distance Down tool within TauDEM. This tool allows you to specific whether you want the horizontal, vertical portion of the distance to the nearest stream. HAND is obviously the vertical  component.

Links:

* [TauDEM Help](https://hydrology.usu.edu/taudem/taudem5/)
* [D-Infinity Distance Down Documentation](https://hydrology.usu.edu/taudem/taudem5/help53/DInfinityDistanceDown.html)
* [D-Infinity Distance Down Code](https://github.com/dtarb/TauDEM/blob/Develop/src/DinfDistDown.cpp)

**Comment by MattReimer** [comment]
tauDEM can now be run on a separate Cybercastor engine. We will need to develop a methodology and a subsequent riverscapes-tools script to enable this. 

In this demo I ran the script (below) which consumed dem.tif and NHDFlowline.shp from rs_context and then ran through the tools in the following order

1. **pitremove** on dem.tif to give us pitfill
2. **dinfflowdir** to give us dinfflowdir_ang and dinfflowdir_slp
3. **gdal_rasterize** on NHDFlowline to give us a really basic rasterized stream
4. **dinfdistdown** to give the final HAND output

```bash
#!/bin/bash


pitremove \
  -z /shared/rs_context/17060304/topography/dem.tif \
  -fel /shared/taudem/17060304/pitfill.tif

dinfflowdir \
  -fel /shared/taudem/17060304/pitfill.tif \
  -ang /shared/taudem/17060304/dinfflowdir_ang.tif \
  -slp /shared/taudem/17060304/dinfflowdir_slp.tif

gdal_rasterize \
    -te -115.9844729762425573 45.9342659162008431 -115.5958355164291333 46.2481900834219459 \
    -ts 4197 3390 \
    -burn 1 \
    /shared/rs_context/17060304/hydrology/NHDFlowline.shp \
    /shared/taudem/17060304/rasterized_flowline.tif

dinfdistdown \
  -ang /shared/taudem/17060304/dinfflowdir_ang.tif \
  -fel /shared/taudem/17060304/pitfill.tif \
  -src /shared/taudem/17060304/rasterized_flowline.tif \
  -dd /shared/taudem/17060304/hand.tif
  -m v

echo "DONE"
```

The initial outputs look very HAND-like.  I suggest we open new issues for further to track this.
