### ISSUE TITLE
Are we using the correct compression on floating point rasters?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#984]
I thought that `DEFLATE` compression was only intended for integer rasters and that we should use `LZW` compression for floating point rasters? I just reviewed a recent [RSC run](https://data.riverscapes.net/p/d9564c61-85e3-49c4-92e7-8fd13e307b74/) that uses DEFLATE for all rasters, including the DEM and slope. Is this correct?

<img width="753" alt="Screenshot 2024-08-19 at 3 29 37 PM" src="https://github.com/user-attachments/assets/981dd70a-87fb-48de-97b6-b1f93ff0436b">

@MattReimer @KellyMWhitehead

**Comment by MattReimer** [comment]
From: https://digital-geography.com/geotiff-compression-comparison/

GDAL supports three lossless compression algorithms for the GeoTiff format – Packbits, LZW and Deflate. The last two also support predictors to reduce the file size even further.

What to take away from that? Packbits is the fastest, but also offers the smallest compressions. Deflate is the smallest, slowest to write but faster to read than LZW. LZW compresses twice as fast as Deflate but is slower to decompress.

**Comment by philipbaileynar** [comment]
Yeesh. Now I'm looking at tauDEM... and it uses `LZW` for all rasters, both integer rasters like hillshade as well as floating point like slope.

<img width="743" alt="Screenshot 2024-08-19 at 4 40 56 PM" src="https://github.com/user-attachments/assets/bdebf60d-6a2e-4128-9aa8-0164ab824d28">

**Comment by MattReimer** [comment]
Actually Deflate is better for floating point and LZW is better for integer rasters, especially if there are large areas with the same value (no data, water etc). If you're compressing more noisy rasters I'm not sure there's a savings.

I think before we rework this let's make 100% sure this is worth doing. Both LZW and Deflate are lossless and excellent compression mechanisms.

Maybe let's test one fairly representative raster and see what the savings actually are before we rework all the tools.

**Comment by philipbaileynar** [comment]
I have confirmed that all (input, intermediate and output) rasters are compressed for the following models:

- RSC
- Channel Area
- tauDEM
- VBET

**Comment by jtgilbert** [comment]
closing as all rasters have compression now.
