### ISSUE TITLE
CC runs for Big Cow Creek

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#987]
As a follow on from #978 I need the following models run for Big Cow Creek (1201000506). Please use the same owner, tags and privacy settings as the existing runs.

Models needed:

- Hydro
- Anthro
- VBET
- BRAT
- RCAT

Please change the model names above to hyperlinks to the Data Exchange projects when complete.

Here are the existing runs:

 - [RSContext](https://data.riverscapes.net/p/fb383601-8f31-46d3-8f03-bc7de035f2ba)
 - [Channel Area](https://data.riverscapes.net/p/6afbd0cd-f816-484b-a3dd-a9217d33adee)
 - [tauDEM](https://data.riverscapes.net/p/9a034fc3-d4a8-4de1-9a79-463ee519844b)

**Comment by KellyMWhitehead** [comment]
VBET: https://data.riverscapes.net/p/9fb8fd54-661e-4b56-b914-693679318b4b
ANTHRO: https://data.riverscapes.net/p/a1cbb5d3-6548-4ac7-9c94-624570d8faf2
RCAT: https://data.riverscapes.net/p/
HYDRO: Failed (missing hydro equation)
BRAT: Cannot run without Hydro/likely missing hydro equations

**Comment by philipbaileynar** [comment]
Was VBET run with the debug flag turned on?

**Comment by KellyMWhitehead** [comment]
The cybercastor shell scripts do not run models with the debug flag. This is not exposed as an option when running on cybercastor.
